### PR TITLE
(@wdio/utils): ignore space before new line when detecting local Chrome version

### LINKED ISSUE #11018: [🐛 Bug]: In Mac/Linux. WebDriverIO fails to detect the local Chrome version due to unexpected newline character.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  "browserName": "chrome",
  "goog:javascriptEnabled": true,
  "goog:chromeOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage",
      "--window-size=1600,900",
      "--allow-insecure-localhost",
      "--disable-web-security",
      "--enable-automation",
      "--safebrowsing-disable-download-protection",
      "--remote-allow-origins=*",
      "--disable-gpu",
      "--no-first-run"
    ],
    "prefs": {
      "acceptInsecureCerts": true,
      "directory_upgrade": true,
      "prompt_for_download": false,
      "safebrowsing.enabled": true,
      "download.default_directory": "downloadDir"
    }
  }
}
```

### What happened?

When WebDriverIO attempts to determine the version of Chrome installed on the local machine, it invokes the --version command. This command yields the result: ‘Google Chrome 116.0.5845.110 \n’.

The issue arises in this line:
https://github.com/webdriverio/webdriverio/blob/24d8f0dccf54e6e19779094d73eb90ae9086ee86/packages/wdio-utils/src/driver/utils.ts#L61C5-L61C5

Here, the code tries to split the version string by whitespace and retrieve the last token. However, the actual last token is the newline character (\n), not the Chrome version. This causes WebDriverIO to bypass the local Chrome installation and default to downloading Chromium.

**Proposed Solution:**
To remedy this, we could first use a regex to eliminate the \n character from the string. Then, apply a trim() method to ensure no leading or trailing whitespaces. Following that, the current split-and-retrieve command can be executed.

image

### What is your expected behavior?

WebDriverIO will correctly parse the output of the --version command for Chrome.

### How to reproduce the bug.

Nothing special, just create a project using a wdio command, set a capability without setting a browserVersion and run the example test.

### Relevant log output

```typescript
Nothing relevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #11018

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by lararojasmr** [comment]
Nice, thanks. I was about to create a PR for this haha. Thanks!

**Comment by christian-bromann** [comment]
Ah damn .. I usually encourage folks to submit a PR but for some reasons I just picked this one up immediately since you've described the bug very well. Will make a release now. If you are interested contributing I am happy to help you find something!

**Comment by lararojasmr** [comment]
Thank you for the quick response! No worries at all – I'm glad the bug description was clear and helpful. I'm definitely interested in contributing further. Just let me know how I can be of assistance or if there's a particular area you'd like me to dive into. Looking forward to collaborating more!

**Comment by lararojasmr** [comment]
@christian-bromann ☝🏼

**Pull request merged**
