### PR TITLE
updated documentation for accepted values for allure reporter > severity

### PR DESCRIPTION
**Pull request by saranyaeaswaran**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Documentation update for issue [7406](https://github.com/webdriverio/webdriverio/issues/7406)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

As per Allure Reporter API documentation, severity level accepts one of the values - blocker, critical, normal, minor, trivial.  Updated webdriverio documentation to reflect this.

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks for the PR. While we are add it, I suggest to also strengthen the types, meaning that:

- let's create a type in `packages/wdio-allure-reporter/src/types.ts` , e.g.
    ```ts
    export type Severity = 'blocker' | 'critical' | 'normal' | 'minor' | 'trivial'
    ```
- import and use it in `index.ts` a `types.ts`, [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/index.ts#L586) and [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/types.ts#L61)

Also please sign the CLA, thank you!

**Comment by saranyaeaswaran** [comment]
Sure, I will work on this. Currently on vacation, will do this by next week.

**Comment by christian-bromann** [comment]
Let's also include the following documentation change:

### Discussed in https://github.com/webdriverio/webdriverio/discussions/7459

<div type='discussions-op-text'>

<sup>Originally posted by **saranyaeaswaran** September 22, 2021</sup>
Allure Report Usage ES5 example [here](https://webdriver.io/docs/allure-reporter/#usage) uses object destructuring format 
```
const { addFeature } = require('@wdio/allure-reporter').default
```
but the Mocha code example mentioned in the  documentation is specific to ES6 example of Allure API usage. Instead, can we correct the ES5 code example to below?
```
const allureReporter = require('@wdio/allure-reporter').default
```
This might help somebody who's new to JS and WebdriverIO.
</div>

**Comment by saranyaeaswaran** [comment]
Hi @christian-bromann, the documentation changes are pushed. But couldn't perform code changes for Allure report severity value typings as discussed in gitter due to local setup issue.

**Review by christian-bromann — APPROVED** [review]
👍  thanks a lot!

**Pull request merged**
