### PR TITLE
ISSUE-1531: allow an array of methods for hooks.

### PR DESCRIPTION
**Pull request by kradical**
## Proposed changes

Make functionality reflect the docs (unless I misunderstood either the docs or how to use hooks properly).

## Types of changes

What types of changes does your code introduce to WebdriverIO?

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

I guess it's kind of both :)
## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

Documentation was already there ;) I just found the test file, I will add some tests to update this PR

### CODE REVIEW

**Comment by christian-bromann** [comment]
Can we have unit tests for this?

**Comment by kradical** [comment]
will add tomorrow!

**Comment by kradical** [comment]
I added basic unit tests, they failed with the old code (y), I tried to follow the format of the other tests.

**Comment by christian-bromann** [comment]
Thanks! 👍

**Pull request merged**
