### PR TITLE
Wait for visible within viewport

### PR DESCRIPTION
**Pull request by wvankuipers**
## Proposed changes

I added a command to wait for an element to be visible within the viewport

## Types of changes

What types of changes does your code introduce to WebdriverIO?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

I created this command so I don't have to "fake" it by doing a timeout before checking if a element exists within the current viewpoint. This new command is useful for checking "sticky" menu's or "popover" elements on a page that appear after a certain timeout.

### CODE REVIEW

**Comment by christian-bromann** [comment]
Hey @wvankuipers ,
I am not sure about this addition. `waitForXXX` commands should only cover most used scenarios. I already declined waitForAlert PRs because you usually don't use that command that often and it is easy replaceable with

```js
browser.waitUntil(() => browser.isVisibleWithinViewport("..."))
```

I don't want to introduce new commands that aren't really necessary. Our API is blown up already. What do you think?

**Comment by wvankuipers** [comment]
This is true, you can use the above to wait for an element to be visible within the viewport, but how do we wait for a element to leave the viewport?

    browser.waitUntil(() => (!browser.isVisibleWithinViewport(btnSelector)));

Results in an error:
    
    { [Error: An element could not be located on the page using the given search parameters (".elem").]
  type: 'NoSuchElement',
  message: 'An element could not be located on the page using the given search parameters (".elem").'

**Comment by christian-bromann** [comment]
> but how do we wait for a element to leave the viewport?

just do

```js
browser.waitUntil(() => !browser.isVisibleWithinViewport("..."))
```

The error just says that it can't find the element (".elem")

**Comment by wvankuipers** [comment]
Hmm it seems to be a issue with my test script 😒 

Lets close this PR as I agree that it can be replaced by the command you provided!

**Pull request closed without merging**
