### PR TITLE
Flat ESLint support

### PR DESCRIPTION
**Pull request by MadSandwich**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

ESLint version: 8.57.0
- [x] cjs support
- [x] esm support
- [x] TS (with restrictions)

ESLint version: 9.0.0
- [x] cjs
- [x] esm
- [x] TS (with restrictions)

What have been done: Using migration guide and some repositories where such changes was already introduced, made some changes to `index.ts` & `package.json` files. Result was tested on several repositories using different types of configuration, no issues where detected, except while tested with TS (https://github.com/typescript-eslint/typescript-eslint/issues/8211), it working well except it fully ignoring `globals`.

To make rule work against `globals`, 'no-undef' rule should be added (TS only).

image
image

p.s. I can attach screenshots with my tests, if it would help anyhow. But it would be great if somebody can take a look on it, before merge.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [x] Back-ported PR at #12716

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by MadSandwich** [comment]
This PR is continue of the feature described in https://github.com/webdriverio/webdriverio/issues/12547
And first PR created https://github.com/webdriverio/webdriverio/pull/12580 (As work stop in it, I've created a separate)

**Comment by MadSandwich** [comment]
> I think this would be a good time to reference Eslint as a peer dependency to ensure that someone using this package also has Eslint v9 installed.
> 
> Wdyt?

This would make people that have a desire to stay on the previous version of eslint 8.57.0 got an error (after package update). As per eslint 9.0.0 they support only flat config, and other config are deprecated. We can reference it as a peer dep, but in that case most of work to make it compatible with 8.57.0 version would be useless.

**Comment by gavvvr** [comment]
> to reference Eslint as a peer dependency to ensure that someone using this package also has Eslint v9 installed.

@christian-bromann  I would not enforce consumers to use eslint 9+, if legacy config is still supported (which should be left supported for gradual migration)
I do not even think that eslint dependency should be upgraded within this PR. Both configs are exported now, which should be compatible with both worlds (legacy and flat config system).

@MadSandwich could you please add more details on changes in `package.json`. Why modifying only a single `index.ts` is not enough?

**Comment by MadSandwich** [comment]
> > to reference Eslint as a peer dependency to ensure that someone using this package also has Eslint v9 installed.
> 
> @christian-bromann I would not enforce consumers to use eslint 9+, if legacy config is still supported (which should be left supported for gradual migration) I do not even think that eslint dependency should be upgraded within this PR. Both configs are exported now, which should be compatible with both worlds (legacy and flat config system).
> 
> @MadSandwich could you please add more details on changes in `package.json`. Why modifying only a single `index.ts` is not enough?

Sure,

"type": "module" - was removed to make it easy for exporting for CJS and ESM, as it allow export = {...}, without this it would require 2 exports and issues then in configuration parsing.

This part was changed, to implicit specify where CJS and ESM should pick up their imports.
  "exports": {
    "import": {
      "types": "./build/index.d.ts",
      "default": "./build/index.js"
    },
    "require": {
      "types": "./build/index.d.ts",
      "default": "./cjs/index.js"
    }
  },
  
  And that part was changed, just to be sure, that written tests inside wdio still would work and rules are not affected.
  "eslint": "^9.0.0"

**Comment by MadSandwich** [comment]
@christian-bromann what do u think, on my comments above?

**Comment by christian-bromann** [comment]
@MadSandwich the change looks good to me. It would be awesome if we could have a smoke test for this, to verify if we actually catch linting issues. However this would be out of scope and it would be fine to put this into a separate issues.

One request I have is to raise the same PR to the `v8` branch so we can release it to the `latest` version.

**Comment by MadSandwich** [comment]
> @MadSandwich the change looks good to me. It would be awesome if we could have a smoke test for this, to verify if we actually catch linting issues. However this would be out of scope and it would be fine to put this into a separate issues.
> 
> One request I have is to raise the same PR to the `v8` branch so we can release it to the `latest` version.

@christian-bromann I will try to write some smoke test on weekend. And same PR is raised on v8 (https://github.com/webdriverio/webdriverio/pull/12716)

**Comment by christian-bromann** [comment]
@MadSandwich thanks, mind updating your branch? We have fixed some things in `main`.

**Comment by christian-bromann** [comment]
@MadSandwich mhm .. I was hoping that your branch would pass now, mind taking a look?

**Comment by MadSandwich** [comment]
> @MadSandwich mhm .. I was hoping that your branch would pass now, mind taking a look?

@christian-bromann for no reason it fails build for wdio-global, and the only one thing help me successfully build is return back `// @ts-expect-error` this line, that you recently deleted.

**Comment by christian-bromann** [comment]
@MadSandwich can you update your `pnpm-lock` file and ensure that `expect-webdriverio` is updated to `v4.13.0`?

**Pull request merged**
