### PR TITLE
webdriver: Fixed url params being encoded twice, breaking id/name based lookups

### LINKED ISSUE #4466: Bug: Double encoding urls breaking element lookups
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5
 - **Mode:** Standalone
 - **Node.js version:** 8.12.0
 - **NPM version:** 6.10.3
 - **Browser name and version:** PhantomJS 2.1.1
 - **Platform name and version:** MacOS 10.14.6
 - **Additional wdio packages used (if applicable):**

**Describe the bug**
Calling any endpoint that uses the element id in the url results in a `Element does not exist in cache` error. `waitForDisplayed()`/`isDisplayed()` for example will trigger the issue, as the URL it tries to call is something like: `/session/cd3edf50-d1bb-11e9-a6d9-85c8430db268/element/%253Awdc%253A1567894018135/displayed`.

This appears to be an issue introduced in 5.11.12 via https://github.com/webdriverio/webdriverio/pull/4283 as its double encoding the url parameters when I believe it should only be doing it once. If I change the webdriver code to only encode once, eg: `encodeURIComponent(arg)` instead of `encodeURIComponent(encodeURIComponent(arg))` then it works as expected as the URL becomes `/session/cd3edf50-d1bb-11e9-a6d9-85c8430db268/element/%3Awdc%3A1567894018135/displayed`.

**To Reproduce**
Here's a rough/basic way to reproduce the error:

```
const { remote } = require('webdriverio');
const child_process = require('child_process')

const proc = child_process.spawn('phantomjs', [ '--webdriver=4444' ]);
proc.stderr.pipe(process.stderr);

(async () => {
    // Wait for PhantomJS to start
    await new Promise(done => setTimeout(done, 2000));

    const browser = await remote({
        logLevel: 'trace',
        capabilities: {
            browserName: 'phantomjs'
        }
    })

    await browser.url('https://duckduckgo.com/')

    const inputElem = await browser.$('#search_form_input_homepage')
    const isDisplayed = await inputElem.isDisplayed()
    console.log('Search input is displayed:', isDisplayed)

    await browser.deleteSession()
})().catch((e) => {
    proc.kill();
    console.error(e)
})
```

**Expected behavior**
The calls to the webdriver server should use urls that aren't double encoded and therefore should work with the above code.

**Log**
If applicable, add logs to help explain your problem.
```
2019-09-07T22:38:49.221Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
2019-09-07T22:38:49.224Z INFO webdriver: DATA { capabilities: 
   { alwaysMatch: { browserName: 'phantomjs' },
     firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'phantomjs' } }
2019-09-07T22:38:49.256Z INFO webdriver: COMMAND navigateTo("https://duckduckgo.com/")
2019-09-07T22:38:49.256Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/42941dc0-d1c0-11e9-8266-4d9924cfd25c/url
2019-09-07T22:38:49.256Z INFO webdriver: DATA { url: 'https://duckduckgo.com/' }
2019-09-07T22:38:50.967Z INFO webdriver: RESULT {}
2019-09-07T22:38:50.970Z INFO webdriver: COMMAND findElement("css selector", "#search_form_input_homepage")
2019-09-07T22:38:50.970Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/42941dc0-d1c0-11e9-8266-4d9924cfd25c/element
2019-09-07T22:38:50.970Z INFO webdriver: DATA { using: 'css selector', value: '#search_form_input_homepage' }
2019-09-07T22:38:50.984Z INFO webdriver: RESULT { ELEMENT: ':wdc:1567895930983' }
2019-09-07T22:38:50.988Z INFO webdriver: COMMAND isElementDisplayed(":wdc:1567895930983")
2019-09-07T22:38:50.988Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/42941dc0-d1c0-11e9-8266-4d9924cfd25c/element/%253Awdc%253A1567895930983/displayed
2019-09-07T22:38:51.107Z DEBUG webdriver: request failed due to status 10
2019-09-07T22:38:51.107Z WARN webdriver: Request failed due to {"errorMessage":"Element does not exist in cache","request":{"headers":{"Connection":"keep-alive","accept":"application/json","host":"localhost:4444"},"httpVersion":"1.1","method":"GET","url":"/displayed","urlParsed":{"anchor":"","query":"","file":"displayed","directory":"/","path":"/displayed","relative":"/displayed","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/displayed","queryKey":{},"chunks":["displayed"]},"urlOriginal":"/session/42941dc0-d1c0-11e9-8266-4d9924cfd25c/element/%253Awdc%253A1567895930983/displayed"}}
```

### PR DESCRIPTION
**Pull request by lnewson**
Fixes #4466 

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

This just makes it so items (eg. element id, cookie names, etc...) used in a command path are only encoded once instead of twice, as doing it twice was causing it to have a different value when interpreted by the browser and therefore would fail to find the specified item.

Note: I also had a look at creating a more end to end test but since everything is mocked, that didn't seem to be feasible with the current tests (since it'd likely require interaction with a real browser).

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
Yes, with this PR case mentioned in https://github.com/webdriverio/webdriverio/pull/4283 will stop working. 
Need to think how to handle both

**Comment by lnewson** [comment]
@mgrybyk if you read my comment on the associated issue, this doesn't break setting cookies with a name such as `/test`. In fact the original fix completely broke the ability to actually delete cookies.

**Comment by christian-bromann** [comment]
I agree with @lnewson , it seems for me that 

```js
expect(endpoint).toBe('/session/:sessionId/element/%2Fpath/element')
```
is properly decoded as oppose to
```js
expect(endpoint).toBe('/session/:sessionId/element/%252Fpath/element')
```

**Comment by mgrybyk** [comment]
Don't you mind if I double check on Monday?
Overall it looks good to me, thank you for the fix @lnewson

**Comment by lnewson** [comment]
Not sure who you're asking sorry, but in case you're asking me, take as long as you need. For now I've just pinned the version I'm using. Let me know if you need anything extra from me. 👍

**Comment by mgrybyk** [comment]
@lnewson the test mentioned by you in the issue also failing if second encode is removed:
```
describe("main suite", () => {
    it("some test", () => {
        browser.url("http://guinea-pig.webdriver.io")

        browser.setCookies({ name: "/test", value: "bla", path: "/", domain: "guinea-pig.webdriver.io" })
        const cookiesBefore = browser.getCookies()
        browser.deleteCookies(["/test"])
        const cookiesAfter = browser.getCookies()
        console.log("Cookies before: ", cookiesBefore)
        console.log("Cookies after: ", cookiesAfter)
    })
})
```

**Comment by mgrybyk** [comment]
with two encode I'm getting the following output:
```
[0-0] Cookies before:  [ { domain: 'guinea-pig.webdriver.io',
    expiry: 2199342126,
    httpOnly: false,
    name: '/test',
    path: '/',
    secure: false,
    value: 'bla' } ]
[0-0] Cookies after:  []
```

which seems to be correct

**Comment by lnewson** [comment]
@mgrybyk can you please provide a **full** replication case? As it looks like you are trying to run it via some other system and not via webdriver alone. So I suspect you have something else decoding the URL before it gets passed to the actual driver.

**Comment by lnewson** [comment]
Here's a basic replication case that doesn't rely on anything else to show that it works with my change, but not with the double encoding (requires a driver running on port 4444 and webdriver/webdriverio installed):

```
const { remote } = require('webdriverio');

(async () => {

    const browser = await remote({
        logLevel: 'trace',
        host: 'localhost',
        path: '/',
        port: 4444,
        capabilities: {
            browserName: 'chrome'
        }
    })

    await browser.url("http://guinea-pig.webdriver.io")

    await browser.setCookies({ name: "/test", value: "bla", path: "/", domain: "guinea-pig.webdriver.io" })
    const cookiesBefore = await browser.getCookies()
    await browser.deleteCookies(["/test"])
    const cookiesAfter = await browser.getCookies()
    console.log("Cookies before: ", cookiesBefore)
    console.log("Cookies after: ", cookiesAfter)

    await browser.deleteSession()
})().catch((e) => {
    console.error(e)
})
```

**Comment by mgrybyk** [comment]
Are you using grid? I have tried with selenium standalone package that uses grid.
What is running on port 4444?

**Comment by lnewson** [comment]
No, I'm much more low level then what you mentioned even, it's just running it directly via node and using chromedriver directly.

Here's all I've been running (where index.js is the above script):
```
Tab 1:
$ chromedriver --port=4444

Tab 2: 
$ node index.js
```

**Comment by lnewson** [comment]
@mgrybyk I tried to reproduce what you were doing, or something similar to what you mentioned by using wdio with the local runner here: https://github.com/lnewson/webdriverio-issue

However when using that, it still fails due to the double encoding issue and upon linking in my fix I've proposed here, then my test above passes.

**Comment by mgrybyk** [comment]
Haven't yet tried your project, however tried locally `77.0.3865.40-x64-chromedriver --port=4444 --url-base=wd/hub` and tests are passing for me with two encodes and failing with one

**Comment by mgrybyk** [comment]
@lnewson ok, figured it out.
double encode works with selenium standalone and grid but doesn't work when using browser drivers directly, like chromedriver or geckodriver

**Comment by mgrybyk** [comment]
I don't know how to deal with it better, but we can check if `path` is `'/wd/hub'` then encode url only twice, otherwise encode url only once

**Comment by lnewson** [comment]
Ahh okay, that would make sense since running via selenium server will parse the URL and decode it, before passing it back on via selenium webdriver. Really it should be encoding the endpoint again before passing it on, but I guess it's not.

In that case, could we do pass through a flag to `command.js` from `utils.js` when we need to double encode the endpoint variables? So maybe something like this?

utils.js:
```
    for (const [endpoint, methods] of Object.entries(ProtocolCommands)) {
        for (const [method, commandData] of Object.entries(methods)) {
            prototype[commandData.command] = { value: command(method, endpoint, commandData, isSeleniumStandalone) }
        }
    }
```

command.js:
```
export default function (method, endpointUri, commandInfo, doubleEncodeVariables) {
...
            /**
             * inject url variables
             */
            if (i < variables.length) {
                const encodedArg = doubleEncodeVariables ? encodeURIComponent(encodeURIComponent(arg)) : encodeURIComponent(arg)
                endpoint = endpoint.replace(`:${commandParams[i].name}`, encodedArg)
                continue
            }
...
}
```

**Comment by lnewson** [comment]
@christian-bromann @mgrybyk I've just pushed up the change I mentioned above, as it worked for me locally with selenium standalone and direct browser interaction. However I'm not overly familiar with appium, etc... so let me know if you don't think that will work and I'll take another look (probably just fallback to using `/wd/hub` as suggested previously).

**Comment by lnewson** [comment]
Awesome, thanks for all the help in getting this solved! :+1:

**Comment by parsable-svorkapic** [comment]
Hello guys,

I've been debugging the problem we have on a project and after some debuging it came down to this fix. 
We are using wdio with appium server and with the latest update to appium 1.22 our runs on saucelabs started to fail with the exact error that was described here, locally it's working fine since the element isn't found with `:wdc:` prefix.

Based on your discussion above, I assume It has to do with the way fix was implemented and how appium has changed now in the latest release (https://github.com/appium/appium-desktop/releases) since we get the `doubleEncodeVariables` set as `true`.

@lnewson, as the one who made the fix and somebody that was using wdio as well, do you have any suggestion here? is there a possibility to provide that flag through wdio config explicitly to set it to `false`?
Or would you guys suggest that I open a new issue for this?

note that I'm relatively new with both js/ts and wdio so I can't provide hands-on help unfortunately

**Pull request merged**
