### PR TITLE
fix memory leak in devtools

### LINKED ISSUE #5048: Devtools: infinite recursive loop in devtools driver
**Environment:**
 - **WebdriverIO version:** webdriverio@5.18.7
 - **Mode:** standalone
 - **Node.js version:** 10.16.0
 - **yarn version:** 1.22.0
 - **Browser name and version:** 80
 - **Platform name and version:** MacOS 10.14
 - **Additional wdio packages used (if applicable):** devtools

**Config of WebdriverIO**
`browserName: chrome`

**Describe the bug**
https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/devtoolsdriver.js#L197

if `pageloadTimeoutReached` is falsy, it will keep calling `this. checkPendingNavigations` until memory runs out:

**To Reproduce**

Hitting control-c sometimes while tests are running can trigger this.

Running node with `node --prof --expose-gc --inspect` makes it easy to see in Chrome the infinite loop.

Screen Shot 2020-02-20 at 4 37 06 PM

**Expected behavior**

* Don't use recursion when we don't know how deep it could get. Maybe [p-retry](https://github.com/sindresorhus/p-retry)?
* With control-c, it should gracefully shut down the devtools package.  Something like this maybe?
```ts
// If the parent of the spawned process becomes 1, then it means the process that spawned our process was killed and we should exit too.
if (process.ppid === 1) {
 process.exit();
}
```

**Log**

```
[88676:0x102802000]    96774 ms: Scavenge 1378.0 (1424.6) -> 1374.3 (1426.1) MB, 2.8 / 0.0 ms  (average mu = 0.330, current mu = 0.315) allocation failure
[88676:0x102802000]    96782 ms: Scavenge 1378.2 (1426.1) -> 1374.5 (1427.1) MB, 2.3 / 0.0 ms  (average mu = 0.330, current mu = 0.315) allocation failure
[88676:0x102802000]    96790 ms: Scavenge 1378.3 (1427.1) -> 1374.6 (1428.6) MB, 2.9 / 0.0 ms  (average mu = 0.330, current mu = 0.315) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3c22f775be3d]
    1: StubFrame [pc: 0x3c22f775d3c6]
Security context: 0x1e9678a9e6e9 <JSObject>
    2: CallSiteToString [0x1e9622f63b09] [/Users/dgreene/medallia/perf-report/node_modules/source-map-support/source-map-support.js:~262] [pc=0x3c22f7e841e5](this=0x1e965b225411 <Object map = 0x1e96113352c1>)
    3: StubFrame [pc: 0x3c22f7713e51]
    4: StubFrame [pc: 0x3c22f775e15b]
    5: prepareStackTrace [0x1e96ba71a...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
10: 0x10055e434 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
11: 0x1007e6714 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
12: 0x3c22f775be3d

<--- Last few GCs --->

[88749:0x102802000]    96322 ms: Scavenge 1382.9 (1424.1) -> 1379.2 (1426.1) MB, 3.3 / 0.0 ms  (average mu = 0.307, current mu = 0.269) allocation failure
[88749:0x102802000]    96333 ms: Scavenge 1383.0 (1426.1) -> 1379.3 (1427.6) MB, 3.2 / 0.0 ms  (average mu = 0.307, current mu = 0.269) allocation failure
[88749:0x102802000]    96344 ms: Scavenge 1383.2 (1427.6) -> 1379.5 (1429.6) MB, 3.4 / 0.0 ms  (average mu = 0.307, current mu = 0.269) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3f86fc5be3d]
    1: StubFrame [pc: 0x3f86fc41b83]
    2: StubFrame [pc: 0x3f86fc1f79e]
    3: EntryFrame [pc: 0x3f86fc04ba1]
    4: ExitFrame [pc: 0x3f86fc5be3d]
Security context: 0x1cf46ff1e6e9 <JSObject>
    5: _tickCallback [0x1cf481f866f9] [internal/process/next_tick.js:68] [bytecode=0x1cf473468f11 offset=157](this=0x1cf4d1483c81 <process map = 0x1cf4ec466389>)
    6: InternalFrame [pc: 0x3f86fc0ee75]
    7: En...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
10: 0x10055e434 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
11: 0x1007e6714 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/dgreene/.nvm/versions/node/v10.16.0/bin/node]
12: 0x3f86fc5be3d
````

### PR DESCRIPTION
**Pull request by dylang**
## Proposed changes

Fixes #5048.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

- `npm install` is failing on me for this repo so I haven't run the tests.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@dylang would you mind signing the CLA?

**Comment by christian-bromann** [comment]
ping @dylang

**Comment by dylang** [comment]
I'd love to get to this when I have time.... 😓

**Comment by christian-bromann** [comment]
@dylang is there anything I can do to support?

**Comment by dylang** [comment]
Hi @christian-bromann, thanks for reaching out.

I've been offline the last week, I hope to take a look again this week. I'll let you know if I run into problems.

**Comment by dylang** [comment]
@christian-bromann - The tests were failing because of invalid test code, which I've fixed.

Before my memory leak fix, those rejections were just being lost as memory leaks. My fixes surfaced them, which is why the tests were suddenly failing.

**Comment by dylang** [comment]
Some E2E tests are failing, but I'm not sure which ones. 

Also the `.nvmrc` is set to a version of node that is not compatible with the version of Jest being used.

**Comment by christian-bromann** [comment]
> Some E2E tests are failing, but I'm not sure which ones.

These are failing:

- e2e/element.test.js
- e2e/transitions.test.js

you can run them individually on your machine via e.g. `npm rub test:e2e -- ./e2e/element.test.js`

> Also the `.nvmrc` is set to a version of node that is not compatible with the version of Jest being used.

Not sure what you mean. We use Jest v26.1.0 which has support for Node v10 (v26 of Jest [dropped](https://github.com/facebook/jest/blob/master/CHANGELOG.md#chore--maintenance-2) support for Node v8).

**Comment by christian-bromann** [comment]
@dylang let me know if there is anything unclear or if there is anything I can help with.

**Comment by jedwards1211** [comment]
@christian-bromann If I understand correctly the test failures are not caused by the changes in this PR, but rather preexisting problems that were revealed by this PR fixing the memory leak, so can you go ahead and merge this?

**Comment by jedwards1211** [comment]
Would you be willing to fix the failing tests if I pay a one-time donation of a certain amount?

**Comment by jedwards1211** [comment]
I guess I'm being a bit of a jerk about it.  Been stressed about getting all of our tests to finally work

**Comment by jedwards1211** [comment]
I'm working on this, and about to open a new PR.  FYI @dylang, I saw you raised the retry interval to `pageLoadTimeout/5`.  I'm not sure what the reason for this was, but the problem is `pageLoadTimeout` can be really high (like `300000` in the tests that were failing) and the first check failed because it was in the middle of navigation, so it makes it too slow to recheck.  I lowered the timeout back to `100` and the tests stopped failing.

**Comment by jedwards1211** [comment]
Okay, other tests failed though in which the `pageLoad` timeout was really low.  So I think `Math.min(100, pageloadTimeout / 5)` will work.

**Comment by christian-bromann** [comment]
Closing in favor of #6240. Thanks @dylang for kicking this of and @jedwards1211 for pushing it over the finish line

**Pull request closed without merging**
