### PR TITLE
Copied changes from Andrew-tompkins to fix issue #9495

### PR DESCRIPTION
**Pull request by patrickschilder**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by djpasch** [comment]
@christian-bromann can you give an approval so the checks on my pull request will start running?

**Comment by christian-bromann** [comment]
@djpasch anything I can do to help to land this?

**Comment by djpasch** [comment]
> @djpasch anything I can do to help to land this?

Can you again appove so the github action will start running?

**Comment by djpasch** [comment]
@christian-bromann can you approve again so the github action wil run? I have now reverted all changes, so expect the action to run succesfully

**Comment by christian-bromann** [comment]
@patrickschilder it seems you reverted all changes 🤔

**Comment by patrickschilder** [comment]
> @patrickschilder it seems you reverted all changes 🤔

@christian-bromann Yes i did. Still the build is failing, so there must be something wrong in the main branch. I think that needs to be fixed before i can push any changes.

**Comment by christian-bromann** [comment]
@patrickschilder totally, I just got back from vacation and am working on this.

**Comment by christian-bromann** [comment]
@patrickschilder the `main` branch is passing again.

**Comment by patrickschilder** [comment]
> @patrickschilder the `main` branch is passing again.

@christian-bromann thanks, i will now re-apply the changes in two steps. If you can approve the github action to run.

**Pull request closed without merging**
