### PR TITLE
fix(webdriverio): Misfound elements when using WebDriver BiDi

### LINKED ISSUE #13556: [🐛 Bug]: [v9 ][CRITICAL] Misfound elements when BiDi locators lose parent context and fall back to WebDriver Classic
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
"browserName": "firefox"
}
```

### What happened?

We issue the commands

```ts
const wrapper = $('[data-testid="wrapper"]')
const nested = wrapper.$('[data-testid="wrapper-nested"]')

```

The nested is retrieved from the root, instead of from nested within wrapper, which brings us a different element !
This happens because internally we get an error:

> WebDriver Bidi command "browsingContext.locateNodes" failed with error: no such node - The node with the reference (wrapper reference) is not known, falling back to regular WebDriver Classic command

Which then executes a normal WebDriver classic but from the root of the page, losing the wrapper parent context, which retrieves a different element !

Classic method is executing a find from the root
Using URL http://localhost:65260/session/${sessionURL}/element
instead of http://localhost:65260/session/${sessionURL}/element/${refetchedElementReference}/element

Here is the offending line of code:
https://github.com/webdriverio/webdriverio/blob/10c8e31abb600f7c31e83df818428813580460db/packages/webdriverio/src/utils/index.ts#L334

`findElements` in called from browser, without parent nesting context !

### What is your expected behavior?

Element nesting and parent context should be respected !

### How to reproduce the bug.

Observed in Firefox.

Conditions tricky to implement due to staleness of elements but solution is not: Element context should be preserved when calling WebDriver Classic method !

### Relevant log output

Here we give a command to find [data-testid="wrapper-nested"] which is located inside a [data-testid="wrapper"]
```ts
INFO webdriver: DATA { using: 'css selector', value: '[data-testid="wrapper-nested"]' }
```
Since this is BiDi v9, `browsingContext.locateNodes` attempts to find it, with the correct context, the element reference for the wrapper is sent in `startNodes`

```json
INFO webdriver: BIDI COMMAND browsingContext.locateNodes {
    "locator": {
        "type": "css",
        "value": "[data-testid=\"wrapper-nested\"]"
    },
    "context": "437e2afe-fd61-4568-af88-26ff1e51ac1e",
    "startNodes": [
        {
            "sharedId": "97e6478d-2fd9-45d3-acfc-ad162ae362a4"
        },
        {
            "sharedId": "3ae62490-0013-4583-aad7-2fe8fbf1660c"
        }
    ]
}
```
Then it fails, due to unknown reference to the wrapper element (97e6478d-2fd9-45d3-acfc-ad162ae362a4)
Possibly a stale element, then falls back to WebDriver classic
```
2024-09-11T14:51:44.626Z WARN webdriverio: Failed to execute browser.browsingContextLocateNodes({ ... }) due to
Error: WebDriver Bidi command "browsingContext.locateNodes" failed with error:
no such node - The node with the reference 97e6478d-2fd9-45d3-acfc-ad162ae362a4 is not known, 
falling back to regular WebDriver Classic command
```
And here lies the problem, Classic method is executing a find from the root
Using URL http://localhost:65260/session/${sessionURL}/element
instead of http://localhost:65260/session/${sessionURL}/element/${refetchedElementReference}/element
```ts
2024-09-11T14:51:44.626Z INFO webdriver: COMMAND findElement("css selector", "[data-testid="wrapper-nested"]")
2024-09-11T14:51:44.626Z INFO webdriver: [POST] http://localhost:65260/session/76788a73-a7c1-4c90-94dc-67f478e3d2a2/element
2024-09-11T14:51:44.626Z INFO webdriver: DATA {
  using: 'css selector',
  value: '[data-testid="wrapper-nested"]'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by nextlevelbeard**
## Proposed changes
Fixes #13556

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [] I have added tests that prove my fix is effective or that my feature works
- [X] I have added the necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [X] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by nextlevelbeard** [comment]
@christian-bromann
I cannot add tests for this because creating a proper test bed for this area of the code is proving tricky to me.
There's no mocks for `ws` and BiDi commands AFAIK. Creating the stale scenario described here is also an unknown.
Looking at few changes there are, I think its quick to see and understand how when BiDi command "browsingContext.locateNodes" throws an error and we fall back to a class WebDriver call, we are disregarding the scope.

This was tested locally and I could check in real world E2E tests that the scenario presented in the original issue was gone.
___
Scenario DOM state: 
```xml
<div id="foo">
    <div id="bar">
<div id="bar">
```

Element 1 (#foo) and element 2 (#bar) exist in the root of the DOM.
Element 3 (also a #bar) is nested inside the Element 1 (#foo), therefore we build a nested element to find them.
This part is important. The process fails because of the webdriverIO feature of nested elements.

```ts
const rootFoo = await $('#foo');
const rootBar = await $('#bar');

// Problem is when you do this
// If "rootFoo" becames stale, and WebDriver BiDi is on, it actually returns "rootBar"
const fakeNestedBar = await rootFoo.$('#bar'); 

// No problem finding the nested #bar here
const realNestedBar = await $('#foo #bar');
```

**Review by christian-bromann — APPROVED** [review]
This makes sense to me 👍 thanks a lot for this contribution!

**Comment by christian-bromann** [comment]
@nextlevelbeard it seems like this change is impacting one of the e2e test, mind taking a look at adjusting the test if you think it corrected the expected behavior?

**Comment by nextlevelbeard** [comment]
> @nextlevelbeard it seems like this change is impacting one of the e2e test, mind taking a look at adjusting the test if you think it corrected the expected behavior?

@christian-bromann Seems to be unrelated to the changes, CI gives a timeout, it passes locally

```shell
it('can reload a session with new capabilities', async () => {
        expect(browser.capabilities.browserName).toBe('chrome')
        await browser.reloadSession({
            browserName: 'edge',
            'ms:edgeOptions': {
                args: ['headless', 'disable-gpu']
            }
        })
        expect(browser.capabilities.browserName).toContain('MicrosoftEdge')
    })
```
```log
» /wdio/headless/reloadSession.e2e.ts
[chrome 130.0.6723.69 mac #0-2] reloadSession
[chrome 130.0.6723.69 mac #0-2]    ✓ can reload a session
[chrome 130.0.6723.69 mac #0-2]    ✓ can reload a session with new capabilities
[chrome 130.0.6723.69 mac #0-2]
[chrome 130.0.6723.69 mac #0-2] 2 passing (20s)
```

**Pull request merged**
