### PR TITLE
docs(jsdoc): Edit JSDoc comments

### PR DESCRIPTION
**Pull request by Zearin**
## Proposed changes

Minor edits to JSDoc comments.  

Mostly adding a hyphen separator between the param name and description of `@param` lines.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/technical-committee

### CODE REVIEW

**Comment by christian-bromann** [comment]
> Mostly adding a hyphen separator between the param name and description of `@param` lines.

Any reason for it? Usually this types of comments are without hyphen

**Comment by mgrybyk** [comment]
How have you reformated all that?

**Comment by Zearin** [comment]
According to [JSDoc documentation](https://devdocs.io/jsdoc/tags-param), the hyphen is totally optional.  

It doesn’t affect generated output.  But it _does_ affect the readability of some comments when browsing through the source code.  

There are many cases where the _nameOfParam_ and the _descriptionOfParam_ are either the same word, or have an ambiguous relationship when reading. (e.g., “Are those two words part of the same sentence, or not?”)

**Comment by christian-bromann** [comment]
@Zearin @mgrybyk I don't really mind adding it. Can you make sure that the docs are generated properly, e.g. for command `@param` like [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/touchAction.js#L46)?

**Comment by mgrybyk** [comment]
I like some changes (typos fixes, arg types) but can't see any value from adding everywhere `-` or uppercase.

**Comment by Zearin** [comment]
Took me a bit to generate the docs.  

Actually, the dash shows up in the generated docs too. ☹  I have not observed this issue when using vanilla JSDoc.

What is the full pipeline of your documentation generation toolset?

**Comment by Zearin** [comment]
I poked around and discovered Docusaurus.  

Continuing my search of where the JSDoc translation occurs…

**Comment by Zearin** [comment]
Aha.  Found `scripts/templates/api.tpl.ejs`.

**Comment by Zearin** [comment]
And…presto!

I fixed the dash in the output generation, and added a few small things to the template, too.

**Comment by Zearin** [comment]
(Forgot to explain the template fix…)  

In the API docs, functions have the table with headings for **param**, **type**, and **description**.  Under **type**, it used to always say “param”.  I found that the template was referencing a different variable than it was supposed to, so I told the template to look up the correct field.

**Comment by christian-bromann** [comment]
Hey @Zearin ,
couple of things in order to move this PR forward:

- fix conflicting files
- add eslint rule so that people are forced to write the comments in a correct format
- can you check if the website generator tool properly understands this format?

Cheers!

**Comment by Zearin** [comment]
Thanks @christian-bromann !  I’ll get to it soon.

**Comment by christian-bromann** [comment]
@Zearin can you check the eslint issues in the build? Also do you have any feedback on my points above?

**Comment by Zearin** [comment]
@christian-bromann I think I’ve done too much at once here.  I learned a lot during the course of this Pull Request, so I think I might reboot my attempt and use this branch as a reference for proceeding in smaller steps.

**Comment by Zearin** [comment]
@christian-bromann Rebooting my efforts in #4763.  Closing this Issue.  (I’ll submit the same work again, but I’ll do it in multiple, smaller Pull Requests.)

**Pull request closed without merging**
