### PR TITLE
Introducing WebdriverIO Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [WebdriverIO Guru](https://gurubase.io/g/webdriverio) to Gurubase. WebdriverIO Guru uses the data from this repo and data from the [docs](https://webdriver.io/) to answer questions by leveraging the LLM.

In this PR, I showcased the "WebdriverIO Guru", which highlights that WebdriverIO now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable WebdriverIO Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@kursataktas thanks for the contribution, mind signing the CLA?

**Comment by BorisOsipov** [comment]
@christian-bromann Check his GitHub profile; he’s just spamming OSS projects. Are you sure we want this in the README?

**Comment by BorisOsipov** [comment]
It is also not an OSS project. Why we need to promote it.

**Comment by christian-bromann** [comment]
Thanks @BorisOsipov for your feedback. I didn't take a closer look but now after reviewing the platform I agree that I don't think it will add much value to the project. We already using mendable.io on our main page.

@kursataktas sorry but at the moment I don't think we are interested. Good luck!

**Comment by kursataktas** [comment]
Thanks for the review, @christian-bromann. Would you like me to disable WebdriverIO Guru on Gurubase?

**Comment by christian-bromann** [comment]
> Would you like me to disable WebdriverIO Guru on Gurubase?

Feel free to keep it on if you think it is valuable for your users.

**Pull request closed without merging**
