### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by christian-bromann**
Enjoy!

### CODE REVIEW

**Comment by BorisOsipov** [comment]
@christian-bromann 	do you have any plans how translations synchronization will work? I mean about process. E.g. case when someone makes changes in english docs and of course, he can't the same chages for other languages...

**Comment by christian-bromann** [comment]
@BorisOsipov the english docs are our base. If someone makes changes to the docs we have to hope that people that speak one of the languages are open to contribute back the translations. It will be as simple as going to https://crwd.in/webdriverio and signup. All translations can be made there. Once someone changes them a PR is automatically proposed by the Crowdin integration.

**Comment by BorisOsipov** [comment]
>Once someone changes them a PR is automatically proposed by the Crowdin integration.
That is nice! I always admired that in 2k19 there is services for any thing we would mind

**Comment by christian-bromann** [comment]
Yeah that Crowdin service is awesome. Many translation that are proposed are actually really good. All of the commits above are made by Crowdin on behalf of me and currently @baruchvlz and me translate Spanish and German.

**Comment by dpgraham** [comment]
Cool!

@christian-bromann are you able to add a Crowdin badge to the README.md? I'd like to see how you were able to translate markdown files. This would be something of interest for Appium.

**Comment by christian-bromann** [comment]
@dpgraham the badge is actually a good idea and would make this more visible for the project. Crowdin works pretty well together with Docosaurus. There are actually pretty good translation suggestions and the integration with Github works great as you can see.

**Comment by dpgraham** [comment]
Yeah we use Crowdin for Appium Desktop and it works pretty well. We set up a weekly pipeline that automates putting in PR's like this that sync up with Crowdin.

**Comment by WarleyGabriel** [comment]
Hi, @christian-bromann could you add Portuguese on Crowdin?

**Comment by christian-bromann** [comment]
Closing as this needs to be re-setup with the new Docusaurus v2 site.

**Pull request closed without merging**
