### PR TITLE
Export Launcher

### PR DESCRIPTION
**Pull request by monolithed**
## Proposed changes

I have to launch my tests in a custom grunt plugin. And I found a [way](https://github.com/webdriverio/grunt-webdriver/blob/master/src/webdriver.js#L9):

```js
import path from 'path'
import resolve from 'resolve'

const Launcher = require(path.join(path.dirname(resolve.sync('webdriverio')), 'lib/launcher'));
new Launcher(...);
```

But this code is ugly, so I think we should to export the Launcher.

```js
import WebdriverIO from 'webdriverio';

new WebdriverIO.Launcher(...);
```

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

@christian-bromann, what do you think?

### CODE REVIEW

**Comment by christian-bromann** [comment]
Yeah, I see the value in exporting it. 👍

**Comment by monolithed** [comment]
@christian-bromann, I would appreciate if you could publish to npm :)

**Comment by christian-bromann** [comment]
There will be a release later today

**Comment by monolithed** [comment]
@christian-bromann, what about release? 🙂

**Comment by christian-bromann** [comment]
just released a new version

**Comment by monolithed** [comment]
Thanks!

**Pull request merged**
