### PR TITLE
Make it possible to use js object as config instead of a file 

### PR DESCRIPTION
**Pull request by axelhildingson**
## Proposed changes

The propose of this PR is to make it possible to launch webdriverio with a dynamic generated  configuration instead of a static file. 

## Types of changes

What types of changes does your code introduce to WebdriverIO?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by axelhildingson** [comment]
We have created a plugin to https://github.com/rocjs/roc (javascript ecosystem), so it is possible to run wdio out of the box. https://www.npmjs.com/package/roc-plugin-test-webdriverio.  

The problem we have is that we need to create a tmp file for every test execution  to act as a config file to make it possible for users to configure their setup. This worked for most of the properties except the hooks, which are functions. We found out that is more or less impossible to stringify a js object with functions.

So the simplest and cleanest solution to this problem is to use a js object instead of a file.

**Comment by christian-bromann** [comment]
> The problem we have is that we need to create a tmp file for every test execution

Why is that?

Why can't you just create temporary config files?

**Comment by monolithed** [comment]
The current config file is executed several times before. I mean:

```js
let AccountManager = require('@qa/account-manager');
let WebDriverIOUtils = require('@qa/wdio-utils');
let WebDriverIOAPI = require('@qa/wdio-api');
let MochaHooks = require.resolve('@qa/wdio-mocha-hooks');
let capabilities = require('@qa/wdio-capabilities');
let YodaAllureReporter = require('@qa/yoda-allure-reporter');
let AllureRuntime = require('@qa/yoda-allure-utils');

let account = new AccountManager.Hooks();

let utils = new WebDriverIOUtils({
	cache: './cache/',
	cases: './cases/'
});

exports.config = {
	/*
	 * Настройки с которыми запущен сервер Selenium
	 *
	 * Операционная система: Windows
	 * Список доступных браузеров: Chrome, Firefox, Opera, IE 11
	 * Грид: http://***.mail.ru:4444/grid/console
	 *
	 * Операционная система: Linux
	 * Список доступных браузеров: Chrome, Firefox
	 * Грид: http://***.mail.ru:4444/grid/console
	 */
	host: '***.mail.ru',
	port: 4444,
	path: '/wd/hub',
	execArgv: ['--harmony'],

	/* Базовый адрес тестирования */
	baseUrl: 'https://e.mail.ru',

	/* Доступные значения: silent, verbose, command, data, result, error */
	logLevel: 'silent',

	/* Максимальное время на выполнение команд ожидания. */
	waitforTimeout: 30 * 1000,

	/*
	 * Максимальное время на ожидание селектора.
	 * Не выставляйте это значение больше 1-3s иначе это очень сильно скажется
	 * на времени выполнении тестов!
	 */
	waitForSelector: 1000,

	/* Максимальное количество попыток на установление соединения с сервером */
	connectionRetryCount: 5,

	/* Максимальное время на выполнение повторного запроса */
	connectionRetryTimeout: 1 * (60 * 1000),

	/* Количество инстансов параллельного запуска тестов */
	maxInstances: 1,

	/* Максимальное количество параллельных сессий (переопределяет maxInstances) */
	// maxSession: 10,

	/** Использовать синхронное API */
	sync: true,

	/*
	 * Опция позволяет отладчику остановить выполнение тестов
	 * в месте вызова инструкции debugger.
	 * Для использования этой опции требуется наличие пакета node-inspector
	 */
	debug: false,

	/**
	 * Список сервисов, которые будет использоваться для запуска тестов
	 *
	 * selenium-standalone — позволяет автоматически запускать и останавливать
	 * работу selenium-сервера (используется только для localhost).
	 */
	// services: ['selenium-standalone'],

	/* Доступные значения: cucumber, mocha, jasmine */
	framework: 'mocha',

	mochaOpts: {
		'ui': 'bdd',

		'require': MochaHooks,
		'compilers': ['ts-node/register'],

		/* Количество попыток на выполнение теста, который не был пройден */
		'retries': 0,

		/** Включить профилирование (сильно увеличивает время выполения тестов) */
		// 'prof': true,

		/** Максимальное время на ожидание результата выполнения теста */
		'timeout': 5 * (60 * 1000),

		/** Показывать стек-трейс */
		'trace': true,
		'full-trace': true,

		/** Ругаться на вызов устаревших функций */
		'throw-deprecation': true,
		'trace-deprecation': true
	},

	/* Для репортера Allure требуется наличие установленного плагина в CI */
	reporters: ['spec', 'junit', YodaAllureReporter],

	/* Директории, куда будут складываться отчеты о прогонах */
	reporterOptions: {
		outputDir: utils.cache('reports'),

		'yoda-allure': {
			outputDir: utils.cache('yoda-allure-results')
		}
	},

	/* Директория, куда будут складываться скриншоты */
	// screenshotPath: utils.cache('shots'),

	/* Директория, куда будут складываться логи сервера */
	seleniumLogs: utils.cache('logs'),

	/*
	 * Список файлов, которые требуется запустить если не передано значение для
	 * опции --suite.
	 * Порядок файлов сохраняется, дубликаты исключаются
	 * ВАЖНО: без метода utils.specs опция --grep не будет работать
	 * если не передано значение в --suite!
	 *
	 * @see utils.specs — [ <files> ]
	 */
	specs: utils.specs(/** [ ... ] */),

	/**
	 * Набор тестовых кейсов
	 * ВАЖНО: без метода utils.suites опция --grep работать не будет!
	 *
	 * @see utils.suites — { <suite>: [ <files> ] }
	 */
	suites: utils.suites(/** { ...} */),

	/*
	 * Обратие внимание на то, что браузеры запускаются параллельно
	 * Конфигуратор https://wiki.saucelabs.com/display/DOCS/Platform+Configurator
	 *
	 * Внутри каждой группы доступны поля specs и exclude
	 *
	 * Список стандартных опций WebDriver и пр. см ниже по ссылке:
	 * @see https://***.mail.ru/projects/QA/repos/wd-capabilities/browse
	 */
	capabilities: utils.capabilities([
		{
			browserName: 'chrome'
		}
	]),

	/**
	 * Хук, который выполняет перед запуском тестов
	 *
	 * @namespace browser
	 * @param {Object} capabilities
	 * @param {Array} specs
	 */
	before (capabilities, specs) {
		browser.timeouts('implicit', this.waitForSelector);

		browser.on('error', error => {
			console.log('[WebDriver Error]:', error);
		});

		AllureRuntime.init(browser);

		let commands = new WebDriverIOAPI();

		commands.export('all');
	},

	afterSuite () {
		account.discard();
	}
};

process.on('unhandledRejection', error => {
	console.error('[UnhandledRejection Error]', error.stack);
});

process.on('message', function (error) {
	console.log('[Message Error]:', error.stack);
});
```


If you see the following fields are filled by other calls:

```js
{
	specs: utils.specs(/** [ ... ] */),
	suites: utils.suites(/** { ...} */),
}
```

```js
let AccountManager = require('@qa/account-manager');
let WebDriverIOUtils = require('@qa/wdio-utils');
let WebDriverIOAPI = require('@qa/wdio-api');
let MochaHooks = require.resolve('@qa/wdio-mocha-hooks');
let capabilities = require('@qa/wdio-capabilities');
let YodaAllureReporter = require('@qa/yoda-allure-reporter');
let AllureRuntime = require('@qa/yoda-allure-utils');
```

I don't like to execute these functions and modules several times. 
It would be nice to pass this config file to the Launcher as is.

**Comment by tjdavenport** [comment]
+1 I'd also like to see this get merged in.

**Comment by christian-bromann** [comment]
> So the simplest and cleanest solution to this problem is to use a js object instead of a file.

@axelhildingson this doesn't work, the launcher spawns child processes and we can't pass along a function with it. Also I don't think it is a good idea to be able to pass in an object to a function with a name like `addConfigFile`.

However we can't propagate functions (hooks) to child processes. This PR doesn't has the right solution for this problem. I don't see a problem using the tmp package to dynamically create config files.

**Comment by tjdavenport** [comment]
For anyone reading, I think you can dynamically pass along spec paths like this:

```
    let launcher = new Launcher('/wdio.conf.js', { 
      specs: ['some/spec/path']
    });
```

**Pull request closed without merging**
