### PR TITLE
Limit very long results in the log output

### PR DESCRIPTION
**Pull request by georgecrawford**
I'm using `browser.log('performance')` which returns a huge result string. It needs limiting in the console output.

### CODE REVIEW

**Comment by georgecrawford** [comment]
Not yet ready for merge

**Comment by georgecrawford** [comment]
This PR is ready now.

**Comment by christian-bromann** [comment]
@georgecrawford LGTM so far. Could your write some unit tests for that?

**Comment by christian-bromann** [comment]
@georgecrawford I think you missed to add the tests in your last commit

**Comment by georgecrawford** [comment]
Oops, sorry.

**Comment by christian-bromann** [comment]
Thanks!

**Pull request merged**
