### PR TITLE
setImmediateValue always throws an exception

### PR DESCRIPTION
**Pull request by agauthiez**
The assertion to throw the `ProtocolError` was wrong.

### CODE REVIEW

**Comment by agauthiez** [comment]
By the way I just noticed that the top documentation block includes `@for android` but I get a 501 ("Not yet implemented" `RuntimeError`) from Appium 1.4.16 when using the Android driver. It works with iOS though. Shouldn't it be changed?

**Comment by christian-bromann** [comment]
Thanks, good catch!

**Comment by agauthiez** [comment]
By the way I just noticed that the top documentation block includes `@for android`. Using Appium 1.4.16, it returns a 501 (a "Not yet implemented" RuntimeError) with the Android driver while it works on iOS. Shouldn't it be changed?

**Comment by christian-bromann** [comment]
Oh interesting, yeah could you do another PR then? I probably switched that up then.

**Pull request merged**
