### PR TITLE
build: change module from NodeNext to ESNext, module resolution from Node16 to Node

### LINKED ISSUE #9729: [🐛 Bug]: Serenity WebdriverIO v8 adoption moduleResolution issues
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.3

### Node.js Version

16.18.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Not relevant
```

### What happened?

I'm working on introducing support for WebdriverIO v8 to [Serenity/JS](https://github.com/serenity-js/serenity-js) and face quite a few issues related to WebdriverIO type definitions/ESM setup. Unfortunately, those issues are currently blocking me from supporting WebdriverIO v8.

Here's some background, as per my [conversation on Gitter](https://gitter.im/webdriverio/webdriverio?at=63e2a4d26fc5ff38e451658b) with @christian-bromann:

- Serenity/JS is a Node.js framework written in TypeScript and relying on CommonJS and Node module resolution (for now; I wanted to upgrade WDIO to v8 before considering migrating to ESM)
- [`@serenity-js/webdriverio` module](https://github.com/serenity-js/serenity-js/tree/main/packages/webdriverio) providing support for integrating with WebdriverIO relies on several WebdriverIO APIs that you'll find referenced [on the `features/webdriverio-8`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio-8/packages/webdriverio/src/screenplay/models) branch I've prepared to work on the upgrade. 
- In particular, Serenity/JS relies on:
  - `Browser` and `Element` types from `webdriverio` in [`src/screenplay`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio-8/packages/webdriverio/src/screenplay)
  - `@wdio/types` and `@wdio/reporter` in [`src/adapter`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio-8/packages/webdriverio/src/adapter)

Serenity/JS WebdriverIO module is compiled using the following [effective `tsconfig.json`](https://github.com/serenity-js/serenity-js/blob/features/webdriverio-8/packages/webdriverio/tsconfig.json):
```json
{
  "compilerOptions": {
    "target": "es2019",
    "lib": [
      "es2019",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "noEmitOnError": false,
    "noImplicitOverride": false,
    "noImplicitReturns": true,
    "pretty": true,
    "removeComments": false,
    "types": [
      "node"
    ]
  }
}
```

It also relies on the following WebdriverIO modules, as you can see in its [`package.json`](https://github.com/serenity-js/serenity-js/blob/features/webdriverio-8/packages/webdriverio/package.json):
```
    "@wdio/cli": "^8.3.3",
    "@wdio/devtools-service": "^8.3.3",
    "@wdio/dot-reporter": "^8.3.0",
    "@wdio/local-runner": "^8.3.3",
    "@wdio/mocha-framework": "^8.3.0",
    "@wdio/reporter": "^8.3.0",
    "@wdio/spec-reporter": "^8.3.0",
    "@wdio/types": "^8.3.0",
    "webdriverio": "^8.3.3"
```

My understanding is that WebdriverIO v8 is designed to support both ESM and CommonJS-compatible consumers. 

However, with the above setup, I'm getting the following compilation error, as you can see in my [CI build on GitHub](https://github.com/serenity-js/serenity-js/actions/runs/4119757238/jobs/7113779569):

```
node_modules/webdriverio/node_modules/webdriver/build/types.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
```

The error is raised against:
```
     2  node_modules/@wdio/reporter/build/index.d.ts:1
     4  node_modules/@wdio/types/build/Options.d.ts:1
     2  node_modules/@wdio/types/build/Reporters.d.ts:1
     1  node_modules/@wdio/types/build/Services.d.ts:1
     1  node_modules/@wdio/types/build/Workers.d.ts:1
     1  node_modules/webdriverio/build/commands/browser/savePDF.d.ts:1
     1  node_modules/webdriverio/build/commands/browser/saveRecordingScreen.d.ts:1
     1  node_modules/webdriverio/build/commands/browser/saveScreenshot.d.ts:1
     1  node_modules/webdriverio/build/commands/element/saveScreenshot.d.ts:1
     1  node_modules/webdriverio/build/types.d.ts:1
     1  node_modules/webdriverio/build/utils/interception/devtools.d.ts:1
     1  node_modules/webdriverio/build/utils/interception/types.d.ts:1
     1  node_modules/webdriverio/node_modules/devtools/build/types.d.ts:1
     1  node_modules/webdriverio/node_modules/webdriver/build/bidi.d.ts:1
     2  node_modules/webdriverio/node_modules/webdriver/build/request/index.d.ts:1
     1  node_modules/webdriverio/node_modules/webdriver/build/types.d.ts:1
```

It feels like the issue is caused by the following assertion present in WebdriverIO dependencies:

```
/// <reference types="node" resolution-mode="require"/>
```

As per the error message, it seems like a consumer module **must** use `moduleResolution` of `node16`/`nodenext` in order to use WebdriverIO v8: 
```
error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.
```
However, switching to [`nodenext`](https://www.typescriptlang.org/tsconfig#moduleResolution) would force Serenity/JS and presumably all _its consumers_ to using [Node ESM](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs).

### What is your expected behavior?

I'd expect WebdriverIO v8 to support both CJS and ESM consumers.

Please feel free to point out any mistakes I might have made when attempting to migrate to v8 :-)

### How to reproduce the bug.

See https://github.com/serenity-js/serenity-js/pull/1493

### Relevant log output

```typescript
See checks for https://github.com/serenity-js/serenity-js/pull/1493
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by SCG82**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Fixes #9729

~~TODO: update tests (mainly remove a few .default)~~

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Great patch! Let's fix the tests and get this merged.

**Comment by SCG82** [comment]
@christian-bromann ready for review

**Review by christian-bromann — APPROVED** [review]
Awesome! 👍

**Comment by jan-molak** [comment]
Thanks @SCG82 and @christian-bromann! I'll give this a go as soon as it's on NPM

**Pull request merged**
