### PR TITLE
Allure report is missing steps, links data when the afterEach() hook is present is the suite #10185

### LINKED ISSUE #10185: [🐛 Bug]: Allure report is missing steps, links data when the afterEach() hook is present is the suite
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.7.0

### Node.js Version

18.14.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
"platformName": "Android",
"deviceName": "Emulator",
"app": "path_to.apk",
"appPackage": "com.sand.appname",
"appWaitActivity": "com.sand.appname.activity",
"udid": "emulator-5556",
"autoGrantPermissions": true,
"systemPort": 6001,
"port": 4723
}
```

### What happened?

When I add the **afterEach()** hook to the suite (**even if it's empty**) - the allure report doesn't contain any steps/links data. The report is fine without the hook.

```
afterEach(async () => {
     // there can be anything or even nothing
})
```

### What is your expected behavior?

Allure steps, severity, links etc. are shown in the report, the same as when I run tests without using the afterEach()

### How to reproduce the bug.

Add any test case inside the suite, add any allure steps data to the test case. Add the afterEach hook:

    afterEach(async () => {
        // anything here or leave empty
    })

NOTE: I'm not sure about other hooks but 100% repro with these steps above

Repo with the code to reproduce (see the readme.md inside): https://github.com/Medvedscak/webdriverio-allure-issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### LINKED ISSUE #10644: [🐛 Bug]: Tag above Examples table doesn't work wdio-cucumberjs
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.8

### Node.js Version

18.16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        maxInstances: 5,
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['head', 'disable-gpu']
        },
        acceptInsecureCerts: true
}
```

### What happened?

We I put a tag above Examples table, show Spec Files:  0 passed, 1 skipped, 0 total (0% completed) in 00:00:0
I am triying run this feature:
```
Feature: The Internet Guinea Pig Website
 @thisTagWorks
  Scenario Outline: As a user, I can log into the secure area
     Given I am on the "login" page
     When I login with "<username>" and "<password>"
     Then I should see a flash message saying "<message>"
     @thisTagDoesntWork
     Examples:
       | username | password             | message                        |
       | tomsmith | SuperSecretPassword! | You logged into a secure area! |
       | foobar   | barfoo               | Your username is invalid!      |
```
```
package.json
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/cli": "^8.6.8",
    "@wdio/cucumber-framework": "^8.6.8",
    "@wdio/local-runner": "^8.6.8",
    "@wdio/spec-reporter": "^8.6.8",
    "chromedriver": "^113.0.0",
    "wdio-chromedriver-service": "^8.1.1"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  },
  "dependencies": {
    "pixelmatch": "^5.3.0"
  }
}
```

I am using webdriverio and cucumber. Additionally I have tried in protractor and cucumber and it works.

### What is your expected behavior?

The scenario in feature file should be ran.

### How to reproduce the bug.

I could replicate on this repository
https://github.com/ldelosreyesm/wdio_poc

and run 
Mac or Linux
make wrer-module arg=TAG2RUN 
Windows
npm run wdio -- --cucumberOpts.tagExpression=TAG2RUN

### Relevant log output

```typescript
Spec Files:  0 passed, 1 skipped, 0 total (0% completed) in 00:00:00
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by BorisOsipov**
## Proposed changes
closes #10185

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@BorisOsipov thanks for the PR, are you sure it is related to https://github.com/webdriverio/webdriverio/issues/10644 given that the issue author doesn't mention Allure

**Comment by BorisOsipov** [comment]
@christian-bromann ahh it is missprint. fixed.

**Comment by christian-bromann** [comment]
Sorry for the failing build, I will try to fix asap and update the branch.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by christian-bromann** [comment]
It seems a valid test is failing:

```
 FAIL  packages/wdio-allure-reporter/tests/suite.test.ts > Hook reporting > should report failed before each hook
AssertionError: expected '"before each" hook' to deeply equal 'My Login application'

- Expected
+ Received

- My Login application
+ "before each" hook

 ❯ packages/wdio-allure-reporter/tests/suite.test.ts:453:33
    451| 
    452|         expect(results).toHaveLength(2)
    453|         expect(results[0].name).toEqual('My Login application')
       |                                 ^
    454|         expect(results[0].status).toEqual(Status.BROKEN)
    455|         expect(results[1].name).toEqual('"before each" hook')
```

**Comment by BorisOsipov** [comment]
@christian-bromann fixed

**Review by christian-bromann — APPROVED** [review]
Awesome, LGTM 👍

**Pull request merged**
