### PR TITLE
Issue 7651: add Cucumber World object back to step/scenario hooks

### PR DESCRIPTION
**Pull request by jvisco**
## Proposed changes

* Fixes issue https://github.com/webdriverio/webdriverio/issues/7651 by including Cucumber's World object in the Before/After Step/Scenario hooks 
* Updates adapter unit test.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have ~added~ updated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Thanks for taking a stab at this! Looks good to me, just one comment:

Can we also update the example config files in:

- examples/pageobject/wdio.conf.js
- packages/wdio-cli/src/templates/wdio.conf.tpl.ejs
- packages/wdio-cucumber-framework/src/types.ts
- website/docs/ConfigurationFile.md
- website/docs/Options.md

**Review by christian-bromann — APPROVED** [review]
Thanks a lot 👍

**Comment by jvisco** [comment]
@christian-bromann Is the `e2e-windows` test failure a blocker? It appears unrelated to this PR.

**Comment by christian-bromann** [comment]
@jvisco rerunning them has fixed the issue.

**Pull request merged**
