### PR TITLE
Add documentation to overwrite and add commands

### PR DESCRIPTION
**Pull request by AutomationReddy**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by mgrybyk — APPROVED** [review]

**Review by christian-bromann — APPROVED** [review]
👌 perfect!

**Comment by christian-bromann** [comment]
@AutomationReddy can you modify [this test](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/tests/commands/browser.test.js#L11-L16) to this to make it pass:

```js
test(scope + ' commands list and strategies', () => {
    const prototype = Object.keys(getPrototype(scope))
    const expected = ['puppeteer', '_NOT_FIBER', ...files, 'strategies']
    /**
     * ignored commands that are just there for documentation purposes
     */
    const ignored = ['addCommand', 'overwriteCommand']

    expect(prototype).toEqual(expected.filter((cmd) => ignored.includes(cmd)))
})
```

**Comment by AutomationReddy** [comment]
@christian-bromann Requested changes were done. Thanks.

**Comment by AutomationReddy** [comment]
@christian-bromann The build was failed again even after modifying the test. 
What I found was: 

Issue is in this line: `expect(prototype).toEqual(expected.filter((cmd) => ignored.includes(cmd)))`

The above filter only returns addCommand and overwriteCommand where we actually need to ignore them from the expected array. So, keeping a not `!` will resolve the problem.

`expect(prototype).toEqual(expected.filter((cmd) => !ignored.includes(cmd)))`

**Failed in CI:**
image

**After modifying:**
image

Please let me know, if this is acceptable.

**Comment by christian-bromann** [comment]
good catch, thanks!

**Pull request merged**
