### PR TITLE
Upgrade to import-meta-resolve v4.1.0 to avoid node 22 deprecation warning

### PR DESCRIPTION
**Pull request by mo**
node v22 prints a deprecation warning:
(node:429057) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.

The "import-meta-resolve" package was using the deprecated API in 4.0.0 but they stopped using the deprecated API in 4.1.0. This PR upgrades to 4.1.0 for a few packages where webdriverio was using 4.0.0

node v22 will be LTS very very soon so it's nice to clean up this warning

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Given that `import-meta-resolve` is defined with a `^` it should automatically pick up minor updates to the package. It requires you to update it on your side by updating your pnpm-lock or npm lock file. There is no need to for this patch as it won't have any impact to the user.

**Comment by mo** [comment]
@christian-bromann that makes sense... however, I have upgraded all webdriver/wdio packages to latest and I still get the error? what am I missing?
image

**Comment by christian-bromann** [comment]
Did you try to rebuild your npm-lock file?

**Comment by mo** [comment]
@christian-bromann I used "npm-check --update" to update wdio and then it updated my deps but the lock file still pointed to 4.0.0 for import-meta-resolve (very strange for an update tool to behave in that way imo?). After that I tried to delete package-lock.json, re-ran "npm install" and I still had import-meta-resolve 4.0.0 in the regenerated lock file. After that I tried to delete node_modules and re-ran "npm install". Still import-meta-resolve 4.0.0 as well. Finally, I tried to BOTH delete the package-lock.json and node_modules simultaneously and re-ran "npm install" and this fixed it, this time I got 4.1.0 for import-meta-resolve. It perplexes me that "npm-check --update" (a tool with the main purpose of upgrading stuff) doesn't just upgrade the transitive deps?!

**Comment by christian-bromann** [comment]
This is why I am using pnpm for my projects as the experience is much better for these scenarios.

**Pull request closed without merging**
