### PR TITLE
Fix error in onHookEnd in reporter for Mocha

### PR DESCRIPTION
**Pull request by sriteja777**
## Proposed changes
The `onHookEnd` in reporter will get called for all frameworks, but we only need to handle it for Jasmine. While other hooks in reporter had handling for frameworks, we missed adding framework handling for `onHookEnd` reporter in v7. So added the framework handler for onHookData too.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Can you explain which bug are you trying to fix with this patch? Also could we have a unit test for this to avoid regression?

**Comment by sriteja777** [comment]
@christian-bromann Have added it to description. Also added tests

**Review by christian-bromann — APPROVED** [review]
Awesome, thanks 👍

**Comment by christian-bromann** [comment]
Seems like when I triggered the last release [it failed](https://github.com/webdriverio/webdriverio/actions/runs/5595390368/job/15155887868) which I didn't notice. Triggered a new release.

**Comment by sriteja777** [comment]
thanks!

**Pull request merged**
