### PR TITLE
Fix "Error in hook: undefined" error message

### PR DESCRIPTION
**Pull request by hieuxlu**
## Proposed changes

Fix error loggin in runLauncherHook, which might result in confusing error message: "Error in hook: undefined"

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by mgrybyk** [comment]
When does this happen?

**Comment by christian-bromann** [comment]
I think this happens if you return a rejected promise passing in a string instead of an error:

```js
onPrepare () {
	return Promise.reject('foo')
}
```

This is rather a user error given that rejected promises should have an error object and not a string.

**Comment by martinfrancois** [comment]
@hieuxlu maybe you can add a test which reproduces the error you've been getting? (Also to make sure we don't run into regressions later).

**Comment by hieuxlu** [comment]
This is indeed an user error. In my case, it's when you request an API during `onPrepare` and reject the Promise using the error response. I closed this because this can be delegated to user for handling these kind of errors, and throw an Error object correctly. Thanks.

**Pull request closed without merging**
