### PR TITLE
fix hostname cli param

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

host option was changed to hostname. Adapted this to cli.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by rdpanek** [comment]
@christian-bromann this change works well

**Comment by christian-bromann** [comment]
released as `@wdio/cli@5.1.2`

**Comment by tbradley-sans** [comment]
Looks like this web page also needs to be updated to reflect the change: https://webdriver.io/docs/options.html

**Comment by christian-bromann** [comment]
@tbradley-sans that's true. Would you mind creating a PR?

**Pull request merged**
