### PR TITLE
browserstack missing capabilities

### PR DESCRIPTION
**Pull request by Vaahin**
## Proposed changes

[//]: # This PR is to include missing browser stack network capabilities. Link to BS - https://www.browserstack.com/docs/app-automate/appium/debug-failed-tests/network-logs

https://github.com/webdriverio/webdriverio/issues/11836

## Types of changes

[//]: # This is a new inclusion which is missing and there is no change to any existing features or code.
[//]: # (_Put an `x` in the boxes that apply_)

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ x ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by Vaahin** [comment]
I have signed the CLA .

**Comment by christian-bromann** [comment]
@Vaahin did you signed it with the same email used to make the commit?

**Comment by Vaahin** [comment]
I believe yes ! Is there other ways to check ?

**Comment by christian-bromann** [comment]
> I believe yes ! Is there an other way to check ?

check your `$ git log` and see if the commit is connected to an email you have used.

**Comment by Vaahin** [comment]
I know where the problem is , I will use the right email to commit and create a new PR ! Thanks for the information .

**Pull request closed without merging**
