### PR TITLE
Select proper input via ancestor label when multiple match

### LINKED ISSUE #12883: [🐛 Bug]: `aria/` selector fails when selecting an input related to a label when there are multiple inputs in the document
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v20.12.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  browserVersion: 'canary',
  webSocketUrl: true
}
```

### What happened?

The XPath selector under `aria/` for finding an `input` or `textarea` related to a `label` do not function properly in cases where there are multiple elements. I have set up test cases for various scenarios, but basically the issue is this when we have a setup like this:
```html
<label>
    Search 1
    <textarea>Hello World! 1</textarea>
</label>
<label>
    Search 2
    <textarea>Hello World! 2</textarea>
</label>
```

If we want to find an input attached to the label `"Search 2"`, we would write `$('aria/Search 2')`.

Currently, that yields the first textarea containing `Hello World! 1`.

The relevant XPath selectors are:
https://github.com/webdriverio/webdriverio/blob/82b38637847c93ee8f7214244e1fc63c72565b3b/packages/webdriverio/src/utils/findStrategy.ts#L180-L181

I'm no XPath XPert, but I believe this XPath is essentially saying:
> Find an input where an ancestor of the document root contains a label with text matching "Search 2"

In other words, the `//` is making XPath find every input in the document, so long as there is a label matching "Search 2".

What we want is for it to say:
> Find an input where a direct ancestor of the input is a label with text matching "Search 2" 

Removing the `//` fixes this issue in the tests.

### What is your expected behavior?

_No response_

### How to reproduce the bug.

Run the `e2e` test suite `lit` tests:
```sh
npm -C e2e run test:browser:lit
```

### Relevant log output

**Before the fix**
```typescript
"spec" Reporter:
------------------------------------------------------------------
[chrome 127.0.6483.0 linux #0-0] Running: chrome (v127.0.6483.0) on linux
[chrome 127.0.6483.0 linux #0-0] Session ID: 6bff94eadd96b320978f7aa937ad6fd9
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] » file:///browser-runner/lit.test.js
[chrome 127.0.6483.0 linux #0-0] Lit Component testing
[chrome 127.0.6483.0 linux #0-0]     Selector Tests
[chrome 127.0.6483.0 linux #0-0]         a11y selectors
[chrome 127.0.6483.0 linux #0-0]            ✓ input with a label
[chrome 127.0.6483.0 linux #0-0]            ✖ multiple inputs with a label
[chrome 127.0.6483.0 linux #0-0]            ✓ textarea with a label
[chrome 127.0.6483.0 linux #0-0]            ✖ multiple textareas with a label
[chrome 127.0.6483.0 linux #0-0]            ✓ input with a label as parent
[chrome 127.0.6483.0 linux #0-0]            ✖ multiple inputs with a label as parent
[chrome 127.0.6483.0 linux #0-0]            ✓ textarea with a label as parent
[chrome 127.0.6483.0 linux #0-0]            ✖ multiple textareas with a label as parent
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] 4 passing (24.3s)
[chrome 127.0.6483.0 linux #0-0] 4 failing
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] 1) a11y selectors multiple inputs with a label
[chrome 127.0.6483.0 linux #0-0] Expect  to have property value

Expected: "Hello World 2"
Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0] Error: Expect  to have property value
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] Expected: "Hello World 2"
[chrome 127.0.6483.0 linux #0-0] Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0]     at Context.<anonymous> (http://localhost:41311/home/evan/dev/webdriverio/e2e/browser-runner/lit.test.js:575:37)
[chrome 127.0.6483.0 linux #0-0]     at Context.executeAsync (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/shim.ts:329:24)
[chrome 127.0.6483.0 linux #0-0]     at Context.testFrameworkFnWrapper (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/test-framework/testFnWrapper.ts:94:18)
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] 2) a11y selectors multiple textareas with a label
[chrome 127.0.6483.0 linux #0-0] Expect  to have property value

Expected: "Hello World 2"
Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0] Error: Expect  to have property value
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] Expected: "Hello World 2"
[chrome 127.0.6483.0 linux #0-0] Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0]     at Context.<anonymous> (http://localhost:41311/home/evan/dev/webdriverio/e2e/browser-runner/lit.test.js:605:37)
[chrome 127.0.6483.0 linux #0-0]     at Context.executeAsync (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/shim.ts:329:24)
[chrome 127.0.6483.0 linux #0-0]     at Context.testFrameworkFnWrapper (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/test-framework/testFnWrapper.ts:94:18)
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] 3) a11y selectors multiple inputs with a label as parent
[chrome 127.0.6483.0 linux #0-0] Expect  to have property value

Expected: "Hello World! 2"
Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0] Error: Expect  to have property value
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] Expected: "Hello World! 2"
[chrome 127.0.6483.0 linux #0-0] Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0]     at Context.<anonymous> (http://localhost:41311/home/evan/dev/webdriverio/e2e/browser-runner/lit.test.js:641:37)
[chrome 127.0.6483.0 linux #0-0]     at Context.executeAsync (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/shim.ts:329:24)
[chrome 127.0.6483.0 linux #0-0]     at Context.testFrameworkFnWrapper (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/test-framework/testFnWrapper.ts:94:18)
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] 4) a11y selectors multiple textareas with a label as parent
[chrome 127.0.6483.0 linux #0-0] Expect  to have property value

Expected: "Hello World! 2"
Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0] Error: Expect  to have property value
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] Expected: "Hello World! 2"
[chrome 127.0.6483.0 linux #0-0] Received: "Hello World! 1"
[chrome 127.0.6483.0 linux #0-0]     at Context.<anonymous> (http://localhost:41311/home/evan/dev/webdriverio/e2e/browser-runner/lit.test.js:677:37)
[chrome 127.0.6483.0 linux #0-0]     at Context.executeAsync (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/shim.ts:329:24)
[chrome 127.0.6483.0 linux #0-0]     at Context.testFrameworkFnWrapper (http://localhost:41311/@fs/home/evan/dev/webdriverio/packages/wdio-utils/src/test-framework/testFnWrapper.ts:94:18)


Snapshot Summary:
3 snapshot(s) unchecked.

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:29  
```

**After the fix**
```typescript
"spec" Reporter:
------------------------------------------------------------------
[chrome 127.0.6483.0 linux #0-0] Running: chrome (v127.0.6483.0) on linux
[chrome 127.0.6483.0 linux #0-0] Session ID: b51db7f73310e443561ae24d22dd1be9
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] » file:///browser-runner/lit.test.js
[chrome 127.0.6483.0 linux #0-0] Lit Component testing
[chrome 127.0.6483.0 linux #0-0]     Selector Tests
[chrome 127.0.6483.0 linux #0-0]         a11y selectors
[chrome 127.0.6483.0 linux #0-0]            ✓ input with a label
[chrome 127.0.6483.0 linux #0-0]            ✓ multiple inputs with a label
[chrome 127.0.6483.0 linux #0-0]            ✓ textarea with a label
[chrome 127.0.6483.0 linux #0-0]            ✓ multiple textareas with a label
[chrome 127.0.6483.0 linux #0-0]            ✓ input with a label as parent
[chrome 127.0.6483.0 linux #0-0]            ✓ multiple inputs with a label as parent
[chrome 127.0.6483.0 linux #0-0]            ✓ textarea with a label as parent
[chrome 127.0.6483.0 linux #0-0]            ✓ multiple textareas with a label as parent
[chrome 127.0.6483.0 linux #0-0]
[chrome 127.0.6483.0 linux #0-0] 8 passing (4s)


Snapshot Summary:
3 snapshot(s) unchecked.

Spec Files:      1 passed, 1 total (100% completed) in 00:00:08
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by evankennedy**
## Proposed changes

Fixes #12883

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at #12889

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Amazing stuff, LGTM 👍

**Comment by evankennedy** [comment]
My apologies @christian-bromann, I left in a lingering `.only`. That's what I get for late-night coding on a new project.

I removed the `.only` and squashed all the commits together. Tests should pass now. Thanks for hanging in there with me.

If you want it, backported PR available at #12889.

**Comment by christian-bromann** [comment]
> That's what I get for late-night coding on a new project.

haha, no worries, happens to me all the time 😉

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Pull request merged**
