### PR TITLE
SivasubramanianV:fix-docs-capabilities driver to browser

### PR DESCRIPTION
**Pull request by SivasubramanianV**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Awesome, thanks for the fix. Mind signing the CLA?

**Comment by SivasubramanianV** [comment]
Thanks Christian, how do i sign the SLA?

**Comment by christian-bromann** [comment]
> I have signed the CLA.

Did you use the same email as used to make the commit?

**Comment by SivasubramanianV** [comment]
> > I have signed the CLA.
> 
> Did you use the same email as used to make the commit?

Both are different, the one I made commit is my spouse git account. Should I recommit?

**Comment by christian-bromann** [comment]
> Should I recommit?

Yes, please overwrite your existing commit or just re-raise the PR.

**Comment by SivasubramanianV** [comment]
I have amended my last commit with different author(my account)
 git commit --amend --author="SivasubramanianV <shivmanny@gmail.com>" --no-edit

**Comment by christian-bromann** [comment]
@SivasubramanianV can you force push it to this branch.

**Comment by SivasubramanianV** [comment]
Can you provide permission
fatal: unable to access 'https://github.com/webdriverio/webdriverio.git/': The requested URL returned error: 403
PS C:\Users\Siva\webdriverio\webdriverio> git branch
* fix-docs-capabilities
  main

**Comment by christian-bromann** [comment]
> Can you provide permission

Please do the force push to your fork.

**Comment by SivasubramanianV** [comment]
Sure i will make it soon

**Comment by SivasubramanianV** [comment]
@christian-bromann please check if this is fine to merge

**Comment by christian-bromann** [comment]
It seems like you know added a [commit](https://github.com/webdriverio/webdriverio/commit/f792e56ddb42aa9a13e7bbc5a8376250be6e70ab) from the other branch that has been made with the a different email address so the CLA is breaking again.

**Pull request closed without merging**
