### PR TITLE
Documentation - pageobjects.md Fix ES6 Page Object

### PR DESCRIPTION
**Pull request by mossnz**
Fixing ES6 page.js error on exported module

## Proposed changes

The ES6 sample page objects provided in the documentation `pageobjects.md` do not work in Node 8.0.0

The export of `page.js` will cause an error when extended in the sample `login.js` of
`TypeError: Class extends value #<Page> is not a constructor or null`

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
You are right, this is indeed not correct. Can we also change the non es6 example in [line 30](https://github.com/webdriverio/webdriverio/pull/2138/files#diff-1ff639a6e3fd0c1a405d827d4e5fb2d1R30)? Thanks!

**Comment by mossnz** [comment]
@christian-bromann 

If we change [line 30](https://github.com/webdriverio/webdriverio/pull/2138/files#diff-1ff639a6e3fd0c1a405d827d4e5fb2d1R30) in the non ES6 example,

The non ES6 `login` page will still load without an error, but when attempting to use [line 71](https://github.com/webdriverio/webdriverio/pull/2138/files#diff-1ff639a6e3fd0c1a405d827d4e5fb2d1L71), `login.open()` an error `TypeError: Cannot read property 'call' of undefined` will occur.

It seems that the `page.js` exports need to be different for differences in ES6 classes and Object.create

**Comment by christian-bromann** [comment]
@mossnz is it possible that Node v8 behaves different than lower versions?

**Comment by ianrenauld** [comment]
I agree with the change for the ES6 version and line 30 did work for me when I was using non-ES6, but then again I never tried it on Node v8.

One more thing that I feel we should change on this document is to add `LoginPage.flash.waitForVisible();` right after both `LoginPage.submit();` lines in the login.spec.js file.  Otherwise for me the example did not work (the "flash" message takes a little while to show up after submitting the form).

It's always best to have actual working examples so beginners get going on the right foot!

**Comment by christian-bromann** [comment]
thanks @mossnz for the PR. I added some additional changes to it (including the suggestion of @ianrenauld).

**Pull request closed without merging**
