### PR TITLE
Fix for isW3C

### PR DESCRIPTION
**Pull request by Oleksandr-Antonkin-epam**
Remove verification of "capabilities.platformName" from "isW3C" method.
Source of request (discussion) : https://gitter.im/webdriverio/webdriverio?at=60b6086379350e7f9276d9e9

## Proposed changes

[//]: # (Hi, I have a question regarding determination of W3C standart in webdriverIO (WebDriver version "7.6.1", NodeJS version 14) The thing is:
I am using Docker image "browsers/safari:14.0" and when "utils.js: startWebDriverSession" sends request in response we have only "browserVersion", "browserName" and "pageLoadStrategy" variables. "platformName" is not present in response.

Than when we call "envDetector.js: sessionEnvironmentDetector" and decide if it is a W3C or not we are getting "capabilities.platformName" variable as undefined and isW3C gets "false"....
And after couple blocs of code we get to browser.executeScript() method which makes a call to endpoint: "/session/{sessionid}/execute" and receive:
"Request failed with status 404 due to unknown command: Unknown command: /session/...../execute" and this is wrong endpoint, correct is (which is used if we hardcode W3C as true) "/session/..../sync"

So, the questing is.... how can we force to use W3C standart. Or overwrite determination of "isW3C" variable... may be there is a way we can overwrite "startWebDriverSession" and make hook to add "platformName" into returned capabilities.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by Oleksandr-Antonkin-epam** [comment]
@christian-bromann please take a look at this PR

**Review by christian-bromann — APPROVED** [review]
Excellent, thank you 👌

**Comment by christian-bromann** [comment]
@Oleksandr-Antonkin-epam mind signing the CLA?

**Comment by ShadySet** [comment]
> @Oleksandr-Antonkin-epam mind signing the CLA so I can merge?

Ok, but what is CLA? Where to click?

**Comment by Oleksandr-Antonkin-epam** [comment]
> @Oleksandr-Antonkin-epam mind signing the CLA so I can merge?

Ok, byt what is CLA, and were I should click?

**Comment by Oleksandr-Antonkin-epam** [comment]
> @Oleksandr-Antonkin-epam mind signing the CLA so I can merge?

@christian-bromann done

**Comment by christian-bromann** [comment]
Released in `v7.7.2`

**Pull request merged**
