### PR TITLE
Fix failing test `should scroll to specific x and y position` (and update bower.json)

### PR DESCRIPTION
**Pull request by mkelley33**
## Proposed changes

[//]: Fix a failing test in test/spec/desktop/scroll.js `should scroll to specific x and y position`. This  will also a fix invalid meta in bower.json by changing the name to lowercase and dasherized.

## Types of changes

[//]: Fixes failing test and invalid meta in bower.json
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: Tested with chromedriver: stable 2.33 installed via brew. Also, using npm v5.3.0 and node v8.4.0.

### CODE REVIEW

**Comment by mkelley33** [comment]
@jsf-clabot I signed the CLA, and Michaux Kelley *is* a GitHub user aka @mkelley33 and the e-mail address used for this commit is added to my account.

**Comment by mkelley33** [comment]
@christian-bromann package.lock was updated after I ran `npm install`, so I thought I was supposed to commit that.  When I was running `bower install` I received warnings ```bower invalid-meta  for: .../test/site/www/bower.json bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes``` I'll revert the bower.json change and package-lock.json changes.  Why aren't the package-lock.json changes necessary?

**Comment by christian-bromann** [comment]
@mkelley33 got it. Then both changes are ok. Just need to get the CLA signed. Not sure why it didn't work for you in the first place

**Comment by mkelley33** [comment]
Yeah, when I go to sign the CLA, it shows that I've already signed it.

**Comment by mkelley33** [comment]
@christian-bromann were there other changes that I need to make, before this PR is approved and/or merged? BTW I did happen to notice that the build has been failing for quite some time now. Do you know if someone(s) actively working to resolve that?

**Comment by christian-bromann** [comment]
> Do you know if someone(s) actively working to resolve that?

Yes, I am but haven't had much time recently

**Comment by mkelley33** [comment]
@christian-bromann if you look under the "Some checks were not successful" section below, you'll see the message "Contributor License Agreement is signed." If you don't, let me know, and if there's still an issue, I may contact Github support to see if there's anything they can do to help resolve this. 

I'm not sure my test change works in Safari and FF as well. I tried changing the browser to safari and selected "Allow Remote Automation" in the Safari "Develop" menu, but the test failed stating that `A request to use a window could not be satisfied because the window could not be found.` Some cursory googling revealed that it may be a bug with the version of Safari. I'm updating my OS tonight, and will check back at some point to see if that's true as well as try to figure out how to set Firefox as the browser correctly and test that.

I'm kind of busy getting ready for a new job, so it may be a while before I can get around to testing in Safari and Firefox, but if it isn't as problematic for you to run the test in those browsers, then maybe you could check for me and let me know if it passes. Otherwise, I'll get to it as soon as I can, thanks.

**Comment by christian-bromann** [comment]
Seems the CLA issue is resolved. Merging.

**Pull request merged**
