### PR TITLE
Fix invalid urls

### PR DESCRIPTION
**Pull request by christian-bromann**
**Is your feature request related to a problem? Please describe.**
When navigating to pages like:
- google.com
- www.google.com
the driver will fail because the url is invalid.

**Describe the solution you'd like**
Always prepend an http in front of the url.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@CrispusDH @BorisOsipov can anyone review this small fix?

**Comment by christian-bromann** [comment]
The current code will actually prevent navigating to urls such as `about:blank` .. not sure if this can have consequences, however people could still use the navigate command that comes without magic.

**Comment by CrispusDH** [comment]
> what about special urls like `about:blank` or `data:text/html, <html contenteditable>` ?

@christian-bromann could we make exceptions for those kind of urls?

**Comment by BorisOsipov** [comment]
We use at least `about:blank` to avoid some issues with SPA routing.

They are legal url schemas. Why should we forbid users to access them?

So I suppose adjust solution by replacing "Always prepend an http in front of the url." =>
"Prepend an http in front of the url *if schema is not specified*"

**Comment by christian-bromann** [comment]
@BorisOsipov @CrispusDH thanks for the feedback, I think I found a good solution using the internal `URL` constructor. Please have a look!

**Pull request merged**
