### PR TITLE
Fixed issue with jest transpilation

### PR DESCRIPTION
**Pull request by oscarocornejo**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
I have a module A which is importing a module B which uses webdriverio. Module A is written with typescript, and has Jest unit tests with typescript runtime transpilation. While running these tests, with the new version of Module B (which now uses wdio-shared-store), there was a recurring issue: **you need to run with a version of node that supports ES Modules in the VM API.**

This change to the way WebdriverIO is importing, allows the transpilation to happen smoothly.
It also isn't a materially significant change to the code.

After making this change locally, all jest tests were passing again.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
Moving import() from the top level of the file, to the function.

[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by erwinheitzman** [comment]
The code seems to be the same as before just structured differently, I'm not sure if this has an actual impact?

**Comment by erwinheitzman** [comment]
Can we have a test to prove this has an actual impact to how the import is done?

**Comment by oscarocornejo** [comment]
Yes, the error was showing up when trying to use ts-jest with jest

I ended up solving the issue by just mocking the imported Module B.
I can potentially add a test later in the week

**Comment by christian-bromann** [comment]
I will go ahead and close this it seems this change isn't necessary anymore.

**Pull request closed without merging**
