### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bcholewinski**
## Proposed changes
I corrected the configuration description because the previous one was not correct and did not want to work. I did not find something like `afterStep`, but using `afterTest` instead fixed the problem.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@bcholewinski `beforeStep` and `afterStep` are for Cucumber users. I wonder if we should just mention this instead of replacing the hooks? Wdyt?

**Comment by christian-bromann** [comment]
> It would be useful, to describe this for both cases separately.

Would you mind making a suggestion so it is more clear?

**Comment by christian-bromann** [comment]
ping @bcholewinski

**Comment by bcholewinski** [comment]
When you see the documentation at https://webdriver.io/docs/allure-reporter#add-screenshots, it is not mentioned anywhere that the description of adding screenshots to the report pertains solely to "cucumber".

This caused me to struggle to get this feature to work for a long time until a random YouTube video helped me where they changed "afterStep" to "afterTest". As a result, I considered this to be a documentation error.

If you think differently, let's just close this PR because frankly, I don't have much time to deal with this at the moment and to better describe what needs to be done in both cases.

**Pull request closed without merging**
