### PR TITLE
Updated ConfigParser waitforTimeout default to match docs

### PR DESCRIPTION
**Pull request by broder**
## Proposed changes

The default value for waitforTimeout in ConfigParser differed from everywhere else in the codebase. This change should correct that.

## Types of changes

What types of changes does your code introduce to WebdriverIO?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
> differed from everywhere else in the codebase

not sure to what you are referring to but I think we should keep it as is to make sure the waitForXXX command checks at least twice.

**Comment by broder** [comment]
Everywhere else in the code waitforTimeout is 500ms and waitforInterval is 250ms e.g. https://github.com/webdriverio/webdriverio/blob/master/docs/guide/getstarted/configuration.md#waitfortimeout. Should we update all these instances to be 1000 / 500ms or just update those in ConfigParser to be 500 / 250ms?

**Comment by christian-bromann** [comment]
> should we update all these instances to be 1000 / 500ms or just update those in ConfigParser to be 500 / 250ms?

Let's update the docs then and also [here](https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L44)

**Comment by broder** [comment]
Sounds good - do you want to reopen this PR or should I raise a new one?

**Comment by christian-bromann** [comment]
I can't reopen this one anymore so please create a new PR. Thanks!

**Pull request closed without merging**
