### PR TITLE
Fix for error handling on before/after hooks

### PR DESCRIPTION
**Pull request by WillBrock**
## Proposed changes

In reference to https://github.com/webdriverio/webdriverio/issues/2494

Tested on mocha and jasmine. It seems to be working when the hooks are before or inside of describe.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jaridmargolin** [comment]
What is the status here? This bug results in swallowed stack traces for any errors in the before/after hooks. It is really difficult to get any insight into failed tests... especially on a CI.

**Comment by gregjopa** [comment]
The Travis build is now failing with the error "Could not start Sauce Connect". Perhaps it just needs to be re-run. 

Looking forward to this fix. Let me know if there's anything I can do to help get this merged.

**Comment by wearhere** [comment]
Can you publish this fix to npm please?

**Comment by serut** [comment]
Still not published ?

**Comment by christian-bromann** [comment]
it is

**Comment by serut** [comment]
Ok. Maybe our Nexus prevents us to get that update.

```
$ npm i
npm ERR! notarget No compatible version found: webdriverio@^4.10.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.9.11, 4.9.10, 4.9.9, 4.9.8, 4.9.7, 4.9.6, 4.9.5, 4.9.4, 4.9.3, 4.9.2, 4.9.1, 4.9.0, 4.8.0, 4.7.1, 4.7.0, 4.6.2, 4.6.1, 4.6.0, 4.5.2, 4.5.1, 4.5.0, 4.4.0, 4.3.0, 4.2.16, 4.2.15, 4.2.14, 4.2.13, 4.2.12, 4.2.11, 4.2.10, 4.2.9, 4.2.8, 4.2.7, 4.2.5, 4.2.4, 4.2.3, 4.2.1, 4.2.0, 4.1.1, 4.1.0, 4.0.9, 4.0.8, 4.0.7, 4.0.5, 4.0.4, 4.0.3, 4.0.2, 4.0.1, 4.0.0, 3.4.0, 3.3.0, 3.2.6, 3.2.5, 3.2.4, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.1.0, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.0, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.2, 2.1.1, 2.1.0, 2.0.1, 2.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```

**Comment by christian-bromann** [comment]
It is released tho: https://www.npmjs.com/package/webdriverio

**Comment by serut** [comment]
Thanks for the clue ! The issue was on our side.

**Pull request merged**
