### PR TITLE
[junit-reporter]: Add function to add additional properties to testcases

### PR DESCRIPTION
**Pull request by sebastian-sauer**
## Proposed changes

This PR allows to add custom properties to testcases in junit xml report.

## Types of changes

- [ ] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

This PR builds on top of changes in https://github.com/webdriverio/webdriverio/pull/13526

### CODE REVIEW

**Comment by christian-bromann** [comment]
@sebastian-sauer I see that this PR also contains commits for #13526, can we create two separate PRs to make reviewing this easier?

**Comment by sebastian-sauer** [comment]
Unfortunately this PR is based on the changes in #13526 (as it uses the new additionalInfoToTestCase property). Not sure how to separate this. My hope was that #13526 is already merged when this PR gets a review ;) 

Do you got any tips how to separate this PR?

**Comment by sebastian-sauer** [comment]
@christian-bromann now the diff includes only the changes for this PR. Is it ok that way? Or should i create a new "fresh" pr with only the commits for this change?

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

I will raise a PR to have a CJS export for this package so people can also require the reporter API.

**Pull request merged**
