### PR TITLE
Check for unsupported `"engines"` package.json fields

### PR DESCRIPTION
**Pull request by colinrotherham**
Reopened from https://github.com/webdriverio/webdriverio/pull/11823 and closes https://github.com/webdriverio/webdriverio/issues/11868

## Proposed changes

Follow up to https://github.com/webdriverio/webdriverio/issues/11793 to configure **.npmrc** with `engine-strict=true` and `strict-peer-dependencies=true` which will prevent Dependabot PRs from successfully completing `pnpm install` when package updates require Node.js > v18 etc

Rather than [silently log warnings](https://github.com/webdriverio/webdriverio/actions/runs/7085870979/job/19282976254#step:4:15) `pnpm install` will now prevent incompatible installs such as:

```console
 WARN  Issues with peer dependencies found
packages/wdio-browser-runner
└─┬ modern-node-polyfills 1.0.0
  └── ✕ unmet peer esbuild@"^0.14.0 || ^0.15.0 || ^0.16.0 || ^0.17.0 || ^0.18.0": found 0.20.2
```

I've also added [`installed-checked`](https://github.com/webdriverio/webdriverio/issues/11868#issuecomment-2015504220) as suggested by @voxpelli but ensured:

1. The flag `--fix` is run to apply suggested changes
2. Existing and suggested `engines` ranges use LTS versions as a minimum

https://github.com/webdriverio/webdriverio/blob/fee2f8a88d132537795eaf144abf1a7e242f99ff/website/docs/GettingStarted.md?plain=1#L183-L188

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by colinrotherham** [comment]
Install error from Node.js 21 thrown during `pnpm install` now [strict install checks](https://github.com/webdriverio/webdriverio/pull/12638/commits/3977a5e1763c087ea339f6231bf551f9b85d9832) are enabled

```console
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/@serenity-js/core/3.21.2".

Expected version: ^16.13 || ^18.12 || ^20
Got: v21.7.2

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

**Comment by christian-bromann** [comment]
@colinrotherham we are 2 weeks away from Node.js v22 release which we will then adopt in our pipelines. We could raise an issue in Serenity and ask for adding v21 to the engines parameter but I would almost suggest to either wait for 2 weeks and adopt v22 in our pipelines, or disable the v21 pipeline until we have support for v22.

**Comment by christian-bromann** [comment]
@colinrotherham we are 2 weeks away from Node.js v22 release which we will then adopt in our pipelines. We could raise an issue in Serenity and ask for adding v21 to the engines parameter but I would almost suggest to either wait for 2 weeks and adopt v22 in our pipelines, or disable the v21 pipeline until we have support for v22.

**Comment by colinrotherham** [comment]
@christian-bromann No rush in the slightest, this PR can wait for v22 changes

**Comment by christian-bromann** [comment]
> this PR can wait for v22 changes

Node.js v22 has just release, maybe we can give this another go ;-)

**Comment by colinrotherham** [comment]
@christian-bromann Closed this by accident 🤦‍♂️

I had chance to try Node.js v22, but the new global `WebSocket` (https://github.com/nodejs/node/pull/51594) isn't mocked by:

https://github.com/webdriverio/webdriverio/blob/3222da3b1f4e8634936c18a78c846ac6c76a9305/packages/webdriver/tests/bidi.test.ts#L5

Probably a job for `vi.stubGlobal()` another day

**Comment by christian-bromann** [comment]
Why would that matter in this context? I can't re-open the PR myself.

**Pull request closed without merging**
