### PR TITLE
chore: Docusaurus with webpack 5

### PR DESCRIPTION
**Pull request by slorber**
Use an unreleased version of Docusaurus to test the webpack5 support works for this site, detect potential problems, and perf improvements.

See also https://github.com/facebook/docusaurus/pull/4089

### CODE REVIEW

**Comment by slorber** [comment]
FYI I got some errors before/after the update, not sure where that comes from:

```

(node:57989) UnhandledPromiseRejectionWarning: Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at emitUnhandledRejectionWarning (internal/process/promises.js:151:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:57989) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:57989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by christian-bromann** [comment]
> FYI I got some errors before/after the update, not sure where that comes from

I am not sure, likely that they have been there before and were ignored as the page was generated just fine. 

Do you want me to try to deploy the page?

**Comment by slorber** [comment]
I tried locally and the error was already there but it's not failing the built.

Couldn't find the source of this error, maybe in a third party lib

**Comment by slorber** [comment]
ready for review, let me know if anything does not work

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
