### PR TITLE
Sauce service before step RDC fix

### PR DESCRIPTION
**Pull request by denis-a1qa**
## Proposed changes
Add return in case using RDC to prevent issues like on screenshot:
image

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@wswebcreation didn't we just removed this `if` statement?

**Comment by denis-a1qa** [comment]
@christian-bromann this issue was introduced here:
https://github.com/webdriverio/webdriverio/pull/7779

**Comment by wswebcreation** [comment]
@christian-bromann 

No, this is a good catch, totally forgot about RDC. PR LGTM

**Comment by christian-bromann** [comment]
@wswebcreation thanks for confirming.

@denis-a1qa can we move the `if` statement into `setAnnotation` so we ensure that we don't attempt this in other hooks? Or is this just not possible in RDC when setting the job title?

**Comment by wswebcreation** [comment]
@christian-bromann 
Not sure what you mean, but the job tittle can also  be set for RDC, the annotation with context doesn’t work

**Comment by christian-bromann** [comment]
Ahh right, so just setting the context via annotation doesn't work. I believe we have some more places where we need to add this if statement then.

**Comment by wswebcreation** [comment]
I think that's already covered @christian-bromann, this PR is only for Cucumber. But maybe it's good to always call the methods and let the method determine if it's AND RDC AND a context call, then don't set it. This will remove the _complexity_ from all other methods

**Review by christian-bromann — APPROVED** [review]
@wswebcreation let's do this as part of a separate PR.

Thanks @denis-a1qa 👍

**Review by christian-bromann — APPROVED** [review]
@wswebcreation let's do this as part of a separate PR.

Thanks @denis-a1qa 👍

**Comment by christian-bromann** [comment]
fyi: the build is broken due to typing issues that I am currently fixing.

**Pull request merged**
