### PR TITLE
Check for unsupported `"engines"` package.json fields

### PR DESCRIPTION
**Pull request by colinrotherham**
## Proposed changes

Follow up to https://github.com/webdriverio/webdriverio/issues/11793 to configure **.npmrc** with `engine-strict=true` which will prevent Dependabot PRs from successfully completing `npm ci` when package updates require Node.js > v16 etc

Rather than [silently log warnings](https://github.com/webdriverio/webdriverio/actions/runs/7085870979/job/19282976254#step:4:15) `npm ci` will now prevent incompatible installs such as:

```console
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@lerna/create@8.0.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'form-data-encoder@4.0.2',
npm WARN EBADENGINE   required: { node: '>= 18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'got@14.0.0',
npm WARN EBADENGINE   required: { node: '>=20' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lerna@8.0.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Is there a way to define this NPM config only for dependencies and not dev dependencies?

**Comment by colinrotherham** [comment]
@christian-bromann Maybe with this push in https://github.com/webdriverio/webdriverio/pull/11823/commits/2faddb77b7edfbee7887b70d415bf663c87c95ce?

Not looking hopeful though

**Comment by christian-bromann** [comment]
@colinrotherham maybe we can use something like https://github.com/voxpelli/node-installed-check?

**Comment by colinrotherham** [comment]
@christian-bromann Just given it a try but it [doesn't support workspaces](https://github.com/voxpelli/node-installed-check/issues/31)

```shell
npx --workspaces installed-check --engine-check --engine-no-dev
```

It throws on `node_modules` not being in the same place as `package.json`

```console
Unexpected error: Failed to list installed modules: Non-existing path set: /path/to/project/webdriverio/packages/devtools/node_modules

ErrorWithCause: Failed to list installed modules
    at file:///path/to/project/webdriverio/node_modules/installed-check-core/index.js:52:13
```

**Comment by erwinheitzman** [comment]
Perhaps we can run dependabot on the "main" branch and on a separate branch, one regularly and one being limited?

**Comment by colinrotherham** [comment]
You can see in the last push I've tested `got@14` in various workspaces

But running `npx installed-check --engine-check --engine-no-dev` doesn't find workspace problems

Feel free to close this one though. My original **.npmrc** idea would need https://github.com/npm/cli/issues/6805 to be fixed and it might not be backported to older `npm` releases

**Comment by christian-bromann** [comment]
@colinrotherham mind raising an issue for this again? I would be great to have a check that all of the package dependencies are compatible with the minimal Node.js version we support.

**Comment by colinrotherham** [comment]
Raised as https://github.com/webdriverio/webdriverio/issues/11868

**Pull request closed without merging**
