### PR TITLE
Allow transformation from classic tag name selector to BiDi

### LINKED ISSUE #13692: [🐛 Bug]: In webdriverio v9, getting element by full tag does not work
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.1.2

### Node.js Version

20

### Mode

WDIO Testrunner

### Which capabilities are you using?

_No response_

### What happened?

Tests that referenced elements by using things like `<div>` no longer work. Instead, they need to be switched to `div`.

### What is your expected behavior?

This should either work like it did in v8 or it should be noted as a breaking change for v9.

### How to reproduce the bug.

test/specs/test.e2e.ts
```js
import { browser } from '@wdio/globals';

describe('Get element by full tag', () => {
    it('works', async () => {
        await browser.url(`https://example.com/`);
        await $('<div>');
    })
})
```

### Relevant log output

```typescript
[0-0] Error in "Get element by full tag.works"
Error: Can't transform classic selector tag name to Bidi selector
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by danielhjacobs**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Fixes #13692

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Thanks for the PR 👍  the good looks good to me, one little request: could we unit test the `transformClassicToBidiSelector` in `packages/webdriverio/tests/index.test.ts`?

**Comment by christian-bromann** [comment]
Oh 🙈 sorry I meant move the tests to `packages/webdriverio/tests/utils/index.test.ts` and can we wrap them within:

```ts
describe('transformClassicToBidiSelector', () => {
   it(....)
})
```

**Review by christian-bromann — APPROVED** [review]
Perfect, thank you 👍

**Comment by danielhjacobs** [comment]
Removed the excess spaces.

**Comment by danielhjacobs** [comment]
I'm not actually sure what the failing test is about. I'm wondering if it is related to this PR or just some random other error.

**Comment by danielhjacobs** [comment]
Review requested for christian-bromann to check if the error is related to this PR.

**Comment by danielhjacobs** [comment]
The [E2E Tests / Testrunner Tests (windows-latest)](https://github.com/webdriverio/webdriverio/actions/runs/11109927037/job/30877598201?pr=13694#logs) timed out.

**Pull request merged**
