### PR TITLE
#7104 wdio-junit-reporter - Mark test as skipped if on retry

### PR DESCRIPTION
**Pull request by lthurr**
Marking test as skipped in junit-reporter, and adding stacktrace if there is a failure

## Proposed changes

This is meant to fix https://github.com/webdriverio/webdriverio/issues/7104 
I did a little analysis in here, all the reporters behave the same, meaning if the test is retried is because it failed, so it will be marked as failed.
For junit, if a test is marked as failed (even tho it passed on the retry) then the whole suite is marked as failed.

So this PR is meant to fix that, it will mark the test as skipped and it will append the stack trace on the report.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

Let's suppose we retry two times and passes on the second time.

Junit XML: Before changes
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="suite" timestamp="..." time="0.008" tests="2" failures="1" errors="1" skipped="0">
    <properties>
      ...
    </properties>
    <testcase classname="..." name="test" time="0.007">
      <failure/>
      <error message="expect(received).toBe(expected) // Object.is equality;Expected: false;Received: true"/>
      <system-err><![CDATA[
Error: expect(received).toBe(expected) // Object.is equality[22m

Expected: false
Received: true
]]></system-err>
    </testcase>
    <testcase classname="" name="test" time="0">
    </testcase>
  </testsuite>
</testsuites>
```

Junit XML: After
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="suite" tests="2" failures="0" errors="0" skipped="1">
    <properties>
      ...
    </properties>
    <testcase classname="..." name="test" time="0.006">
      <skipped/>
      <system-err><![CDATA[
Error: expect(received).(expected) // Object.is equality[22m

Expected: false
Received: true
]]></system-err>
    </testcase>
    <testcase classname="..." name="test" time="0.001">
    </testcase>
  </testsuite>
</testsuites>
```

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thank you for raising the PR.

Can we add a unit test for this?

**Review by mgrybyk — APPROVED** [review]
LGTM
Let's wait for unit tests to be added

**Comment by GPSC1** [comment]
Is this implemented for just "junit reporter" or all of the reporters??.. because i am facing this issue with "wdio-html-nice-reporter".
Issue- If there is 1 flaky test case which gets retried thrice and gets passed in 3rd attempt then repost shows failed tests count as 2 even when the test got passed in 3rd retry.

**Comment by GPSC1** [comment]
Ok.. Thanks for the info.. Is thr a way to resolve this issue if faced while using "wdio-html-nice-reporter version"?

**Pull request merged**
