### PR TITLE
Save Selenium screenshot from command response where available

### PR DESCRIPTION
**Pull request by georgecrawford**
Addresses https://github.com/webdriverio/webdriverio/issues/1018

### CODE REVIEW

**Comment by georgecrawford** [comment]
@christian-bromann This is not finished yet - it will only save a screenshot if the error comes through the `afterCommand` hook. Also, there's duplicated logic between these changes and the in-build webdriverio screenshot saving at https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L98, so this needs to be abstracted out. But in principle, are you happy with the idea of the runner saving the screenshot and firing an event to say it's done it? The reason not to have it controlled in the same place is that you can't send the huge string buffer up to the launcher using `process.send`, as there's quite a small JSON length limit.

Interestingly, for me, Chromedriver on the Selenium Grid saves a screenshot of the whole OS window, not just the browser, which might potentially be very useful for debugging issues.

**Comment by christian-bromann** [comment]
> The reason not to have it controlled in the same place

What do you mean by that? If possible it would be the best I think if we can have this logic within the webdriverio.js code because then it would also work without using wdio.

**Comment by georgecrawford** [comment]
I'd love to have this in a single place, inside webdriverio, but I couldn't find a way, so I fear we may need to handle it in two separate places. If you call:

```
		browser.executeAsync(function(done) {
			throw Error('George error')
		});
```
...then the error is thrown [here](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L150), and I don't know how to catch it. The only way I could find the `Error` object was in the `afterCommand` callback.

Can you work out how to handle this exception from within the webdrverio.js file? This kind of thing bugs me again and again as I don't really understand what the hell goes on in this file!

To be perfectly honest with you, I don't really have time to implement stuff in webdriverio without using `wdio`, as it's not so familiar with me. I need to concentrate on the parts I'm actually going to use.

**Comment by christian-bromann** [comment]
So where to catch it highly depends whether we are running in wdio mode or if you run the standalone version and call then afterwards or/and have a catch block. I know pretty weird but that's how it is. Let's go through all possibilities:

__1:__ no then called
```js
var browser = require('./build').remote({
    screenshotPath: './',
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
})

browser
    .init()
    .url('http://localhost:8080')
    .executeAsync(function () {
        throw new Error('catch me if you can!')
    })
    .end()
```

In this case you only can catch it [here](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L170-L184).

__2:__ then is called
```js
var browser = require('./build').remote({
    screenshotPath: './',
    desiredCapabilities: {
        browserName: 'phantomjs'
    }
})

browser
    .init()
    .url('http://localhost:8080')
    .executeAsync(function () {
        throw new Error('catch me if you can!')
    }).then(function () {
        // do stuff
    })
    .end()
```
In this case it gets propagated [here](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L94-L118) first and then at the position above.

__3:__ if you use wdio there will be always a then/catch method call after each command due to fiber (wdio-sync). If you have now `screenshotPath` given it already creates a screenshot.

**Comment by georgecrawford** [comment]
Thanks for the first two examples. Could you add one for *3.* please, and a link to the line where I could catch the error inside webdriverio.js? Just so I'm 100% sure.

**Comment by georgecrawford** [comment]
The reason I ask is that with `wdio`, neither [1](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L170-L184) nor [2](https://github.com/webdriverio/webdriverio/blob/v4.0/lib/webdriverio.js#L94-L118) are hit with the exception.

**Comment by georgecrawford** [comment]
I'm now wondering whether a `throw` [here](https://github.com/webdriverio/wdio-sync/blob/master/index.js#L150) is correct?

**Comment by georgecrawford** [comment]
@christian-bromann Another oddity I've just discovered. I happened to have an `afterTest` hook which takes a screenshot on failure. In addition, for the first time, I have set `screenshotPath` to a directory which actually exists. I found that with `wdio`, the automatic screenshot performed by webdriverio.js is not waited for, resulting in this:
```
Demo test
taking screenshot /Users/george/Shell/sandboxes/ft-app-webdriverio/output/all/2016-01-14-16-29-58/screenshots/ERROR_chrome.latest.mac_2016-01-14T16:30:03.137Z.png
  1) should throw an error
taking screenshot /Users/george/Shell/sandboxes/ft-app-webdriverio/output/all/2016-01-14-16-29-58/screenshots/Test failure: An element could not be located on the page using the given search parameters.
screenshot complete /Users/george/Shell/sandboxes/ft-app-webdriverio/output/all/2016-01-14-16-29-58/screenshots/Test failure: An element could not be located on the page using the given search parameters.
  ✓ should pass a test (2ms)
screenshot complete /Users/george/Shell/sandboxes/ft-app-webdriverio/output/all/2016-01-14-16-29-58/screenshots/ERROR_chrome.latest.mac_2016-01-14T16:30:03.137Z.png
```
i.e.:
```
- spec starts
- bad test starts
- error encountered, automatic screenshot starts
- error thrown
- `afterHook` starts and completes screenshot
- bad test completes
- good test starts
- automatic screenshot finally completes, but will not be associated with the correct test
```

**Comment by christian-bromann** [comment]
So you take a screenshot (run a command) in the afterTest hook and it does not wait?

**Comment by georgecrawford** [comment]
Other way round - the afterHook screenshot *does* wait, but the in-built webdriverio one does not. 

________________



George

**Comment by christian-bromann** [comment]
Interesting! I was thinking of dropping that feature because it also applies to v3.x (see #1030). Though it should be possible to delay the execution of the command until the screenshot is taken. It's probably because I don't use the promise that is returned by https://github.com/webdriverio/webdriverio/blob/master/lib/webdriverio.js#L120-L122.

**Comment by georgecrawford** [comment]
OK, happy to drop that feature then. We could suggest that people use an `afterTest` hook instead - or even add one by default. However, my other points in this thread are now even more valid, as I'd like to properly handle screenshots on errors in a single location, and have lots of open questions. Could you add any answers you're able to?

**Comment by christian-bromann** [comment]
@georgecrawford I think we can solve this and the onError hook with #969. This is currently the primary task I am working on. If I return the promise and then throw the error I should be able to reject the actual command. If I can get this working we should go with that solution instead of injecting a new hook.

**Comment by christian-bromann** [comment]
@georgecrawford I ported your path to the webdriverio.js file where it gets handled in standalone mode too

**Pull request closed without merging**
