### PR TITLE
(@wdio/config): memoize ConfigParser.getSpecs

### LINKED ISSUE #4880: Cache list of spec files
**Is your feature request related to a problem? Please describe.**
Finding specs in a big monorepo takes ages. Think 130K+ files (sources + tests + assets).
Rough directory structure is this:
```
page1/
	- features/
		page1.feature
	- subpage1/
		- features/
			- subpage1.feature
		- subpage1.js
	- page1.js
	- page1.css
page2/
	<same structure>
ui/shared_component/
	- features/
		- shared_component_in_page1.feature
		- shared_component_in_page2.feature
	- shared_component.js
```

This is a screenshot from a JS CPU profile of the first ~2 minutes of running WDIO on our repo. At that point, it didn't even get to actually running the tests.

Screen Shot 2019-12-14 at 19 55 39

Note how consistently [`ConfigParser#getSpecs`](https://github.com/webdriverio/webdriverio/blob/f89319bb91a35f99bda361b9bcdb95e7a7c5d35d/packages/wdio-config/src/lib/ConfigParser.js#L167) appears in the chart, and how much time it consumes.

This massive time is to find just ~250 `.feature` files among the sources.
I also had passed a tag expression that would filter that down to just 4 files, so it's unacceptable that WDIO takes this long.

**Describe the solution you'd like**
`ConfigParser#getSpecs` could be memoized, so that when it takes the same input, it always returns the same value. Should shave a bunch of time from the 

I guess that adding/removing files could become a problem with that solution, in which case it should be coupled with a file system watching solution to manipulate the cache.

**Describe alternatives you've considered**
The `specs` option was too inclusive (`src/**/features/*.feature`), so I tinkered with the `suites` option:

```js
suites: {
	page1: ['src/page1/**/features/*.feature', 'src/ui/**/features/*.feature']
	// and so on
}
```

This didn't help bringing the time to boot up down noticeably, though.

And, as probably obvious from above, keeping a list of `.feature` files in the config that doesn't make use of wildcards is impossible.

**Additional context**
Node.js v10.16.3

`@wdio` packages used:
```json
    "@wdio/cli": "^5.16.10",
    "@wdio/cucumber-framework": "^5.16.10",
    "@wdio/local-runner": "^5.16.10",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.10",
    "@wdio/sync": "^5.16.10",
```

### PR DESCRIPTION
**Pull request by erwinheitzman**
## Proposed changes

Memoized the getSpecs method of the ConfigParser to cache the results for all workers.

Fixes #4880 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
The solution looks good to me, mind verifying if updating the `spec` parameter in the `onPrepare` or `onWorkerStart` hook still works. I am actually not sure if this currently works but I could see someone trying to modify this as part of service functionality.

**Comment by erwinheitzman** [comment]
Currently it does not play nicely with the merge. We merge A LOT apparently and it looks like this is because it is making changes to the config indirectly instead of returning a new object which we could also cache.

**Comment by erwinheitzman** [comment]
From doing some testing I think we would have to memoize the initialise method so that we don't execute a merge and run all of the underlying methods if nothing has changed. Will have to do more investigation though, to be continued =]

**Comment by erwinheitzman** [comment]
Going to close this for now as I have to focus on other things first

**Pull request closed without merging**
