### PR TITLE
Updated Mobile Detector to include isTablet and isPhone. 

### PR DESCRIPTION
**Pull request by fijijavis**
These will be useful when building page objects for responsive design testing

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

With responsive web design, often it is necessary to build page objects and/or tests that can account for layout changes.  The intent of this change is to expose isPhone and isTablet via mobileDetector.js.

**isPhone** 
Will return true if:
deviceName is a case insensitive match to iPhone OR
device-type is a case insensitive match to phone OR
deviceType is a case insensitive match to phone

**isTablet** 
Will return true if:
deviceName is a case insensitive match to iPad OR
device-type is a case insensitive match to tablet OR
deviceType is a case insensitive match to tablet

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by fijijavis** [comment]
I didn’t think it was either but the existing isMobile check had it there so I thought I should duplicate it.

**Comment by fijijavis** [comment]
@christian-bromann I'm sure you are busy.  Wanted to see if you had any other thoughts on this one?

**Comment by christian-bromann** [comment]
@fijijavis I don't think deviceType is a legit capability anymore. You can only use the deviceName these days to figure out whether or not your device is a phone or tablet.

**Comment by fijijavis** [comment]
Closing.  Need to do some additional research and come up with a better proposal

**Pull request closed without merging**
