### PR TITLE
Fix syntax in touchAction example

### PR DESCRIPTION
**Pull request by WillBrock**
## Proposed changes

Fixes syntax in the touchAction example.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Can you please resolve the conflicts?

**Comment by christian-bromann** [comment]
@WillBrock maybe could you merge these 4 commits into 1?

**Comment by WillBrock** [comment]
Should be good now.

**Comment by christian-bromann** [comment]
👍

**Pull request merged**
