### PR TITLE
Adding and passing snyk tests

### PR DESCRIPTION
**Pull request by apergy**
## Proposed changes

Adding `snyk test` to the travis build and upgrading the `archiver` and `request` packages to fix vulnerabilities found by using snyk.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Snyk is used to determine if any project dependencies have known vulnerabilities all the way down the tree, running `snyk test` as part of the build ensures things are kept as secure and up-to-date as possible. Many organisations will use snyk in their projects - ensuring these tests/builds pass will help many of us.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@apergy thanks for the proposal. I like the idea of having this as part of the build process. Don't we need a `. snyk` file though? This is what the readme says, unfortunately the docs page is not reachable for me right now.

**Comment by apergy** [comment]
We use snyk on some of our other projects and we haven't required the `.snyk` file to explicitly be there so far, normally only if we want to ignore or apply patches for vulnerabilities/issues until a fix is found or the affected downstream package has been updated.

**Comment by christian-bromann** [comment]
@apergy gotcha, could you rebase against current master?

**Comment by apergy** [comment]
I think that should now be rebased.

**Comment by christian-bromann** [comment]
@apergy mhm .. looks like these unit test errors are legit

**Comment by apergy** [comment]
I've fixed the tests and can now see `snyk test` running as expected.

**Comment by christian-bromann** [comment]
@apergy nice, LGTM!

**Pull request merged**
