### PR TITLE
wdio-cucumber-framework:  Filter cucumber features before process spawned

### LINKED ISSUE #1247: Possibility to configure test spec process spawning?
## The problem

According to https://github.com/webdriverio/webdriverio/issues/1106#issuecomment-184728530 `each test spec gets executed in a single child process`.
We have currently 101 individual `.feature files` (we are using Cucumber) and cannot put them into one big file.
When we launch our test script, my Selenium Server is trying to spawn 101 process, this results in a very heavy lag and I need to kill the processes.

Is there a way to configure this behaviour? Do we need to adjust our wdio.conf?
## Environment

**updated on 07/05/16**
- WebdriverIO version: 4.1.1
- Node.js version: 4.4.6
- Selenium Server 2.53.0
- using wdio testrunner
- running synchronous or asnychronous tests: does not matter
- Additional wdio packages used (if applicable):
  wdio-cucumber-framework: 0.2.0
## Details

Even with the cucumber option tags like `-cucumberOpts.tags=@foo`, it will spawn 101 processes, even though only 1 feature was tagged with `@foo`
(Note: The setup is working fine with wdio 3.4.0)

### PR DESCRIPTION
**Pull request by jayrepo**
## Proposed changes

Fix #1247
Do an additional filtering  in `wdio-cli/src/launcher.js` before process spawned

Export a utility function to filter features by tag expression
Use with `specsFilter` option in config `specFilter: (config) => string[]`

```js
// wdio.conf.js
exports.config = {
  // ...
  specsFilter: require('@wdio/cucumber-framework').filterSpecsByTag
  // ...
  cucumberOpts: {
      // ...
    tagExpression: '@smoke and @stable'
      // ...
  }
  // ...
}
```
A simple example of filter by file name using `specsFilter`:
```js
const { ConfigParser } = require('@wdio/config')
exports.config = {
  // ...
  namePattern: 'moduleA',
  specsFilter: (config) => {
      const specs = ConfigParser.getFilePaths(config.specs, false)
      return specs.filter(spec => spec.includes(config.namePattern))
  }
  // ...
}
```
Other frameworks should exported their own filters, as each framework has its own implementation.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
Can you please help understanding what is the difference between your implementation and built in tagExpression filter?

**Comment by jayrepo** [comment]
@mgrybyk It's almost the same as the built in filter.

The problem is that when built in tag filter starts to work, processes are already spawned for each feature file. Even if the feature does not contain a matching tag expression, the process will still start a seesion, run no test, close session and report pass

It's really annoying if you have hundreds of feature files. For mobile app test, it takes around 1 min start a session.

This proposal did a pre-processing to filter the features before everything starts.

**Comment by mgrybyk** [comment]
I'd better have it working natively for all frameworks! We have the same issue with mocha

If it's not possible, can we tune somehow built in tag expression filter, to work like your implementation or add another option to cucumberOpts and reuse existing  code as much as possible? 

Even though current solution work for you  it doesn't look clean enough, from my point of view

**Comment by jayrepo** [comment]
@mgrybyk 
> I'd better have it working natively for all frameworks! We have the same issue with mocha

My original thought was add a config like `specsFilter: (config) => string[]`, so other framework can also export a filter function to use it.

This requires changes to the `wdio-config` package. As I'm not familiar with other frameworks and configs, I didn't touch it.
Is it OK to apply the filter just before return? https://github.com/webdriverio/webdriverio/blob/91bc19ae25477184efbd89e72b8dd64417fbd433/packages/wdio-config/src/lib/ConfigParser.js#L201

**Comment by mgrybyk** [comment]
Let me take a look

**Comment by mgrybyk** [comment]
not sure how to handle it better right now

**Comment by jayrepo** [comment]
Made some changes, need to do some e2e test

**Comment by jayrepo** [comment]
Add a config.
Filter the specs in `launcher` of `wdio-cli`

**Comment by mgrybyk** [comment]
There is one more approach (suggestion) to handle it more widely, it is not a part of current PR!

We may change a bit the way how browser object is created. 
Currently we init browser before framework.
It might be changed, we may first create browser object, then init framework (but not run!) and verify if there are tests to run, if so, create browser session, and then run framework.

**Comment by christian-bromann** [comment]
I prefer @mgrybyk solution here. We can change the interface of the wdio framework packages so that hey have an `init` and `run` function. This is related to #2859.

**Comment by jayrepo** [comment]
@mgrybyk @christian-bromann 

That will be great. what I proposed is just a temporary workaround.

If my understanding is correct, your solution will work like this:
```js
const browser = new Browser()  // not start session
const specs = framework.init()  // parsing specs with framework's native tag implementation
if (specs.length) {
  brower.startSession()
  framework.run()
}
```

**Comment by mgrybyk** [comment]
Yes.
As I've mentioned it requires refactoring in framework core, so I don't think it gonna be soon. If no one can pick it up I'll start working on it somewhere in September if there are no critical tasks.
Additionally I'm waiting for devtools PR to be merged first to avoid tons of conflicts.

**Comment by codiophile** [comment]
Interestingly enough, we have this feature in our framework, although to solve a different problem. We filter the feature files based on tags before sending the list of spec files to the launcher. I do like @mgrybyk's proposed solution; I just wanted to point out that until it arrives you can implement the filtering outside of webdriverio.

**Comment by mgrybyk** [comment]
@jayrepo please see https://github.com/webdriverio/webdriverio/pull/4531

**Comment by mgrybyk** [comment]
Closing the PR.
Let's proceed convo in https://github.com/webdriverio/webdriverio/pull/4531

**Pull request closed without merging**
