### PR TITLE
devtools-service: upgrade lighthouse

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Upgrade lighthouse to 6.4.1 as far as https://github.com/webdriverio/webdriverio/pull/5914 is breaking for the ones used elder version.

See also https://github.com/GoogleChrome/lighthouse/pull/11355

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by pmerwin** [comment]
Thanks You!!!

**Comment by pmerwin** [comment]
Can we publish this https://github.com/webdriverio/webdriverio/commit/c699da9134ce9e4af02334d545e27188ec41fc1a?

**Comment by mgrybyk** [comment]
@pmerwin of course, let me get an approval for this one as well and will release

**Comment by pmerwin** [comment]
@mgrybyk thanks man, we have tests down and it would help me to go forward to fix instead of backwards

**Comment by pmerwin** [comment]
FYI have to go back to 6.3.0 of lh to fix with devtools fix

**Comment by mgrybyk** [comment]
Thanks for information!

**Review by BorisOsipov — APPROVED** [review]

**Pull request merged**
