### PR TITLE
Throw error if select element/option is disabled 

### PR DESCRIPTION
**Pull request by harsha509**
## Proposed changes

* Currently WDIo select, selects the option even if the Select tag/ option is disabled for selection. We need to throw an error is Select tag/option is disabled for selection

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@harsha509 thanks for raising the PR!

For some reason I was not able to reproduce this problem. Here is an example script I used:

```js
await browser.url('http://guinea-pig.webdriver.io/')

const select = await $('#selectTest')
await browser.execute(
    (elem) => elem.setAttribute('disabled', true),
    await select.$$('option')[2])
await browser.pause(2000)
await select.selectByVisibleText('tres')
await expect(select).toHaveValue('someValue3')
```

As you can see I disable the 3rd option and then try to use one of the select commands to change the value. However the test fails and I am not able to modify the select input.

Can you provide a reproducible example?

**Comment by harsha509** [comment]
Hi @christian-bromann ,

https://github.com/harsha509/test_selector_wdio

**Comment by christian-bromann** [comment]
> The test fails only on assertion, but it allows the user to select disabled option according to logic.

Ah, so you would like to have the attempt of changing a disabled input fail. That could be an interesting approach, the only problem I see with this is that it requires an additional command which could slow down the tests if there are a lot of inputs.

@webdriverio/project-committers any feedback, suggestions?

**Comment by christian-bromann** [comment]
@harsha509 another option would be to extend our [`CustomRequestError`](https://github.com/webdriverio/webdriverio/blob/53eefeb7ad55d3d9ac0f83d5c6d5f02d0ea5da62/packages/webdriver/src/utils.ts#L238-L265) class and modify the error message there. What do you think?

**Pull request closed without merging**
