### PR TITLE
(webdriverio): polish intercepted errors

### PR DESCRIPTION
**Pull request by erwinheitzman**
## Proposed changes

Backport of #12533

## Types of changes

- [x] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Review by wswebcreation — CHANGES_REQUESTED** [review]
LGTM, can you also add UTs for this?

**Review by christian-bromann — APPROVED** [review]
Awesome 👍

**Comment by christian-bromann** [comment]
🤔 seems like the test is failing in CI.

**Comment by erwinheitzman** [comment]
I believe that the current failing tests are due to something else right?

**Comment by christian-bromann** [comment]
> I believe that the current failing tests are due to something else right?

Correct, some of the e2e tests that we don't have anymore in `main` are flaky, we can continue.

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
