### PR TITLE
retry with logs, retry on any connection error

### PR DESCRIPTION
**Pull request by sbmaxx**
port of #987

### CODE REVIEW

**Comment by christian-bromann** [comment]
I don't understand, this is already ported:
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L234

**Comment by sbmaxx** [comment]
@christian-bromann it does retry on `500` response from server, and also log retries (can be helpful), and do a small refactoring — separate retry logic from request result/error handling

**Comment by sbmaxx** [comment]
I added test for this.

**Comment by christian-bromann** [comment]
@sbmaxx yeah but request retry is already implemented isn't it? What is the additional enhancement of your PR?

**Comment by sbmaxx** [comment]
@christian-bromann yes. i will fix errors later today, and you can merge ;)

**Comment by christian-bromann** [comment]
@sbmaxx so if it is implemented, what value adds your PR then?

**Comment by sbmaxx** [comment]
@christian-bromann i rebased this PR from dev, and didn't find any error in my code.

This PR is about fixing https://github.com/webdriverio/webdriverio/pull/987 then webdriver doesn't retry connection if server responds with 500 error.
```
[10:14:43][test name] REQUEST response end http://GRID_URL:4444/wd/hub/session/6c92c9913909c9b8b333a3843ba1eca36a4c4eb0-f2cb-4a2b-b325-77b46063381d/execute 500 { server: 'nginx',
[10:14:43][test name]   date: 'Thu, 07 Jan 2016 07:14:43 GMT',
[10:14:43][test name]   'content-type': 'application/json;charset=UTF-8',
[10:14:43][test name]   'content-length': '13458',
[10:14:43][test name]   connection: 'keep-alive',
[10:14:43][test name]   expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
[10:14:43][test name]   'cache-control': 'no-cache',
[10:14:43][test name]   'set-cookie': [ 'uid=CmajrVaOEGPASkHSKTKTAg==; path=/' ] }
```
Here is the fragment from `request` debug's log. Selenium grid (or some balancer in front of it) can sometimes replies with `500` error. I think this should also be covered with retries.

I wrote [test](https://github.com/webdriverio/webdriverio/pull/1088/files#diff-3485a7191bfc57a01d4d0f39dc748199R29) for this. It fails at `master` branch

**Comment by sbmaxx** [comment]
@christian-bromann `wdio` tests fails at master on my localhost. Any ideas how can i fix this test? :)

```
[INFO  - 2016-02-23T12:34:53.538Z] GhostDriver - Main - running on port 8581
[INFO  - 2016-02-23T12:34:53.909Z] Session [d6ed2c10-da29-11e5-ab47-09a4085be53f] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2016-02-23T12:34:53.909Z] Session [d6ed2c10-da29-11e5-ab47-09a4085be53f] - page.customHeaders:  - {}
[INFO  - 2016-02-23T12:34:53.909Z] Session [d6ed2c10-da29-11e5-ab47-09a4085be53f] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-unknown-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2016-02-23T12:34:53.909Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: d6ed2c10-da29-11e5-ab47-09a4085be53f
15:34:53.912 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@3cb86cf7, browserName=phantomjs, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.0.3, url=http://webdriver.io}}]]
15:34:55.053 INFO - Executing: [get: http://127.0.0.1:8080/stale.html])
15:34:55.179 INFO - Done: [get: http://127.0.0.1:8080/stale.html]
15:34:55.204 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.342 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.352 INFO - Executing: [is displayed: 0 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:34:55.367 INFO - Done: [is displayed: 0 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:34:55.382 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.395 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.407 INFO - Executing: [is displayed: 0 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:34:55.421 INFO - Done: [is displayed: 0 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:34:55.434 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.446 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.460 INFO - Executing: [is displayed: 0 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:34:55.473 INFO - Done: [is displayed: 0 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:34:55.494 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.511 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.520 INFO - Executing: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:34:55.534 INFO - Done: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:34:55.568 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.585 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.599 INFO - Executing: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:34:55.610 INFO - Done: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:34:55.619 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.634 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.642 INFO - Executing: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:34:55.664 INFO - Done: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:34:55.678 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:34:55.692 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:34:55.700 INFO - Executing: [is displayed: 1 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])



15:35:06.866 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: {"errorMessage":"Element is no longer attached to the DOM","request":{"headers":{"Accept-Encoding":"gzip,deflate","Cache-Control":"no-cache","Connection":"Keep-Alive","Host":"localhost:8581","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_65)"},"httpVersion":"1.1","method":"GET","url":"/displayed","urlParsed":{"anchor":"","query":"","file":"displayed","directory":"/","path":"/displayed","relative":"/displayed","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/displayed","queryKey":{},"chunks":["displayed"]},"urlOriginal":"/session/d6ed2c10-da29-11e5-ab47-09a4085be53f/element/%3Awdc%3A1456230895341/displayed"}}
Command duration or timeout: 125 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sbmaxx.local', ip: '95.108.172.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=1.9.8, platform=MAC, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.1.0, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: d6ed2c10-da29-11e5-ab47-09a4085be53f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:334)
	at com.sun.proxy.$Proxy2.isDisplayed(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.isDisplayed(EventFiringWebDriver.java:388)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy3.isDisplayed(Unknown Source)
	at org.openqa.selenium.remote.server.handler.GetElementDisplayed.call(GetElementDisplayed.java:32)
	at org.openqa.selenium.remote.server.handler.GetElementDisplayed.call(GetElementDisplayed.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sbmaxx.local', ip: '95.108.172.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_65'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:138)
	... 23 more
Caused by: org.openqa.selenium.StaleElementReferenceException: {"errorMessage":"Element is no longer attached to the DOM","request":{"headers":{"Accept-Encoding":"gzip,deflate","Cache-Control":"no-cache","Connection":"Keep-Alive","Host":"localhost:8581","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_65)"},"httpVersion":"1.1","method":"GET","url":"/displayed","urlParsed":{"anchor":"","query":"","file":"displayed","directory":"/","path":"/displayed","relative":"/displayed","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/displayed","queryKey":{},"chunks":["displayed"]},"urlOriginal":"/session/d6ed2c10-da29-11e5-ab47-09a4085be53f/element/%3Awdc%3A1456230895341/displayed"}}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sbmaxx.local', ip: '95.108.172.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_65'
Driver info: driver.version: unknown
15:35:47.462 WARN - Exception: {"errorMessage":"Element is no longer attached to the DOM","request":{"headers":{"Accept-Encoding":"gzip,deflate","Cache-Control":"no-cache","Connection":"Keep-Alive","Host":"localhost:8581","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_65)"},"httpVersion":"1.1","method":"GET","url":"/displayed","urlParsed":{"anchor":"","query":"","file":"displayed","directory":"/","path":"/displayed","relative":"/displayed","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/displayed","queryKey":{},"chunks":["displayed"]},"urlOriginal":"/session/d6ed2c10-da29-11e5-ab47-09a4085be53f/element/%3Awdc%3A1456230895341/displayed"}}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'sbmaxx.local', ip: '95.108.172.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_65'
Driver info: driver.version: unknown
15:35:55.054 INFO - Executing: [get: http://127.0.0.1:8080/stale.html])
15:35:55.180 INFO - Done: [get: http://127.0.0.1:8080/stale.html]
15:35:55.194 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.326 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.331 INFO - Executing: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.344 INFO - Done: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.353 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.366 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.371 INFO - Executing: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.391 INFO - Done: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.399 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.410 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.420 INFO - Executing: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.441 INFO - Done: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.449 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.460 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.466 INFO - Executing: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.483 INFO - Done: [is displayed: 2 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.495 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.505 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.511 INFO - Executing: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.528 INFO - Done: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.542 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.554 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.565 INFO - Executing: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.592 INFO - Done: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.602 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.621 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.634 INFO - Executing: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
15:35:55.657 INFO - Done: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]]
15:35:55.672 INFO - Executing: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row])
15:35:55.698 INFO - Done: [find elements: By.cssSelector: .staleElementContainer1 .stale-element-container-row]
15:35:55.710 INFO - Executing: [is displayed: 3 [[PhantomJSDriver: phantomjs on MAC (d6ed2c10-da29-11e5-ab47-09a4085be53f)] -> css selector: .staleElementContainer1 .stale-element-container-row]])
```

**Comment by christian-bromann** [comment]
@sbmaxx could you please explain what this PR does? We already have a retry mechanism implemented. I don't see any enhancements in this PR!

**Comment by sbmaxx** [comment]
@christian-bromann already tried ;)

**Pull request closed without merging**
