### PR TITLE
fix for findStrategy

### PR DESCRIPTION
**Pull request by Gilad-WT**
Very similar to https://github.com/webdriverio/webdriverio/pull/3226.
When $ gets called from an element the element's isMobile is not set so if you use a mobile selector it will throw InvalidSelectorStrategy
## Proposed changes
I had a few ideas:
1) pass the capabilities into all elements when they are created and create an isMobile check inside findStrategy.
2) pass isMobile to all element when they are created so they will have it when they are passed to findStrategy.
@christian-bromann @martomo @abjerstedt  would love your input on which one you think is better or if you have a different ideas 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
This PR has no change in it.

**Comment by Gilad-WT** [comment]
@christian-bromann I'll take that as 2

**Comment by christian-bromann** [comment]
> I'll take that as 2

I don't understand?

**Comment by Gilad-WT** [comment]
The bug is:
When $ gets called from an element the element's isMobile is not set so if you use a mobile selector it will throw InvalidSelectorStrategy

Which option to implement in order to solve the bug:
1) pass the capabilities into all elements when they are created and create an isMobile check inside findStrategy.
2) pass isMobile to all element when they are created so they will have it when they are passed to findStrategy.

**Comment by christian-bromann** [comment]
This will be fixed as part of #3271

**Comment by Gilad-WT** [comment]
Ok Thanks

**Pull request closed without merging**
