### PR TITLE
webdriver: Add strictSSL option

### PR DESCRIPTION
**Pull request by martinfrancois**
## Proposed changes

When executing a test behind a corporate proxy, even with correctly set `HTTP_PROXY` and `HTTPS_PROXY` environment variables, an error like:
```
Error: unable to verify the first certificate
```
or
```
Error: tunneling socket could not be established, cause=write EPROTO 8888:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:
```
can appear, if the corporate proxy is also doing SSL interception and inspection due to the certificate not being recognized as valid in https connections.

The [request node package](https://www.npmjs.com/package/request) has an option `strictSSL` which can be set to `false`, leading to SSL certificates not being validated in https connections and thus solving the issue.

The proposed change is to set the `strictSSL` option depending on the value of an environment variable `STRICT_SSL`. If it is set to `false`, `strictSSL` will also be defined as `false` and in all other cases, `strictSSL` will default to `true`.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)
The functionality of this is similar to what exists for npm already: https://docs.npmjs.com/misc/config#strict-ssl
I considered passing the flag in via parameters, but wanted to keep the definition of the flag consistent with the other already existing proxy-related settings `HTTP_PROXY` and `HTTPS_PROXY`, as described in the proxy documentation.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@martinfrancois please sign the CLA so this can be merged

**Comment by martinfrancois** [comment]
Thanks, I just signed it!

**Comment by christian-bromann** [comment]
it seems that the linter is not happy

**Comment by martinfrancois** [comment]
just noticed it too - let's hope it's happy now 😉

**Comment by martinfrancois** [comment]
Mhm.. the tests failing is a bit strange, they pass on my machine?

**Comment by christian-bromann** [comment]
@martinfrancois make sure you run v8 as we use this in Travis too

**Comment by martinfrancois** [comment]
Good point! Indeed, using node v8 it fails the same... I think the easiest would be to mock `process.env` here, but I didn't succeed... Any ideas?

**Comment by martinfrancois** [comment]
Turned out there was an issue with the previous logic, which caused it to only work on Windows (since it treats environment variables case insensitive). I corrected the logic now to work on both platforms equally.

**Pull request merged**
