### PR TITLE
fix: Stop BrowserStack service from console patching constructors

### LINKED ISSUE #11159: [🐛 Bug]: TypeError: console_1.Console is not a constructor
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.6

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

I followed the `Getting Started` documentation using the wizard which generates the below `package.json`
```
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/browserstack-service": "^8.16.6",
    "@wdio/cli": "^8.16.6",
    "@wdio/cucumber-framework": "^8.16.6",
    "@wdio/local-runner": "^8.16.6",
    "@wdio/spec-reporter": "^8.16.3"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  }
}
```
Along with the `wdio.conf.js`
```
export const config = {
    runner: 'local',
    user: '**********',
    key: '*********',
    specs: [
        './features/**/*.feature'
    ],
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [{
        browserName: 'chrome'
    }],
    logLevel: 'debug',
    bail: 0,
    baseUrl: 'https://webdriver.io',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['browserstack'],
    framework: 'cucumber',
    reporters: ['spec'],
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./features/step-definitions/steps.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    }
}
```
When running `npx wdio run ./wdio.conf.js` I receive the error `[0-0]  Error:  console_1.Console is not a constructor`

### What is your expected behavior?

I would expect the code to run through Browserstack and open the baseUrl https://the-internet.herokuapp.com as in the example feature auto generated with the setup. 

Commenting out the Browserstack credentials and services the test executes locally as expected.
```
[chrome 116.0.5845.187 mac os x #0-0] Running: chrome (v116.0.5845.187) on mac os x
[chrome 116.0.5845.187 mac os x #0-0] Session ID: a47385f16f81de2bee010665a3670f97
[chrome 116.0.5845.187 mac os x #0-0]
[chrome 116.0.5845.187 mac os x #0-0] » features/login.feature
[chrome 116.0.5845.187 mac os x #0-0] The Internet Guinea Pig Website
[chrome 116.0.5845.187 mac os x #0-0] As a user, I can log into the secure area
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Given I am on the login page
[chrome 116.0.5845.187 mac os x #0-0]    ✓ When I login with tomsmith and SuperSecretPassword!
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Then I should see a flash message saying You logged into a secure area!
[chrome 116.0.5845.187 mac os x #0-0]
[chrome 116.0.5845.187 mac os x #0-0] As a user, I can log into the secure area
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Given I am on the login page
[chrome 116.0.5845.187 mac os x #0-0]    ✓ When I login with foobar and barfoo
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Then I should see a flash message saying Your username is invalid!
[chrome 116.0.5845.187 mac os x #0-0]
[chrome 116.0.5845.187 mac os x #0-0] 6 passing (2.4s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:14 
```

### How to reproduce the bug.

Follow the Getting Started documentation using the wdio wizard with values 

`local` for e2e testing
`browserstack` for automation backend
`cucumber` for framework
`no` for compiler
`test files` yes auto-generate
default for paths
`pageobject` yes
`spec` reporter
`no` plugins

I then installed with `yarn`

`npx wdio run ./wdio.conf.js` results in the error.

### Relevant log output

```typescript
[0-0] 2023-09-13T06:54:09.961Z ERROR @wdio/runner: TypeError: console_1.Console is not a constructor
[0-0]     at new ConsoleLogger (/Users/sean.darley/projects/wdio/node_modules/@cucumber/cucumber/lib/api/console_logger.js:9:24)
[0-0]     at loadConfiguration (/Users/sean.darley/projects/wdio/node_modules/@cucumber/cucumber/lib/api/load_configuration.js:20:20)
[0-0]     at CucumberAdapter.run (file:///Users/sean.darley/projects/wdio/node_modules/@wdio/cucumber-framework/build/index.js:197:48)
[0-0]     at async Runner.run (file:///Users/sean.darley/projects/wdio/node_modules/@wdio/runner/build/index.js:148:24)
[0-0]  Error:  console_1.Console is not a constructor
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by nextlevelbeard**
## Proposed changes

Fixes #11159 

To enable BrowserStack service to use the Observability feature, the service patches the console. The problem is that it overrides the Constructor as well.
Attempting to use this service/feature with Cucumber produces an error:
```ts
ERROR @wdio/runner: TypeError: console_1.Console is not a constructor
    at new ConsoleLogger (/Users/user/repos/repo/node_modules/@cucumber/cucumber/lib/api/console_logger.js:9:24)
    at loadConfiguration (/Users/user/repos/repo/node_modules/@cucumber/cucumber/lib/api/load_configuration.js:20:20)
    at CucumberAdapter.run (file:///Users/user/repos/repo/node_modules/@wdio/cucumber-framework/build/index.js:197:48)
    at async Runner.run (file:///Users/user/repos/repo/node_modules/@wdio/runner/build/index.js:148:24)
```

Cucumber is constructing new Consoles and cannot do so if the Constructor is overridden with an arrow function.
https://github.com/cucumber/cucumber-js/blob/3a945b1077d4539f8a363c955a0506e088ff4271/src/api/console_logger.ts#L5-L8

To reproduce, use Cucumber framework and enable the BrowserStack service to use the Observability feature:
```js
frameowrk: 'cucumber',
services: [
  ['browserstack', {
      testObservability: true,
      testObservabilityOptions: {
        user: '[REDACTED]',
        key:'[REDACTED]',
        projectName: 'any',
        buildName: 'main',
        buildTag: '123'
    },
  }]
]
```
___
[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks for raising the PR @nextlevelbeard , anything I can do to help?

**Comment by christian-bromann** [comment]
@nextlevelbeard thanks for your work, is this ready for review?

**Comment by nextlevelbeard** [comment]
Should be ready to review yes, thanks @sriteja777

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Pull request merged**
