### PR TITLE
feat: display command name for webdriver calls in allure reporter

### PR DESCRIPTION
**Pull request by sudharsan-selvaraj**
## Proposed changes
Currently the allure reporter will display only the endpoint and method name for all webdriver api calls. As part of the change, i have enabled the command name to be also displayed along with the endpoint. 
Fixes #12926

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Polish (an improvement for an existing feature)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added the necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by sudharsan-selvaraj** [comment]
> @sudharsan-selvaraj thanks for taking a step at this. Mind adding a unit test so we can be sure we don't regress?

Sure @christian-bromann. Will raise a patch with the unit tests.

**Comment by sudharsan-selvaraj** [comment]
@christian-bromann I have added the required unit test. Kindly look into it and let me know your thoughts. Thank you!

**Comment by BorisOsipov** [comment]
@sudharsan-selvaraj let's look at things straight, who need `/session/:sessionid/` info? it is useless, let's remove it. it will make step name shorter

**Comment by sudharsan-selvaraj** [comment]
@BorisOsipov sounds good. The step name is now defaulted just to display the command name and added the endpoints as a fallback incase of missing command name.

**Review by christian-bromann — APPROVED** [review]
Thank you @sudharsan-selvaraj , changes look good to me 👍 
Mind raising a PR for the `v8` branch?

@BorisOsipov can you approve?

**Comment by sudharsan-selvaraj** [comment]
@christian-bromann sure will create a new PR for v8 branch.

**Review by BorisOsipov — APPROVED** [review]

**Pull request merged**
