### PR TITLE
Capture stacktrace after message modifying in ErrorHandler

### PR DESCRIPTION
**Pull request by rostik404**
## Proposed changes

[//]: `capturestacktrace` is unnecessary here and after babel processing stacktrace is lost. I left more information about this problem in issue https://github.com/webdriverio/webdriverio/issues/2275

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by eGavr** [comment]
Great PR!

**Comment by DudaGod** [comment]
Awesome! You rock!

**Comment by christian-bromann** [comment]
Your patch seems to be fix an issue in Node v8 but might break stuff in other version of node. Not sure if just removing this is the right solution.

**Comment by rostik404** [comment]
@christian-bromann, added correct taking of stack for all versions of Node.

**Comment by christian-bromann** [comment]
@rostik404 I don't understand how this is any more useful? The stack you assign to the error object won't point to any location within the test file or where the actual error has been thrown?

**Comment by rostik404** [comment]
I've found another solution. We should capture stacktrace after modifying of message.
/cc @christian-bromann

**Comment by christian-bromann** [comment]
@rostik404 great, can you add a unit test for this?

**Comment by rostik404** [comment]
yes, sure

**Comment by rostik404** [comment]
@christian-bromann, done. Wrote unit-test which falls down without my changes because stacktrace wouldn't include modified message

**Comment by rostik404** [comment]
@christian-bromann, ping :)

**Comment by christian-bromann** [comment]
@rostik404 before I can merge this I need to look into the patch and see how it affects the error handling by myself.

**Comment by rostik404** [comment]
👍  looking forward :)

**Comment by rostik404** [comment]
@christian-bromann, my first commit fixed problem with absent message, but not with stack. 
I've found a reason of problem with absent stack. It seems that this is because of  babel https://github.com/babel/babel/issues/6216. I added a hotfix in a second commit.

**Comment by rostik404** [comment]
@christian-bromann, can you give some estimates, when this PR will be tested and merged?

**Comment by rostik404** [comment]
@christian-bromann, ping

**Comment by christian-bromann** [comment]
@rostik404 I will get to it as soon as I have a minute

**Comment by rostik404** [comment]
@christian-bromann, ping

**Pull request merged**
