### PR TITLE
Adding a standard header 'Content-Length' to the headers list to support testing some additional applications like Qt which expects these header in their request payload.

### PR DESCRIPTION
**Pull request by nami-varthakavi**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi can you elaborate who is using this header?

This is in regard to our discussion we had earlier about one of the application we use for desktop-testing which uses a Qt application wrapped around a chromium-based application.In order to communicate with the Qt-wrapper while making requests to the qtDriver it expects this header in the payload which won't cause any crashing of the application while testing.

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi can you elaborate who is using this header?

Since this is a very standard header and was included before in V4, this shouldn't cause any trouble for other requests.

**Comment by christian-bromann** [comment]
In my understanding the content-length header should be set automatically in the request module. Also can you link to the qtDriver you are using?

**Comment by nami-varthakavi** [comment]
> In my understanding the content-length header should be set automatically in the request module. Also can you link to the qtDriver you are using?

I assumed the same, but on comparing with the V4, this is the only thing that causes the trouble. 
This is the link to the qtwebdriver: https://github.com/cisco-open-source/qtwebdriver. But we have modified it extensively to work with our product. I have very limited knowledge of how the product is built.

**Comment by nami-varthakavi** [comment]
I’m yet to fix the unit test, will do first thing in the morning tomorrow.

**Comment by nami-varthakavi** [comment]
@christian-bromann Is it possible to add this header in my config file, so I can skip adding this to the WDIO codebase?

**Comment by christian-bromann** [comment]
> Is it possible to add this header in my config file, so I can skip adding this to the WDIO codebase?

not for specific commands

**Comment by nami-varthakavi** [comment]
> > Is it possible to add this header in my config file, so I can skip adding this to the WDIO codebase?
> 
> not for specific commands

Hmmm, I believe this header shouldn't bring any harm? Will it be possible to approve this over then :) Pretty please :D

**Comment by christian-bromann** [comment]
> Will it be possible to approve this over then :) Pretty please :D

If you add unit tests, yes!

**Comment by nami-varthakavi** [comment]
> Can you add a unit test?

sure I can. I only fixed the existing one I can add one to check this specific header.

**Comment by nami-varthakavi** [comment]
> > Will it be possible to approve this over then :) Pretty please :D
> 
> If you add unit tests,

**Comment by nami-varthakavi** [comment]
> Can you add a unit test?

Added

**Comment by nami-varthakavi** [comment]
I have made the necessary changes and re-opened the merge request. Not sure, it got closed for some reason.

**Comment by abjerstedt** [comment]
@nami-varthakavi I can review the UT and merge if its good, but we have a problem with the CLA signature. 

You will need to rebase and edit your authors on your commits to use only the account that you signed with.

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi I can review the UT and merge if its good, but we have a problem with the CLA signature.
> 
> You will need to rebase and edit your authors on your commits to use only the account that you signed with.

Ok Let me check what I can do.

**Comment by nami-varthakavi** [comment]
Check #3516

**Pull request closed without merging**
