### PR TITLE
Added Accessibility Test to TypeScript boilerplate

### PR DESCRIPTION
**Pull request by dalenguyen**
## Proposed changes

WebdriverIO can check the accessibility of a page with Axe-Core package.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by dalenguyen** [comment]
CLA should be updated now.

**Comment by BorisOsipov** [comment]
@dalenguyen I guess if you change email in commit(and commit itself) CLA will be  re-triggered automatically.

**Comment by BorisOsipov** [comment]
I mean double check your commits\gh profile emails

**Comment by christian-bromann** [comment]
closing and reopening the PR does the trick 😉

**Comment by dalenguyen** [comment]
Thanks @BorisOsipov @christian-bromann

**Pull request merged**
