### PR TITLE
wdio-cli: fix failing launcher tests

### PR DESCRIPTION
**Pull request by stsvilik**
## Proposed changes

Fix failing tests for `wdio-cli`. Not sure what is going on or how they passed during merge, but they're definitely failing for me.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by stsvilik** [comment]
This looks to be related to node version. Original tests (before my fix) are failing on node 11, but pass on 8. Something in node has changed related to calculating running instances.

**Comment by mgrybyk** [comment]
@stsvilik looks like the tests are failing only for you

**Comment by abjerstedt** [comment]
https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md#set-up-project
The project is currently built in Node 8, and so, you should only be using node 8 when contributing.

**Comment by stsvilik** [comment]
I understand that node 8 is the standard, though someone should still investigate why tests are failing under current node version. At some point you need to move forward ;)

**Comment by mgrybyk** [comment]
Works fine with 10

**Comment by abjerstedt** [comment]
At some point we can do a migration. There is absolutely no point in supporting multiple versions of node within our repo for committers.

Supporting multiple versions for people consuming our project is a different story.

**Pull request closed without merging**
