### PR TITLE
Fix VPN chromedriver connection issues by changing default hostname

### PR DESCRIPTION
**Pull request by DIFSRIP**
## Proposed changes

This change updates the default hostname for the ChromeDriver from 0.0.0.0 to 127.0.0.1. When connected to a VPN, connections to 0.0.0.0 are not possible, leading to failures. This update ensures that the connection can be established reliably even when a VPN is used.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

The need for this change was identified while using WebdriverIO behind a VPN connection, which prevented connections to `0.0.0.0` (Error: `Failed to create session. read ENOTCONN at startWebDriverSession`). Switching to `127.0.0.1` ensures connectivity. This solution was chosen after considering options, with the selected approach being the most straightforward and reliable.

### Reviewers: @webdriverio/project-committers

### CODE REVIEW

**Comment by christian-bromann** [comment]
@DIFSRIP mind addressing issues in tests?

**Comment by DIFSRIP** [comment]
> @DIFSRIP mind addressing issues in tests?

sure will fix them today

**Comment by DIFSRIP** [comment]
Dear @christian-bromann, could you please guide me in fixing the tests so we can proceed with the merge. This issue is blocking our whole test executions. 

Any support to speed things up is highly appreciated. 
Thanks in advance!

**Review by christian-bromann — APPROVED** [review]
I think we are good to go with this. Thanks a lot!

👍

**Comment by christian-bromann** [comment]
This patch has been released in `v8.40.2`, thank you again for raising the PR.

**Comment by DIFSRIP** [comment]
> This patch has been released in `v8.40.2`, thank you again for raising the PR.

Thank you @christian-bromann for the quick response and release.

**Comment by erwinheitzman** [comment]
This is great stuff!

Previously we tried doing the same (https://github.com/webdriverio/webdriverio/pull/11542/files) but the tests for the devtools package failed back then, now we got rid of that all should be good.

Very happy to see this 😃

**Pull request merged**
