### PR TITLE
Update Cucumber Dependency Version

### PR DESCRIPTION
**Pull request by tamil777selvan**
## Proposed changes

upgrading the version of @cucumber/cucumber to 9.5.1, which addresses the issue mentioned in https://github.com/webdriverio/webdriverio/pull/11010#discussion_r1316999608.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Nice 👌

**Comment by tamil777selvan** [comment]
Hi @christian-bromann, I apologize for not updating the PR as draft; Unfortunately, the issue with cucumber is still present and I was busy with a bootcamp vm where I'm actively working on resolving the issue and couldn't update this pull request. Considering this, would it be advisable to revert the changes, as they might potentially cause disruptions?

**Comment by christian-bromann** [comment]
I guess with the other PR merged we are good to release this?

**Comment by christian-bromann** [comment]
Thanks!

**Pull request merged**
