### PR TITLE
enable edge for devTools env detector

### PR DESCRIPTION
**Pull request by lacell75**
## Proposed changes

polish backport #12432 to v8

## Types of changes

- [x] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by erwinheitzman** [comment]
I have replied to your changes in #12432

**Comment by christian-bromann** [comment]
> I have replied to your changes in #12432

@erwinheitzman I can't see a reply in that issue 🤔

**Comment by erwinheitzman** [comment]
Oh my bad I think I meant to post this in a different PR 👀 I had not seen this code yet

**Review by erwinheitzman — APPROVED** [review]
LGTM 👍

**Pull request merged**
