### PR TITLE
Update github assertions in example mocha file

### PR DESCRIPTION
**Pull request by klamping**
Github must have updated their page title/logo. This makes the tests pass again.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@klamping thanks! Could you also update the other examples? A simple search and replace would be sufficient enough :wink:

**Comment by klamping** [comment]
Yeah, I was thinking the other files would probably need to be updated. Will do!

**Comment by klamping** [comment]
Updated now, i believe that covers all of the tests/examples.

**Comment by christian-bromann** [comment]
Sweet, thanks!

**Pull request merged**
