### PR TITLE
backward compatibility for node 12,13

### PR DESCRIPTION
**Pull request by udarrr**
dependand bot had changed fs-extra from ^10.0.0 to ^11.1.0 for wdio7 but  fs-extra ^11.1.0 support only node>=14 the pull request change version fs-extra back to ^10.0.0 for backward compatibility with node 12,13

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Please revert the changes that manually update the package versions. This happens automatically as part of the release

**Comment by udarrr** [comment]
Reverted

**Comment by christian-bromann** [comment]
Can we add `fs-extra` to the ignore list so we don't accidentally update it again? See https://github.com/webdriverio/webdriverio/blob/v7/.github/dependabot.yml#L10-L17

**Comment by udarrr** [comment]
Added

**Review by christian-bromann — APPROVED** [review]
LGTM, thanks 👍

**Comment by udarrr** [comment]
Look like for windows it's failed due to a test

it('should allow to check for PWA', async () => {

**Pull request merged**
