### PR TITLE
@wdio/junit-reporter: Fixes issue with junit reporter not working on windows

### PR DESCRIPTION
**Pull request by lukefitz1**
## Proposed changes

This is a bug fix for [this bug](https://github.com/webdriverio/webdriverio/issues/10391). 

The reporter checks that the filepath for the spec file matches the expected filepath, but on Windows, due to forward slashes and 1 leading slash, the comparison will always fail. This change removes the leading slash and replaces forward slashes with backslashes when tests are running on windows. Tested on macOS (Ventura), Windows 11, and Ubuntu just to verify that the change didn't affect mac/linux users. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thank you for looking into this.

I think instead of using string `replace` methods here we should use Node.js APIs to handle paths and transform them the way we need it, e.g. use `url.pathToFileUrl` etc. Would you mind checking this option?

**Comment by lukefitz1** [comment]
@christian-bromann Thanks for the suggestion, it did end up simplifying the code, no more ternary. Please give it another look when you have a chance. Thanks!

**Comment by christian-bromann** [comment]
@lukefitz1 looks good, it seems that tests are failing though, mind taking a look?

**Comment by christian-bromann** [comment]
ping @lukefitz1

**Pull request closed without merging**
