### PR TITLE
Support for running WebdriverIO TypeScript tests on Node 20. Fixes #10901

### LINKED ISSUE #10901: [🐛 Bug]: First time test run of WDIO with default configs results in ES related errors
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v20.5.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

I started with WDIO installation following these steps

- Created a git repo, cloned it on my system and did `npm init`
- Proceeded with `npm init wdio` and accepted the default behavior in most cases 
-  Ran `npm run wdio` and faced errors

Attached screenshot of the `npm init wdio` step 

Screenshot 2023-08-09 at 11 10 26 AM

### What is your expected behavior?

The initial `npm run wdio` should have worked fine. Instead it started throwing error - 

`SyntaxError: Cannot use import statement outside a module`

Full stack trace I have pasted in the log output section.

### How to reproduce the bug.

-  Clone this repo : https://github.com/zac11/wdio-work-demo
-  Run `npm run wdio`

### Relevant log output

```typescript
npm run wdio

> wdio-work-demo@1.0.0 wdio
> wdio run ./wdio.conf.ts

2023-08-09T05:30:14.234Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/annubha/Documents/Rahul/wdio-work-demo/wdio.conf.ts: Cannot use import statement outside a module
/Users/annubha/Documents/Rahul/wdio-work-demo/wdio.conf.ts:1
import type { Options } from '@wdio/types'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async ConfigParser.addConfigFile (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/config/build/lib/ConfigParser.js:85:36)
    at async ConfigParser.initialize (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/config/build/lib/ConfigParser.js:47:13)
    at async Launcher.run (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/cli/build/launcher.js:37:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by jan-molak**
## Proposed changes

A more targeted variation of #11173, aimed at resolving #10901.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by jan-molak** [comment]
@christian-bromann e2e-mac failure seems to have something to do with node module caching, perhaps?

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by jan-molak** [comment]
> Why do we install Serenity just to test some functionality? I suggest that we replace it with a check of our own

Hey @erwinheitzman - This is to avoid changes to WDIO / TS-Node integration breaking WDIO / Serenity/JS integration. Adding a single dev dependency to be used in an integration test seemed like a reasonable way to enable a fast feedback loop for the WDIO project. Plus, it follows the same pattern WDIO uses to test integration with the Testing Library and other frontend frameworks like Lit, Preact, React, Svelte and Vue.

**Comment by christian-bromann** [comment]
@jan-molak it seems like the added e2e tests are failing, mind taking a look?

**Comment by jan-molak** [comment]
@christian-bromann - it looks like the failure of e2e-windows is unrelated to the change I proposed:

```
[2-0] RUNNING in firefox - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[0-0] RUNNING in chrome - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[1-0] RUNNING in chrome - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[3-0] RUNNING in firefox - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[4-0] RUNNING in edge - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[4-0] FAILED in edge - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[1-0] PASSED in chrome - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[0-0] PASSED in chrome - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[3-0] PASSED in firefox - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
[2-0] PASSED in firefox - file:///D:/a/webdriverio/webdriverio/e2e/wdio/headless/secondTest.e2e.ts
```
and the `e2e-mac` build fails because it can't find the new dependency, even though the windows one can... It seems rather odd, but maybe I'm misunderstanding how deps are installed in the WDIO build on CI 🤔 

Let me take another stab at this on a fresh branch

**Comment by jan-molak** [comment]
Closing in favour of #11202 11202

**Comment by erwinheitzman** [comment]
> > Why do we install Serenity just to test some functionality? I suggest that we replace it with a check of our own
> 
> Hey @erwinheitzman - This is to avoid changes to WDIO / TS-Node integration breaking WDIO / Serenity/JS integration. Adding a single dev dependency to be used in an integration test seemed like a reasonable way to enable a fast feedback loop for the WDIO project. Plus, it follows the same pattern WDIO uses to test integration with the Testing Library and other frontend frameworks like Lit, Preact, React, Svelte and Vue.
> 
> I hope this explanation helps, but let me know if you have any other questions.
> 
> Also see #10816 for reference.

Thanks for the reply, makes sense 👍

**Pull request closed without merging**
