### PR TITLE
Provide documentation for more than just one language

### PR DESCRIPTION
**Pull request by christian-bromann**
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**

WebdriverIO should provide its docs in more than just English. Anyone who is interested in helping out translating the docs please answer on this thread.

### CODE REVIEW

**Comment by abjerstedt** [comment]
@christian-bromann since this PR isn't going anywhere, can we close this and reopen it as a draft pr?

**Comment by baruchvlz** [comment]
Once the strings are added to crowdin's website I can start with the Spanish translations, but until then there isn't much I can do.

**Comment by christian-bromann** [comment]
@abjerstedt I want to pick this up again next week

**Comment by christian-bromann** [comment]
@baruchvlz I setup a Crowdin integration, so you can just go to https://crwd.in/webdriverio and start translating.

**Comment by DmitrijParchomenko** [comment]
@christian-bromann I can help with Russian translation

**Comment by Werewolfas** [comment]
@christian-bromann I can help with Russian translation

**Comment by christian-bromann** [comment]
@Werewolfas awesome, thank you! Please go to https://crwd.in/webdriverio and translate await 😉

**Comment by Werewolfas** [comment]
@christian-bromann I think you need to add Russian as target language or I can't find where to add language in this project

**Comment by CrispusDH** [comment]
I also can not find how to add new language

**Comment by christian-bromann** [comment]
@Werewolfas I added Russian as target language.

@CrispusDH I think the process we have to use is that the @webdriverio/technical-steering-committee that will manage the translation integration add a new target language on the platform and others can start translating that language. It doesn't make sense to open all languages and some people only translate parts of the API.

**Comment by tadashi0713** [comment]
@christian-bromann I can help with Japanese 🇯🇵

**Comment by christian-bromann** [comment]
@tadashi0713 I just added Japanese as target language, feel free to suggest translations on https://crwd.in/webdriverio

**Comment by WarleyGabriel** [comment]
Hi, @christian-bromann could you add Brazilian Portuguese on Crowdin?

**Comment by junghanChoi** [comment]
The translation is interesting! I made 4% of Korean.

**Comment by christian-bromann** [comment]
@junghanChoi thanks! We are looking forward to finally get one language translated

**Comment by christian-bromann** [comment]
We will have to create a new PR for the Docusarus v2 Crowdin integration. If anyone has some time to [help us out](https://crowdin.com/project/webdriverio/invite/public?show_welcome&d=1b8342566d4c69f3fe2cb9606ada83e11144411) in one of the language, please continue to do so.

**Pull request closed without merging**
