### PR TITLE
Refactor type generation after killing sync mode

### PR DESCRIPTION
**Pull request by christian-bromann**
It's time to refactor and improve our browser types, due to the following issues:

- we currently still generate synchronous types even though with v8 we killed all sync features
- we also face issues where IDEs like VS Code would autocomplete element call chains, e.g. `await (await browser.$("fooo")).click()`

This patch basically:

- makes sure we use the namespace everywhere, e.g. `WebdriverIO.Browser` instead of importing the type from the `webdriverio` package (which is why I had to add `@wdio/globals/types` to the `tsconfig.json` types)
- use `getInstance` to get a browser instance from a multiremote object (easier typing), this is what we should recommend doing moving forward
- added `MultiRemoteElement` to the `WebdriverIO` namespace
- removed all sync commands and generated types
- export all commands by name instead of `default` to carry over all type information without reformatting the export object

### CODE REVIEW

**Comment by christian-bromann** [comment]
@SCG82 mind taking a look once you have time, I tried to describe the changes above. While a lot of files are touched, the changes are fairly trivial and easy to review. Let me know what you think!

**Comment by SCG82** [comment]
> @SCG82 mind taking a look once you have time, I tried to describe the changes above. While a lot of files are touched, the changes are fairly trivial and easy to review. Let me know what you think!

I'll take a look after work today.

**Review by SCG82 — APPROVED** [review]
Nice!

Do these need to be changed to namespaced types?
```
 packages/webdriverio/tests/addCommand.test.ts
 packages/webdriverio/tests/middleware.test.ts
 packages/webdriverio/tests/multiremote.test.ts
```

**Comment by christian-bromann** [comment]
> Do these need to be changed to namespaced types?

Yes, I fixed them. Hope there shouldn't be any `Browser` or `Element` type imports around.

**Comment by christian-bromann** [comment]
Weird, I don't get the compile issues on my machine, even after checking out the project into a new directory.

**Comment by christian-bromann** [comment]
> * we also face issues where IDEs like VS Code would autocomplete element call chains, e.g. `await (await browser.$("fooo")).click()`

It seems still be a valid problem with all the changes. I will create a new issue and tackle it individually.

**Comment by christian-bromann** [comment]
> [@github-actions ](/apps/github-actions)
> ** Test / e2e-windows (pull_request) ** In progress — This check has started...
> [Details](/webdriverio/webdriverio/actions/runs/3956288345/jobs/6775353169)
> [ @github-actions ](/apps/github-actions)
> ** Test / e2e-mac (pull_request) ** Failing after 9m

These also fail on `main` I will go ahead, merge and send a fix for the build tomorrow.

**Pull request merged**
