### PR TITLE
Update CustomServices.md

### PR DESCRIPTION
**Pull request by tzurp**
## Proposed changes
Clarify the need for framework-specific hooks in a worker service.
[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
This note seems to be thrown in without context. Could you elaborate on this?

**Comment by erwinheitzman** [comment]
I asked @tzurp if he would be so kind to create a PR to mention this in our docs after resolving the following issue together in this service: https://github.com/tzurp/performance-total/issues/15

The issue was that for Cucumber the `beforeTest` and `afterTest` where not triggered which @tzurp thought would work.

**Comment by christian-bromann** [comment]
Thanks for providing more context. I think it makes sense to add this information but would love to see a better place for it or written in a larger paragraph. Right now it feels like the sentence is thrown in there and not many people will understand what it means.

**Comment by christian-bromann** [comment]
@tzurp sounds like a plan

**Comment by christian-bromann** [comment]
@tzurp any updates?

**Comment by tzurp** [comment]
I reverted the doc text and added to the worker service code snippet examples for beforeTest (for Mocha/Jasmin) and beforeScenario (for Cucumber). Please tell me what do you think.

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
