### PR TITLE
No more files property but via npmignore

### PR DESCRIPTION
**Pull request by paazmaya**
## Proposed changes

Ignore non needed files via `.npmignore` instead of whitelist.

## Types of changes

What types of changes does your code introduce to WebdriverIO?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

For some reason in this project, the `files`property did not work as usual, might be due to the nature of `build` folder being creating during pre publish step...

### CODE REVIEW

**Comment by christian-bromann** [comment]
screen shot 2016-08-17 at 19 57 03

Doesn't work either. I also tried plenty variations without success. Could you publish it as scoped npm package?

**Comment by just-boris** [comment]
Tip: to test NPM logic you can also run `npm package` then you will get `<package>.tgz` archive. This is the same archive that will be uploaded during `npm publish`.

**Comment by paazmaya** [comment]
The command I have used when testing `npm pack`

**Comment by just-boris** [comment]
@paazmaya you are right. I meant `npm pack` of course.

**Comment by christian-bromann** [comment]
Just realized that `npm pack` bundles the package correctly, will try to release that.

**Comment by christian-bromann** [comment]
Ok, did some minor tweak to npmignore and published as `v4.2.7`. After a quick sanity check it looks all fine now. Thanks!

**Comment by paazmaya** [comment]
Sorry for the troubles...

**Pull request merged**
