### PR TITLE
[sauce-service] Add RDC update job support

### PR DESCRIPTION
**Pull request by wswebcreation**
## Proposed changes

Sauce Labs now also supports test annotation for Real Devices. This PR removes the limitation and has some small updates for the docs

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by wswebcreation** [comment]
Not sure why the tests are failing, as far as I can see they are not related to my change

**Comment by SCG82** [comment]
https://github.com/webdriverio/webdriverio/pull/9744

**Comment by wswebcreation** [comment]
Ahh, crap, you're right @SCG82 , tnx for the fix, will merge it into mine when the tests passed

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Pull request merged**
