### PR TITLE
Added (failing) tests for windows/tabs opened via Javascript

### PR DESCRIPTION
**Pull request by fireproofsocks**
I'm submitting this pull request to share the failing tests I added for demonstrating issue https://github.com/webdriverio/webdriverio/issues/951

If there's an issue with the syntax that can be corrected to make the tests pass, I'd love to see it (and I can add it to the docs).  If this demonstrates a legitimate bug, then please feel free to reference the included tests to reproduce the error.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@fireproofsocks thanks for submitting this PR. You've posted the following code:

```js
// localhost has 2 pages: main.html (parent) and secondary.html
var main;
var secondary;
browser
.url('http://localhost/main.html')
.pause(1000)
.getTitle()
.then(function(title) {
    console.log('On window: ' + title);  // Main
})
.getCurrentTabId().then(function(ret){
    main = ret;
})
.click('span*=Popup') // Open the secondary window via a popup
.pause(1000)
.getTabIds().then(function (handles) {
    secondary = handles[handles.length - 1];
})
.switchTab(secondary)
.pause(1000)
.getTitle()
.then(function(title) {
    console.log('On window: ' + title);  // Expected: Secondary, Actual: Main!
})
.switchTab(main)
.pause(1000)
.getTitle()
.then(function(title) {
    console.log('On window: ' + title); // Main
})
.pause(1000)
.call(done);
});
```

I am note sure but if I remember correctly I was also confused by that. I think if you call getTitle on a window you switched to you will still get the old window title of the other tab (not 100% sure though). This seems to be a Selenium issue if turns out to be true. However instead of using getTitle could you try to query an element that only exists on the second page?

**Comment by fireproofsocks** [comment]
Yeah, I'm afraid it might be a Selenium issue... take a look at the tests in that branch for switchTab() -- it relies on the tab id, and it does not change.  In my own project I've tried to select stuff in the popup or populate form fields in there and it fails, but I think it all boils down to the included tests.

**Comment by christian-bromann** [comment]
@fireproofsocks we updated the code base (merged v4 branch). Could you please fetch a fresh copy from the master branch and open a new PR? Thanks!

**Comment by fireproofsocks** [comment]
Errr.... can you walk me through this?  Sorry, my Git shui is not good enough to follow how to do this without completely redoing all my work.

**Comment by mselvanambi** [comment]
Guys, 
I still face the same issue of switching tab not working with  web driver io .
Can someone tel me was there solution already in place for this  or something an issue with the selenium itself ??
Thankyou.

**Pull request closed without merging**
