### PR TITLE
Support multiple tables in scenario outline

### LINKED ISSUE #4287: Cucumber: Scenario Outline fails if there is more than one table
**Environment:**
"@wdio/cucumber-framework": "^5.11.11

**Log:**
```
ERROR @wdio/runner: TypeError: Cannot read property 'steps' of undefined
at CucumberEventListener.onTestCasePrepared (ode_modules\@wdio\cucumber-framework\build\cucumberEventListener.js:132:42)
```

**Steps to reproduce:**
Step definition:
```
Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})
```
Feature
```
Feature: Foo
    foobar

    Scenario Outline: Bar
        Given User <userId> with <password> is logged in

        @first
        Examples:
                | userId    | password |
                | 345       | pw3      |

        @second
        Examples:
                | userId    | password |
                | 456       | pw4      |
```

More information on below thread:
https://github.com/webdriverio/webdriverio/issues/4195

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Support multiple tables in scenario outline.
fix #4287

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works

## Further comments

TODO:
- [ ] add unit tests
- [ ] add smoke tests

### CODE REVIEW

**Comment by mgrybyk** [comment]
@christian-bromann I spend couples of hours to find that god damn line as well, haha

Here is how it looks in smoke tests
image

if there are no comments, can be merged

**Comment by mgrybyk** [comment]
_Thanks_ to wdio-cucumber-framework I lear cucumber more and more!

**Comment by gtilekar** [comment]
Thank you . Your help is highly appreciated. 👍

**Comment by nextlevelbeard** [comment]
@mgrybyk I will open an issue if confirmed but just FYI, with this change (5.11.12), after nuking modules, I'm getting:
```none
0-0 worker error {
  name: 'TypeError',
  message: "Cannot read property 'type' of undefined",
  stack: "TypeError: Cannot read property 'type' of undefined\n    at " +
    'getStepFromFeature ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\@wdio\\cucumber-framework\\build\\utils.js:144:18)\n' +
    '    at CucumberEventListener.onTestStepStarted ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\@wdio\\cucumber-framework\\build\\cucumberEventListener.js:58:48)\n' +
    '    at EventEmitter.emit (events.js:205:15)\n    at EventEmitter.emit ' +
    '(domain.js:471:20)\n    at TestCaseRunner.emit ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:85:27)\n' +
    '    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:177:13\n' +
    '    at Generator.next (<anonymous>)\n    at asyncGeneratorStep ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:22:103)\n' +
    '    at _next ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:194)\n' +
    '    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:364\n' +
    '    at new Promise (<anonymous>)\n    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:97\n' +
    '    at TestCaseRunner.aroundTestStep ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:201:7)\n' +
    '    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:296:24\n' +
    '    at Generator.next (<anonymous>)\n    at asyncGeneratorStep ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:22:103)\n' +
    '    at _next ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:194)\n' +
    '    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:364\n' +
    '    at new Promise (<anonymous>)\n    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:97\n' +
    '    at ' +
    'C:\\Users\\[REDACTED]\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:300:24\n' +
    '    at tryCatcher ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n' +
    '    at Object.gotValue ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\reduce.js:155:18)\n' +
    '    at Object.gotAccum ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\reduce.js:144:25)\n' +
    '    at Object.tryCatcher ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n' +
    '    at Promise._settlePromiseFromHandler ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\promise.js:510:31)\n' +
    '    at Promise._settlePromise ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\promise.js:567:18)\n' +
    '    at Promise._settlePromise0 ' +
    '(C:\\Users\\[REDACTED]\\node_modules\\bluebird\\js\\release\\promise.js:612:10)'
}
```

with Feature
```none
@tag
Feature: Feature
  Description 1
  Description 2
  Description 3

  Background:
    Given I do something

  @tag
  Scenario Outline: User can do stuff <type>
    Given I do stuff 1
    And I do stuff <type>
    Then I should have done stuff 3
      Examples:
        | type |
        | asd  |
      @tag2
      Examples:
        | type  |
        | que   |
```

Both tests tun but only the first is printed with the spec reporter.

**Comment by mgrybyk** [comment]
@nextlevelbeard cannot reproduce it

**Comment by mgrybyk** [comment]
Here is my feature
```
@tag
Feature: Foo
    foobar 1
    foobar 2
    foobar 3

    Backgroud:
        Given stub

    @tag
    Scenario Outline: Bar
        Given stub
        Then User <userId> with <password> is logged in
            Examples:
                    | userId    | password |
                    | 345       | pw3      |

            @tag2
            Examples:
                    | userId    | password |
                    | 456       | pw4      |
```

and my definitions:
```

Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})

Given('stub', function () {
    console.log('stub')
})
```

**Comment by nextlevelbeard** [comment]
I haven't been able to pinpoint why exactly.
`getStepFromFeature` is accessing `combinedSteps` which is out of bounds.
I suspect it might be related to the hooks I have. Do you have any in your setup?

**Comment by mgrybyk** [comment]
Don't know, if you have steps to reproduce, I can take a look

**Comment by jonn-set** [comment]
This was fixed back in March, https://github.com/webdriverio-boneyard/wdio-cucumber-framework/issues/162

Looks like it never got released, can someone just release a new version, please?

**Pull request merged**
