### PR TITLE
added qmate service

### PR DESCRIPTION
**Pull request by DIFSRIP**
## Proposed changes

Added the qmate-service https://sap.github.io/wdio-qmate-service/ to the supported services and docs.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

**Not applicable**

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍  thanks!

**Comment by christian-bromann** [comment]
@DIFSRIP mind signing the CLA? Thanks!

**Comment by christian-bromann** [comment]
ping @DIFSRIP

**Comment by christian-bromann** [comment]
@DIFSRIP also would you mind to raise the same PR for the `v7` branch?

**Comment by christian-bromann** [comment]
@DIFSRIP I went ahead and pushed the change myself. Please make sure you or your company has signed the CLI.

**Comment by DIFSRIP** [comment]
> @DIFSRIP I went ahead and pushed the change myself. Please make sure you or your company has signed the CLI.

So sorry for the late reply. I was on vacation for some weeks and just came back. My user is now signed to the CLI. Thanks for taking over. Anything left, I need to do from SAP side?

**Comment by christian-bromann** [comment]
> Anything left, I need to do from SAP side?

Nope, all good!

**Pull request closed without merging**
