### PR TITLE
typings: Add appium capabilities.

### PR DESCRIPTION
**Pull request by aha-oretama**
## Proposed changes

Add appium capabilities #3984 

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

I don't have added tests. But I check local environment.

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by CrispusDH** [comment]
I don't see added capability. Could you write what exactly capability(ies) you added?

**Comment by aha-oretama** [comment]
I added `General Capabilities` in the following link.
http://appium.io/docs/en/writing-running-appium/caps/

**Comment by aha-oretama** [comment]
Does it mean that all the capabilities should be listed, and Generic and

**Comment by wswebcreation** [comment]
> It means that all the capabilities should be listed, and the capabilities definition should be divided to Generic, Android , iOS interface. right?

Yes, to prevent new PR's / issues in the future I'd suggest to put them all in here. Dividing it like it is done on the appium site would be useful I think.

**Comment by erwinheitzman** [comment]
Since these are Appium specific properties, please extend the interface with a Appium interface instead so it's easy to see where the properties belong to.

**Comment by wswebcreation** [comment]
@erwinheitzman 

> Since these are Appium specific properties, please extend the interface with a Appium interface instead so it's easy to see where the properties belong to.
> 
> EDIT: seems I can't deny the PR for now hence I have added it as a comment here

I agree on that one, but that means we need to create separate interfaces for each browser. I don't think that's part of the PR. I'd say for now keep it in the same structure and fix it with a  💅-PR unless it's really easy not to fix for all

**Comment by aha-oretama** [comment]
I added all the appium capabilities.
But now I didn't divide into some interfaces.
Although I didn't test them yet, this pull request's scope is all, right?
If right, I'll check more that all the capabilities are passed to appium correctly.

**Comment by christian-bromann** [comment]
Thanks!

> Although I didn't test them yet, this pull request's scope is all, right?

Yes, can you please sign the CLA so I can merge this?

**Comment by aha-oretama** [comment]
> Although I didn't test them yet,

I've tested all the capabilities, and made some fixes.
Please merge this PR.

**Pull request merged**
