### PR TITLE
Fix screenshot saves after error

### PR DESCRIPTION
**Pull request by sbmaxx**
This will fix case when `client.end()` is called before screenshot is saved after error.

For example:
```js
describe('test', function() {
    before(function() {
        return client.init();
    });

    after(function() {
        return client.end();
    });

    it('set value', function() {
        return client.url('someurl').click('someElement');
    });
});
```

If `click` fails — there are no guarantee that webdriver will have enough time to send `saveScreenshot` request and get response.

Second case — if `saveScreenshot` fails it cause recursion.

### CODE REVIEW

**Comment by sbmaxx** [comment]
@christian-bromann what do you think?

**Comment by christian-bromann** [comment]
We are currently working in the v4 branch and I don't think we should add any more core changes to the master branch as it makes porting commits difficult later one.

**Comment by sbmaxx** [comment]
Any estimates about v4?

четверг, 14 января 2016 г. пользователь Christian Bromann написал:

> We are currently working in the v4 branch and I don't think we should add
> any more core changes to the master branch as it makes porting commits
> difficult later one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webdriverio/webdriverio/pull/1030#issuecomment-171689520>
> .
>


-- 

Roman Rozhdestvenskiy

**Comment by christian-bromann** [comment]
we are at 90% and try to get it out asap

**Comment by christian-bromann** [comment]
@sbmaxx we updated the code base (merged v4 branch). Could you please fetch a fresh copy from the master branch and open a new PR? Thanks!

**Comment by georgecrawford** [comment]
Hey @sbmaxx. I think I've just run into this bug in v4. I notice that even though an error is caught, and a screenshot command is issued, we don't wait for the result before continuing the chain of queued commands. So the result from the screenshot might come later, after some other commands/results have already occurred, which messes up reporting and might also change the browser's state before the screenshot is taken.

I don't really understand how you fixed it, but could you have a look at how it might be done in v4?

**Comment by georgecrawford** [comment]
```
[12:39:49]  COMMAND	POST 	 "/wd/hub/session/3ee8e216-7212-47c7-a6e2-992730f28514/elements"
[12:39:49]  DATA		{"using":"id","value":"splash"}
[12:39:50]  RESULT		[{"ELEMENT":"1"}]
[12:39:50]  COMMAND	GET 	 "/wd/hub/session/3ee8e216-7212-47c7-a6e2-992730f28514/element/1/displayed"
[12:39:50]  DATA		{}
[12:39:50]  RESULT		true
[12:39:50]  COMMAND	POST 	 "/wd/hub/session/3ee8e216-7212-47c7-a6e2-992730f28514/elements"
[12:39:50]  DATA		{"using":"id","value":"splash"}
[12:39:51]  ERROR	ServerError	element (#splash) still  visible after 4000ms
ERROR: element (#splash) still  visible after 4000ms
chrome.latest.mac
    no stack available
[12:39:51]  COMMAND	GET 	 "/wd/hub/session/3ee8e216-7212-47c7-a6e2-992730f28514/screenshot"
  1) "before all" hook
[12:39:51]  DATA		{}
[12:39:51]  COMMAND	DELETE 	 "/wd/hub/session/3ee8e216-7212-47c7-a6e2-992730f28514"
[12:39:51]  DATA		{}
[12:39:51]  RESULT		[{"ELEMENT":"1"}]
[12:39:51]  COMMAND	GET 	 "/wd/hub/session/3ee8e216-7212-47c7-a6e2-992730f28514/element/1/displayed"
[12:39:51]  DATA		{}
[12:39:53]  RESULT		[base64] 767584 bytes
[12:39:53]  RESULT		null
```
See that the screenshot result (penultimate line) is way later than the screenshot command.

**Comment by sbmaxx** [comment]
@georgecrawford the fix was in [this commit](https://github.com/sbmaxx/webdriverio/commit/4dc1d50117207c6ddf1b360b76eb70d161e57418). I'll take a look in v4 for this bug

**Pull request closed without merging**
