### PR TITLE
fix scrollIntoView to use well browser.Action

### PR DESCRIPTION
**Pull request by qaflorent**
## Proposed changes

My [previous MR ](https://github.com/webdriverio/webdriverio/pull/11496) doesn't solve the verbose error log `ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds`

I reviewed my initial thoughts about these lines

```
await browser.action('wheel')
            .scroll({ duration: 0, x: deltaX, x: deltaY, origin: this })
            .perform()
```

Checking [the doc on browser.action('wheel')](https://github.com/webdriverio/webdriverio/blob/8ca026c75bf7c27ef9d574f0ec48d8bc13658602/packages/webdriverio/src/utils/actions/wheel.ts#L4-L29) , params x/y are the starting coordinates and deltaX/Y are delta to scroll to target.

Delta is computed in `scrollIntoView` as the diff between the element position and the current scroll position. So it makes sense for me to use the param `deltaX/Y` of `browser.action('wheel')` instead of `x/y`

Of Course, I am open to discussion if I am wrong 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

To follow https://github.com/webdriverio/webdriverio/pull/11496#issuecomment-1798455109 and thanks to @christian-bromann I managed to test it directly in my local project updating manually in `node_modules`

### Reviewers: @webdriverio/project-committers

@christian-bromann @erwinheitzman

### CODE REVIEW

**Comment by qaflorent** [comment]
I am checking the test :eyes:

**Comment by christian-bromann** [comment]
@qaflorent any updates?

**Comment by qaflorent** [comment]
> @qaflorent any updates?

Tests seem to be inaccurate, but I don't have the knowledge to understand if it comes from my MR or not. 
Last week, tests failed in windows tests related to `scrollIntoView` which made me look closer, but I can't reproduce, and today we have failures in other tests.

**Comment by christian-bromann** [comment]
Maybe try update your branch since we had a lot of changes coming in.

**Comment by qaflorent** [comment]
I don't feel confident with this change, and my deep tests made me doubt. I prefer to close it, even if the logs I get from this code even if all works good are very annoying 

```
[0-49] 2023-11-22T11:03:54.721Z WARN webdriver: Request failed with status 500 due to move target out of bounds
[0-49]   (Session info: chrome=111.0.5563.64)
[0-49] 2023-11-22T11:03:54.742Z WARN webdriver: Request failed with status 500 due to move target out of bounds
[0-49]   (Session info: chrome=111.0.5563.64)
[0-49] 2023-11-22T11:03:54.762Z WARN webdriver: Request failed with status 500 due to move target out of bounds
[0-49]   (Session info: chrome=111.0.5563.64)
[0-49] 2023-11-22T11:03:54.783Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds
[0-49]   (Session info: chrome=111.0.5563.64)
[0-49] 2023-11-22T11:03:54.783Z WARN webdriverio: Failed to execute "scrollIntoView" using WebDriver Actions API: move target out of bounds
[0-49]   (Session info: chrome=111.0.5563.64)!
```

**Comment by christian-bromann** [comment]
> even if the logs I get from this code even if all works good are very annoying

Let's work this out, do you have `logLevel` set to `error`?

**Pull request closed without merging**
