### PR TITLE
Fix debug in Node 7+

### PR DESCRIPTION
**Pull request by mltsy**
## Proposed changes

Fixes the bug caused by the `--debug` flag being replaced with `--inspect` in Node 7+

This is a re-submission of an abandoned PR, with requested changes: https://github.com/webdriverio/webdriverio/pull/2200

Related Issues: #1640 , #2194

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

I wasn't able to run tests because when I got to `bower install` I got a `command not found` message.  I tried `npm install bower` and that didn't help.  Any hints?

Also, I'm not sure I understand how these changes are supposed to work, now that I've looked at them.  I would think we'd just want to use `--inspect` if the node version is 7+ and use `--debug` otherwise, but this seems more complex than that... or just harder to understand perhaps?  (Sorry about this - I'm the the odd position of submitting a PR someone else wrote!) :wink:

### CODE REVIEW

**Comment by mltsy** [comment]
Oh boy... I dont' know if we'll be able to get @hermanho's attention to sign the CLA.  If not, I can remove that commit, and just re-create the same functionality, which... I might do differently anyway, depending on the response to my questions under "Further Comments".

**Comment by NicolasSiver** [comment]
Hello guys.
Where are we with these changes?

**Comment by codiophile** [comment]
> Also, I'm not sure I understand how these changes are supposed to work, now that I've looked at them. I would think we'd just want to use --inspect if the node version is 7+ and use --debug otherwise, but this seems more complex than that... or just harder to understand perhaps? (Sorry about this - I'm the the odd position of submitting a PR someone else wrote!)

I'm as confused as you. I just changed `--debug` to `--inspect` and everything works fine. No clue what this code is good for.

I opened a pull request with this change https://github.com/webdriverio/webdriverio/pull/2377 before I saw this one. It doesn't check node version, but maybe it should? In what version was `--inspect` introduced? Maybe it's supported far back enough, that we don't need that check?

**Comment by mltsy** [comment]
Yeah, it looks like that goes back to at least Node 6.3, which is before the current LTS release (6.11) so I would think that would be fine at this point. (Does wdio already require Node 6.3+ ?)  @christian-bromann - what do you think of closing this and merging #2337?

**Comment by codiophile** [comment]
@mltsy You got the number wrong for the merge request. It's #2377 :)

**Comment by mltsy** [comment]
Oops!  Thanks, fixed :)

**Comment by mltsy** [comment]
Oh!  I actually thought #2377 looked more straight-forward and solved the problem (I was suggesting merging that one and closing this one).  I actually don't understand how this one is supposed to work, but if you think this does what we need, then great! :)

**Comment by codiophile** [comment]
I don't mind whichever PR you merge, as long as it works, but I have a couple of concerns about this one.

My first concern is that sending both `--debug` and `--inspect` to a node version that supports both, e.g. node 6, might cause a conflict. Also, sending `--debug` to a version in which it is deprecated, will cause node to print the deprecation warning. This might be harmless, but not nice and not necessary.

My second concern is that the debugging is now based on the arguments node was started with, rather than whether the debug flag is set. I think this makes sense, but it makes the debug flag redundant, which hasn't been addressed. I think we should deprecate it and simply use this strategy rather than a mix of both.

I might make a PR later to show you what I mean.

**Comment by christian-bromann** [comment]
> Oh! I actually thought #2377 looked more straight-forward and solved the problem

@mltsy @codiophile is it backwards compatible to node v4 tho?

> I think we should deprecate it and simply use this strategy rather than a mix of both.

I agree. @mltsy can you address this? I would be happy to remove one config property from the wdio.conf.js

**Comment by codiophile** [comment]
I didn't make the PR yet, because I got stuck on building it, so that I could test it. Hence #2401. I think it would have made things clear.

> @mltsy @codiophile is it backwards compatible to node v4 tho?

My idea is that we don't have to worry about the node version if we just pass along the flags that we get from `process.execArgv`, i.e. if the parent is started with `--debug`, the children will be started with `--debug` and if the parent is started with `--inspect`, the children will be started with `--inspect`. That way we leave it to the user to choose which flag to use, which I think is the best option considering that node 6 supports both. 

To answer your question, `--inspect` was experimental in node 6 and I don't think it was available in node 4, but I haven't checked that.

As soon as I get things working I would be happy to make the PR.

**Comment by christian-bromann** [comment]
> To answer your question, --inspect was experimental in node 6 and I don't think it was available in node 4, but I haven't checked that.

With the next version we still support node v4. Once Node v10 is out (probably May next year) I will kill support for Node v4.

> As soon as I get things working I would be happy to make the PR.

Awesome, thanks!

**Comment by christian-bromann** [comment]
Closing in favor of #2418

**Pull request closed without merging**
