### PR TITLE
Allow spec files to be passed via --spec without the full path of the file

### PR DESCRIPTION
**Pull request by andrew-tompkins**
## Proposed changes

These changes should address this issue: https://github.com/webdriverio/webdriverio/issues/9495

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by andrew-tompkins** [comment]
Looking into the failed tests.

**Comment by christian-bromann** [comment]
@andrew-tompkins let me know if I can help in any way.

**Comment by andrew-tompkins** [comment]
@christian-bromann Well I'm not sure why the specs are failing. I changed around the initial PR to fix the specs that were failing at that point. But I'm unsure about the latest failures. To make it harder, I'm having issues getting them to run properly on my local env. It's conflicting with other "work" stuff I have on my laptop. 

I'm hoping to come back to this in the next couple days to take another look.

**Comment by djpasch** [comment]
Hi, are there any updates on this pull request?
Currently i'm unable to use wildcards to run my spec files, so it would be great if this gets fixed.

**Comment by andrew-tompkins** [comment]
Sorry, I haven't gotten back to this as work has gotten busy lately. Last time I looked though, I wasn't sure what the failing tests were about, and was unable to get them running locally either to try and figure it out.

**Comment by awhisler** [comment]
Any updates on when this will be merged?

**Comment by christian-bromann** [comment]
> Any updates on when this will be merged?

Did you see @andrew-tompkins comment?

**Comment by djpasch** [comment]
@christian-bromann as @andrew-tompkins was not able to fix it till now, isn't is possible that you take over this pull request? For me it's the last issue that prevents me from switching to V8

**Comment by christian-bromann** [comment]
> isn't is possible that you take over this pull request?

I have my own priorities. Would you like to chip in an support?

**Comment by bhanuagarwal73** [comment]
Eagerly waiting for this

**Comment by andrew-tompkins** [comment]
I still have this on my list to come back to but I've been swamped at work lately, and real life is even busier. So not sure when I will get back to this.

If you want to try and have a look at why the specs are failing, that would help a lot.

**Comment by andrew-tompkins** [comment]
I had a few spare hours, so I came back to look at this. But i'm getting test failures when I run them off the `main` branch. Are there any known errors in `main` today?

**Comment by christian-bromann** [comment]
@andrew-tompkins awesome, the last commit on `main` [passed](https://github.com/webdriverio/webdriverio/actions/runs/5694241465). Did you pull everything on the `main` branch and rebased? This is what I would do:

```sh
git checkout main
git pull origin main
git checkout issue-9495-spec-cli
git rebase main
```

Let me know if this works!

**Comment by andrew-tompkins** [comment]
@christian-bromann What I mean was when I run the tests on my local against `main`, so nothing with my changes, they are failing for me. So I must have something wrong with my setup.

**Comment by adrian-cocoara-lgp** [comment]
Hello @christian-bromann and @andrew-tompkins, I know you guys are busy with other stuff, but can we have an ETA for merging this PR? This is the last issue that prevents me to upgrade to v8. Thanks!

**Comment by christian-bromann** [comment]
@adrian-cocoara-lgp please get involved help to fix the bug, any help is appreciated.

**Comment by christian-bromann** [comment]
resolved by https://github.com/webdriverio/webdriverio/pull/10921

**Pull request closed without merging**
