### PR TITLE
Fix devtools-service

### LINKED ISSUE #5951: devtools enable performance throws error in browser.url() in 6.6.0 => @wdio/sync: TypeError: Cannot read property 'start' of undefined
Steps to reproduce:

Update to all latest 6.6.0 packages,
run this test, use sync mode with devtools service and devtools as automation protocol at chrome:

```
const assert = require('assert');

describe('JSON.org page', () => {
    before(() => {
        browser.enablePerformanceAudits();
    });

    it('should load within performance budget', () => {
        browser.url('http://json.org');

        // let metrics = browser.getMetrics();
        // assert.ok(metrics.speedIndex < 1500); // check that speedIndex is below 1.5ms

        // let score = browser.getPerformanceScore(); // get Lighthouse Performance score
        // assert.ok(score >= 0.99); // Lighthouse Performance score is at 99% or higher

        // $('=Esperanto').click();

        // metrics = browser.getMetrics();
        // assert.ok(metrics.speedIndex < 1500);
        // score = browser.getPerformanceScore();
        // assert.ok(score >= 0.99);
    });

    after(() => {
        browser.disablePerformanceAudits();
    });
});
```

when browser.url is called error is thrown, test times out =>

 (node:40878) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of undefined
    at TraceGatherer.onLoadEventFired (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/devtools-service/build/gatherer/trace.js:95:42)

2020-10-07T19:21:19.879Z INFO @wdio/devtools-service:TraceGatherer: Start tracing frame with url http://json.org
**2020-10-07T19:21:19.881Z ERROR @wdio/sync: TypeError: Cannot read property 'start' of undefined**
    at TraceGatherer.startTracing (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/devtools-service/build/gatherer/trace.js:44:33)
    at DevToolsService.beforeCommand (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/devtools-service/build/index.js:40:35)
    at execHook (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:21:31)
    at /Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:35:60
    at new Promise (<anonymous>)
    at /Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:16:33
    at Array.map (<anonymous>)
    at Object.executeHooksWithArgs [as default] (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:16:19)
    at Browser.runCommandHook (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/wrapCommand.js:84:45)
    at Browser.runCommandWithHooks (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/wrapCommand.js:66:26)

My options:

{
  "capabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--incognito"
      ]
    }
  },
  "logLevel": "trace",
  "connectionPollInterval": 500,
  "connectionRetryCount": 3,
  "requestedCapabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--incognito"
      ]
    }
  },
  "automationProtocol": "devtools",
  "specs": [
    "./lib/perf-example.js"
  ],
  "exclude": [],
  "suites": {},
  "baseUrl": "https://www.qanuggets.com",
  "bail": 0,
  "waitforInterval": 500,
  "waitforTimeout": 45000,
  "framework": "mocha",
  "reporters": [
    [
      "json",
      {
        "outputDir": "./data/report"
      }
    ],
    "spec"
  ],
  "services": [
    "devtools"
  ],
  "execArgv": [],
  "maxInstances": 5,
  "maxInstancesPerCapability": 100,
  "outputDir": "./data/wdio-logs",
  "filesToWatch": [],
  "onPrepare": [],
  "onWorkerStart": [],
  "before": [
    null,
    null
  ],
  "beforeSession": [
    null,
    null
  ],
  "beforeSuite": [],
  "beforeHook": [],
  "beforeTest": [
    null
  ],
  "beforeCommand": [
    null
  ],
  "afterCommand": [
    null
  ],
  "afterTest": [
    null
  ],
  "afterHook": [],
  "afterSuite": [],
  "afterSession": [],
  "after": [],
  "onComplete": [],
  "onReload": [
    null
  ],
  "beforeFeature": [],
  "beforeScenario": [],
  "beforeStep": [],
  "afterStep": [],
  "afterScenario": [],
  "afterFeature": [],
  "logLevels": {},
  "connectionRetryTimeout": 90000
}

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

- pass proper args to TraceGatherer
- fix Auditor call without args on `tracingError` event

fixes #5951

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Review by pmerwin — APPROVED** [review]
Tested this branch locally and issue appears to be fixed:

Ref => https://github.com/webdriverio/webdriverio/issues/5951
```
2020-10-13T17:55:39.524Z INFO webdriver: COMMAND enablePerformanceAudits()
2020-10-13T17:55:39.525Z INFO webdriver: RESULT undefined
2020-10-13T17:55:39.577Z INFO devtools: COMMAND navigateTo("https://magnificent-cabbage.glitch.me/")
2020-10-13T17:55:41.417Z INFO devtools: RESULT null
2020-10-13T17:55:51.171Z INFO webdriver: COMMAND getMetrics()
2020-10-13T17:55:51.511Z INFO webdriver: COMMAND getPerformanceScore()
2020-10-13T17:55:51.511Z INFO webdriver: RESULT {
  estimatedInputLatency: 16,
  timeToFirstByte: 566,
  serverResponseTime: 566,
  domContentLoaded: 1834,
  firstVisualChange: 1116,
  firstPaint: 1143,
  firstContentfulPaint: 1143,
  firstMeaningfulPaint: 1143,
  largestContentfulPaint: 1143,
  lastVisualChange: 4066,
  firstCPUIdle: 1834,
  firstInteractive: 1834,
  load: 1838,
  speedIndex: 1225,
  totalBlockingTime: 0,
  cumulativeLayoutShift: 0
}
```

**Review by christian-bromann — APPROVED** [review]
I would be interested why `tracelogs` is undefined but I have the feeling it might be due to random certainties and conditions of the app being tested. Therefor this seems like a good fix.

Thank you @mgrybyk  👍

**Comment by mgrybyk** [comment]
@christian-bromann it happens here https://github.com/webdriverio/webdriverio/blob/246a9330d321c145a355e12a1c19d7fbb9aa57a5/packages/wdio-devtools-service/src/index.js#L64

As you can see we don't pass anything to Auditor constructor, where as it requires two arguments.

If you know how to improve let's do it!

**Comment by christian-bromann** [comment]
> If you know how to improve let's do it!

Haven't played with LH for a while, so no for now.

**Pull request merged**
