### PR TITLE
Typescript documentation update

### PR DESCRIPTION
**Pull request by osmolyar**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thanks for raising the PR. Is it possible to have tabs within tabs? So we can have 2 tabs for ambient/modules and in there another choice for sync/async? Is this possible?

**Comment by osmolyar** [comment]
I don't know?  Not sure how to build the page to check

**Comment by christian-bromann** [comment]
> Not sure how to build the page to check

You can find docs on how to deploy the website locally here: https://webdriver.io/docs/contribute#deploying-the-documentation-locally

**Comment by christian-bromann** [comment]
@osmolyar I hope it is ok that I went ahead and added the change on your behalf. I was going through some PRs to clean up and thought it would be great to include this one for the release.

**Comment by osmolyar** [comment]
@christian-bromann , thanks very much for making the changes!  

One question on https://github.com/webdriverio/webdriverio/commit/b458d998e5622181d7119694b4bbeeaeaecf2b97;

My understanding is that ambient type definition files should not be included in a tsconfig include section since the point of them is that they are automatically visible to typescript; in fact having an 'include' or 'files' section means ambient .d.ts files won't be visible to the compiler.

(Also I think include is for directories and files is for individual files.)

For example our tsconfig using multiple ambient .d.ts files in the project looks like this (and I think the typeRoots is not required since there are .d.ts files elsewhere also):

`{
  "compilerOptions": {
    "target": "es6",
    "outDir": "out",
    "types": [
      "node",
      "webdriverio/sync",
      "chai"
    ],
    "moduleResolution": "node",
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "strict": false,
    "downlevelIteration": true,
    "typeRoots": [
      "./common/declarations"
    ],
    "allowSyntheticDefaultImports": true
  }
}`

**Pull request closed without merging**
