### PR TITLE
Adding ability to override Suite Name

### PR DESCRIPTION
**Pull request by facusantillo**
## Proposed changes

#7645 

This PR contains the changes to allow users to override suite names on junit reports

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by facusantillo** [comment]
@christian-bromann had to open a new pull request but seems there is a problem with the EasyCLA. Not sure how to fix it, but I created a support ticket. I have reviewed my identity on GH and everything seems to be fine

**Comment by BorisOsipov** [comment]
@facusantillo does your email on github profile equal with email from commit\git config? please check `git config user.email`

**Comment by facusantillo** [comment]
> @facusantillo does your email on github profile equal with email from commit\git config? please check `git config user.email`

Indeed is the same email. Also checked that the email was public on GH profile, and I have already signed to easyCLA

**Comment by facusantillo** [comment]
@BorisOsipov I've fixed the EasyCLA. PR is ready for the workflows

**Comment by christian-bromann** [comment]
Thanks @facusantillo , glad it worked out.

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
