### PR TITLE
Add missing capability types in BrowserStackCapabilities

### PR DESCRIPTION
**Pull request by SCG82**
## Proposed changes

- Adds missing capabilities found in https://www.browserstack.com/automate/capabilities?tag=selenium-4 to BrowserStackCapabilities interface:
  - disableCorsRestrictions
  - buildTag
- Adds documentation for some of the more obscure options.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by SCG82** [comment]
The e2e-windows failure appears unrelated to the changes made in this PR.

**Comment by christian-bromann** [comment]
@SCG82 thanks for the PR. Would you mind raising the same PR to the `v7` branch so we can also release this for `v7`?

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by SCG82** [comment]
> @SCG82 thanks for the PR. Would you mind raising the same PR to the `v7` branch so we can also release this for `v7`?

https://github.com/webdriverio/webdriverio/pull/9121

**Pull request merged**
