### PR TITLE
Issue 3416: Support multiple errors in the Allure-reporter

### PR DESCRIPTION
**Pull request by nicholasbailey**
## Proposed changes
Over several PRs, we've introduced fixes to allow Jasmine to pass more than one failing expect to WebdriverIO. This matches Jasmine's soft assertion model, where expectation failures do not stop test execution. 

This PR passes those additional errors to Allure.

Unfortunately, Allure reporter itself assumes one error per test. The easiest way to work around that is to combine the errors into a single error holding their aggregated messages and stacks. It's not ideal, but allure doesn't offer us a great alternative.

## Types of changes
- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
@nicholasbailey Thanks for improving allure reporting. Please make linter happy for next review steps.

**Comment by nicholasbailey** [comment]
@christian-bromann @BorisOsipov linter errors _should_ be fixed (sorry about that!)

**Comment by christian-bromann** [comment]
@nicholasbailey something seems to be still off with the unit tests

**Comment by nicholasbailey** [comment]
So there does. Fixing now

**Comment by nicholasbailey** [comment]
@christian-bromann @BorisOsipov we should be good now (finally).
Sorry a lot of those tests passed locally because stack traces depend a bit on how you run the tests :)

**Comment by BorisOsipov** [comment]
I don't forget about this. I am a bit busy now, I will see a few days later

**Comment by nicholasbailey** [comment]
@CrispusDH just making sure I understand what you want. If there's only one error in a Jasmine test case, we still want to wrap that error in a CompoundError for reporting? 

While it's a little simpler from an implementation perspective, that seems like it would add noise to the reports themselves. I'm ok with that if that's folk's preference, but it's not what I would personally prefer.

Note that Jasmine test cases will always return an errors array, even if there is only one item in the array.

**Comment by CrispusDH** [comment]
Let @BorisOsipov choose what option is preferable. I was thinking about what place should actual take in account this piece of `if .. else` logic:
```js
    if (test.errors && test.errors.length) {
        if (test.errors.length == 1) {
            return test.errors[0]
        } else {
            return new CompoundError(...test.errors)
        }
    } else {
        return test.error
    }
```
If you think that `CompoundError()` should work only with `test.errors` part of `test` entity it could be an option. In my opinion it should take `test` entity and decide what to do inside method instead of giving this this part of work to `getErrorFromFailedTest ()`.

**Pull request merged**
