### PR TITLE
fix(mocha-framework): move @types/mocha and @types/node to devDepende…

### PR DESCRIPTION
**Pull request by PiQx**
…cies

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
@PiQx mind signing the CLA?

**Comment by PiQx** [comment]
> @PiQx mind signing the CLA?

im siginig CLA, but pipeline is pending

I need to repeat pipilene?

изображение

**Comment by christian-bromann** [comment]
@PiQx please sign with the same email you used to do the commit

**Comment by PiQx** [comment]
@christian-bromann thanks. Licence check done

**Comment by alexkvak** [comment]
@christian-bromann why did you revert this PR in 0dbcfbf3b1ee21e5bb137f883c7d37645fbc35eb?

**Comment by christian-bromann** [comment]
because it broke the build. The mocha framework adapter [exposes](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-mocha-framework/src/types.ts#L114) Mocha types so it needs to stay a dependency.

**Pull request merged**
