### PR TITLE
@wdio/devtools-service udpate to 6.4.0 causes timeout at browser.relo…

### PR DESCRIPTION
**Pull request by joshskumar**
…adSession()

## Proposed changes

[//]: # change to the function passed in the map into an async function and have an await in the definition of the function.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

I would like the reviewer to review it in the angle of performance as well as I am not sure of the complexity involved in the execution of the hook function..

I have ran the tests and confirmed that the code flows into the If condition and it look good

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Can you reference the issue you are trying to fix here?

I think 
```js
await Promise.all(this.options.onReload.map((hook) => await hook(oldSessionId, this.sessionId)))
```
and
```js
await Promise.all(this.options.onReload.map(async (hook) => await hook(oldSessionId, this.sessionId)))
```

do exactly the same. So I don't believe that this patch helps with anything.

**Comment by joshskumar** [comment]
@christian-bromann Yes I agree it is doing the same

would you mind telling me where to look for the definition of the the hook method so I can give the right fix

**Comment by christian-bromann** [comment]
> of the the hook method

which hook method?

**Comment by joshskumar** [comment]
hi @christian-bromann  sorry I get it from where hook comes from after some research..

my basic idea of adding await there was to make sure the array of functions are mapped one at a time and then await for the entire Promise completion.. rather than starting off together and waiting for them all to complete..

but if you feel if this does not make sense I will close my PR

**Comment by christian-bromann** [comment]
It is intentional that all service hooks run at the same time. No service should take precedence over another service.

**Comment by joshskumar** [comment]
thanks for clarification @christian-bromann

**Pull request closed without merging**
