### PR TITLE
(@wdio/config): fix duplicate paths in glob result for Windows

### PR DESCRIPTION
**Pull request by hbc007**
## Proposed changes
fixes: https://github.com/webdriverio/webdriverio/issues/11009

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thanks for taking a look. Can we have a unit test for this?

**Comment by christian-bromann** [comment]
ping @hbc007

**Comment by erwinheitzman** [comment]
Are you planning to finish this @hbc007 ?

**Comment by christian-bromann** [comment]
I am going ahead and close this due to inactivity. Looking back at this I am not sure if this is the right solution to the problem. Also the problem is not clear to me: it seems like there is a duplicate returned because of [this](https://github.com/webdriverio/webdriverio/blob/3486fc03a546757d3fdd4896f821ffc26550e9a6/packages/wdio-config/src/lib/FileSystemPathService.ts#L43-L45) but when writing tests for this I wasn't able to reproduce the failure state because `!globResult.includes(fileName)` would not allow to enter this if statement if the disk letter have a different casing.

**Comment by christian-bromann** [comment]
Actually I came up with an alternative fix: https://github.com/webdriverio/webdriverio/pull/11177

**Pull request closed without merging**
