### PR TITLE
setViewportSize should repeat action only if width isn't correct

### PR DESCRIPTION
**Pull request by amitaibu**
#700

### CODE REVIEW

**Comment by amitaibu** [comment]
Just to better explain to motivation for this. I have noticed several times that the `width` may be wrong when repeating the `windowHandleSize`

For example, the final result's width was 400, where 640 was requested:

```
Result:
{ screenWidth: 400, screenHeight: 674 }
Size:
{ width: 640, height: 697 }
```

**Comment by christian-bromann** [comment]
@amitaibu I don't quite understand why you've removed the height check, this doesn't really solve the problem, doesn't it?

**Comment by amitaibu** [comment]
> this doesn't really solve the problem, doesn't it?

It actually does. In my cases I've seen the browsers weren't always able to set the `height` value, but always able to set the `width`. So what currently happens with the existing code, is that we try 5 times to set the window size - it may set the height with wrong values, thus fail in the end, as the width somehow gets messed up as-well.

Ever since I've patched this for Shoov I have not received any failing tests.

**Comment by christian-bromann** [comment]
After reading #700 again I know get the problem. Can we do the following: instead of ignoring height could we introduce a flag that allows to ignore height or width? `setViewportSize` should change the height __and__ width of the viewport, if people run into problems because the resolution isn't tall enough the command just keeps resizing until the limit (of 5) is reached and the move forward

**Comment by amitaibu** [comment]
:+1: in vacation now, so I'll change the PR after it :)

**Comment by christian-bromann** [comment]
Nice, have a good time on vacation

**Comment by christian-bromann** [comment]
ping @amitaibu

**Comment by amitaibu** [comment]
Yeah, didn't forget about it - just a bit lazy. I'll tackle it soon :)

**Comment by philipwalton** [comment]
So I just encountered this issue as well. It took me a bit to realize that multiple resizes were happening before I discovered why my tests were flaky.

In my case, I'm resizing the browser and then checking that an action happens before a timeout, but if webdriverio is resizing multiple time, measuring, resizing again, etc., then in many cases the timeout occurrs before the logic runs to check for my action.

* * *
 
Couldn't you measure the difference between the window and the viewport at the original size before resizing, and then assume the browser chrome dimensions aren't going to change?

And I guess at minimum I'd like to see this behavior documented, as it wasn't immediately apparent to me that multiple resizes were happening.

**Comment by christian-bromann** [comment]
> resizing again, etc., then in many cases the timeout occurrs before the logic runs to check for my action.

It reruns the process max 5 times (see [here](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/setViewportSize.js#L30)). We could make this an optional parameter though.

@amitaibu we updated the code base (merged v4 branch). Could you please fetch a fresh copy from the master branch and open another PR? Thanks!

**Comment by Strongground** [comment]
So what happened to this?
Apparently nothing has changed.

**Comment by christian-bromann** [comment]
@Strongground what do you mean by that? According to my last comment it should be fixed by now. If you still see issues feel free to open a new issue.

**Pull request closed without merging**
