### PR TITLE
Added Documentation to devtools command

### PR DESCRIPTION
**Pull request by thescripted**
## Proposed changes

[//]: # 
Resolving [#4962](https://github.com/webdriverio/webdriverio/issues/4962), this PR added documentations to devtools commands. All of the comments were taken from the [protocol docs](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-protocols/protocols/webdriver.json). 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)
I've simply copied the description of each commands from the protocol docs. If I've missed anything or created an error, please let me know!

### CODE REVIEW

**Comment by thescripted** [comment]
seems like it's mostly linting problems. Going to reconfigure and try again

**Comment by christian-bromann** [comment]
Awesome, thanks @thescripted! While we at it, could you also add parameter, alias and return value (e.g. like [here](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/browser/custom%24%24.js#L19-L22))?

**Comment by christian-bromann** [comment]
any updates @thescripted ?

**Comment by christian-bromann** [comment]
ping @thescripted

**Comment by christian-bromann** [comment]
@thescripted is there anything I can do to help?

**Comment by christian-bromann** [comment]
Closing in favor of #5573

**Pull request closed without merging**
