### PR TITLE
[#11473] - Refactor wdio-allure-reporter package for better hooks handling

### PR DESCRIPTION
**Pull request by lararojasmr**
## Proposed changes
Code has been restructured across the wdio-allure-reporter package for enhanced handling of hooks in different situations. Additionally, constant names and util function names have been updated for increased clarity. The handling of hooks particularly for mocha tests has been revised, improving the accuracy of test reports.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [x] Back-ported PR at https://github.com/webdriverio/webdriverio/pull/12855

### Reviewers: @webdriverio/project-committers

### CODE REVIEW

**Comment by lararojasmr** [comment]
@christian-bromann is there an issue with pipelines, because i'm not getting those failures in my machine?  I'm using a mac. Could you check that please?

**Comment by christian-bromann** [comment]
@lararojasmr yes, I am currently working on fixing the `main` build. We can move forward with your contribution no matter what. Mind, raising a PR for `v8` as well? It can help us verify the changes there.

**Comment by lararojasmr** [comment]
I hope I did it right @christian-bromann if you have time, please confirm.

**Comment by lararojasmr** [comment]
> @lararojasmr yes, I am currently working on fixing the `main` build. We can move forward with your contribution no matter what. Mind, raising a PR for `v8` as well? It can help us verify the changes there.

v8: https://github.com/webdriverio/webdriverio/pull/12854

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
