### PR TITLE
$$ returns an object not an array

### PR DESCRIPTION
**Pull request by ianwalter**
## Proposed changes

The docs say that the `$$` command returns and array of elements but it's actually an object that is returned. This changes the docs to reflect what is actually returned.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
  Sorry, read this after. Let me know if I have to change my commit message.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
It's an array eventhough has some properties

**Comment by ianwalter** [comment]
> It's an array eventhough has some properties

`typeof` returns `object` and also I can't use the return value in a for..of loop, I get: `.for is not iterable`.

**Comment by ianwalter** [comment]
> > It's an array eventhough has some properties
> 
> `typeof` returns `object` and also I can't use the return value in a for..of loop, I get: `.for is not iterable`.

Ignore my typeof comment, haha. I don't know how many times I forget an array will return object as type of.

**Comment by mgrybyk** [comment]
for of also works fine, Array.isArray returns true as well.
Let's close this?

**Comment by ianwalter** [comment]
You're right, this is my mistake, sorry for the noise. Closing.

**Pull request closed without merging**
