### PR TITLE
You need to enable co-mocha or all your tests will silently pass

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by christian-bromann** [comment]
@graingert there is no support for generators planned in v4. All commands are running synchronous anyway.

**Comment by graingert** [comment]
@christian-bromann this is a documentation update

**Comment by christian-bromann** [comment]
I know but since there is absolutely no need to use co-mocha in v4 there shouldn't be any documentation around it

**Comment by christian-bromann** [comment]
Please note that some parts of our docs aren't still updated :-/

**Pull request closed without merging**
