### PR TITLE
feat(hooks): add onWorkerEnd hook implementation

### PR DESCRIPTION
**Pull request by Slashgear**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

I wanted to solve this issue (#6356) in order to implement a new hook to perform an effect at the end of the execution of a worker.

I was very inspired by what was done when creating the `onWorkerStart` hook. (#4926)

I still have a few things to study:

- Should we give the same parameter to the `onWorkerStart` ? Should we add new ones ?
- Still need to implement unit test with jest to cover this new feature
- Where should I hook the implementation of this hook ? (I am a new contributor of this project and I don't really know where to make it correctly 😊 )
  - onExit ? 
  - onEnd ?
  - onError ?

I think the solution will be here.

https://github.com/webdriverio/webdriverio/blob/c049615763126177866b8b5b2ec3524449691d0a/packages/wdio-cli/src/launcher.ts#L106-L163

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
It seems that something went wrong with the rebase. Can you update your branch?

**Comment by Slashgear** [comment]
Hi @christian-bromann I updated the PR and cleanup commits but I struggle with test, may need help on that :)

**Comment by christian-bromann** [comment]
@Slashgear thanks! Where do you struggle with the test? Can you run them?

**Comment by christian-bromann** [comment]
ping @Slashgear

**Comment by christian-bromann** [comment]
@Slashgear are you still plan to work on this PR?

**Comment by christian-bromann** [comment]
ping @Slashgear

**Comment by christian-bromann** [comment]
Closing in favor of #8100

Thank you @Slashgear for all leg work on this!

**Pull request closed without merging**
