### PR TITLE
Update Cucumber framework README

### LINKED ISSUE #6186: Cucumber reporter
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

(I am unsure if it is missing or unclear, but I've not been able to find, google or github search it)

**Description of the improvement / report**

Using the cucumber framework for wdio via nodeJs, I get the following output

```
--------
TIMELINE REPORTER: Created C:\Users\lewis\projects\gutenberg-shortcode-preview-block\test-reports/timeline-report.html
--------

Spec Files:      1 passed, 1 total (100% completed) in 00:00:16 
```

I would like something more akin to a per-scenario report

```
PASS  e2e/features/login.feature (25.59 s)
  As a user, I recieve an error message when using invalid credentials to log into the application
    √ Missing Username
    √ Missing Password
  As a user, I can login
    √ as an admin (28 ms)
```

Others have suggested 

> have you looked at cucumber --format ?

I have no idea what that advice entails, it seems to be about abandoning this integration.

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Fixes #6186

## Proposed changes

I Had an issue pivoting to using webdriverio. I did not find the documentation clear enough on getting the output format I have a preference for.

Worse still, most support from elsewhere seemed like it was teaching me how to use cucumber or berating me, which was... not fantastic.

I Believe this would have helped me find what I was looking for when searching using github, or a code editor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

It's likely this might need iteration. It's enough rough notes that I can add to it or expand upon it later, and I believe enough detail that a user could recognize it.

I've tried to put this in an appropriate place.

### CODE REVIEW

**Comment by christian-bromann** [comment]
> I did not find the documentation clear enough on getting the output format I have a preference for.

Have you tried the [Getting Started](https://webdriver.io/docs/gettingstarted.html) guide? Even though it uses Mocha we hoped it would be clear enough that what is shown would also apply for the other frameworks like Cucumber.

> most support from elsewhere seemed like it was teaching me how to use cucumber or berating me, which was... not fantastic.

Not sure which places you are referring to here. [YouTube](https://www.youtube.com/watch?v=FV_FhBh4v8k&list=PLXBKC3hh6AEr5dMdptmk5-S5_yyHKQ4cW&ab_channel=RPA%26AutomationTraining-AfsarAli) and the internet have a bunch of tutorials for getting started with WebdriverIO and Cucumber. Most of these tutorials use the spec reporter by default.

Thank you for providing a addition to the docs. While it might have helped you I am not sure if it would also help others to point to the spec reporter in the cucumber docs. How about adding a sentence to the getting started guide to emphasize that the result can also be accomplished using Cucumber or Jasmine.

**Comment by Lewiscowles1986** [comment]
I did read the mocha guide. Because cucumber had a file called reporter in it, I tried several times to work out why that wasn't the correct reporter.

I've used this with Mocha and it just worked, which was why I'd thought that something was wrong with cucumber.

I searched using Google and none of those came up, but also I was searching on text content. I did search Google, GitHub and the codebase. No links to youtube for cucumber and reporter, reporting report were found.

Happy to make the edit to the getting started as opposed to this.

**Comment by christian-bromann** [comment]
> Because cucumber had a file called reporter in it

What file do you mean?

> Happy to make the edit to the getting started as opposed to this.

I think a little enhancements to the getting started guide is better and receives more 👀 the current approach.

**Comment by Lewiscowles1986** [comment]
> What file do you mean?

https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/reporter.js

I'm closing, as looking at the other area although none of the examples are given specifically, if I had clicked to the examples and gone to a third-party repo, I would have seen a note on one of the Cucumber examples.

It's sad this is not part of GitHub, Google searches, but perhaps it is an edge that is covered.

**Pull request closed without merging**
