### PR TITLE
Fix for feature label

### LINKED ISSUE #8982: [🐛 Bug]: wrong test result structure for allure + cucumber integrations
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7.25.1

### Node.js Version

16.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  maxInstances: 5,
  browserName: 'chrome',
  acceptInsecureCerts: true
}
```

### What happened?

The problem relates to incorrect structure of allure reports generated by wdio integration (allure-framework/allure-js#483).

As far as I see, `wdio-cucumber-framework` emits wrong feature data and event listener in the allure reporter marks step name as feature name:

image

Here you can see a default example from cucumber/allure wdio template. There should by one entry named `The Internet Guinea Pig Website` with multiple steps inside.

The feature code is below:

```feature
Feature: The Internet Guinea Pig Website

  Scenario Outline: As a user, I can log into the secure area

    Given I am on the login page
    When I login with <username> and <password>
    Then I should see a flash message saying <message>

    Examples:
      | username | password             | message                        |
      | tomsmith | SuperSecretPassword! | You logged into a secure area! |
      | foobar   | barfoo               | Your username is invalid!      |
```

### What is your expected behavior?

`@wdio/allure-reporter` should generate report with a correct structure.

### How to reproduce the bug.

1. Create new project via wdio cli generator
2. Pick `cucumber` framework and `allure` reporter in the prompt
3. Install the dependencies in the generated project `npm i`
4. Run `npm run wdio`
5. Upload the result to allure test ops instance and open the new launch
6. Display the result tree in `Feature` mode
7. The feature name should be correct

### Relevant log output

```typescript
λ npm run wdio

> webdriverio-tests@0.1.0 wdio
> wdio run wdio.conf.js


Execution of 1 workers started at 2022-10-10T09:22:41.740Z

2022-10-10T09:22:41.750Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-10-10T09:22:41.779Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.0)
2022-10-10T09:22:41.780Z INFO chromedriver: Start Chromedriver (/Users/epszaw/Code/Work/qameta/allure-wdio-demo/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2022-10-10T09:22:41.797Z INFO chromedriver: Starting ChromeDriver 106.0.5249.61 (511755355844955cd3e264779baf0dd38212a4d0-refs/branch-heads/5249@{#569}) on port 9515
2022-10-10T09:22:41.797Z INFO chromedriver: Only local connections are allowed.
2022-10-10T09:22:41.797Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-10-10T09:22:41.815Z INFO chromedriver: ChromeDriver was started successfully.
2022-10-10T09:22:41.889Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-10-10T09:22:41.890Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2022-10-10T09:22:42.060Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /features/login.feature
[0-0] 2022-10-10T09:22:42.329Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-10-10T09:22:42.355Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-10-10T09:22:42.356Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2022-10-10T09:22:43.991Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2022-10-10T09:22:43.991Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/url
[0-0] 2022-10-10T09:22:43.992Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2022-10-10T09:22:45.866Z INFO webdriver: COMMAND findElement("css selector", "#username")
[0-0] 2022-10-10T09:22:45.866Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:45.866Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2022-10-10T09:22:45.874Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '01dfa870-f5f2-4a81-9436-bb461d9a94e3'
[0-0] }
[0-0] 2022-10-10T09:22:45.878Z INFO webdriver: COMMAND elementClear("01dfa870-f5f2-4a81-9436-bb461d9a94e3")
[0-0] 2022-10-10T09:22:45.878Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/01dfa870-f5f2-4a81-9436-bb461d9a94e3/clear
[0-0] 2022-10-10T09:22:45.901Z INFO webdriver: COMMAND elementSendKeys("01dfa870-f5f2-4a81-9436-bb461d9a94e3", "<Screenshot[base64]>")
[0-0] 2022-10-10T09:22:45.901Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/01dfa870-f5f2-4a81-9436-bb461d9a94e3/value
[0-0] 2022-10-10T09:22:45.901Z INFO webdriver: DATA { text: 'tomsmith' }
[0-0] 2022-10-10T09:22:45.960Z INFO webdriver: COMMAND findElement("css selector", "#password")
[0-0] 2022-10-10T09:22:45.961Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:45.961Z INFO webdriver: DATA { using: 'css selector', value: '#password' }
[0-0] 2022-10-10T09:22:45.969Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '0aa6d712-7902-4d35-80e8-559345619402'
[0-0] }
[0-0] 2022-10-10T09:22:45.971Z INFO webdriver: COMMAND elementClear("0aa6d712-7902-4d35-80e8-559345619402")
[0-0] 2022-10-10T09:22:45.971Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/0aa6d712-7902-4d35-80e8-559345619402/clear
[0-0] 2022-10-10T09:22:45.985Z INFO webdriver: COMMAND elementSendKeys("0aa6d712-7902-4d35-80e8-559345619402", "SuperSecretPassword!")
[0-0] 2022-10-10T09:22:45.985Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/0aa6d712-7902-4d35-80e8-559345619402/value
[0-0] 2022-10-10T09:22:45.985Z INFO webdriver: DATA { text: 'SuperSecretPassword!' }
[0-0] 2022-10-10T09:22:46.009Z INFO webdriver: COMMAND findElement("css selector", "button[type="submit"]")
[0-0] 2022-10-10T09:22:46.009Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.009Z INFO webdriver: DATA { using: 'css selector', value: 'button[type="submit"]' }
[0-0] 2022-10-10T09:22:46.015Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '604dc1be-584f-404b-adb7-42a266053b15'
[0-0] }
[0-0] 2022-10-10T09:22:46.017Z INFO webdriver: COMMAND elementClick("604dc1be-584f-404b-adb7-42a266053b15")
[0-0] 2022-10-10T09:22:46.017Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/604dc1be-584f-404b-adb7-42a266053b15/click
[0-0] 2022-10-10T09:22:46.342Z INFO webdriver: COMMAND findElement("css selector", "#flash")
[0-0] 2022-10-10T09:22:46.343Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.343Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2022-10-10T09:22:46.349Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '99c11d10-a088-4675-80e7-93babfc929da'
[0-0] }
[0-0] 2022-10-10T09:22:46.351Z INFO webdriver: COMMAND findElements("css selector", "#flash")
[0-0] 2022-10-10T09:22:46.352Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/elements
[0-0] 2022-10-10T09:22:46.352Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2022-10-10T09:22:46.369Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '99c11d10-a088-4675-80e7-93babfc929da'
[0-0]   }
[0-0] ]
[0-0] 2022-10-10T09:22:46.372Z INFO webdriver: COMMAND findElement("css selector", "#flash")
[0-0] 2022-10-10T09:22:46.372Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.372Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2022-10-10T09:22:46.376Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '99c11d10-a088-4675-80e7-93babfc929da'
[0-0] }
[0-0] 2022-10-10T09:22:46.378Z INFO webdriver: COMMAND getElementText("99c11d10-a088-4675-80e7-93babfc929da")
[0-0] 2022-10-10T09:22:46.378Z INFO webdriver: [GET] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/99c11d10-a088-4675-80e7-93babfc929da/text
[0-0] 2022-10-10T09:22:46.385Z INFO webdriver: RESULT You logged into a secure area!
[0-0] ×
[0-0] 2022-10-10T09:22:46.391Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2022-10-10T09:22:46.391Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/url
[0-0] 2022-10-10T09:22:46.391Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2022-10-10T09:22:46.548Z INFO webdriver: COMMAND findElement("css selector", "#username")
[0-0] 2022-10-10T09:22:46.548Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.548Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2022-10-10T09:22:46.552Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '9fa16d7c-cbe1-487e-91a4-56077b1f2180'
[0-0] }
[0-0] 2022-10-10T09:22:46.554Z INFO webdriver: COMMAND elementClear("9fa16d7c-cbe1-487e-91a4-56077b1f2180")
[0-0] 2022-10-10T09:22:46.554Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/9fa16d7c-cbe1-487e-91a4-56077b1f2180/clear
[0-0] 2022-10-10T09:22:46.568Z INFO webdriver: COMMAND elementSendKeys("9fa16d7c-cbe1-487e-91a4-56077b1f2180", "foobar")
[0-0] 2022-10-10T09:22:46.568Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/9fa16d7c-cbe1-487e-91a4-56077b1f2180/value
[0-0] 2022-10-10T09:22:46.568Z INFO webdriver: DATA { text: 'foobar' }
[0-0] 2022-10-10T09:22:46.596Z INFO webdriver: COMMAND findElement("css selector", "#password")
[0-0] 2022-10-10T09:22:46.596Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.596Z INFO webdriver: DATA { using: 'css selector', value: '#password' }
[0-0] 2022-10-10T09:22:46.600Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'edc963ae-91e4-433b-bef7-4e26aeec280b'
[0-0] }
[0-0] 2022-10-10T09:22:46.601Z INFO webdriver: COMMAND elementClear("edc963ae-91e4-433b-bef7-4e26aeec280b")
[0-0] 2022-10-10T09:22:46.601Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/edc963ae-91e4-433b-bef7-4e26aeec280b/clear
[0-0] 2022-10-10T09:22:46.614Z INFO webdriver: COMMAND elementSendKeys("edc963ae-91e4-433b-bef7-4e26aeec280b", "barfoo")
[0-0] 2022-10-10T09:22:46.614Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/edc963ae-91e4-433b-bef7-4e26aeec280b/value
[0-0] 2022-10-10T09:22:46.614Z INFO webdriver: DATA { text: 'barfoo' }
[0-0] 2022-10-10T09:22:46.630Z INFO webdriver: COMMAND findElement("css selector", "button[type="submit"]")
[0-0] 2022-10-10T09:22:46.630Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.630Z INFO webdriver: DATA { using: 'css selector', value: 'button[type="submit"]' }
[0-0] 2022-10-10T09:22:46.633Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '7072adfc-f521-4e72-a773-868144693962'
[0-0] }
[0-0] 2022-10-10T09:22:46.634Z INFO webdriver: COMMAND elementClick("7072adfc-f521-4e72-a773-868144693962")
[0-0] 2022-10-10T09:22:46.634Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/7072adfc-f521-4e72-a773-868144693962/click
[0-0] 2022-10-10T09:22:46.950Z INFO webdriver: COMMAND findElement("css selector", "#flash")
[0-0] 2022-10-10T09:22:46.950Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.950Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2022-10-10T09:22:46.954Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '7d20badb-a917-4d94-a99a-ba8deaf03028'
[0-0] }
[0-0] 2022-10-10T09:22:46.955Z INFO webdriver: COMMAND findElements("css selector", "#flash")
[0-0] 2022-10-10T09:22:46.955Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/elements
[0-0] 2022-10-10T09:22:46.955Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2022-10-10T09:22:46.959Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '7d20badb-a917-4d94-a99a-ba8deaf03028'
[0-0]   }
[0-0] ]
[0-0] 2022-10-10T09:22:46.961Z INFO webdriver: COMMAND findElement("css selector", "#flash")
[0-0] 2022-10-10T09:22:46.961Z INFO webdriver: [POST] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element
[0-0] 2022-10-10T09:22:46.961Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2022-10-10T09:22:46.964Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '7d20badb-a917-4d94-a99a-ba8deaf03028'
[0-0] }
[0-0] 2022-10-10T09:22:46.965Z INFO webdriver: COMMAND getElementText("7d20badb-a917-4d94-a99a-ba8deaf03028")
[0-0] 2022-10-10T09:22:46.965Z INFO webdriver: [GET] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63/element/7d20badb-a917-4d94-a99a-ba8deaf03028/text
[0-0] 2022-10-10T09:22:46.973Z INFO webdriver: RESULT Your username is invalid!
[0-0] ×
[0-0] 2022-10-10T09:22:46.979Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-10-10T09:22:46.979Z INFO webdriver: [DELETE] http://localhost:9515/session/bf88599406e9fcfbc3a61ca5bca12b63
[0-0] PASSED in chrome - /features/login.feature
2022-10-10T09:22:47.139Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-10-10T09:22:47.140Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      1 passed, 1 total (100% completed) in 00:00:05 

2022-10-10T09:22:47.140Z INFO @wdio/local-runner: Shutting down spawned worker
2022-10-10T09:22:47.391Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-10-10T09:22:47.391Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by epszaw**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

fixes #8982, allure-framework/allure-js#483

Tested locally using official wdio cucumber + allure-reporter template.

Before:

image

After:

image

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by epszaw** [comment]
@BorisOsipov could you please take a look here? This is a very-very basic fix for the problem, the best solution is a migration to new version of allure, of course, but the PR is the cheapest one.

**Review by BorisOsipov — CHANGES_REQUESTED** [review]
@epszaw fix looks ok.

Please add unit tests.
You can find an example [here](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/tests/cucumber.suite.test.ts#L89)

**Comment by epszaw** [comment]
@BorisOsipov I forgot to push rest of the commits with unit-tests due `eslint` :)
Please, check it one more time

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Mind raising the same PR to the `v7` branch so we can release it to the current `stable` version?

**Review by BorisOsipov — APPROVED** [review]

**Pull request merged**
