### PR TITLE
devtools: fix import of devices

### LINKED ISSUE #5368: Update of puppeteer-core breaks the launcher
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.14.4

**Describe the bug**
Puppeteer has moved away from Javascript and is now fully converted to Typescript.
This change broke some of the functionality in the launcher by throwing the following error: `TypeError: Cannot convert undefined or null to object`

**To Reproduce**
```
mkdir some-dir
cd some-dir
npm init -y
npm i @wdio/cli
npx wdio config
```

**Log**
```
(node:50622) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/Users/erwinheitzman/Documents/temp/ts-test/node_modules/devtools/build/launcher.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/erwinheitzman/Documents/temp/ts-test/node_modules/devtools/build/index.js:28:40)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
(node:50622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by erwinheitzman**
## Proposed changes

Fixes #5368 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by vitalyiegorov** [comment]
Same errors occurs with `devtools: 6.1.11` and `puppeteer-core: 3.0.2` as it has no exported field `devicesMap`, now everything is exported directly from `var _DeviceDescriptors = require("puppeteer-core/DeviceDescriptors");`

To make devtools `launcher.js` work this npm script fix can be applied:
`"fix:devtools": "sed -e \"s/_DeviceDescriptors.devicesMap/_DeviceDescriptors/g\" -i.bak ./node_modules/devtools/build/launcher.js",`

**Comment by lg-kialo** [comment]
Can confirm what @vitalyiegorov noted, this change breaks our test suite

**Comment by christian-bromann** [comment]
@vitalyiegorov @lg-kialo I can't reproduce the issue. Would you mind to clean up `node_modules` and `package-lock.json` and re-install all your capabilities? I just ran a fresh install with the devtools package and had no issues running this script:

```js
const DevTools = require('devtools').default

;(async() => {
    const client = await DevTools.newSession({
        capabilities: { browserName: 'chrome' }
    })

    await client.navigateTo('https://www.google.com/ncr')
    console.log(await client.getTitle())

    await client.deleteSession()
})()
```

**Comment by lg-kialo** [comment]
I did that and it fixed it, not sure what the issue was. Could be that puppeteer was on an older version.

**Comment by vitalyiegorov** [comment]
@christian-bromann Tried, but the issue is still here, 

I have investigated the versions of the packages and it resolves to [`puppeteer-core:3.0.2` ](https://github.com/puppeteer/puppeteer/blob/v3.0.2/src/DeviceDescriptors.ts) which exports the whole object from the module. 

If you will take a look at the master version of [puppeteer-core](https://github.com/puppeteer/puppeteer/blob/v3.0.2/src/DeviceDescriptors.ts) it has the same behavior, so I guess you should update the import of `devicesMap` to 
`import devicesMap from 'puppeteer-core/DeviceDescriptors'` and it will fix the issue

**Comment by christian-bromann** [comment]
@vitalyiegorov please update your packages, your puppeteer-core version should be at `3.1.0`.

**Pull request merged**
