### PR TITLE
[allure-report] handle case for broken status of tests with retry

### PR DESCRIPTION
**Pull request by a-skindzer**
## Fix status for first retries when the test failed with the BROKEN status:

image

## Types of changes

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thanks for the PR 👏 

Can we have a unit test for this to ensure we don't regress?

**Comment by a-skindzer** [comment]
@christian-bromann, thanks for the comment.

I've added a few tests that reproduce retrying flow with the cucumber framework and check my changes.

Could you take a look, please?

**Review by christian-bromann — APPROVED** [review]
Fabulous , thanks a lot 👍

**Comment by christian-bromann** [comment]
@a-skindzer mind raising the same PR to the `v8` branch so we can release it to the current `latest` version?

**Comment by a-skindzer** [comment]
@christian-bromann It would be great to release it for v8 as well

**Comment by christian-bromann** [comment]
Let's do it! Mind raising a PR on the `v8` branch?

**Comment by a-skindzer** [comment]
I see :facepalm: 
will do soon)
thanks

**Pull request merged**
