### PR TITLE
Edit pull-file return type

### PR DESCRIPTION
**Pull request by lumyjuwon**
## Proposed changes

According to this document (http://appium.io/docs/en/commands/device/files/pull-file/)
pull-file response of command is base64(string) but pull-file of webdriver.d.ts is void so i change void to string

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
This file is auto-generated. To add a return file please edit: https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-protocols/protocols/appium.json#L611-L632. After you updated that please run `npm run generate:typings`.

(this will change with the upcoming version which we have in the `main` branch)

**Comment by lumyjuwon** [comment]
aha, i understood how to generate typings file. thanks.

**Comment by christian-bromann** [comment]
@lumyjuwon would you mind to sign the CLA with the email you've used to make the commit?

**Comment by lumyjuwon** [comment]
i have done it.

**Review by christian-bromann — APPROVED** [review]
👍  thank you!

**Comment by MichelAmin47** [comment]
Created PR with a rebase from master not the new main, PR closed

**Pull request merged**
