### PR TITLE
doc(README): add a reference to @wdio/schematics

### PR DESCRIPTION
**Pull request by Badisi**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
mhm .. the indentation of that list is to explain all packages in `/packages`. Everything else should go to https://github.com/webdriverio/awesome-webdriverio, what do you all think?

**Comment by Badisi** [comment]
My thoughts : the name of the package is `@wdio/schematics` and it seems like everything that's `@wdio/` is in the main repo. So I would move `@wdio/schematics` to /packages.

**Comment by Badisi** [comment]
Also, I would add a Community section that talks about awesome-webdriverio and links to it (because there is none).

Maybe a new section like **Packages** ?

## :package: Community

There are many wonderful curated resources the WebdriverIO community has put together.  

Make sure to contribute yours at [awesome-webdriverio](https://github.com/webdriverio-community/awesome-webdriverio)!

A curated list of awesome WebdriverIO resources, libraries, tools and applications.

**Comment by christian-bromann** [comment]
> Also, I would add a Community section that talks about awesome-webdriverio and links to it (because there is none).

Sounds good to me!

**Comment by Badisi** [comment]
> > Also, I would add a Community section that talks about awesome-webdriverio and links to it (because there is none).
> 
> Sounds good to me!

Done in #7721

**Comment by christian-bromann** [comment]
Great, I guess we can close this one then. Again the list in the readme is suppose to document the packages located in this repository.

**Comment by Badisi** [comment]
@christian-bromann, I'm aligned with that.

But we have 2 options here:
1. add a reference to `@wdio/schematics` in [awesome-webdriverio](https://github.com/webdriverio-community/awesome-webdriverio)
2. move `@wdio/schematics` to `/packages` and reference it here

I'm still convinced by 2) but it's up to you 😉

**Comment by christian-bromann** [comment]
> 2\. move `@wdio/schematics` to `/packages` and reference it here

I am happy to move more packages into the core if bootstrapping them becomes more performant. Right now it takes a lot of time and is rather negative to the dev experience. `@wdio/schematics` has a bunch of heavy Angular packages that would add to that problem.

Let's go with `#1`

**Comment by Badisi** [comment]
Closed in favor of https://github.com/webdriverio/awesome-webdriverio/pull/3

**Pull request closed without merging**
