### PR TITLE
 AWS DeviceFarm Desktop Browser testing support

### PR DESCRIPTION
**Pull request by workeitel**
## Proposed changes

Work in progress version for https://github.com/webdriverio/webdriverio/issues/6018 - Still requires some changes like README.md update and tests.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

Still in progress

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

All details are in https://github.com/webdriverio/webdriverio/issues/6018 - it's a first draft to verify I'm on the right path.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@workeitel thanks for submitting this service. Before I review the code I would like to ask if it is possible to host the service under your account or in the AWS GitHub org. Reason is that with 35 sub packages or so the time to build the project is already quit CPU and time consuming. We got very careful adding new packages to the core due to that. Services that are published as e.g. `wdio-devicefarm-service` can be integrated into WebdriverIO the same way as core services.

WDYT?

**Comment by workeitel** [comment]
I updated the code to include unit tests. I think only the `README.md` is missing.

Thank you for the suggestion with a separate repository. I agree, that might be possible. But I see it a benefit when the package becomes part of the built-in experience and might even be documented on the website similar to other services. I understand if you're hesitant of adding more and more packages to the mono-repo but compared to other services the addition is fairly trivial. Ignoring the boilerplate and additional example it's probably less than 30 LOC. On the other hand the mono-repo helps with build-tools, test coverage, code style and automatic version upgrades which would make long-term maintenance significant easier.

**Comment by christian-bromann** [comment]
> and might even be documented on the website similar to other services

This will still be possible if the code does not live in this repository. Just do a similar PR as [this one](https://github.com/webdriverio/webdriverio/pull/6078) and the project will be shown on the project docs like any other service.

> the addition is fairly trivial.

Given the size of additional dependencies it significantly adds to the bootstrap time of the whole project. This is particularly concerning for a service that is rarely being touched and only has 30 LOC.

Here is what I would suggest: move the service into an own repository and modify this PR to be similar as to [this one](https://github.com/webdriverio/webdriverio/pull/6078). Cheers!

**Comment by workeitel** [comment]
Ok, Thanks for your feedback. I will try to follow-up on this with a separate repository. Feel free to resolve the PR

**Comment by christian-bromann** [comment]
Don't forget to open a new PR similar to [this one](https://github.com/webdriverio/webdriverio/pull/6078) to add the service to the CLI.

**Pull request closed without merging**
