### PR TITLE
exitCode doesn't reset after failed tests

### PR DESCRIPTION
**Pull request by WillBrock**
## Proposed changes

When a test fails it is setting the exitCode to 1 but it never sets it back to 0. This results in the exitCode to be 1 when the next test is ran and internally is increasing runnerFailed by 1 after each test even if it passes.

When the bail config option is set to say 10 and a test fails only 9 more tests will run and then bail no matter if they pass or fail.

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by monolithed** [comment]
Thanks for the PR!

**Comment by christian-bromann** [comment]
@WillBrock can you please elaborate on what this change will do and why it is needed? If one test fails it should exit with 1 no matter if following test are passing.

**Comment by monolithed** [comment]
Oh, I misunderstood the problem, so the same question.

**Comment by WillBrock** [comment]
Inside the endHandler method this.runnerFailed is set to 0 or 1 based on the exitCode. When a single test fails exitCode is set to 1 resulting in runnerFailed to be true and increase by 1. Since exitCode is never reset to 0 runnerFailed keeps increasing by one after each test no matter a pass or fail.

runnerFailed is used to keep track of how many tests have failed before exiting based on the "bail" number that is set in the config file.

If the bail config option is set to 10 and you have 50 tests and the 6th test fails then only 16 tests will be ran because runnerFailed increases by 1 after the first failed test and the attempts will hit the bail limit.

**Comment by christian-bromann** [comment]
@WillBrock please rebase on top of current master. I updated the projects test infrastructure.

**Comment by christian-bromann** [comment]
I don't think resetting exit code is a good idea. Found a better approach. Thanks for finding this bug.

**Pull request closed without merging**
