### PR TITLE
Fix update of cucumber pickle data for before/after hooks

### PR DESCRIPTION
**Pull request by 07souravkunda**
## Proposed changes
Emit _cucumberPickle data for each event when updated at cucumberFormatter. In this [change](https://github.com/webdriverio/webdriverio/pull/11010/files#diff-e0efb0f89f079be1829b09cfadaf2d248ae64bd988b3a2f940aea3ea13744551R271) we are emitting pickle data only onGherkinDocument, before this we were sending updated pickle data to getHookParams passed to before/after hooks. Which results in step as undefined [here](https://github.com/webdriverio/webdriverio/pull/11010/files#diff-38b3bc00fc303b526589acdf1f7211bab55ad3f92f47e8405909ba5ba1f78239R402).

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thanks for raising a PR, mind adding a small test to ensure we don't regress here?

**Comment by 07souravkunda** [comment]
> Thanks for raising a PR, mind adding a small test to ensure we don't regress here?

done

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by sourav-kundu** [comment]
@christian-bromann
This PR has been released [in v8.27.1](https://github.com/webdriverio/webdriverio/releases/tag/v8.27.1) but why is the latest version mentioned in NPM as 8.27.0?

https://www.npmjs.com/package/webdriver?activeTab=versions

**Pull request merged**
