### PR TITLE
fix: pin fibers version to 5.0.1

### LINKED ISSUE #8610: [🐛 Bug]: Issue with fibers@5.0.2 version
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

>7.10.16

### Node.js Version

>14.19.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

_No response_

### What happened?

It is installing pyhton which is not required.

### What is your expected behavior?

It should not install python for node > 14.x

### How to reproduce the bug.

Here is the reproduce steps:

- Install nodejs > 14.19.0 
- Use @wdio/sync as dependency in your project
- Do npm install
- It will break for fibers npm package which will install python internally. 
- It will try to install **fibers@5.0.2** 

### Relevant log output

```typescript
Here is detailed analysis link and possible solution.
[https://stackoverflow.com/questions/73166618/npm-installation-error-python-is-not-set-from-command-line-or-npm-configurati/73166619#73166619](https://stackoverflow.com/questions/73166618/npm-installation-error-python-is-not-set-from-command-line-or-npm-configurati/73166619#73166619)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by harsha509**
## Types of changes

Pin fibers version to 5.0.1 as 5.0.2 is no more compatible with node 14.x.x

Fixes #8610 !

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

<a href="https://gitpod.io/#https://github.com/webdriverio/webdriverio/pull/8611"></a>

### CODE REVIEW

**Comment by erwinheitzman** [comment]
That's odd, I can't find the release (5.0.2) [here](https://github.com/laverdet/node-fibers) nor [here](https://github.com/laverdet/node-fibers/tags). I'd like to find out what has changed.

**Comment by erwinheitzman** [comment]
Also, I agree with @christian-bromann that this will fix itself soon when we remove fibers.

**Comment by harsha509** [comment]
Not sure, but an npm package is released yesterday. https://www.npmjs.com/package/fibers

**Comment by christian-bromann** [comment]
Weird, seems like the patch is not on GitHub. Even more important to pin the version.

https://www.npmjs.com/package/fibers/v/5.0.2

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
Released 🎉  thanks @harsha509

**Pull request merged**
