### PR TITLE
Add JS boilerplate with closure functions

### PR DESCRIPTION
**Pull request by luuizeduardo**
## Proposed changes

This pull request add JS boilerplate using closure functions + docker-compose file (to selenium grid).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by luuizeduardo** [comment]
@christian-bromann I already check the CLA with my primary e-mail, but this commit was did from my secondary e-mail (work e-mail). What should I do?

**Comment by mgrybyk** [comment]
you may change email in your local repo to primary one then amend and push --force

**Comment by luuizeduardo** [comment]
Thanks @mgrybyk =)

**Comment by mgrybyk** [comment]
oh wow, you did it! 👍

**Pull request merged**
