### PR TITLE
Jim D | Support context being passed from wdio-mocha-framework

### PR DESCRIPTION
**Pull request by fijijavis**
## Proposed changes

This change adds support for passing a customizable ```context``` key that was implemented in [wdio-mocha-framework issue 114](https://github.com/webdriverio/wdio-mocha-framework/issues/114)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

I wasn't able to find any unit tests for ```ReporterStats.js``` as part of the v5 effort I'd be more than happy to figure out how we can get some setup.

### CODE REVIEW

**Comment by fijijavis** [comment]
@christian-bromann How do I re-run the pipeline?  It looks like the failures are due to not being able to connect to Sauce Labs

**Comment by snoblenet** [comment]
Two possible solutions:
- @christian-bromann, having write access to the repo, triggers a new build of the existing PR in Travis
- @fijijavis marks the PR as closed and then opens it again

**Comment by snoblenet** [comment]
Sauce Labs is not launching again. This is clearly an issue with something other than the PR, which code-wise is minimal: https://github.com/webdriverio/webdriverio/pull/2518/files.

Also I can see there are a whole string of PRs that are currently failing with exactly the same error.

Could a Webdriver.io committer pull the branch, run the tests locally, and then merge it? 

Alternatively, could a Webdriver.io committer work out why Sauce Labs is not launching?

**Comment by christian-bromann** [comment]
> Could a Webdriver.io committer pull the branch, run the tests locally, and then merge it?

Yes. This is due to the security changes Travis did some time ago. I tried JWT tokens which also didn't work. Will merge it as soon as I can verify it doesn't break things.

**Pull request merged**
