### PR TITLE
(docs): saveScreenshot requires afterTest hook to be async

### PR DESCRIPTION
**Pull request by hashar**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

When requesting a screenshot in `afterTest` I would sometime lack a screenshot file. I eventually found `browser.saveScreenshot` is async and the hook has to be explicitly defined `async`: https://github.com/webdriverio/webdriverio/issues/5545#issuecomment-1215272473

Add an example for using `browser.saveScreenshot` in the `afterTest` hook with the hook being set `async` explicitly. This would have saved me a bit of troubleshooting time.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by hashar** [comment]
I am making this contribution with a shared copyright between me as an individual and @wikimedia foundation. I don't know whether this contribution is copyrightable or subject to CLA, if it can be opted out feel free to merge it in.

Meanwhile I will reach out to @wikimedia legal department to review and sign the OpenJS CCLA which I can not sign in name of the organization.

**Comment by zeljkofilipin** [comment]
@hashar I have contacted @wikimedia legal team while working on #7999. I think the CLA is signed. They will probably know what to do, but as far as I remember, you have to add your wikimedia email to your github profile and sign the commit with it.

https://github.com/settings/emails

**Comment by hashar** [comment]
I have amended the commit message to add:

     Signed-off-by: Antoine Musso <amusso@wikimedia.org>

But EasyCLA still fails. That is now pending approval of my account by the Wikimedia Legal team :)

**Comment by erwinheitzman** [comment]
Honestly this applies to all commands you use, not just in a hook but everywhere, so I don't really agree to explicitly add this

**Comment by christian-bromann** [comment]
Any updates @hashar ?

**Comment by hashar** [comment]
> Any updates @hashar ?

I went ahead and signed an individual CLA since I have shared copyright for the work I am doing while working for Wikimedia. I will still reach out to our the organization legal team to find out how to get added to the corporate CLA as well.

I have no idea how to retrigger EasyCLA verification :)

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by hashar** [comment]
> > Any updates @hashar ?
> 
> I went ahead and signed an individual CLA since I have shared copyright for the work I am doing while working for Wikimedia. I will still reach out to our the organization legal team to find out how to get added to the corporate CLA as well.
> 
> I have no idea how to retrigger EasyCLA verification :)

As a follow-up, I got added to the Wikimedia Foundation contributors and signed the corporate CLA through EasyCLA. Success!

**Comment by christian-bromann** [comment]
Nice 🎉 looking forward to more contributions then 😉

**Pull request merged**
