### PR TITLE
fix: skipped tests not showing jasmine pending() reason in spec reporter

### PR DESCRIPTION
**Pull request by kerkeniakov**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
This adds jasmine pending() output to the test results from spec reporter, if a skipped test has pending reason.  Fixes this issue : https://github.com/webdriverio/webdriverio/issues/8170 , 
## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

<a href="https://gitpod.io/#https://github.com/webdriverio/webdriverio/pull/8686"></a>

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Implementation looks good, can we have unit tests for this?

**Comment by kerkeniakov** [comment]
@christian-bromann I've added 2 unit tests.

**Comment by christian-bromann** [comment]
It seems that the CLA bot is still not happy with the PR. Make sure that you have signed with the same email you have used to make all commits within this PR.

**Comment by christian-bromann** [comment]
Also, do you mind raising the same PR for the `v7` branch so we can release this to the current version as well?

**Comment by kerkeniakov** [comment]
Will do !

**Comment by christian-bromann** [comment]
Can you re-open a new PR with changes to the `main` branch?

**Comment by kerkeniakov** [comment]
@christian-bromann 
I'm getting a little confused here 😄  I've opened a new PR from v7 to v7 https://github.com/webdriverio/webdriverio/pull/8688 , 
Should I close it , then close this one , and open a new one to main branch?

**Comment by christian-bromann** [comment]
@kerkeniakov sorry for the confusion. We need 2 PRs. One against the `main` branch and one against `v7`. Our current `main` branch is for WebdriverIO `v8` which we will release in the future.

**Comment by kerkeniakov** [comment]
@christian-bromann Ahhhh I see. Thanks for clarifying! 
Cheers 🍻

**Pull request closed without merging**
