### PR TITLE
fix: set hostname to 127.0.0.1 for node 18 support

### LINKED ISSUE #8760: [🐛 Bug]: Appium does _not_ start with Node v18 but works with Node v16
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7.23.0

### Node.js Version

18.7.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  specs: [ './e2e/specs/**/*.spec.js' ],
  reporters: [ 'spec' ],
  capabilities: [
    {
      'appium:platformVersion': '15.5',
      'appium:deviceName': 'iPhone Simulator',
      browserName: 'Safari',
      platformName: 'iOS'
    }
  ],
  services: [ [ 'appium' ] ],
  maxInstances: 1,
  execArgv: [],
  sync: false,
  deprecationWarnings: true,
  waitforTimeout: 15000,
  connectionRetryTimeout: 240000,
  connectionRetryCount: 1,
  framework: 'jasmine',
  runner: 'local',
  port: 4723,
  baseUrl: 'http://0.0.0.0:4000/',
  suites: { home: [ './e2e/specs/home.spec.js' ] },
}
```

### What happened?

Using node v16, this works as expected: `WDIO_LOG_PATH=wdio.log WDIO_DEBUG=trace wdio --suite home`. The ios simulator boots up, loads up safari, loads the website running locally and passes the tests.

Using node v18, the same command does not work. It fails to launch the ios simulator. I can go between node v16 and v18 for chrome driver, safari driver as expected, this is isolated to appium as a service as listed above.

I traced the error down to the the webdriver package, specifically request/factory which returns a NodeJSRequest. From here I'm not sure if its the implemented _libRequest that relies on got that is the issue or an unpredictable behavior with EventEmitter in node v18.

When makeRequest is called by the startWebDriverSession from utils, its either an issue with the call to this.emit('request') or afterwards when making call to this._request which ends up making a call to the _libRequest from NodeJSRequest.

I feel like it is related to the EventEmitter either from this library or got's, something could of changed with node 18, as it usually does. I also tried using node v18.2.0 with same result. Its also entirely possible since we're not using esm module type this could be it too. I say this because when i run yarn why got, it shows as got@11.8.5 and neglects to use the version of got as seen in the webdriver/package.json of ^12.1.0. should we be using wedriver@next or is it possible the regular tag releases aren't getting the updates from main?

i dont expect this to get fixed as its pretty low level and can i can get around by using node v16 instead. wanted to report it in case anyone else came across the same thing and started pulling their hair out.

### What is your expected behavior?

_No response_

### How to reproduce the bug.

use node 18 and run `WDIO_LOG_PATH=wdio.log WDIO_DEBUG=trace wdio --suite home` with the above wdio.conf.js

### Relevant log output

```typescript
dont pay attention to the logs, they are not indicative of the issue as the result from the appium not starting earlier up the call stack

[0-0]     at ClientRequest.<anonymous> (./node_modules/got/dist/source/core/index.js:970:111)
[0-0]     at Object.onceWrapper (node:events:642:26)
[0-0]     at ClientRequest.emit (node:events:539:35)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at ClientRequest.origin.emit (./node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:454:9)
[0-0]     at Socket.emit (node:events:527:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by harsha509**
## Proposed changes

As node18 accepts hostname to 127.0.0.1 instead of localhost.  fixes #8760

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
According to https://github.com/webdriverio/webdriverio/issues/8760#issuecomment-1227758809 the server needs to start the service with a hostname of `127.0.0.1` and not the client side. However this change might be still needed anyway. I would suggest to first have the Appium change come in and see how it behaves.

**Comment by christian-bromann** [comment]
@harsha509 do you still think this is needed? I am a bit concerned this could cause other side effects.

**Comment by harsha509** [comment]
> @harsha509 do you still think this is needed? I am a bit concerned this could cause other side effects.

This is no longer needed. The issue was observed with geckodriver and it was fixed in wdio-geckodriver-service!

Hence closing this PR!

**Review by christian-bromann — APPROVED** [review]
I am reconsidering this, given we changed Geckodriver to also use `127.0.0.1`. I will leave this in `v8` only to not cause any breaking changes. Thanks @harsha509 for the patch 👍

**Comment by harsha509** [comment]
Thank you @christian-bromann !

**Pull request merged**
