### PR TITLE
TypeScript auto compiling

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

Currently it is not quite straight forward to setup TypeScript with WDIO. You need to modify your config to ensure the TS compiler is triggered. We can help here a bit and automatically trigger it if found.

Also by adding `ts-node` to your dev dependencies it makes it easier to start with a TS setup right away.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

This might have an impact on the load performance but some e2e testing showed that it is marginal and doesn't really makes a difference.

### CODE REVIEW

**Comment by christian-bromann** [comment]
Moving forward as I am cutting a new release and would love to include this. I am happy to address any considerations / feedback afterwards.

**Comment by robd** [comment]
I gave this a try tonight and ran into errors around const enums. I see:
```Cannot read property 'X' of undefined```

I chased this down to this issue: https://stackoverflow.com/questions/50365598/typescript-runtime-error-cannot-read-property-of-undefined-enum, and was able to reproduce this locally by changing

```require('ts-node/register');``` 
to 
```require('ts-node/register/transpile-only');```

Not sure of the pros and cons of transpile only, but wanted to mention that using the new version would mean I'd need to change my prod code.

**Comment by christian-bromann** [comment]
@robd thanks for the note. We do transpile-only in Babel too and I think it makes sense to do the same in TypeScript.

**Comment by unickq** [comment]
Hey there

I updated `@wdio/cli           ^6.10.11  →  ^6.11.0`

and got many errors.
image

```
    "@wdio/appium-service": "^6.11.0",
    "@wdio/cli": "^6.11.0",
    "@wdio/junit-reporter": "^6.11.0",
    "@wdio/local-runner": "^6.11.0",
    "@wdio/logger": "^6.10.10",
    "@wdio/mocha-framework": "^6.11.0",
    "@wdio/selenium-standalone-service": "^6.11.0",
    "@wdio/spec-reporter": "^6.11.0",
    "@wdio/sync": "^6.11.0",
```
wdio.conf.js
```
require("ts-node/register");
require("tsconfig-paths/register");
require("dotenv").config();

exports.config = require("src/configs/wdio.config").config;
```

<details>
  <summary>Errors</summary>
```
2021-01-08T14:12:18.988Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: C:\Git\GreetingsIsland\wdio.conf.js: ⨯ Unable to compile TypeScript:
src/configs/hooks.config.ts:2:5 - error TS7022: '__importDefault' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

2 var __importDefault = (this && this.__importDefault) || function (mod) {
      ~~~~~~~~~~~~~~~
src/configs/hooks.config.ts:2:67 - error TS7006: Parameter 'mod' implicitly has an 'any' type.

2 var __importDefault = (this && this.__importDefault) || function (mod) {
                                                                    ~~~
src/configs/hooks.config.ts:8:7 - error TS2451: Cannot redeclare block-scoped variable 'path_1'.

8 const path_1 = __importDefault(require("path"));
        ~~~~~~

  src/configs/wdio.config.ts:4:7
    4 const path_1 = require("path");
            ~~~~~~
    'path_1' was also declared here.
src/configs/hooks.config.ts:11:17 - error TS7006: Parameter 'config' implicitly has an 'any' type.

11     onPrepare: (config, capabilities) => {
                   ~~~~~~
src/configs/hooks.config.ts:11:25 - error TS7006: Parameter 'capabilities' implicitly has an 'any' type.

11     onPrepare: (config, capabilities) => {
                           ~~~~~~~~~~~~
src/configs/hooks.config.ts:16:35 - error TS7006: Parameter 'cap' implicitly has an 'any' type.

16             capabilities.forEach((cap) => {
                                     ~~~
src/configs/hooks.config.ts:20:23 - error TS7006: Parameter 'c' implicitly has an 'any' type.

20                 .map((c) => {
                         ~
src/configs/hooks.config.ts:35:14 - error TS7006: Parameter 'capabilities' implicitly has an 'any' type.

35     before: (capabilities) => {
                ~~~~~~~~~~~~
src/configs/hooks.config.ts:44:18 - error TS7006: Parameter '_test' implicitly has an 'any' type.

44     beforeTest: (_test, _context) => {
                    ~~~~~
src/configs/hooks.config.ts:44:25 - error TS7006: Parameter '_context' implicitly has an 'any' type.

44     beforeTest: (_test, _context) => {
                           ~~~~~~~~
src/configs/hooks.config.ts:50:17 - error TS7006: Parameter 'test' implicitly has an 'any' type.

50     afterTest: (test, context, result) => {
                   ~~~~
src/configs/hooks.config.ts:50:23 - error TS7006: Parameter 'context' implicitly has an 'any' type.

50     afterTest: (test, context, result) => {
                         ~~~~~~~
src/configs/hooks.config.ts:50:32 - error TS7006: Parameter 'result' implicitly has an 'any' type.

50     afterTest: (test, context, result) => {
```
</details>

**Comment by christian-bromann** [comment]
@unickq try to remove `require("ts-node/register");`

**Comment by unickq** [comment]
Removed `"ts-node/register"` from everywhere - worked, thanks

**Comment by r4j4h** [comment]
While handy, I think this can break people's setups by forcing the use of the root tsconfig.

Could we use the wdio conf to provide a way to control the options incase someone needs a different tsconfig used, or other ts-node options?

I found a case where removing the "ts-node/register" elsewhere does not fix things, and running the runner in a sub-directory doesn't change anything, so there seems to be no workaround but modifying the source of @wdio/config directly.

Here is how I came to this conclusion:

I tested with a project with two tsconfig.json's, one in root for app that doesn't know about any of the BDD stuff, another in tests/bdd/ directory with tests and other stuff. TypeScript offers an "extends" functionality, so I think this is an expected use case for it. More importantly, this project requires "files: true" also in ts-node to work properly.

```
Folder structure for clarity:
/tests/bdd/tsconfig.json <-- ts-node
/tsconfig.json <-- app
```

So the wdio.conf.js for this project before looked like (using undocumented but working function style):

```
    requireModule: [
() => {
        require('ts-node').register({
          files: true,
          project: './tests/bdd/tsconfig.json',
        })
      }
]
```

With this change, I get type errors when both run:

```
[0-0] 2021-01-29T20:43:21.171Z ERROR @wdio/runner: TSError: ⨯ Unable to compile TypeScript:
tests/bdd/hooks/common-hooks.ts(10,1): error TS2769: No overload matches this call.
  Overload 1 of 3, '(tags: string, code: TestCaseHookFunction): void', gave the following error.
    Argument of type '{ tags: string; }' is not assignable to parameter of type 'string'.
  Overload 2 of 3, '(options: IDefineTestCaseHookOptions, code: TestCaseHookFunction): void', gave the following error.
    Argument of type '() => string' is not assignable to parameter of type 'TestCaseHookFunction'.
      Type '() => string' is not assignable to type 'TestCaseHookFunctionWithoutParameter'.
        Type 'string' is not assignable to type 'void | Promise<void>'.
tests/bdd/hooks/common-hooks.ts(20,7): error TS2345: Argument of type '() => Promise<any[]>' is not assignable to parameter of type 'TestCaseHookFunction'.
  Type '() => Promise<any[]>' is not assignable to type 'TestCaseHookFunctionWithoutParameter'.
    Type 'Promise<any[]>' is not assignable to type 'void | Promise<void>'.
      Type 'Promise<any[]>' is not assignable to type 'Promise<void>'.
        Type 'any[]' is not assignable to type 'void'.

at createTSError (/Users/user/app/node_modules/ts-node/src/index.ts:434:12)
at reportTSError (/Users/user/app/node_modules/ts-node/src/index.ts:438:19)
at getOutput (/Users/user/app/node_modules/ts-node/src/index.ts:578:36)
at Object.compile (/Users/user/app/node_modules/ts-node/src/index.ts:775:32)
at Module.m._compile (/Users/user/app/node_modules/ts-node/src/index.ts:858:43)
at Module.m._compile (/Users/user/app/node_modules/ts-node/src/index.ts:858:23)
at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at require.extensions.<computed> (/Users/user/app/node_modules/ts-node/src/index.ts:861:12)
    at Object.require.extensions.<computed> [as .ts] (/Users/user/app/node_modules/ts-node/src/index.ts:861:12)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Module._load (internal/modules/cjs/loader.js:769:14)
        at Function.hookedLoader [as _load] (/Users/user/app/node_modules/mockery/mockery.js:111:12)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at /Users/user/app/node_modules/@wdio/cucumber-framework/build/index.js:171:13
        at Array.forEach (<anonymous>)
```

When I remove that from wdio.conf.js, the usage of the wrong ts config becomes apparent:

```
[0-0] 2021-01-29T20:49:29.837Z ERROR @wdio/runner: /Users/user/app/tests/bdd/step-definitions/common/login.ts:1
import { Given } from '@cucumber/cucumber'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
```

If I modify node_modules/@wdio/config/build/utils.js's loadTypeScriptCompiler function to be like:

```
    try {
        require.resolve('ts-node');
        require('ts-node').register({
            files: true,
            transpileOnly: true,
            project: './tests/bdd/tsconfig.json'
        });
        log.debug('Found \'ts-node\' package, auto-compiling TypeScript files');
        return true;
    }
```

It works fine.

So for this reason I think we need loadTypeScriptCompiler function to look through the config file for something like a tsNodeOptions block and spread that. It could default to { transpileOnly: true } if undefined?

**Comment by christian-bromann** [comment]
@r4j4h good findings. It was indeed a breaking change which we should have introduced in v7. I am wondering if it makes sense to remove it again in v6 and add it to v7 only.

**Comment by fellowseb** [comment]
Hey! Just wanted to let you know it took me quite some time to detect this breaking change as [the public documentation for the v6](https://v6.webdriver.io/docs/typescript.html) still seems to refer to the previous way of doing things (i.e. with `require("ts-node/register");`).
Is there a documentation publishing/deployment issue ? The page says it's been updated "Last updated on 3/24/2020" though.

**Pull request merged**
