### PR TITLE
[Browserstack-service] Local App file upload to browserstack for Appium sessions

### PR DESCRIPTION
**Pull request by avinash-bharti**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
This PR:
- Add support for app upload using the local app file path to browserstack
  - app upload used in appium sessions
  - the value of the app can be a file path, app_url, custom_id, shareable_id. [ref](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app)
  - custom_id can also be provided while uploading the app
## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@avinash-bharti thanks for raising the PR. Great changeset 👏 

Two things:
- mind signing the CLA?
- Could you create the same PR for the `main` branch, so that we have this feature also in v8?

**Comment by avinash-bharti** [comment]
@christian-bromann 
- Have signed the CLA
- Changes in my PR have been done on the top of branch `v7 ` (`main` branch was not working correctly during dev testing), There will be a lot of conflicts If I raise the same PR for the `main` branch due to the base branch `v7`. Can you guide me here on how I should proceed?

**Comment by christian-bromann** [comment]
> * `main` branch was not working correctly during dev testing

Can you elaborate what was not working for you?

> * Can you guide me here on how I should proceed?

I suggest to just manually apply the changes to the `main` branch.

**Comment by avinash-bharti** [comment]
[`main` dev testing issue]
- Appium script has dependencies
  - @wdio/cli "^7.23.0"
  - @wdio/browserstack-service "^7.23.0"
  - @wdio/local-runner "^7.23.0"
  - @wdio/mocha-framework "^7.23.0"
  
To test browserstack-service locally:
- Executed `run setup-full` inside the root folder of `webdriverio`
- Moved to browserstack-service folder and executed `npm link`
- moved into appium script and executed `npm link @wdio/browserstack-service`
- Executing script throwing below error 
```Execution of 1 workers started at 2022-09-14T10:09:11.650Z

2022-09-14T10:09:11.672Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/browserstack-service".
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/avinash/BrowserStack/onboarding_repos/sdk/webdriverio/packages/wdio-browserstack-service/build/index.js from /Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/utils.js not supported.
Instead change the require of index.js in /Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/utils.js to a dynamic import() which is available in all CommonJS modules.
    at safeRequire (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/utils.js:189:16)
    at initialisePlugin (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/initialisePlugin.js:30:50)
    at initialiseServices (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at handler (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/commands/run.js:165:16)
    at Object.run (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/index.js:77:34)
    at safeRequire (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/utils.js:192:15)
    at initialisePlugin (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/initialisePlugin.js:30:50)
    at initialiseServices (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at handler (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/commands/run.js:165:16)
    at Object.run (/Users/avinash/BrowserStack/onboarding_repos/sdk/test_repo/webdriverio-appium-app-browserstack/android/node_modules/@wdio/cli/build/index.js:77:34)
```
- Seems like this issue is caused because the other dependencies used inside `browserstack-service` has been installed with v7 and use require statement rather than an import. 
- Linking `cli` `local-runner` `mocha-framework` with `main` branch build giving below issue 
```
> webdriverio-appium-app-browserstack@0.1.0 first
> ./node_modules/.bin/wdio examples/run-first-test/first.conf.js

node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'async-exit-hook' imported from /Users/avinash/BrowserStack/onboarding_repos/sdk/webdriverio/packages/wdio-cli/build/launcher.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:910:9)
    at moduleResolve (node:internal/modules/esm/resolve:959:20)
    at defaultResolve (node:internal/modules/esm/resolve:1176:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.0.0
```

- @christian-bromann Please help with the steps required to test the `main` branch build locally.

**Comment by christian-bromann** [comment]
> * moved into appium script and executed `npm link @wdio/browserstack-service`

It seems that your project is using CJS and WDIO packages with v7. These are not compatible. I recommend to create a reproducible example using the [`examples`](https://github.com/webdriverio/webdriverio/tree/main/examples/wdio) directory.

**Comment by avinash-bharti** [comment]
@christian-bromann Thanks for helping, I have created the same PR against the `main` branch. Please let me know if any action is required from my side to get this PR reviewed.

**Comment by avinash-bharti** [comment]
@christian-bromann I am just following up to check if you managed to look at the PRs, Let me know if any information is needed from my side to move things forward.

**Pull request merged**
