### PR TITLE
Revert "implemented polyfill for safaridriver interaction API - closes #1419"

### LINKED ISSUE #1419: Implement workaround for moveTo command in Safari
## The problem

I'm consistently getting failures when running the `rightClick` method in Safari 9 (and 6, haven't tried other versions). I don't get these same failures in other browsers.

## Environment

* WebdriverIO version: 4.1.1
* Node.js version: 6.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):

## Details

Here is the error I'm getting:

```
Unknown command: {"id":"rjli6wikh89u","name":"mouseMoveTo","parameters":{"element":":wdc:1467223117657"}} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
System info: host: 'itako47220.prod.miso', ip: '172.20.47.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
```

### PR DESCRIPTION
**Pull request by git-jiby-me**
Safari driver now supports these protocol actions

This reverts commit 79ff992e302676f014c24297278f3e832aa39b61.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@git-jiby-me thanks for the PR. I will have to test this for myself before I can merge this. Would be awesome though if the Safaridriver finally supports this out of the box.

**Comment by patthiel** [comment]
@git-jiby-me  @christian-bromann, fyi when testing.. it likely only supports these commands when using the latest safari technology preview.

**Comment by git-jiby-me** [comment]
@patthiel interesting for me it was working with safari 11 on browserstack

**Comment by christian-bromann** [comment]
We need to make sure that it still works on older Safari versions

**Comment by christian-bromann** [comment]
Given that many people still test on older Safari versions, let's keep this around until some time has left

**Comment by patthiel** [comment]
@christian-bromann @git-jiby-me wondering, if it'd be possible to allow this command on versions of safari >= 11.0.. Guess that's a bit hacky and non-standard though.

**Comment by christian-bromann** [comment]
@patthiel `moveTo` is deprecated anyway. So I am not planning in putting any much time into this command as it will be replaced with the actions command anyway.

**Comment by christian-bromann** [comment]
Closing due to v5 update.

**Pull request closed without merging**
