### PR TITLE
Add request timeout to init call

### PR DESCRIPTION
**Pull request by cyrusmith**
Call to init sometimes hangs forever in my testing environment. Wouldn't it be useful to be able to set request timeout?

### CODE REVIEW

**Comment by christian-bromann** [comment]
What's up with your test environment?

**Comment by christian-bromann** [comment]
ping @cyrusmith

**Comment by christian-bromann** [comment]
closing due to inactivity. Don't really see why the init command should have a timeout.

**Comment by jasonslyvia** [comment]
I facing the same issue here, a selenium grid is hung whatsoever, and my test script only exist when mocha timeout. In this case, I'd like to switch to an alternative grid.

But I guess a simple `setTimeout` call to wrap `.init()` should be sufficient.

**Pull request closed without merging**
