### PR TITLE
add cucumber html reporter

### PR DESCRIPTION
**Pull request by yon-cuadrado**
## Proposed changes

I have created a new reporter for webdriverio. [wdio-reporter-html]( https://www.npmjs.com/package/wdio-reporter-html ). This reporter is based in the plugin [cucumber-html-report-generator](https://www.npmjs.com/package/cucumber-html-report-generator) that is a fork of the plugin [multiple-cucumber-html-reporter](https://www.npmjs.com/package/multiple-cucumber-html-reporter), wtih some extra additions like typescript or dark theme.

## Types of changes

  [//]: # (What types of changes does your code introduce to WebdriverIO?)
  [//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

<a href="https://gitpod.io/#https://github.com/webdriverio/webdriverio/pull/8360"></a>

<a href="https://gitpod.io/#https://github.com/webdriverio/webdriverio/pull/8361"></a>

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
@yon-cuadrado thanks for raising a PR.

After merging it I realised that your reporter seems to be very similar to [multiple-cucumber-html-reporter](https://github.com/wswebcreation/multiple-cucumber-html-reporter) as you also mentioned in your PR description. Can you describe a bit why you did create this reporter and which features are you missing in the current existing reporter. I wonder if it is possible to contribute back to that project rather than creating a new reporter that would do almost the same things.

While the WebdriverIO community loves to see new reporters in the ecosystem we should avoid creating to many similar reporter that don't have a clear differentiation. This would only cause confusion.

**Comment by yon-cuadrado** [comment]
[multiple-cucumber-html-reporter](https://github.com/wswebcreation/multiple-cucumber-html-reporter) and the reported I have created: [wdio-reporter-html](https://www.npmjs.com/package/wdio-reporter-html) are both reporters intended to be used for formatting cucumber tests execution results in a html report. 

The main differences between this reporter and mine are these ones: 
- Typescript included
- Themes
- Outline scenarios are displayed grouped in the results in the same way they are in the feature files.

I have updated the readme of the reporter to make it more clear.

**Comment by christian-bromann** [comment]
@yon-cuadrado why did you decide to build this reporter from scratch rather than contributing to the [community driven one](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter#readme)? It has already has quite a lot of downloads. You even still have [references](https://github.com/yon-cuadrado-projects/wdio-cucumber-html-reporter/blob/master/package.json#L43-L46) to our community driven project.

How about we work together to improve the community driven reporter rather than maintaining two (almost identical ones)? I feel like this would be much more beneficial for the community at large. WDYT?

**Comment by yon-cuadrado** [comment]
I decided to build the reporter in a separate project because I have used it to learn trying a lot of modifications, not all of them successful. I agree with you that it is better only to have only one project. I will try to to include the modifications of my project in the other.

**Comment by christian-bromann** [comment]
Thanks a lot! We are happy to give you access to the project and invite you to the org so we all can collaborate on it together.

**Pull request merged**
