### PR TITLE
Update minimum node version requirement to Node 10

### PR DESCRIPTION
**Pull request by patthiel**
## Proposed changes

As raised in https://github.com/webdriverio/webdriverio/pull/4305 and https://github.com/webdriverio/webdriverio/issues/4346, the minimum node version for webdriverio should be updated to Node 10 due to [dependency](https://www.npmjs.com/package/fibers#supported-platforms)(s) that require it.

I've tried to update the node version wherever I could find it, but i'm sure there's a spot or two that i missed.. Please let me know and i'll update this PR. The CI build passes locally and in a local `node:10-jessie` container.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change 

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by kellyselden** [comment]
Does this project use SemVer? If so, anyone using webdriver unpinned on node 8 will start breaking (as we did). This should be reverted in v5 and rereleased as v6.

**Comment by patthiel** [comment]
@kellyselden I kind of agree, that's why I marked the change as breaking (but i'm also not sure if this project uses SemVer).

However, wdio-sync already relies on a dependency that is only compatible with  >=node 10 and any version of that library beyond `wdio-sync "5.7.13"` will throw a node compatibility error when upgrading. This change makes official, a [change](https://github.com/webdriverio/webdriverio/pull/3898) in compatibility that was made months ago.

As to whether we should reverted this change and re-release it as v6, I would defer to @webdriverio/technical-committee. If reverted, i would recommend downgrading Fibers to ensure this whole monorepo is compatible with node8.

**Comment by christian-bromann** [comment]
@patthiel is right here. The compatibility problem was already caused by the fibers update month ago. So we messed up already at that point which makes it useless to revert this change now. We are definitely using semver in the project and gonna upgrade accordingly the next time when we drop any Node.js support. I apologies if this has caused any inconvenience.

**Comment by harlentan** [comment]
This commit just break my npm install!

My project run in node 8 for a long time.

**Comment by harlentan** [comment]
What is your problem!

@christian-bromann

**Comment by wswebcreation** [comment]
@harlentan,

What do you mean with your remark?

**Comment by kellyselden** [comment]
I would like to argue for sticking to SemVer. It would be a benefit to your consumers with not much work (reverting the two commits). Even though this is an open project run by volunteers and can obviously do whatever it wants, here is my case:

1. My internal company project that wraps webdriver supports all active Node LTSs, so I would have to pin to the version before SemVer break.
1. My org (Ember.js) also supports all active Node LTSs, so my plans to start promoting a bridge between the two will either have to wait until December (Node 8 EOL), or release with a old pinned version (lame).
1. People would be losing out on your bugfixes until December.
1. Basically I'm arguing that breaking SemVer and dropping Node early is more impactful to your consumers than you may realize.

I'm saying this with love as a fellow open-source junkie. Please reconsider :)

I love the project BTW.

**Comment by mgrybyk** [comment]
I'm against reverting PR but we may raise another PR with changing minimum version to 8 and downgrading fibers version to 3.0.1

**Comment by mgrybyk** [comment]
Here you go, let's discuss it here https://github.com/webdriverio/webdriverio/pull/4360

**Comment by christian-bromann** [comment]
Wrote a short post mortem on this issue: https://gist.github.com/christian-bromann/1b6245c04b894b5b989accdc90eb250d

**Pull request merged**
