### PR TITLE
Added a new service for sending test results to the Google chat space.

### PR DESCRIPTION
**Pull request by qajonatasmartins**
https://github.com/qajonatasmartins/wdio-google-chat-service 
https://www.npmjs.com/package/wdio-google-chat-service

## Proposed changes

[//]: # added a new service integrated with google chat to send notifications of the results of successful and failed tests or just failed.

## Change types

[//]: # Just add a new service
 
[//]:

- [ ] Bugfix (non-stop change that fixes an issue)
- [] New feature (non-stop change that adds functionality)
- [ ] Last minute change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## Checklist

[//]: #

- [X] I read the document [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is ​​effective or my feature works
- [X] Added required documentation (if appropriate)
- [ ] I added appropriate type definitions for new commands (if appropriate)

### Reviewers: @webdriverio/project-committers

### CODE REVIEW

**Comment by christian-bromann** [comment]
@qajonatasmartins thanks for raising the PR and creating a new plugin for the ecosystem. Very cool!

Two comments:
- mind signing the CLA with the email you've used to make the commit?
- could you translate your docs to english? Most WebdriverIO users are english speaking and might be confused why these docs are in Spanish (I assume?)

**Comment by qajonatasmartins** [comment]
> @qajonatasmartins thanks for raising the PR and creating a new plugin for the ecosystem. Very cool!
> 
> Two comments:
> 
> * mind signing the CLA with the email you've used to make the commit?
> * could you translate your docs to english? Most WebdriverIO users are english speaking and might be confused why these docs are in Spanish (I assume?)

hi christian, i'm fine and you? The readme.md was written in Portuguese-BR.

I already changed to English and connected with EASY CLI 👍🏼

**Comment by christian-bromann** [comment]
> I connected with the EASY CLA, I accepted the term but it is not performing the "1 workflow awaiting approval", can you help me?

Can you make sure you sign with the same email that you've used to make the commit? I tried to retrigger the easycla without success. Another option is to make this commit myself.

> I already changed to English

Mind making another release so it gets propagated to NPM?

**Comment by qajonatasmartins** [comment]
I will open a new PR @christian-bromann

**Pull request closed without merging**
