### PR TITLE
fix devtools tracing for click transitions

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Proposed changes

fix dev-tools tracing for click transitions

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@SrinivasanTarget can you explain what was broken?

**Comment by SrinivasanTarget** [comment]
@christian-bromann ah sorry I forget to share the link above. Here you go - https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/index.js#L46

**Comment by christian-bromann** [comment]
> Here you go - [https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/index.js#L46](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-devtools-service/src/index.js?rgh-link-date=2020-09-25T06%3A37%3A06Z#L46)

How about we move this string into a constant and use it in both areas so that this bug won't happen again.

**Review by christian-bromann — APPROVED** [review]
perfect 👍

**Pull request merged**
