### PR TITLE
Minor fix to add a try-catch block if the delete-session throws an error.

### PR DESCRIPTION
**Pull request by nami-varthakavi**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
When does it throw an exception?

**Comment by nami-varthakavi** [comment]
> When does it throw an exception?

We have special application were we use multiremote in which both drivers are embedded in single application. So if you kill one automatically the second one is killed.

**Comment by nami-varthakavi** [comment]
> Please add unit tests

Yes I can.

**Comment by christian-bromann** [comment]
> So if you kill one automatically the second one is killed.

If you run multiremote you have to call deleteSession for both browser because you run 2 sessions in parallel. I have my reservations with this patch. Can you please explain in more detail your situation?

**Comment by nami-varthakavi** [comment]
Sure. The application has two components 
1. chromium based application controlled using chromedriver
2. A qt component which is controlled using qtdriver and the driver lib is already embedded in it. 

Even though multi-remote config is to interact between two different apps. In this scenario multi remote works out of the box. 

For example when I kill the chromedriver the application and the session is ended. And after that when the deleteSession tries to delete the qtDriver session, it has been already killed by the first delete session. So it throws an error.

**Comment by nami-varthakavi** [comment]
If you guys are ok I may suggest one more option to add a new boolean ‘config’ option to provide a choice for the user to handle the clean up instead of handling it by wdio.

**Comment by nami-varthakavi** [comment]
> Sure. The application has two components
> 
> 1. chromium based application controlled using chromedriver
> 2. A qt component which is controlled using qtdriver and the driver lib is already embedded in it.
> 
> Even though multi-remote config is to interact between two different apps. In this scenario multi remote works out of the box.
> 
> For example when I kill the chromedriver the application and the session is ended. And after that when the deleteSession tries to delete the qtDriver session, it has been already killed by the first delete session. So it throws an error.

Can I get this one reviewed please? @christian-bromann @mgrybyk.

**Comment by mgrybyk** [comment]
@nami-varthakavi there reason why it is not yet merged is that introducing try/catch there looks for me like a hacky workaround (a bit).

Maybe introducing config option on whether to close session or not is more reasonable? In such case you'll be able to end session for only one of your multiremote sessions.

What are your thoughts regarding this one @christian-bromann ? Is it good to merge or we should think on different solution?

**Comment by christian-bromann** [comment]
It seems like a workaround for me too. Usually if a session is started it needs to be closed again. Even though the browser process was killed the session still exists in the driver. I would like to explore what is causing the error and who is closing the session in the first place. Then apply a fix that would only apply for that specific scenario.

**Comment by nami-varthakavi** [comment]
> It seems like a workaround for me too. Usually if a session is started it needs to be closed again. Even though the browser process was killed the session still exists in the driver. I would like to explore what is causing the error and who is closing the session in the first place. Then apply a fix that would only apply for that specific scenario.

I can probably explain it to u directly if that is fine because I don't want to share too many details in here

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi there reason why it is not yet merged is that introducing try/catch there looks for me like a hacky workaround (a bit).
> 
> Maybe introducing config option on whether to close session or not is more reasonable? In such case you'll be able to end session for only one of your multiremote sessions.
> 
> What are your thoughts regarding this one @christian-bromann ? Is it good to merge or we should think on different solution?

Yeah I can make the necessary changes to create a new config option

**Comment by nami-varthakavi** [comment]
> It seems like a workaround for me too. Usually if a session is started it needs to be closed again. Even though the browser process was killed the session still exists in the driver. I would like to explore what is causing the error and who is closing the session in the first place. Then apply a fix that would only apply for that specific scenario.

DMed to describe the scenario we are encountering. If you still feel, are you cool with updating to use a new config-option?

**Comment by christian-bromann** [comment]
> use a new config-option

I am not a fan of adding a config option. I want to rather explore why the session is being closed by the QT driver and maybe fix the error there.

**Comment by nami-varthakavi** [comment]
> > use a new config-option
> 
> I am not a fan of adding a config option. I want to rather explore why the session is being closed by the QT driver and maybe fix the error there.

It's how the application has been built because both the drivers are just part of a single application. 
Anyway, I will make the changes and update the PR soon.

**Comment by nami-varthakavi** [comment]
> > use a new config-option
> 
> I am not a fan of adding a config option. I want to rather explore why the session is being closed by the QT driver and maybe fix the error there.

The application is built in such a way that the qt driver will be only listening to port 9517 if the application is up and running. When the driver session communicating chromium part of the application is deleted, it kills the application altogether. Since the application is killed, there is no longer existence of the qtDriver application.

**Comment by nami-varthakavi** [comment]
@christian-bromann is it okay to add the config option. I understand try-catch is a workaround but adding a config option is a much safer way to do this. And providing an option to the user to do the clean up by either wdio/themselves can be considered as a feature request?

**Comment by christian-bromann** [comment]
@nami-varthakavi to get more context: are you automating the same application with two drivers?

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi to get more context: are you automating the same application with two drivers?

yeah

**Comment by nami-varthakavi** [comment]
> > @nami-varthakavi to get more context: are you automating the same application with two drivers?
> 
> yeah

**Comment by christian-bromann** [comment]
> yeah! The desktop application's toolbar is controlled by QT and the chrome driver controls the application inside like the main menus and basic contents.

How about not using multiremote then and instead use WebdriverIO to create a separate standalone session calling the `remote` function in the before hook?

**Comment by nami-varthakavi** [comment]
> > yeah! The desktop application's toolbar is controlled by QT and the chrome driver controls the application inside like the main menus and basic contents.
> 
> How about not using multiremote then and instead use WebdriverIO to create a separate standalone session calling the `remote` function in the before hook? I don't think multiremote is the best approach here given that you automate a single application and given the fact that apparently the qtDriver closes the session when the application closes.
> 
> Also please file an issue in the qtDriver project. A session in the driver should not be automatically closed if the application (e.g. the browser) is being closed. You can try this with Chrome and Chromedriver where you still have a session even you quit the browser window.

It's not basically a problem of qt driver. We have packaged the qt driver and its libraries within the application, that's why it is killing the application whenever we kill the driver. Our devs have tried many ways to fix this but the solution was only to embed within the application. I don't think there is a way around that, 

I will anyway try doing it in the before the block and see.

**Comment by nami-varthakavi** [comment]
Currently, in our end, this fix has been deprioritized. I'm closing this PR for now.

**Pull request closed without merging**
