### PR TITLE
change regex for id

### PR DESCRIPTION
**Pull request by APshenkin**
https://github.com/webdriverio/webdriverio/issues/2105

### CODE REVIEW

**Comment by christian-bromann** [comment]
Can you please add a unit test for this?

**Comment by APshenkin** [comment]
@christian-bromann I added test for this change. After this change you are not be able to locate pseudo class elements via css selector, but I'm not sure that Webdriver can locate pseudo class elements itself https://stackoverflow.com/a/37355292

**Comment by DavertMik** [comment]
This change is important for Appium tests. This simplifies locators from

```
//android.widget.TextView[@resource-id="io.selendroid.testapp:id/label_email_data"]
```
to 

```
#io.selendroid.testapp:id/label_email_data
```

**Comment by APshenkin** [comment]
Now in this PR https://github.com/webdriverio/webdriverio/pull/2161

**Pull request closed without merging**
