### PR TITLE
Retries per specfile

### PR DESCRIPTION
**Pull request by bennieswart**
This is a continuation of #2556.

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Add retries on a per-specfile basis, as discussed in https://github.com/webdriverio/webdriverio/issues/2484.

Previously only test-level and suite-level retries were available, which
are fine in most cases. In any test which involves state, such as on a
server or in a db, the state may be left invalid once the test fails the
first time. Any subsequent retries may have no chance of passing due to
the invalid state they would have to start with.

A new browser instance is created for each specfile, which makes this an
ideal place to hook and setup any other states (server, db). Retries on
this level would mean that the whole setup process could simply be
repeated as if it were for a new specfile, with the results of the
failing specfile (that is to be retried) being discarded.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @christian-bromann

### CODE REVIEW

**Comment by bennieswart** [comment]
@christian-bromann anything that still needs doing here?

**Comment by christian-bromann** [comment]
@bennieswart two questions:

- how is this affecting reporter from not reporting the same spec as failed and passed at the same time?
- do we want to port this to v5? If so a PR is required.

**Comment by WillBrock** [comment]
This will be really nice to have.

**Comment by aikrasnov** [comment]
Image of qa

**Comment by AdrieanKhisbe** [comment]
Very interesting feature! 
What's the status on this @bennieswart ? :)

**Comment by shackijj** [comment]
Hello

This feature is really good because it allows running tests in a new environment.

For those who want to get it now, there is an [alternative implementation of a test runner](https://github.com/gemini-testing/hermione) which works fine. The one drawback of the runner is that wdio's sync option is not supported there. It's the main reason why I don't want to use that in my projects. Literally it means that I have rewrite hundreads of tests.

@bennieswart @christian-bromann
Looking at history of this PR, I see that the last message about two monts ago.
Please, let me know if you need some help here.

**Comment by christian-bromann** [comment]
This was closed because I moved everything related to v4 to https://github.com/webdriverio-boneyard/v4

**Pull request closed without merging**
