### PR TITLE
pass id to getLocation && touch

### PR DESCRIPTION
**Pull request by gogoyqj**
## Proposed changes

try to fix [# 2104](https://github.com/webdriverio/webdriverio/issues/2104)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@gogoyqj can you provide a test case for this?

**Comment by gogoyqj** [comment]
@christian-bromann ， i'm using with both selenium 2.0/appium and chrome mobile
test:
```javascript
let webdriverio = require('webdriverio');
let client = webdriverio.remote({
    port: 4723,
    logLevel: 'verbose',
    desiredCapabilities: {
        browserName: 'chrome',
        platformName: "Android",
        platformVersion: "5.1",
        deviceName: "emulator-5554"
    }
});
let browser = client
    .init();

browser.url('http://ued.qunar.com/hy2/yo/demo/src/html/component/scroller/lazyimage.html')
    .pause(1000)
    .touch('body')
    .then(function() {
        setTimeout(function() {
            browser.end();
        }, 15000);
    }, function(err) {
        console.log("err", err);
        setTimeout(function() {
            browser.end();
        }, 15000);
    });
```
threw error:
```
[12:16:51]  COMMAND     POST     "/wd/hub/session/74df5b2d-9305-46be-948e-ba89b2ea794a/touch/click"
[12:16:51]  DATA                {"element":"0"}
err { Error: stale element reference: element is not attached to the page document
  message: 'stale element reference: element is not attached to the page document',
```
a really bug, or some api i called wrong?

**Comment by christian-bromann** [comment]
The touch command was indeed borked for some reason. Not sure if it ever suppose to take x and y variables. Fixed the issue.

**Comment by neofreko** [comment]
Any chance to release this bugfix as minor version on npmjs?

**Pull request closed without merging**
