### PR TITLE
Cucumber boilerplate showcasing advanced page object structure, Cucum…

### PR DESCRIPTION
**Pull request by osmolyar**
Added 

### [osmolyar/page-object-structure-with-cucumber](https://github.com/osmolyar/page-object-structure)  

Boilerplate project to run E2E tests with Cucumber, showcasing advanced page object structure, Cucumber world context, business options, various cucumber step data parsing methods.

- Frameworks:
    - WebdriverIO (v6)
    - @wdio/cucumber-framework
    - Typescript
- Features:
    - Increased modularization
        - Page object structure leveraging return of landing page instances on navigation to pages
            - Isolates step definition files and page object classes from dependencies on downstream pages.
            - No need to import each page class that will be navigated to. 
            - Increases the modularity of the framework and enforces guardrails on methods defined within a page
            - Implicitly validates having landed on the correct page inside each page's constructor
                - Calls a method that validates the page's title or some text
                - Further enforces expected navigation results prior to interacting with a page's elements
            - Allows the framework to model the navigation structure of the application
            - Steps can traverse multiple pages using a single method.
         - Page Ui services separate from page objects
            - Model higher-level business logic
            - Page objects contain only DOM-level logic
            - Ui services import those of downstream pages and define relationships among pages
      - Custom browser and element commands
            -With color logging and parameterized wait and trailing wait options
      - Use of Cucumber 'world' object with custom World constructor
            - Initialize functionality-specific business option objects
            - Populate business options with step definitions
            - Step definitions pass only required business options, validation options to ui Service methods
            - Step definitions examples using various Cucumber 
                - data-tables methods (https://github.com/cucumber/cucumber-js/blob/master/features/data_tables.feature) 
      - Separation of validation and navigation logic
            - Collect artifacts for validation during navigation 
            - Capture in validationOptions business option objects
            - Compare to expected values using subsequent validation steps
    - Allure report (screenshots on failure)

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Can we fix the indentation to 4 spaces? Also all bullet points require a space after the `-`

**Review by christian-bromann — COMMENTED** [review]
I still see two issues:

- you put this boilerplate at the bottom which would list it under the v5 boilerplates but it seems you are using v6
- the intentation of the list is still 4 but should be 2, e.g.:

```patch
-    - WebdriverIO (v6)
+  - WebdriverIO (v6)
```

**Comment by osmolyar** [comment]
Thanks; will move it - I thought you initially mentioned 
>Can we fix the indentation to 4 spaces? 

But can update to 2.

(Also will work on a runnable version of the boilerplate that executes against an unrestricted site. Adding this for examples for now.)

**Review by christian-bromann — APPROVED** [review]
👍 Thanks

(sorry for the misunderstanding)

**Pull request merged**
