### PR TITLE
Dedupe Capabilities

### PR DESCRIPTION
**Pull request by EdmundasD**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

This is an addition to https://github.com/webdriverio/webdriverio/pull/12430.

`capabilities` are also being duped when initializing WDIO via `Launcher`. Appears the dev decided not to include this change. More context here: https://github.com/webdriverio/webdriverio/pull/12430#discussion_r1527504299

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks so much for raising the PR 👏  Some requests:

- mind signing the CLA? Let me know if you have any questions
- mind enhancing the unit test in `packages/wdio-config/tests/node/configparser.test.ts`?
- mind raising the same PR for v8 so we can release it to the latest version?

**Comment by christian-bromann** [comment]
Any updates @EdmundasD ?

**Comment by EdmundasD** [comment]
@christian-bromann, this was placed on my back burner as I was busy with other projects. When I was working on adding a unit test for this scenario, I was unable to get the duped capabilities to appear, so I'll look into this again this week and try to reproduce the issue within the unit test.

**Comment by EdmundasD** [comment]
@christian-bromann, this is opened against `v8` branch. Want me to open another one against `main`?

**Comment by christian-bromann** [comment]
I will hold on, merging this until the `main` PR is raised. Thanks again.

**Comment by EdmundasD** [comment]
Here is the `main` PR: https://github.com/webdriverio/webdriverio/pull/13211

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
