### PR TITLE
Repair chrome maximize devtools

### PR DESCRIPTION
**Pull request by rdelhaise-wiiisdom**
Maximize when no viewport in provided in chrome, add test

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments
Retrieve the code from this [PR](https://github.com/webdriverio/webdriverio/pull/10883)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Mind signing the CLA?

**Comment by rdelhaise-wiiisdom** [comment]
Hello ! 
Thank you, I'm looking at this with my manager to be able to sign in :), 

Have a good week-end!

**Comment by christian-bromann** [comment]
Thanks @rdelhaise-wiiisdom , will merge once test pass. Note that we have deprecating automation through the `devtools` package and will likely remove this package with the next major version. We recommend using `webdriver` as `automationProtocol` option.

**Comment by rdelhaise-wiiisdom** [comment]
Ahha, just seen that I didn't configured ESLint in my VScode so the tests failed because of semicolons, I'll change that

**Comment by rdelhaise-wiiisdom** [comment]
@christian-bromann I updated the branch with Eslint friendly code :)

**Comment by rdelhaise-wiiisdom** [comment]
Mmh, I have no clue why tests don't pass, seems like I forgot to do some steps 🫠

**Comment by christian-bromann** [comment]
This is not related to your PR. I will go ahead and merge.

**Comment by rdelhaise-wiiisdom** [comment]
Super ! Do you know when it will be released?

**Comment by christian-bromann** [comment]
Keep an eye one the release notes.

**Comment by christian-bromann** [comment]
Congratulations on your first WebdriverIO contribution 🎉

**Pull request merged**
