### PR TITLE
Browserstack service changes

### PR DESCRIPTION
**Pull request by Ankit098**
## Proposed changes

1. Moving browserstack-service to browserstack maintained fork of `@wdio/browserstack-service`.
2. Update the default env variable for browserstack username.
3. Update template of conf file to add path only when provided by user as default value was empty string which gives an error by itself.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by esaari** [comment]
@Ankit098 Why does Browserstack maintain their own fork and not contribute changes to the wdio official service hosted here?

**Review by wswebcreation — CHANGES_REQUESTED** [review]
Hi @Ankit098 

thanks for this PR, can you also elaborate why Browserstack is maintaining its own fork. We'd love to see contributions back to the WDIO project and if the current project misses functionality then please let us know/create a PR to solve this.

**Comment by Ankit098** [comment]
@wswebcreation @esaari 
Currently the service is coupled with the wdio release. We are pushing a few changes that can go in independently of the webdriverio version.
As of now changes done in fork allow for single version of the service to be used across webdriverIO versions, and a few changes in browserstack local launcher.

**Comment by wswebcreation** [comment]
Hi @Ankit098 

This service can be released whenever there’s a fix. To prevent double work I’d advise you to create a PR for this service, we can then review it and release it.
It will prevent double versions that are not in line with each other, last but not least, all BS users that use WDIO already know and use this service so your fixes will not reach them

**Comment by esaari** [comment]
@Ankit098 I agree with @wswebcreation, my organization leverages Browserstack and the wdio plugin heavily. We would not be interested in using a fork outside of WDIO. Please create a new PR to merge any fixes/changes made on the fork with this service here.

**Comment by wswebcreation** [comment]
Closing this PR and love to see the changes in a new PR for this service that would benefit all users

**Comment by christian-bromann** [comment]
I agree with @wswebcreation and @esaari - we happily accept all PRs to the BS service and also happy to release a new version after every PR made. If this hasn't been this way in the past please let me know but so far we haven't received much contributions for the service yet.

Does this sound ok with you @Ankit098 ?

**Pull request closed without merging**
