### PR TITLE
Assume JsonWP if platform cap is given

### LINKED ISSUE #3611: setValue broken with safaridriver in --legacy mode
**Environment:**
 - **WebdriverIO version:** 5.6.2
 - **Mode:** Both
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** Safari 12
 - **Platform name and version:** OSX 10.13, 10.14

**Describe the bug**
When safaridriver is in `--legacy` mode, `setValue` breaks with the following error:

```
Request body does not contain required parameter 'value'.
```

This is particularly inconvenient because wdio doesn't currently work well with safaridriver's W3C mode, either. (See #2962.)

**To Reproduce**
```javascript
const { remote } = require('webdriverio');

(async () => {
    const browser = await remote({
        logLevel: 'warn',
        path: '/',
        capabilities: {
            browserName: 'safari'
        }
    });

    await browser.url('https://www.google.com');
    const elt = await browser.$('input[name="q"]');

    // See #2962: This fails with safaridriver in w3c mode
    //   Error: The command 'GET /session/:id/element/:nodeId/displayed' was not found.
    await elt.waitForDisplayed();

    // This fails with safaridriver in --legacy mode:
    //   Error: Request body does not contain required parameter 'value'.
    await elt.setValue("webdriver");

    await browser.deleteSession();
})().catch((e) => console.error(e));
```

**Expected behavior**
When safaridriver is running in `--legacy` mode, I expected webdriver to recognize that and use the jsonwp version of `setValue`. (Which would have the parameter as `value`, not `text`.)

Couple of other thoughts:

- As a workaround, being able to specify the protocol directly (with `--protocol=jsonwp` or something) would be handy.
- But if there's some other way to force it to use jsonwp in the meantime, that would be really helpful.

Thanks!

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

If we find a `platform` capability in the session response we should refer to it as a jsonwp session.

Fixes #3611

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
@christian-bromann can we assume jsonWP in some different way?

In case I'm passing platform capability to selenium grid server webdriverio will just crash because we have to pass non W3C capabilities in prefix way, ex: vendor:platform.

Can we add platform to DEFAULT_CONFIGS so that sanitizeCaps remove it?

Maybe we should move non W3C caps to desiredCapabilities, not sure

**Comment by mgrybyk** [comment]
@christian-bromann do we need some documentation for this feature?

**Comment by christian-bromann** [comment]
@mgrybyk this PR is about better detecting JSONWP sessions by making sure that there is no `platform` capability is the session response body. I don't use the grid but if you run geckodriver or latest Safari in w3c mode it should not return a `platform` capability, no?

**Comment by mgrybyk** [comment]
I can't even start the session if there is non W3C property in alwaysMatch in capabilities.

I thought this PR is about ability to forcibly set jsonWP

**Comment by christian-bromann** [comment]
> I thought this PR is about ability to forcibly set jsonWP

No please see the test. Safari in legacy mode returns `platformName` and `platform` in which case we should assume a jsonwp session which is correct.

> I can't even start the session if there is non W3C property in alwaysMatch in capabilities.

That is fine. This PR is about checking the session response values which contains the capabilities on which we judge whether or not it is a w3c or jsonwp session.

**Comment by christian-bromann** [comment]
@mgrybyk is this good to go or do you have any further questions?

**Pull request merged**
