### PR TITLE
embed expect-webdriverio in framework adapters

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

See issue #5326. We have to embed `expect-webdriverio` typings into the framework typings so that it will be available automatically.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by christian-bromann** [comment]
@mgrybyk seems like some issue with the typings:

```
../../../packages/wdio-cucumber-framework/node_modules/expect-webdriverio/types/jest-expect-clone/jest-expect.d.ts:76:15 - error TS2430: Interface 'Matchers<R, T>' incorrectly extends interface 'Matchers'.
  The types returned by 'toHaveProperty(...)' are incompatible between these types.
    Type 'R' is not assignable to type 'undefined'.

76     interface Matchers<R, T> {
```

**Comment by mgrybyk** [comment]
Let me take a look

**Comment by mgrybyk** [comment]
@christian-bromann this one https://github.com/webdriverio/expect-webdriverio/commit/a4f7a7ac03791929503cbeb1cc7409c6de8b43da broke everything.

Have to partially revert it and all the errors in the current PR will gone

**Comment by mgrybyk** [comment]
@christian-bromann https://github.com/webdriverio/expect-webdriverio/commit/a4f7a7ac03791929503cbeb1cc7409c6de8b43da#diff-045247205377646525c5096c7eed6582L67-R67

We can't use `undefined` there, it should be either `any` or generic. I'll rise PR to expect-webdriverio in a moment.

My local project fails to compile with latest expect-webdriverio as well

**Comment by mgrybyk** [comment]
@christian-bromann https://github.com/webdriverio/expect-webdriverio/pull/63

**Comment by christian-bromann** [comment]
There are still some Jasmine errors which should be fixeable in this PR I assume:
```
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(112,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(119,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(126,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(131,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/expect-[secure]/types/jest-global.d.ts(3,15): error TS2451: Cannot redeclare block-scoped variable 'expect'.
jasmine.ts(18,25): error TS2339: Property 'toHaveTitle' does not exist on type 'Matchers<BrowserObject>'.
jasmine.ts(21,20): error TS2339: Property 'toHaveTextContaining' does not exist on type 'Matchers<Element>'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(112,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(119,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(126,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/@types/jasmine/ts3.1/index.d.ts(131,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
../../../packages/wdio-jasmine-framework/node_modules/expect-[secure]/types/jest-global.d.ts(3,15): error TS2451: Cannot redeclare block-scoped variable 'expect'.
```

**Comment by mgrybyk** [comment]
On it :)

**Comment by christian-bromann** [comment]
> On it :)

Feel free to push directly on this branch. Thanks!

**Comment by mgrybyk** [comment]
Two issues here, on in expect-webdriverio, another one here. Working on PR for expect-webdriverio

**Comment by christian-bromann** [comment]
@mgrybyk I will make a release for `expect-webdriverio` with your fix.

**Comment by mgrybyk** [comment]
@christian-bromann some unit tests are failing, not related to types now, so we are good :)

**Comment by christian-bromann** [comment]
unit test failures are legit, looking into it.

**Comment by mikerusso-tsi** [comment]
The issue here seems related to what I'm seeing when webdriverio is used via Appium.  It fires exceptions of "expect is not a function".

**Comment by christian-bromann** [comment]
@mikerusso-tsi until we release this patch please add `expect-webdriverio` to your types as described in https://webdriver.io/docs/typescript.html#framework-types

**Comment by christian-bromann** [comment]
Thanks for the help @mgrybyk , releasing it now.

**Comment by mikerusso-tsi** [comment]
> @mikerusso-tsi until we release this patch please add `expect-webdriverio` to your types as described in https://webdriver.io/docs/typescript.html#framework-types

Thanks for your reply, @christian-bromann, I added it to the tsconfig.json of my appium client but still see the error.  Pardon my ignorance on this, but, does appium make use of one of your framework adapters?  I simply have an appium client in a node-based javascript file and am not making use of jasmine, mocha, or cucumber.  Should expect-webdriverio be available in such case?  I tried installing expect-webdriverio to the project and requiring it, but to no avail.  When using appium, is the WDIO testrunner invoked (which is the piece that is said to include expect-webdriverio)?  Thank you!

**Comment by christian-bromann** [comment]
@mikerusso-tsi if you use `expect-webdriverio` without the testrunner you need to import it as described here https://www.npmjs.com/package/expect-webdriverio#usage

**Comment by mikerusso-tsi** [comment]
Thank you, Christian.  The instructions do not seem suitable when coming from an appium test environment.  First of all, I don't have a wdio.conf.js file, I think because I did not start with the npx instruction that you normally use to create a webdriverio project.  Nevertheless, I tried just adding it into my folder with the appium test specs, as well as installing expect-webdriverio into my project, but 'expect' is still not available to me.  Here's my wdio.conf.js:


?

exports.config = {
beforeSession() {
require('expect-webdriverio');
}
};

I very much appreciate your time!
Mike


Mike Russo
Senior Software Engineer

TSI Incorporated
Oconomowoc, WI
Tel: 262.354.6139
mike.russo@tsi.com
www.tsi.com<http://www.tsi.com>




________________________________

**Comment by christian-bromann** [comment]
@mikerusso-tsi just require the package anywhere before you first use it

**Comment by mikerusso-tsi** [comment]
Well, there still appears to be a higher-level problem.  Although 'expect' is now defined, when used it throws the exception 'browser' is not defined.  For instance,


?node_modules/expect-webdriverio/lib/matchers/element/toBeDisplayed.js:7:5


Which is this:


return browser.call(async () => {
        const result = await utils_1.executeCommandBe.call(this, received, async (el) => {
            try {
                return el.isDisplayed();
            }
            catch (_a) {
                return false;
            }
        }, options);
        return result;
    });


By the way, I am not testing a browser app but rather an Android Cordova app, which internally uses a Chrome webview.  Again, this is via Appium.

?

Thank you!

Mike


________________________________

**Comment by christian-bromann** [comment]
oh, ok. I assumed it would be possible to use it without the testrunner but apparently you can only use it with that.

**Comment by mikerusso-tsi** [comment]
Well that's disappointing!  So it looks like expect-webdriverio is relying on this 'browser' object and 'browser' is somehow provided by the testrunner, is that how you see it?  Can you suggest any other way to provide the browser object from Appium?


Or, can you suggest any other means of using expect-webdriverio with Appium?  E.g., via the mocha framework?  Was expect-webdriverio built by forking expect (for Jest) and adapting it for webdriverio?


Thanks again for you help!

Mike

________________________________

**Comment by christian-bromann** [comment]
> Or, can you suggest any other means of using expect-webdriverio with Appium?

You can use the library with Appium. You just need to run WebdriverIO with the testrunner. You could also try to set browser as global:

```js
global.browser = await remote({...})

await expect(browser).toHaveTitle()
```

**Comment by mikerusso-tsi** [comment]
Christian,

I didn't like the thought of running the WebDriverIO testrunner, so I tried the global.browser idea and THAT DID IT!!!  Such a relief!


And such a simple fix, of course.  I was so close, having tried assigning the result of remote() to 'browser' but didn't think of the global context to make it available deep down in expect-webdriverio.


Thanks for putting up with all of my questions!?

Mike


________________________________

**Pull request merged**
