### PR TITLE
updating mocha version

### PR DESCRIPTION
**Pull request by vasikarla**
## Proposed changes

[//]: # Updating the Mocha version 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Major version upgrade of a dependency

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by vasikarla** [comment]
image
@christian-bromann  : i did it actually, not sure why its not allowing you to merge!

**Comment by vasikarla** [comment]
@jsf-clabot  :  could you help me here please, why is the cls still orange after i signed the agreement.

**Comment by BorisOsipov** [comment]
@vasikarla your commit performed from `Raj_Vasikarla@intuit.com` email address.
So probably you need to accept CLA for this email address.

**Comment by vasikarla** [comment]
@BorisOsipov : can you help me how to accept the SLA from that email please.

**Comment by BorisOsipov** [comment]
@vasikarla you need to change your email settings in your git client to your gmail account
https://help.github.com/articles/setting-your-commit-email-address-in-git/

after that commit your changes again.

**Comment by vasikarla** [comment]
@BorisOsipov : i actually did that

➜  webdriverio git:(master) git config --global user.email
vasikarla.raj@gmail.com

and pushed a change.

**Comment by BorisOsipov** [comment]
@vasikarla for old commits in this pr too. you need o recreate them

**Comment by vasikarla** [comment]
let me close this and re-create the entire PR.  
@christian-bromann  : watch out for the new PR, ignore this one...

**Pull request closed without merging**
