### PR TITLE
Wdio Percy Support v7

### PR DESCRIPTION
**Pull request by amaanbs**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@amaanbs can we incorperate the feedback from https://github.com/webdriverio/webdriverio/pull/11865 into this PR?

**Comment by rev-doshi** [comment]
@christian-bromann incorporated the feedback from https://github.com/webdriverio/webdriverio/pull/11865 in this PR, can you please review?

**Comment by christian-bromann** [comment]
@rev-doshi seems like the coverage treshold is not met, can you either add more unit tests or reduce coverage. As we are not actively working on v7 anymore we don't mind reducing the coverage treshold when they block new features to be released.

**Comment by christian-bromann** [comment]
@rev-doshi mind updating the snapshots for the junit tests? Just run `npx jest packages/wdio-junit-reporter -u`

**Comment by rev-doshi** [comment]
@christian-bromann I ran the command  `npx jest packages/wdio-junit-reporter -u` on my local, but it didn't not change anything that I could commit

**Review by christian-bromann — APPROVED** [review]
I will go ahead then and merge. Will try to release v7 today.

Thanks a lot 👍

**Comment by karanshah-browserstack** [comment]
@christian-bromann Did you get a chance to release this? Let us know if there are any blockers.

**Comment by christian-bromann** [comment]
This was released as `v7.35.0`

**Pull request merged**
