### PR TITLE
[v7] Browserstack Accessibility support with WebdriverIO 🚀

### PR DESCRIPTION
**Pull request by kamal-kaur04**
## Proposed changes

BrowserStack Accessibility Automation Support to conduct accessibility testing on pre-existing test builds and generate health reports on BrowserStack

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
LGTM 👍  Thanks!

**Comment by christian-bromann** [comment]
@kamal-kaur04 it seems like there are some conflicts after merging the other Browserstack PR, mind resolving those?

**Comment by kamal-kaur04** [comment]
Sure! doing that. Thank you.

**Comment by kamal-kaur04** [comment]
@christian-bromann Have resolved the merge conflicts.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by kamal-kaur04** [comment]
Hi @christian-bromann, Apologies for reaching out to you on the behalf of the team. Could you please let us know if any challenges in releasing v7 for the merged PRs or when can we release it?

**Comment by christian-bromann** [comment]
It seems to me that the v7 build is still broken, mind taking a look at it?

**Comment by kamal-kaur04** [comment]
@christian-bromann I tried building the v7 branch. It's not breaking as such. I've run tests also, they are also passing. Could you please point me out which command is breaking?

**Comment by christian-bromann** [comment]
I just triggered a release.

**Pull request merged**
