### PR TITLE
Improve typings

### PR DESCRIPTION
**Pull request by ablok**
## Proposed changes

Adds `services` to typings and documentation.
Fixes optionality for the `moz:firefoxOptions` in the typings template.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

First attempt at a PR, please be gentle ;)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@ablok please sign the CLA

**Comment by christian-bromann** [comment]
@ablok please sign the CLA with the same email you did the commit. The CLA is still not signed.

**Comment by ablok** [comment]
> @ablok please sign the CLA with the same email you did the commit. The CLA is still not signed.

Ok, so I did the commits with my work email adress. Now I added that email adress to my github email adresses. How do I make sure I sign it for that email address?

**Comment by christian-bromann** [comment]
> How do I make sure I sign it for that email address?

Either make a new commit or create a new PR

**Pull request closed without merging**
