### PR TITLE
Add QUnit test framework

### PR DESCRIPTION
**Pull request by mucaho**
SIC: Work in progress.
I tested it with the provided example and inside a real project, seems to work.
However, I have a couple of questions:
* How many test suites shall there be? Is there only one for all specs, one for each spec, or one for each group of tests ([QUnit.module](http://api.qunitjs.com/QUnit.module/))?
* Shall `test:start` and `test:end` fire for each individual assertion or for a test case?
* Shall `test:pass`, `test:fail` and `test:pending` fire for each individual assertion or for a test case? Shall the error message in the latter case refer to the first failed assertion (of possibly multiple failed assertions)?
* When shall `hook:start` and `hook:end` fire?
* How to implement generators? I have looked at other frameworks implementation, they wrap all framework relevant methods in a `co` construct. How would I implement this for QUnit?

### CODE REVIEW

**Comment by christian-bromann** [comment]
First of all thanks so much for adding a new framework adaption. In v4.0 we started to port the adaption into own npm modules (e.g. [wdio-mocha-framework](https://github.com/webdriverio/wdio-mocha-framework)). Would you be interested in working on such a qunit adaption module? If so I would send you an invite to join the organisation. We release v4 soon and it would be cool if we could support qunit in v4 too.

> How many test suites shall there be? Is there only one for all specs, one for each spec, or one for each group of tests (QUnit.module)?

Could you provide an example here? I am not that familiar with qunit.

> Shall test:start and test:end fire for each individual assertion or for a test case?

For each test case.

> Shall test:pass, test:fail and test:pending fire for each individual assertion or for a test case? Shall the error message in the latter case refer to the first failed assertion (of possibly multiple failed assertions)?

The latter and yes let's refer to the first failed assertion. What would you suggest here?

> When shall hook:start and hook:end fire?

Right before a hook starts and right after it has ended. I don't see it critical if this event is missing. I don't see it in the jasmine adaption either.

> How to implement generators? I have looked at other frameworks implementation, they wrap all framework relevant methods in a co construct. How would I implement this for QUnit?

I would do it the same way.

**Comment by mucaho** [comment]
Thanks for clearing that up.

>> How many test suites shall there be? Is there only one for all specs, one for each spec, or one for each group of tests (QUnit.module)?

> Could you provide an example here? I am not that familiar with qunit.

I'm just curious whether the reporters support multiple test suites. If they do, I would change the code to report a new test suite for each group of tests (QUnit.module).

> Would you be interested in working on such a qunit adaption module?

I would be interested, however the syntax (ES6 I assume) and the abstractions (fibers, ...) used are completely new to me, so better (and more efficient) to let someone more proficient write it.

**Comment by christian-bromann** [comment]
@mucaho 

> I'm just curious whether the reporters support multiple test suites. If they do, I would change the code to report a new test suite for each group of tests (QUnit.module).

Go ahead with a solution you think would work best ;-)

**Comment by mucaho** [comment]
Ok, I added generator support and made each group of tests report a new test suite.

Keep in mind that the [QUnit hooks](http://api.qunitjs.com/category/callbacks/) do **not** support asynchronous functions or promises. I don't know a way around this. Maybe fibers could help here when this framework will get ported to wdio v4.0.

There is one more design question: The `QUnit` framework is added to global namespace so that users can set custom configuration and QUnit-specific hooks inside their `before` callback in their configuration file. Should these configuration options be explicitly added to a `qunitOpts` configuration property, similar to the other frameworks?

**Comment by christian-bromann** [comment]
> Should these configuration options be explicitly added to a qunitOpts configuration property, similar to the other frameworks?

Yes please

**Comment by christian-bromann** [comment]
@mucaho what's the state of this PR? Would like to get this merged. Seems that everything is in place.

**Comment by christian-bromann** [comment]
ping @mucaho

**Comment by mucaho** [comment]
PR is still unfinished. I hope to finish it by end of this weekend.

On Wed, Jan 13, 2016 at 2:52 AM, Christian Bromann <notifications@github.com

**Comment by christian-bromann** [comment]
@mucaho we updated the code base (merged v4 branch). We moved all framework adapters to be an own package on NPM (e.g. [wdio-mocha-framework](https://github.com/webdriverio/wdio-mocha-framework)). I created a repository for the qunit framework (see [here](https://github.com/webdriverio/wdio-qunit-framework)) and added you as collaborator. Please use the same setup we did in the other framework adapters (babel + grunt) to implement this. If you need help setting this up let me know! Thanks

**Pull request closed without merging**
