### PR TITLE
(@wdio/cli): use ts-node/esm and ts-node/register

### LINKED ISSUE #10901: [🐛 Bug]: First time test run of WDIO with default configs results in ES related errors
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v20.5.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

I started with WDIO installation following these steps

- Created a git repo, cloned it on my system and did `npm init`
- Proceeded with `npm init wdio` and accepted the default behavior in most cases 
-  Ran `npm run wdio` and faced errors

Attached screenshot of the `npm init wdio` step 

Screenshot 2023-08-09 at 11 10 26 AM

### What is your expected behavior?

The initial `npm run wdio` should have worked fine. Instead it started throwing error - 

`SyntaxError: Cannot use import statement outside a module`

Full stack trace I have pasted in the log output section.

### How to reproduce the bug.

-  Clone this repo : https://github.com/zac11/wdio-work-demo
-  Run `npm run wdio`

### Relevant log output

```typescript
npm run wdio

> wdio-work-demo@1.0.0 wdio
> wdio run ./wdio.conf.ts

2023-08-09T05:30:14.234Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/annubha/Documents/Rahul/wdio-work-demo/wdio.conf.ts: Cannot use import statement outside a module
/Users/annubha/Documents/Rahul/wdio-work-demo/wdio.conf.ts:1
import type { Options } from '@wdio/types'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async ConfigParser.addConfigFile (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/config/build/lib/ConfigParser.js:85:36)
    at async ConfigParser.initialize (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/config/build/lib/ConfigParser.js:47:13)
    at async Launcher.run (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/cli/build/launcher.js:37:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

Taking another stab at this one.

fixes #10901

@nextlevelbeard @jan-molak I would like to again get your input on this. I remember we reverted it last time because of weird stacktrace side effects. However I remember we added a test for this so if this build is passing we should be fine to go ahead. I don't see any other way to fix above issue.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by jan-molak** [comment]
Let me try this locally and get back to you. I remember seeing ts-node go crazy when you specify the loader and use the registration function at the same time

**Comment by jan-molak** [comment]
Hey @christian-bromann. I made the below change to `node_modules/@wdio/cli/build/commands/run.js` locally:
```diff
- NODE_OPTIONS += ' --loader ts-node/esm/transpile-only --no-warnings';
+ NODE_OPTIONS += ' --loader ts-node/esm/transpile-only -r ts-node/register --no-warnings'
```
Unfortunately, I can confirm that while it helps to work around #10901 and makes the tests load correctly on Node 20, it breaks source maps support on Node 20, 18, and 16.

**Comment by christian-bromann** [comment]
>  it breaks source maps support on Node 20, 18, and 16.

Can you elaborate? In the demo project if I put in a failing assertion it gives me the correct line of code.

>  is not making any changes to @wdio/cli, but instead changing the generated project to use ESM

That would be the ideal solution but many folks still run on CJS even though using a lot of mixed ESM primitives. Ideally I would like WebdriverIO to support TypeScript with CJS.

**Comment by jan-molak** [comment]
> > it breaks source maps support on Node 20, 18, and 16.
> 
> Can you elaborate? In the demo project if I put in a failing assertion it gives me the correct line of code.

Could you share your demo project? I'm putting together a repro now.

> > is not making any changes to @wdio/cli, but instead changing the generated project to use ESM
> 
> That would be the ideal solution but many folks still run on CJS even though using a lot of mixed ESM primitives. Ideally I would like WebdriverIO to support TypeScript with CJS.

OK, let's keep thinking then :)

**Comment by christian-bromann** [comment]
> Could you share your demo project? I'm putting together a repro now.

See https://github.com/zac11/wdio-work-demo

**Comment by jan-molak** [comment]
I have a repro, give me a sec to clean it up

**Comment by jan-molak** [comment]
OK, so here's a minimal example we can use for testing:
https://github.com/zac11/wdio-work-demo/pull/2/files

Here are my results using `@wdio/cli`: `^8.14.4` from @zac11's demo

## Test 1: Using original `wdio-work-demo`

```typescript
// node_modules/@wdio/cli/build/commands/run.js:164
NODE_OPTIONS += ' --loader ts-node/esm/transpile-only --no-warnings';
```

| Node    | Result |
| ------- | ------ |
| 16.20.0 | ✅ PASS   |
| 18.16.0 | ✅ PASS   |
| 20.6.1  | 🚨 **SyntaxError: Cannot use import statement outside a module**   |

## Test 2: Local patch

I modified `@wdio/cli/build/commands/run.js` in the demo to apply the patch from #11173

```diff
// node_modules/@wdio/cli/build/commands/run.js:164
- NODE_OPTIONS += ' --loader ts-node/esm/transpile-only --no-warnings';
+ NODE_OPTIONS += ' --loader ts-node/esm/transpile-only -r ts-node/register --no-warnings'
```

| Node    | Result |
| ------- | ------ |
| 16.20.0 | 🚨 **FAIL: Incorrect line locations in source maps** |
| 18.16.0 | 🚨 **FAIL: Incorrect line locations in source maps** |
| 20.6.1  | ✅ PASS   |

### Node 18 output
```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 117.0.5938.62 mac os x #0-0] Running: chrome (v117.0.5938.62) on mac os x
[chrome 117.0.5938.62 mac os x #0-0] Session ID: 565be0638decbece2f4e9fc4f5917925
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] » /test/specs/source-maps.e2e.ts
[chrome 117.0.5938.62 mac os x #0-0] Source maps support
[chrome 117.0.5938.62 mac os x #0-0]    ✖ should detect line number correctly
[chrome 117.0.5938.62 mac os x #0-0]    ✖ should detect instantiation location of a Serenity/JS interaction
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] 2 failing (67ms)
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] 1) Source maps support should detect line number correctly
[chrome 117.0.5938.62 mac os x #0-0] expect(received).toEqual(expected) // deep equality

- Expected  - 4
+ Received  + 4

  Array [
-   "source-maps.e2e.ts:39:19",
-   "source-maps.e2e.ts:35:12",
-   "source-maps.e2e.ts:31:12",
-   "source-maps.e2e.ts:5:40",
+   "source-maps.e2e.ts:31:19",
+   "source-maps.e2e.ts:28:12",
+   "source-maps.e2e.ts:25:12",
+   "source-maps.e2e.ts:6:38",
  ]
[chrome 117.0.5938.62 mac os x #0-0] Error: expect(received).toEqual(expected) // deep equality
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] - Expected  - 4
[chrome 117.0.5938.62 mac os x #0-0] + Received  + 4
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0]   Array [
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:39:19",
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:35:12",
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:31:12",
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:5:40",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:31:19",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:28:12",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:25:12",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:6:38",
[chrome 117.0.5938.62 mac os x #0-0]   ]
[chrome 117.0.5938.62 mac os x #0-0]     at Context.<anonymous> (/Users/jan/Projects/jan-molak/wdio-work-demo/test/specs/source-maps.e2e.ts:10:27)
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] 2) Source maps support should detect instantiation location of a Serenity/JS interaction
[chrome 117.0.5938.62 mac os x #0-0] expect(received).toEqual(expected) // deep equality

Expected: 22
Received: 18
[chrome 117.0.5938.62 mac os x #0-0] Error: expect(received).toEqual(expected) // deep equality
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] Expected: 22
[chrome 117.0.5938.62 mac os x #0-0] Received: 18
[chrome 117.0.5938.62 mac os x #0-0]     at Context.<anonymous> (/Users/jan/Projects/jan-molak/wdio-work-demo/test/specs/source-maps.e2e.ts:20:31)
------------------------------------------------------------------
[chrome 117.0.5938.62 mac os x #0-1] Running: chrome (v117.0.5938.62) on mac os x
[chrome 117.0.5938.62 mac os x #0-1] Session ID: 8ad04d6691b3005d3c6c906db4ba9092
[chrome 117.0.5938.62 mac os x #0-1]
[chrome 117.0.5938.62 mac os x #0-1] » /test/specs/test.e2e.ts
[chrome 117.0.5938.62 mac os x #0-1] My Login application
[chrome 117.0.5938.62 mac os x #0-1]    ✓ should login with valid credentials
[chrome 117.0.5938.62 mac os x #0-1]
[chrome 117.0.5938.62 mac os x #0-1] 1 passing (1.5s)

```

### Node 16 output
```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 117.0.5938.62 mac os x #0-0] Running: chrome (v117.0.5938.62) on mac os x
[chrome 117.0.5938.62 mac os x #0-0] Session ID: dd8122606c4ce499e5dd2e95a59dc267
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] » /test/specs/source-maps.e2e.ts
[chrome 117.0.5938.62 mac os x #0-0] Source maps support
[chrome 117.0.5938.62 mac os x #0-0]    ✖ should detect line number correctly
[chrome 117.0.5938.62 mac os x #0-0]    ✖ should detect instantiation location of a Serenity/JS interaction
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] 2 failing (70ms)
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] 1) Source maps support should detect line number correctly
[chrome 117.0.5938.62 mac os x #0-0] expect(received).toEqual(expected) // deep equality

- Expected  - 4
+ Received  + 4

  Array [
-   "source-maps.e2e.ts:39:19",
-   "source-maps.e2e.ts:35:12",
-   "source-maps.e2e.ts:31:12",
-   "source-maps.e2e.ts:5:40",
+   "source-maps.e2e.ts:31:19",
+   "source-maps.e2e.ts:28:12",
+   "source-maps.e2e.ts:25:12",
+   "source-maps.e2e.ts:6:38",
  ]
[chrome 117.0.5938.62 mac os x #0-0] Error: expect(received).toEqual(expected) // deep equality
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] - Expected  - 4
[chrome 117.0.5938.62 mac os x #0-0] + Received  + 4
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0]   Array [
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:39:19",
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:35:12",
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:31:12",
[chrome 117.0.5938.62 mac os x #0-0] -   "source-maps.e2e.ts:5:40",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:31:19",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:28:12",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:25:12",
[chrome 117.0.5938.62 mac os x #0-0] +   "source-maps.e2e.ts:6:38",
[chrome 117.0.5938.62 mac os x #0-0]   ]
[chrome 117.0.5938.62 mac os x #0-0]     at Context.<anonymous> (/Users/jan/Projects/jan-molak/wdio-work-demo/test/specs/source-maps.e2e.ts:10:27)
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] 2) Source maps support should detect instantiation location of a Serenity/JS interaction
[chrome 117.0.5938.62 mac os x #0-0] expect(received).toEqual(expected) // deep equality

Expected: 22
Received: 18
[chrome 117.0.5938.62 mac os x #0-0] Error: expect(received).toEqual(expected) // deep equality
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] Expected: 22
[chrome 117.0.5938.62 mac os x #0-0] Received: 18
[chrome 117.0.5938.62 mac os x #0-0]     at Context.<anonymous> (/Users/jan/Projects/jan-molak/wdio-work-demo/test/specs/source-maps.e2e.ts:20:31)
------------------------------------------------------------------
[chrome 117.0.5938.62 mac os x #0-1] Running: chrome (v117.0.5938.62) on mac os x
[chrome 117.0.5938.62 mac os x #0-1] Session ID: 7f74068f8a8d40747c3ed6c98a00cde9
[chrome 117.0.5938.62 mac os x #0-1]
[chrome 117.0.5938.62 mac os x #0-1] » /test/specs/test.e2e.ts
[chrome 117.0.5938.62 mac os x #0-1] My Login application
[chrome 117.0.5938.62 mac os x #0-1]    ✓ should login with valid credentials
[chrome 117.0.5938.62 mac os x #0-1]
[chrome 117.0.5938.62 mac os x #0-1] 1 passing (2.4s)

```

**Comment by jan-molak** [comment]
There's an interesting thread on TS-Node about a similar issue with source maps - https://github.com/TypeStrong/ts-node/issues/2006

**Comment by jan-molak** [comment]
@christian-bromann - I wonder if it makes sense to vary NODE_OPTIONS based on the major version of Node.js people use? I.e. apply your latest patch only on Node 20 but not on the previous major versions 🤔

**Comment by christian-bromann** [comment]
Closing in favor of #11173 .. thanks for all the work on this @jan-molak

**Pull request closed without merging**
