### PR TITLE
chore(comments): Use 1-star for non-JSdoc comments

### PR DESCRIPTION
**Pull request by Zearin**
## Proposed changes

Use of 2-stars at the beginning of comment blocks (i.e. `/**…`) is supposed to mark these comments as different from normal 1-star block comments.

Several comments that were clearly not intended to be used for documentation had 2 stars.  This Pull Request fixes that.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

This is part of a redo of Issue #4597.  If this is accepted, I plan to continue the work in a series of more Pull Requests.  (Next, I hope to add `eslint-plugin-jsdoc` and do some cleanup to the existing JSDoc comments.  After that, I can add JSDocs to undocumented public functions, classes, and methods.)

### CODE REVIEW

**Comment by Zearin** [comment]
I’ll be looking into ESLint rules in my next Pull Request.

**Comment by christian-bromann** [comment]
> I’ll be looking into ESLint rules in my next Pull Request.

Would you mind including the EsLint change here? I think if we change this across the whole code base we should ensure that it can't be changed again. It also is a good exercise to see if we have caught all appearances.

**Comment by Zearin** [comment]
> Would you mind including the EsLint change here? I think if we change this across the whole code base we should ensure that it can't be changed again. It also is a good exercise to see if we have caught all appearances.

Well, there are _a lot_ of lint rules to choose from.  I’ll need to know which rules you think are appropriate for your project.

Also, there is no way for any linter to “make sure that non-JSDoc comments are 1-star”.  All the linter can do is scan for 2-star comments, and then lint them according to the rules provided.  

If you want me to add some initial ESLint stuff in this Pull Request, I’ll need to know:

- **What sorts of rules do you want?**  
  (See https://github.com/gajus/eslint-plugin-jsdoc for the full list.)

- **In which file(s) should I specify rule(s)?**
  (There is `/.eslintrc.js` at project root, but also `packages/eslint-plugin-wdio`, with a README that says it’s supposed to be the ESLint config for all WDIO projects. I’m not sure how you decide to put config in one location or another.)

**Comment by christian-bromann** [comment]
> Also, there is no way for any linter to “make sure that non-JSDoc comments are 1-star”.

How do we make sure that we don't break this convention? Even if we pay attention during code reviews it will slip through.

> * In which file(s) should I specify rule(s)?

It would be in `/.eslintrc.js`.

**Comment by Zearin** [comment]
> How do we make sure that we don't break this convention? Even if we pay attention during code reviews it will slip through.

Well…now that I think about it, while there is no way to tell ESLint…

 “If this comment is not for JSDoc make it 1-star!”

…I suppose that it should be enough to specify enough rules to say,

“If this comment is 2-star, it had better be valid JSDoc.”

Will that work for you?

**Comment by christian-bromann** [comment]
> Will that work for you?

Yes. Is there anything left in this PR?

**Comment by Zearin** [comment]
> Yes. Is there anything left in this PR?

Yes.  When I add the rules, there are **A LOT** of edits required to the comments, or the tests fail.  

I’ve been working on it.  Lots done, but lots to go.

**Comment by christian-bromann** [comment]
Please remove the label if this is ready to be reviewed.

**Comment by Zearin** [comment]
> Please remove the label if this is ready to be reviewed.

Will do.

In the meantime, can you explain [this `@uses` tag](https://github.com/webdriverio/webdriverio/blob/03a572e9a05f0aa6632c89686c6eca65182bc7e6/packages/webdriverio/src/commands/browser/deleteCookies.js#L40) to me?

* Is this tag used in the generated documentation?
* I know this references a command from the vanilla WebDriver protocol, but I cannot seem to find it.  Does this reference a line of code?

**Comment by christian-bromann** [comment]
> In the meantime, can you explain [this `@uses` tag](https://github.com/webdriverio/webdriverio/blob/03a572e9a05f0aa6632c89686c6eca65182bc7e6/packages/webdriverio/src/commands/browser/deleteCookies.js#L40) to me?

I was used in the v4 docs but not in v5 anymore.

**Comment by Zearin** [comment]
(Awesome!  Only 2 JSDoc lint rules have violations now.)  

Can you help explain another curiosity to me?  Use of the `@type` tag seems to be at odds with how JSDoc describes it should be used.  [Here’s one example](https://github.com/webdriverio/webdriverio/blob/03a572e9a05f0aa6632c89686c6eca65182bc7e6/packages/wdio-repl/src/index.js#L29).

Are you still using `@type` in this manner?  (Or is it leftovers from an old version?)

**Comment by christian-bromann** [comment]
> Are you still using `@type` in this manner?

We also don't use `@type` anymore. It is a relict from v4. I think it would be great to put commands in sub-categories like browser > utilities > debug. Is it possible to keep it?

**Comment by Zearin** [comment]
> We also don't use `@type` anymore. It is a relict from v4. I think it would be great to put commands in sub-categories like browser > utilities > debug. Is it possible to keep it?

Oh, I’m all for categorizing commands like that. I just think it should not be done using JSDoc tags that have a totally different documented purpose. If you agree, I’ll see if I come up with an alternative tag to do that job.

Do you agree?

**Comment by christian-bromann** [comment]
> Do you agree?

How would we then categorize commands without maintaining an extra document for it? Is there a JSDoc tag that we could use for that?

**Comment by christian-bromann** [comment]
ping @Zearin

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to reopen if there is still interest in this.

**Pull request closed without merging**
