### PR TITLE
Fixes for module mocking

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

Some issues I discovered while applying the new mocking capabilities to projects. To summarise:

- adds ability to mock pre bundled vite deps (e.g. `/node_modules/.vite/deps/algoliasearch_lite.js?v=e31c24e`)
- implements #9850 (wip)
- properly export `@wdio/browser-runner` types for `mock` method (wip)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by nextlevelbeard** [comment]
I'm seeing an improvements in being able to use prebundled vite deps but I'm facing an error with these (functional) changes:
```
 Error:  Test failed due to following error(s):
  - spy.js: Uncaught Error: [wdio] There was an error, when mocking a module. If you are using the "mock" factory, make sure there are no top level variables inside, since this call is hoisted to top of the file. Read more: https://webdriver.io/docs/component-testing/mocking
TypeError: Failed to fetch dynamically imported module: http://localhost:54674/node_modules/.vite/deps/@myscope/depToMock.js?import
TypeError: Failed to fetch dynamically imported module: http://localhost:54674/node_modules/.vite/deps/@myscope/depToMock.js?import
    at mock (http://localhost:54674/node_modules/@wdio/browser-runner/build/browser/spy.js:38:15)
    at http://localhost:54674/Users/user/repos/myrepo/src/components/my.test.jsx?import:3:1
```


```ts
mock('@myscope/depToMock, async (origModuleFactory) => {

  // Causes the error, but I need the originalModule
  const originalModule = await origModuleFactory()

  // console.log()
  return {
    __esModule: true,
    ...originalModule,
    functionToMock: fn(),
  }
})
```

**Comment by christian-bromann** [comment]
Does `@myscope/depToMock` actually exist?

**Comment by nextlevelbeard** [comment]
> Does `@myscope/depToMock` actually exist?

It does.
[Here](https://github.com/nextlevelbeard/wdio-mock-repro) is a repro project @christian-bromann

**Comment by christian-bromann** [comment]
Yeah, you are right, I ran into this as well and forgot to add it. Will push another fix for it.

**Comment by christian-bromann** [comment]
> [Here](https://github.com/nextlevelbeard/wdio-mock-repro) is a repro project @christian-bromann

This should be fixed with `v8.5.0`, at least I can run the test without issues.

> it errors because there is no `__mocks__` folder created at the root of the project.

Fixed in #9864

Let me know if you see other strange things.

**Comment by nextlevelbeard** [comment]
> This should be fixed with `v8.5.0`, at least I can run the test without issues.

Sorry I forgot to uncomment the lines that make it import the original module and crash.
I also update to the versions 8.5.1 and 8.5.2.
Could you try now? @christian-bromann

**Pull request merged**
