### PR TITLE
Fix for issue #513: Need support for positional CSS selectors (:first-child, :first-of-type, :nth-child etc)

### PR DESCRIPTION
**Pull request by vdineva**
Updated the regular expression for find element strategy

### CODE REVIEW

**Comment by christian-bromann** [comment]
@vdineva thanks for your contribution.

Looking at your changes makes me feel that you've forgot to push something. The [changes](https://github.com/webdriverio/webdriverio/pull/514/files#diff-f3e68f1ab6fc51142d872b0b32cb899dR23) you made only apply for selectors with an `#` at the beginning. Did you touch any other selector regex without pushing them?

**Comment by vdineva** [comment]
@christian-bromann Yes, I've only updated the regex for selectors that starts with `#`. I noticed that actually most of the time positional selectors work just fine and after some testing I noticed the pattern. Currently a positional element such as `:first-child` fails only after being used after a selector for id. All other cases (positional css selector after an html element e.g. `body :first-child`, or after a class name e.g.`.someClass :first-child`, or on it's own `nth-child(1)`) work fine as they fall though all the `else if` statements and end up at the final `else`, so basically using 'css selector' strategy which later on calls `document.querySelectorAll()`. So basically the only update needed was the regex for selectors with an # at the beginning.

**Comment by christian-bromann** [comment]
@vdineva gotcha! However I don't think it make sense to "fix" that as it wouldn't be an invalid selector since there should only be one single id per element. Therefor something like `#myId:first-Child` isn't valid as there should only be one element with that id.

Is there an use case I've forgot?

**Comment by vdineva** [comment]
@christian-bromann : I might have created some confusion, for which I apologize.

As per Mozilla Developer Network (https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child) : "The :first-child CSS pseudo-class represents any element that is the first child element of its parent."
So `#myId:first-Child` is a valid css selector which will return 
1. either the element (if it's a first child of it's parent element)
```html
<div>
    <div id="myId"></div>
</div>
```
OR
2. null, if #myId is not the first child of it's parent element
```html
<div>
    <div class="box black"></div>
    <div id="myId"></div>
</div>
```

**Comment by christian-bromann** [comment]
@vdineva your right but querying elements using an `id` will always return one element as there is only one element allowed on the page using that id. Meaning: `#myId:first-Child` is unnecessary as `#myId` will do the same trick. Does that make sense? The use of pseudo selectors on elements with an id as prefix doesn't make any sense ;-)

**Comment by christian-bromann** [comment]
With classes it is different. There could be one class applied to multiple elements. The use of pseudo selector to fetch the first/last or nth child makes sense as it makes the query more specific

**Comment by christian-bromann** [comment]
ping @vdineva

**Comment by vdineva** [comment]
@christian-bromann I don't quite agree here. Given the following html snippet, in plain vanilla javasctipt
`document.querySelector('#myId:first-child')` will return the element as it is a first child of it's parent element. (note the `:first-child` selector returns an element that is the first child of its parent )
```html
<div>
    <div id="myId"></div>
</div>
```
With the following html plain javasctipt `document.querySelector('#myId:first-child')` returns `null` as the element with id `myId` is not the first child of its parent
```html
<div>
    <div class="box black"></div>
    <div id="myId"></div>
</div>
```
And since under the hood WebdriverIO uses the javascript API I thought it should mimic it's behavior as closely to it as possible.

I came up with a workaround for my project and am closing this pull request for now.

**Comment by christian-bromann** [comment]
Ahh I see. Well if someone queries `#myId:first-child` he should expect to get an element with an id `#myId` no matter if it is the first or last child as there is only _one_ single element with that id on the page.  WebdriverIO relies on Selenium when it comes to query elements on the page.

Still, thanks for contributing to the project!

**Pull request closed without merging**
