### PR TITLE
(wdio-config): check existence of ts-node/esm/transpile-only.mjs & fix a type issue

### PR DESCRIPTION
**Pull request by johnp**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Fixes two issues behind https://github.com/webdriverio/webdriverio/issues/12434. The first fix is to check for the existence of the `ts-node/esm/transpile-only.mjs` loader before trying to use it, as it does not exist in ts-node versions <9 (in our case pulled in by a transitive dependency). The 2nd fix is a type issue with the argument `autoCompileConfig.autoCompile=false` which ends up as the string `"false"`. I added a conversion step to take care of this. Note that this CLI argument is already documented in `wdio --help`.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

- [x] Back-ported PR at [`#12437`](https://github.com/webdriverio/webdriverio/pull/12437)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

### CODE REVIEW

**Comment by erwinheitzman** [comment]
Hi @johnp currently the access is checked but nothing is done with the result which doesn't seem right.

Usually you see something like:
```js
try {
  await access('path')
} catch (error) {
  // do something
}
```

Regarding the autocompileopts, I am planning to remove it and instead recommend use of the environment variables as shown in our docs here: https://webdriver.io/docs/typescript as this is how ts-node expects things to be used. It also prevents us from adding magic/logic that doesn't have to be maintained and isn't needed.

**Comment by christian-bromann** [comment]
I just want to point out that we have https://github.com/webdriverio/webdriverio/issues/11878 planned for v9. I wonder if this might help us resolve some of these issues.

**Comment by erwinheitzman** [comment]
@johnp I tried reproducing this with a new project and using that it works fine. I am currently unsure what the difference is but I think the problem lies in the setup/configuration still

**Comment by erwinheitzman** [comment]
Can you explain why you need this when you can set `autoCompile` to `false` in your config?

**Comment by erwinheitzman** [comment]
@johnp good points. looks good to me. what do you think @christian-bromann ? What I do think is that perhaps we should merge this only to v8

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Let's move forward and merge this for v9 too in case we decide not to migrate to `tsx`.

Thanks @johnp

**Pull request merged**
