### PR TITLE
fix for https://github.com/webdriverio/webdriverio/issues/8335

### PR DESCRIPTION
**Pull request by mighty98**
## Proposed changes

[//]: # Commented out onComplete hook in @wdio/shared-store-service launcher

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

<a href="https://gitpod.io/#https://github.com/webdriverio/webdriverio/pull/8349"></a>

### CODE REVIEW

**Comment by christian-bromann** [comment]
I suggest to remove it rather than commenting it out.

**Comment by mighty98** [comment]
> I suggest to remove it rather than commenting it out.

@christian-bromann  Will do. 
Also, for the test, should i remove it or do you prefer .not.toBeCalled ? as a test

**Comment by christian-bromann** [comment]
> Also, for the test, should i remove it or do you prefer .not.toBeCalled ? as a test

Let's just remove it.

**Comment by mighty98** [comment]
> > Also, for the test, should i remove it or do you prefer .not.toBeCalled ? as a test
> 
> Let's just remove it.

@christian-bromann Thanks for the review. I have made changes as suggested

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by mighty98** [comment]
@christian-bromann Just curious.. When can i expect this to be merged??

**Comment by mighty98** [comment]
@christian-bromann  I see the test failures in other PR's too. I am not very sure if i can help but if there is something i can do to help fastrack this please let me know

**Comment by christian-bromann** [comment]
> I am not very sure if i can help but if there is something i can do to help fastrack this please let me know

I will have to fix this in `main` and will go ahead with this one.

**Pull request merged**
