### PR TITLE
Workaround for chromedriver domain name change

### PR DESCRIPTION
**Pull request by paymand**
## Proposed changes

Workaround for chromedriver domain name change.
Fixes https://github.com/webdriverio/webdriverio/issues/12251 for v8.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Thanks a lot 👍

**Comment by Abel0916** [comment]
Thanks for the quick fixing. It looks like there is no new V8 version published to include this fixing. @christian-bromann Will you publish a new version? Thanks.

**Comment by christian-bromann** [comment]
Yes, eventually later today or tomorrow latest.

**Comment by SinghMegha27** [comment]
Is this a workaround for this error error Downloading Chromedriver v121.0.6167.185
2024-02-18T14:50:45.738Z WARN webdriver: Chromedriver v121.0.6167.185 don't exist, trying to find known good version.. ?

**Comment by christian-bromann** [comment]
@SinghMegha27 this is related to a different issue which WebdriverIO has an internal workaround for, it should still be able to find the right version for you.

**Pull request merged**
