### PR TITLE
Export DataTable from @cucumber/cucumber

### PR DESCRIPTION
**Pull request by kaksjonovs**
## Proposed changes
Export `DataTable` from `@cucumber/cucumber`. 

Changes to avoid 2 imports from `@wdio/cucumber` and  `@cucumber/cucumber` for steps.

Example:
```
import { Given, When, Then, DataTable } from '@wdio/cucumber-framework';
import { DataTable } from '@cucumber/cucumber';

When("I login with:", async (dataTable: DataTable) => {
    dataTable.rows();
});
```

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
@kaksjonovs mind approving the CLA?

**Comment by christian-bromann** [comment]
> [@linux-foundation-easycla ](/apps/linux-foundation-easycla) ** EasyCLA ** — Missing CLA Authorization.

It seems you didn't signed. Make sure the commit email is the same as the email you've used to sign the CLA.

**Comment by kaksjonovs** [comment]
Now it's done. Sorry once again.

**Comment by kaksjonovs** [comment]
@christian-bromann Should something be done from my side to resolve failing pipelines/tests?
Seems like not related at all to my changes.

**Comment by christian-bromann** [comment]
@kaksjonovs please rebase on top of current `main`. The branch should be green again.

**Comment by christian-bromann** [comment]
@kaksjonovs I went ahead and merged the PR. Thanks for the contribution.

**Pull request closed without merging**
