### PR TITLE
[#4949] WIP: feat: batch specs per suite

### PR DESCRIPTION
**Pull request by joscha**
This is a fix for #4949; it uses batching for the spec files, which mean it is possible to run more than one spec file in each test run.
Unfortunately the reporters expect a fixed 1 spec per test run, so reporting is broken.

### CODE REVIEW

**Comment by joscha** [comment]
> The new option also needs to be added to [/docs/Options.md@`master`#wdio-options](https://github.com/webdriverio/webdriverio/blob/master/docs/Options.md#wdio-options)

will do, do you have any hints on how to best fix the reporting?

**Comment by christian-bromann** [comment]
@joscha what is the status of this? Anything we can do to help you land this?

**Comment by joscha** [comment]
Hey Christian,

Basically there are two ways to fix this:

* Run more than one spec per child process up to a number of Infinity specs in a child process, effectively allowing the user to decide what the optimum is between time spent transpiling and time spent in sequential spec runs
* Reusing workers and runners between runs, allowing to have a pool of runners that have a transpiled version of the code ready to run.

I tried both approaches and I think the first one is more manageable. The fix in the WIP pull request is doing the first approach and whilst it works perfectly for the runs itself the reporting is broken (and if I understand the did right most likely also some of the rerun logic as it is suite-based, not spec-based at the moment). Initially I thought it was just the spec reporter that was funky but looking at the code it seems like it was never intended to run more than one spec in a worker/runner sub process, hence the callbacks are all incorrect (they count up and down by one for the most part). I currently don't see a good way to split this refactor and I think some of the logic around it is also not covered by tests, yet.
Any recommendations around which part to tackle first or a general approach on how to make the callbacks spec-aware would be welcome!

Cheers,
Joscha

**Comment by joscha** [comment]
@christian-bromann any chance we can iterate on this together, especially after seeing https://www.linkedin.com/posts/christian-bromann-01a91244_sauce-labs-deepens-investment-in-oss-community-activity-6638889939675164674-aX4r :)

**Comment by christian-bromann** [comment]
> any chance we can iterate on this together

Sure thing. I was on PTO last week and will try to have a look this week.

**Comment by joscha** [comment]
That would be great! Happy to jump on a zoom, Skype, Hangout, chat,
email-chain, Tik took ;) any time!

**Comment by christian-bromann** [comment]
How about instead of adding a config `maxSpecsPerSuite` we allow the user more control as to which spec files are run in a single process. So instead of:

```js
// wdio.conf.js
specs: [
	"test1.js",
	"test2.js",
	"test3.js"
]
```

Where all spec files are being run in parallel, a user could define specs as `string | string[]`, e.g.:

```js
// wdio.conf.js
specs: [
	["test1.js", "test2.js", "test3.js"],
    ["test4.js"]
]
```

Here, test1 and test4 would start at the same time but after test1 it would start test2 and test3 sequentially in the same process.

**Comment by joscha** [comment]
Re: string[] | string for specs definition: absolutely that would work as well if that is easier to implement.

**Comment by joscha** [comment]
@christian-bromann was your suggestion in https://github.com/webdriverio/webdriverio/pull/4974#issuecomment-609704220 something that is implemented or planned currently?

**Comment by christian-bromann** [comment]
> was your suggestion in [#4974 (comment)](https://github.com/webdriverio/webdriverio/pull/4974#issuecomment-609704220) something that is implemented or planned currently?

@joscha it is not implemented yet and I think it makes the most sense to specify multiple test suites per worker.

**Comment by joscha** [comment]
Okay. If I implemented your sample API, would you be able to help with the
reporting?

Cheers,
Joscha

**Comment by christian-bromann** [comment]
> Okay. If I implemented your sample API, would you be able to help with the reporting?

Yes!

**Comment by christian-bromann** [comment]
@joscha any updates on this?

**Comment by joscha** [comment]
Hi Christian,

Yes, we planned the change for the next development cycle. Once we
implemented your API we'll need help fixing the reporting.

**Comment by abubakarafzal** [comment]
Is this functionality implemented?

**Comment by joscha** [comment]
it is not (yet) unfortuantely @abubakarafzal

**Comment by azinchenko91** [comment]
@josha Do you have any updates about this request?

**Comment by joscha** [comment]
No, no good news, sorry, we're currently actually discussing abandoning
wdio altogether because of it.

**Comment by christian-bromann** [comment]
We will tackle this effort in a separate issue #6469

**Pull request closed without merging**
