### PR TITLE
Add ability to navigate by relative urls without pathname parts

### PR DESCRIPTION
**Pull request by tormozz48**
## Types of changes

What types of changes does your code introduce to WebdriverIO?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tormozz48** [comment]
> Can you please explain a bit further what this change does?

We have a cases when:

* `baseUrl` has protocol, host, and pathnane for example: `http://localhost/search`
* `url` has only query part and starts with `?` for example: `?foo=bar&...`

Also sometimes it is not possible or very difficult to modify `url` from our side. 😢 

> Also can you add a test for it?

Yes I can. Please explain how can I get or modify baseUrl [here](https://github.com/webdriverio/webdriverio/blob/master/test/spec/functional/baseUrl.js) ? It will be helpful for me

**Comment by tormozz48** [comment]
@christian-bromann update

**Comment by christian-bromann** [comment]
@tormozz48 thanks! There are some eslint errors. Could you please fix them?

**Comment by tormozz48** [comment]
@christian-bromann fix up

**Comment by tormozz48** [comment]
@christian-bromann Thank you for accepting my pr. When are you planning to release a new version of webdriverio ?

**Comment by christian-bromann** [comment]
this week

**Pull request merged**
