### PR TITLE
V3.4.2 fix exclude openissue

### PR DESCRIPTION
**Pull request by mcaruso85**
## Proposed changes

This is a fix for the issue: https://github.com/webdriverio/webdriverio/issues/1067#issuecomment-210621665
The issue is present in the version 3.4.1. So, this change is a branch from tag v3.4.1, and a new tag 3.4.2 should be created. 
This is useful for developers who are still using v3.
Tests were added and can be executed with: npm run-script test-unit

P.S: In order to create a pull request I couldn't select the tag v3.4.1 as the base. GitHub does not let me use a tag, and I couldn't find a branch for v3.4.1. So, i had to use a the master as the base. 

## Types of changes

What types of changes does your code introduce to WebdriverIO?
_Put an `x` in the boxes that apply_

- [X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by christian-bromann** [comment]
Can you point me to a specific commit?

**Comment by mcaruso85** [comment]
Christian, 

628a53c43d49c00ef7f62d71b91109fc4bc4e348 FIX #1067: Exclude tests per browser not working => My last commit

**Comment by mcaruso85** [comment]
Let me clarify a little bit more: 
The important commits are:
628a53c43d49c00ef7f62d71b91109fc4bc4e348 FIX #1067: Exclude tests per browser not working
420aa87ad4199d562f0c8ac409bc16bb0ca897cf FIX #1067: Exclude tests per browser not working

The others next two was a mistake, the first one is the mistake and the next one is the revert
f15f2d982e9d37fb017be697c67964c03c1d72f6 Revert "FIX #1067: Exclude tests per browser not working"
8bc8d7f24be0d6b0ae8d98e31cf2960cf24c6894 FIX #1067: Exclude tests per browser not working

**Comment by christian-bromann** [comment]
@mcaruso85 could you please squash them into one commit so I can cherry-pick it?

**Comment by mcaruso85** [comment]
HI Chris, 

Do you still need the fix for the v3.4.1? I can see that you are closing the issue.  The issue is fixed in v4.  

Let me know, if you want I can put all into one commit as you requested.

**Comment by christian-bromann** [comment]
I really would rather spend time in improving v4 instead of fixing old bugs in v3. So if it is not that important for you I would leave it as is

**Comment by mcaruso85** [comment]
No Chris, is not a problem at all. You can close the pull request. I've just created the fix in case it is needed.

**Comment by mcaruso85** [comment]
I've closed it. ;)

**Pull request closed without merging**
