### PR TITLE
docs(mock): 'matches' -> 'calls' property

### PR DESCRIPTION
**Pull request by KuznetsovRoman**
## Proposed changes

Change `Mock` interface in [docs](https://webdriver.io/docs/api/mock#properties)  (use `calls` property instead of `matches`)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks for raising the PR.

I think this is an issue with the docs. The user is suppose to use `calls` to receive these information. `matches` is more an internal object for this.

**Comment by KuznetsovRoman** [comment]
> Thanks for raising the PR.
> 
> I think this is an issue with the docs. The user is suppose to use `calls` to receive these information. `matches` is more an internal object for this.

Ok, i will update the docs in this PR. Also, about mocks: i need an ability to check if mock (spy) has some pending requests. Will you approve a feature, which emits something like `onRequest`, `onResponse` on request and response accordingly?

**Comment by christian-bromann** [comment]
> Will you approve a feature, which emits something like `onRequest`, `onResponse` on request and response accordingly?

Seems like a reasonable feature request. Yeah totally!

> (i see how it can be done with `devtools` mock, but not with `webdriver` one)

For WebDriver we will have to use the new WebDriver Bidi features which have not landed yet. While you can already get request information, it is not yet possible to mock/replace requests and responses.

**Comment by KuznetsovRoman** [comment]
Also, do you mind if i add documentation about `WDIO_LOG_LEVEL` environment variable? It looks like a part of public api (because [here](https://github.com/webdriverio/webdriverio/blob/62e24d4dd9d58f3b4168866189d60e7e8da09a9b/packages/wdio-logger/src/node.ts#L162-L164) it assumes, it can be set from the outside) but is not being documented. I want to use this env variable in my code (i already asked about this in gitter, but didn't got the answer to my question), but i'm scared of using undocumented variables

**Comment by christian-bromann** [comment]
> Also, do you mind if i add documentation about `WDIO_LOG_LEVEL` environment variable?

Good call, let's add it to https://webdriver.io/docs/api/environment

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Pull request merged**
