### PR TITLE
fix(webdriverio): reconnect to bidi on reloadSession

### LINKED ISSUE #13789: [🐛 Bug]: Timeout error with reloadSession API
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      args: [
        '--disable-backgrounding-occluded-windows',
        '--window-size=1980,1080',
        '--lang=fr_FR.UTF-8',
        '--disable-search-engine-choice-screen',
      ],
    },
  },

Grid with Selenium-server-4.25.0
```

### What happened?

If reload session is used, the test breaks with a timeout error.

### What is your expected behavior?

_No response_

### How to reproduce the bug.

```
  await browser.reloadSession();
  await browser.url(
    'https://webdriver.io/blog/2024/08/15/webdriverio-v9-release'
  );
  await $('[href="/blog"]').waitForDisplayed();
```

### Relevant log output

```typescript
[0-0] 2024-10-22T13:55:30.142Z INFO webdriver: COMMAND deleteSession(<object>)
[0-0] 2024-10-22T13:55:30.143Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/bff0845355593ed7b100644eaccc694f
[0-0] 2024-10-22T13:55:30.143Z INFO webdriver: DATA { deleteSessionOpts: { shutdownDriver: false } }
[0-0] 2024-10-22T13:55:30.809Z INFO webdriver: RESULT null
[0-0] 2024-10-22T13:55:30.812Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2024-10-22T13:55:30.812Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-10-22T13:55:33.211Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"CE6C5F1343C782BBC3DED3A225FE0C50","url":"https://webdriver.io/blog/2024/08/15/webdriverio-v9-release","wait":"complete"}
[0-0] 2024-10-22T13:56:33.257Z INFO webdriver: COMMAND getUrl()
[0-0] 2024-10-22T13:56:33.258Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/cdbf45f49986aea09d6a6f435e50e69d/url
[0-0] 2024-10-22T13:56:33.278Z INFO webdriver: RESULT about:blank
[0-0] Error: Command browsingContext.navigate with id 9 (with the following parameter: {"context":"CE6C5F1343C782BBC3DED3A225FE0C50","url":"https://webdriver.io/blog/2024/08/15/webdriverio-v9-release","wait":"complete"}) timed out
    at Timeout._onTimeout (C:\2-gitlab\end-to-end-tests-wdio\node_modules\webdriver\build\index.js:246:16)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```
Selenium grid errors
```
 Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-backgrounding-occ..., --window-size=1980,1080, --lang=fr_FR.UTF-8, --disable-search-engine-cho...], prefs: {}}, webSocketUrl: true}]
10:11:50.268 INFO [LocalNode.newSession] - Session created by the Node. Id: e65e05edb82b40d7ed9cc92839a42efd, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:14852/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:11:50.277 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: e65e05edb82b40d7ed9cc92839a42efd
 Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:14852/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:11:50.334 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://localhost:14852/session/e65e05edb82b40d7ed9cc92839a42efd
10:12:00.244 INFO [LocalSessionMap.remove] - Deleted session from local Session Map, Id: e65e05edb82b40d7ed9cc92839a42efd
10:12:00.247 INFO [GridModel.release] - Releasing slot for session id e65e05edb82b40d7ed9cc92839a42efd
10:12:00.253 INFO [SessionSlot.stop] - Stopping session e65e05edb82b40d7ed9cc92839a42efd
10:12:00.282 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-backgrounding-occ..., --window-size=1980,1080, --lang=fr_FR.UTF-8, --disable-search-engine-cho...], prefs: {}}, webSocketUrl: true}]
10:12:02.484 INFO [LocalNode.newSession] - Session created by the Node. Id: 86f60d538758d2e1472e2934bd45bb25, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62469}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:32182/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:12:02.490 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 86f60d538758d2e1472e2934bd45bb25
 Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62469}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:32182/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:12:02.500 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
org.openqa.selenium.WebDriverException: java.io.IOException: Output closed
Build info: version: '4.25.0', revision: '030fcf7918'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:320)
        at org.openqa.selenium.grid.node.ProxyNodeWebsockets.lambda$createWsEndPoint$6(ProxyNodeWebsockets.java:237)
        at org.openqa.selenium.netty.server.WebSocketMessageHandler.lambda$channelRead0$0(WebSocketMessageHandler.java:47)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Output closed
        at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
        at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
        at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.lambda$send$1(JdkHttpClient.java:271)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:310)
        ... 10 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #13789

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

n/a

### CODE REVIEW

**Review by erwinheitzman — APPROVED** [review]

**Comment by damencho** [comment]
Hey @christian-bromann is reloadSession working with multiRemote? I was just testing it (updated to 9.3.1) but when I do a reloadSession to one of the multiremote browsers I get the following error when trying to navigate to url:
```
Error: WebDriver Bidi command "browsingContext.navigate" failed with error: no such frame - Context 35D912DA7B709EBFB778772532FBE886 not found
```

**Comment by christian-bromann** [comment]
@damencho do you have a reproduction case?

**Comment by damencho** [comment]
I will prepare one and will add it here.

**Comment by damencho** [comment]
Hum, it behaves differently in the simple case, it just hangs without navigating and timeouts after jasmineOpts.defaultTimeoutInterval.
```
await multiremotebrowser.getInstance('b1').url('https://example.com');
await multiremotebrowser.getInstance('b1').reloadSession();
await multiremotebrowser.getInstance('b1').url('https://example2.com');
```
I'm getting the navigate error `no such frame - Context` in my complex test case because there is an iframe and I am using switchFrame. 
I will need more time to make an example for that. I will come back to you.

**Comment by damencho** [comment]
Ups. I forgot to update the versions to 9.3.1 in the example. Yep, I reproduce it.

```
capabilities: {
        b1: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        b2: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },
```
And in the test:
```
await multiremotebrowser.getInstance('b1').url('https://example.com');
await multiremotebrowser.getInstance('b1').reloadSession();
await multiremotebrowser.getInstance('b1').url('https://example2.com');
```
Error:
```
[MultiremoteBrowser on chrome and chrome #0-0] Error: WebDriver Bidi command "browsingContext.navigate" failed with error: no such frame - Context 570ADCF01AC02F043BD87109989D8751 not found
```

**Comment by damencho** [comment]
The complete example:

[simple.zip](https://github.com/user-attachments/files/17878295/simple.zip)
```
npm i
npm run test-simple
```

**Comment by damencho** [comment]
After updating to 9.3.1 I started getting problems I was not seeing before ... now I get "Error: WebDriver Bidi command "browsingContext.navigate" failed with error: unknown error - Page.navigate {"url":"https://127.0.0.1:8081/iframeAPITest.html........","frameId":"42A75C42F69DBAB517D2749C8A1E11CF"} B8592E0BB98951096536B63752A2455F call rejected because the connection has been closed."

And this is just after internal changes in the page ... I'm still not able to isolate it in a simple case to open a new issue ...

**Comment by damencho** [comment]
Thank you for letting me know!

**Comment by nair-sumesh** [comment]
This is a blocker for my test cases.
Request you to kindly resolve this ASAP.

**Pull request merged**
