### PR TITLE
Avoid calling googlechromelabs.github.io when offline + ffx

### PR DESCRIPTION
**Pull request by step21**
## Proposed changes

[//]: # Ideally this allows tests with Firefox to work offline and not call googlechromelabs.github.io (and thus fail). As discussed in https://github.com/webdriverio/webdriverio/issues/12705

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [x] Back-ported PR at `#12718`

## Further comments

[//]: # Right now at least locally there was one test failure, but I am not sure how bad this is or how to solve it. So I wanted to get started on the PR anyway for now. It seems the test expect a Windows version, maybe it failed for me on macOS because of that?
```
FAIL  packages/wdio-utils/tests/node/utils.test.ts > driver utils > setupPuppeteerBrowser > should install chrome stable if browser is not found
AssertionError: expected "spy" to be called 1 times, but got 0 times
 ❯ packages/wdio-utils/tests/node/utils.test.ts:147:36
    145|                 executablePath: '/path/to/stable'
    146|             })
    147|             expect(resolveBuildId).toBeCalledTimes(1)
       |                                    ^
    148|             expect(resolveBuildId).toBeCalledWith('chrome', 'windows', '116.0.5845.110')
    149|         })

```

### CODE REVIEW

**Comment by christian-bromann** [comment]
Can we raise the same PR to the `v8` branch please?

**Review by christian-bromann — APPROVED** [review]
Thank you!

👍

**Review by christian-bromann — CHANGES_REQUESTED** [review]
@step21 can you check the failing test?

**Comment by step21** [comment]
> @step21 can you check the failing test?

For the failing test, most obvious to me seems that when `expect(resolveBuildId).toBeCalledTimes(0)`, I also need to delete the second line `expect(resolveBuildId).toBeCalledWith('chrome', 'windows', '116.0.5845.110')` as ofc if it is not called, it is not called with something. This might however negate the point of the test. I do not have that much knowledge about the webdriverio codebase, but maybe it would need separate tests for when chrome is previously installed, and when it is not?

**Comment by christian-bromann** [comment]
@step21 it is likely that we don't clear the mock beforehand.

**Comment by christian-bromann** [comment]
Closing as this hand landed as part of #12720

**Pull request closed without merging**
