### PR TITLE
Adding support for WDIO-Mochawesome-Reporter

### PR DESCRIPTION
**Pull request by fijijavis**
## Proposed changes

This change adds CLI support for the [wdio-mochawesome-reporter](https://github.com/fijijavis/wdio-mochawesome-reporter)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@fijijavis please sign the CLA so I can merge the PR

**Comment by fijijavis** [comment]
@christian-bromann I'm clicking the link provided and signing in with my github account but this isn't picking it up

**Comment by christian-bromann** [comment]
@fijijavis see

> Davis seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

**Comment by fijijavis** [comment]
@christian-bromann I think I have it fixed now

**Comment by christian-bromann** [comment]
@fijijavis doesn't look like it? Can you try make a new PR?

**Pull request closed without merging**
