### PR TITLE
Ensure correct reporting when a thread runs more then 1 Cucumber feature (spec)

### PR DESCRIPTION
**Pull request by mikesalvia**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

When grouping specs the reporter goes wacky and does not assign test cases to test suites properly, original code which I wrote assumed 1 spec per thread worker which is an incorrect assumption.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mikesalvia** [comment]
Will resolve the linting issues on Monday, or perhaps sooner if I have time.

**Comment by mikesalvia** [comment]
@christian-bromann Can you point me to the person that would be able to assist me with the failures I am seeing? I don't understand the failure message.

**Comment by christian-bromann** [comment]
@mikesalvia these are typescript failures and were introduced by dependency updates in the `main` branch. Either we have to wait until someone makes a PR to resolve these or I find some time to do it myself.

**Comment by mikesalvia** [comment]
@mikesalvia I will look at this and attempt fix.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 
Thanks for the contribution.

Will look into the typing issue.

**Pull request merged**
