### PR TITLE
wdio-cli: Update documentation wrt. overwriting the path variable

### PR DESCRIPTION
**Pull request by tugend**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Updated the documentation wrt. overwriting the path variable. I spent a lot of time and confusion figuring out that it should be changed (or outcommented) before I could run IE or EDGE drivers.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
I'm not sure if the PR is useful. All you need to make iedriver work with selenium standalone is remove path from config. It's in the docs, I've mentioned it in the issue as well. Not sure if the change make it more clear

**Comment by tugend** [comment]
That's fair. Can you point me in the direction of the doc that mentions it?
Because I missed it entirely. 

It works fine either removing it or setting the path explicityly to /wd/hub, I thought it was a bit cleaner to change it explicitly.

**Comment by tugend** [comment]
Previous discussion can be found here; https://github.com/webdriverio/webdriverio/issues/4688#issuecomment-546586689

**Comment by mgrybyk** [comment]
I'd keep the files you've changed untouched and add hint to remove path here https://webdriver.io/docs/selenium-standalone-service.html

By default path is commented out so that selenium standalone users don't need to do anything, while it's only mentioned for chromedriver users to uncomment path https://webdriver.io/docs/wdio-chromedriver-service.html#configuration

**Comment by tugend** [comment]
I went and retested. If I use config and only pick selenium-standalone, you're right. So I have to agree, the setup makes sense. If one picks both chromedriver and selenium-standalone the path variables is included and the confusion arises.

Hence, my mistake. Thank you for commenting. 
I'll close the issue.

```
npm i --save-dev @wdio/cl
./node_modules/.bin/wdio config // pick selenium-standalone only
```

**Pull request closed without merging**
