### PR TITLE
Use a flat namespace for selenium options for finding WebDriver Bidi endpoint

### PR DESCRIPTION
**Pull request by BorisOsipov**
See https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392 for details.
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
cc @dylanlive

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by dylanlive** [comment]
Thanks! Haven't had a chance to test Selenium 4 Beta 2 yet, so glad you were able to get this in so quickly

**Comment by christian-bromann** [comment]
Will release this as `v7.3.0` once the [outstanding PRs](https://github.com/webdriverio/webdriverio/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Aneeds-review) are reviewed and merged.

**Pull request merged**
