### PR TITLE
dont show welcome message on error log level

### PR DESCRIPTION
**Pull request by sbmaxx**
subj.

minor change, but fix annoying log entry ;)

### CODE REVIEW

**Comment by christian-bromann** [comment]
What is so annoying with it? :-D

**Comment by sbmaxx** [comment]
We run test in many browsers (without `wdio`) with many sessions per browser in parallel..

**Comment by sbmaxx** [comment]
@christian-bromann look at this screenshot https://yadi.sk/i/7UIK4Tw4n6PUj . It's the error level. I don't think anyone using it [with error level] need this welcome message.

**Comment by christian-bromann** [comment]
@sbmaxx we updated the code base (merged v4 branch). Could you please fetch a fresh copy from the master branch and open a new PR? Thanks!

**Pull request closed without merging**
