### PR TITLE
fix(ui5-service): name of service

### PR DESCRIPTION
**Pull request by vobu**
## Proposed changes

this PR fixes the wrong service name offered in the `cli` at scaffolding-time.

image

also, it updates the recommended Node.js version to use for contributing.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [?] I have added tests that prove my fix is effective or that my feature works
  given that this is a 3rd party service, I assume no tests for that 3rd party service should be included here ❓ 
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

also see https://github.com/webdriverio/webdriverio/pull/6078#issuecomment-1036185309 and https://github.com/js-soft/wdi5/issues/140

### CODE REVIEW

**Comment by vobu** [comment]
thanks for triggering things @WillBrock!
looking at the errors, not much I can do at first glance:
- win e2e: seems to be a fibers issue w/ node 16 → want me to dig deeper and wire the sync tests to node 14 lts or similar?
- mac e2e: either false positive or expired saucelab credentials 😄

**Comment by WillBrock** [comment]
@vobu I noticed those tests were failing on other pull requests, I'll take a look. Those failures won't prevent this getting merged though.

**Comment by vobu** [comment]
> @vobu I noticed those tests were failing on other pull requests, I'll take a look. Those failures won't prevent this getting merged though.

great, thanks, much appreciated! 
let me know if i can help with the ci-error regarding node-gyp on the win2022 runner. have some devops firepower in-house (ping @jkoenig134)

**Review by christian-bromann — APPROVED** [review]
👍 

I will go ahead and merge.

**Pull request merged**
