### PR TITLE
Adding applitools eyes service support

### PR DESCRIPTION
**Pull request by yanirta**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@yanirta there is already a service for the Applitools eyes integration: https://github.com/webdriverio/v5/tree/master/packages/wdio-applitools-service

It seems we did both the same work here. What I don't understand is that you have used the selenium binding integration with Applitools even though there is already a great integration with WebdriverIO (https://www.npmjs.com/package/%40applitools%2Feyes.webdriverio). It looks like both services do the same. How about we settle on one project instead of maintaining both?

**Comment by yanirta** [comment]
Hey @christian-bromann , as of now direct webdriverio has many missing features such as supporting native mobile apps, proper batching and reporting. I don't say there is no room for the service you propose but as of now the old selenium binding supports more cases and best practices.

**Comment by christian-bromann** [comment]
> but as of now the old selenium binding supports more cases and best practices.

mhm .. are there any plans to update the WebdriverIO bindings?

**Comment by yanirta** [comment]
@christian-bromann there are, but not sure when it will be ready and some folks were asking for a solution.
My trigger was that @applitools/eyes.webdriverio doesn't currently fit to native apps.
And some other small topics.

**Pull request closed without merging**
