### PR TITLE
(@wdio/selenium-standalone-service): good bye 👋

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

With v8.14.0 and the new [driver management](https://webdriver.io/blog/2023/07/31/driver-management) this service is no longer needed and can be removed from the code repository.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Cleanup (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by christian-bromann** [comment]
@erwinheitzman yes, the package will stay around, I will just deprecate it.

**Comment by answer-equals-42** [comment]
@christian-bromann @erwinheitzman I am kinda new to the testing domain. Please excuse me, if this is a stupid question, but how do I properly migrate? We were using some older 8- and up versions.

The thing is we want to make sure that both the local setup and the setup on GitLab CI are running selenium and not for example chromium. I had some issues with the setup once I removed the "@wdio/selenium-standalong-service" and the config.services where it used to say "config.services = ['selenium-standalone']".

It used to run on a selenium server on localhost. Now it is telling me, that it runs on the DevProtocol using Pupeteer and chromedriver. I've also asked a question on StackOverflow: https://stackoverflow.com/questions/77949565/how-to-properly-replace-wdio-selenium-standalone-service-service.

Do we need to configure something additionally? I've read that there is Google Chrome for Testing now. Is the new setup now using this browser when I use it locally? I don't quite get it.

Thank you in advance for the help.

**Comment by erwinheitzman** [comment]
Hi @answer-equals-42 no need to apologise, could you please share the logs of a run?

**Comment by erwinheitzman** [comment]
Apologies, I was in a meeting when I typed my previous message and I just noticed that you added a part of the log over on Stackoverflow.

If it is running with the devtools protocol it means you either did not upgrade to a version that has the built-in driver manager yet or perhaps you are using the devtools service.
Could you share your package.json and config?

**Comment by erwinheitzman** [comment]
@answer-equals-42 I think it is a local thing on your end as I cannot reproduce it with that repo. For me it is running just fine cloning that and installing the packages

**Comment by answer-equals-42** [comment]
@erwinheitzman It is running now, because I have modified config.services from undefined to an empty array. However, I wanted to know if this still runs on selenium because it says chromedriver in the logs and refers to my local chrome installation as you can see in the logs. Is it now using chromedriver or selenium?

image

**Comment by erwinheitzman** [comment]
I think that Selenium isn't what you think it is. WebdriverIO either uses Webdriver or Devtools (protocols), the selenium server was used in the past only to download and start the drivers, which is now built into webdriverio itself.

You are running WebdriverIO with the same protocol as before (webdriver) instead of devtools.

Regarding the local browser binary, you can add the browserVersion property to your capabilities. I recommend to set it to "stable" and if you run your tests with this, it will go ahead and download the latest stable Chrome for Testing along with the matching driver for it.

Good luck 😎

**Pull request merged**
