### PR TITLE
@wdio/browserstack-service: Add option to set job (session) name via setJobName function

### PR DESCRIPTION
**Pull request by SCG82**
## Proposed changes

Based on https://github.com/webdriverio/webdriverio/pull/9107, so that needs to be merged in prior to this PR.

Please see https://github.com/webdriverio/webdriverio/pull/9134/commits/a247c7773f4b661241035f7df0b972c903796152 to view the diff

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by SCG82** [comment]
```
 ✓ packages/wdio-browserstack-service/tests/service.test.ts  (44 tests) 
```

**Comment by christian-bromann** [comment]
Let's wait for feedback from @Ankit098

**Comment by christian-bromann** [comment]
ping @Ankit098 , would you like to review?

**Comment by SCG82** [comment]
I'm going to incorporate this into https://github.com/webdriverio/webdriverio/pull/9107

**Pull request closed without merging**
