### PR TITLE
fix url.ts for when working remotely

### PR DESCRIPTION
**Pull request by larryg01**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
await browser.url('https://webdriver.io');

Before fix: #6460 
In its current state it, it passes a blank url to the remote session
console.log(browser.getUrl()); // outputs: " "

After fix: 
It pass the correct url to the remote session (i.e. browserstack).
console.log(browser.getUrl()); // outputs: "https://webdriver.io"

This works as expected locally both Before and After the fix
console.log(browser.getUrl()); // outputs: "https://webdriver.io"

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Can we add a test for this?

**Comment by erwinheitzman** [comment]
Could you add some tests here https://github.com/webdriverio/webdriverio/blob/1065b755174bccd60edb9b1abae9113aacbdb5c6/packages/webdriverio/tests/commands/browser/url.test.ts to verify this behaviour?

**Comment by larryg01** [comment]
> Can we add a test for this?

I added and additional test, hope its all good

**Comment by christian-bromann** [comment]
@larryg01 it seems that you removed the actual fix in the command. This PR only contains the test now. Also make sure that you have a test that fails without your fix and now passes because I think the current test is already existing.

**Comment by larryg01** [comment]
> @larryg01 it seems that you removed the actual fix in the command. This PR only contains the test now. Also make sure that you have a test that fails without your fix and now passes because I think the current test is already existing.

Hopeless me!!!
Not sure what happened there but i added an additional test to the existing one url.test.ts and also i was under the impression that since i updated the PR with the test it will only show that but if you look at the previous commit to the PR it will show the file fix. (if thats not the case how do i commit the change again)

**Comment by christian-bromann** [comment]
> without the fix it will fail and pass with the fix (i just ran it again to confirm)

Great!

> if thats not the case how do i commit the change again

Not sure, just make the change again and commit/push.

**Comment by larryg01** [comment]
> > if thats not the case how do i commit the change again
> 
> Not sure, just make the change again and commit/push.

https://github.com/webdriverio/webdriverio/pull/6461/commits/1065b755174bccd60edb9b1abae9113aacbdb5c6
I just checked and the fix is in the code, so once you merge the fix will be there, but i will try and do a commit again as you suggested

**Comment by larryg01** [comment]
File added back to the PR, hope I got it right this time

**Comment by christian-bromann** [comment]
> File added back to the PR, hope I got it right this time

Doesn't seem like it, if you see the changes, you just added a new line:
https://github.com/webdriverio/webdriverio/pull/6461/files

**Comment by larryg01** [comment]
I think I finally figured out how to repost the whole file, so its now there
Third time luck I hope

**Comment by christian-bromann** [comment]
@larryg01 please open this link: https://github.com/webdriverio/webdriverio/pull/6461/files

You see that you just added new lines.

**Comment by larryg01** [comment]
@christian-bromann The fix I have for this works fine both locally and remotely but its not passing the 'relative url test' when it comes to relative url, the baseUrl is not getting passed. so I am stuck where that is concern.
so this is whats being returned  json: { url: 'http://foobar/' }
SO this is where i am totally stuck and looking for a better solution

**Comment by christian-bromann** [comment]
@larryg01 your PR includes a bunch of unrelated commits due to an incorrect rebase I assume. Please update your repository and your branch and re-apply your initial changes. Let me know if I can help in any way.

**Comment by christian-bromann** [comment]
Given the status of the PR I will close and recommend to create a new one with updated code base.

**Pull request closed without merging**
