### PR TITLE
fix(webdriver): browser request should use btoa for basic auth, not atob

### PR DESCRIPTION
**Pull request by jlipps**
Oops :-) I thought "atob" meant "ascii to base64", but it does not!

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Can we add a test for this?

**Comment by jlipps** [comment]
Hmm, yes, I think we can add a test for this, but only one that mocks `atob` in the first place, since it's not a Node function, and we don't have a test harness that bundles and runs code in a browser context.

Is a test that mocks `atob` any better than no test at all? I suppose the most it would do is make sure we don't change it to some other function name in the future?

**Comment by christian-bromann** [comment]
@jlipps you can run Jest tests within a browser environment using jsdom, similar we do this e.g. with the [`isFocused`](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/tests/scripts/isFocused.test.ts) test.

**Comment by jlipps** [comment]
Oh, sweet! Done.

**Comment by jlipps** [comment]
the windows CI failure seems unrelated.

**Review by christian-bromann — APPROVED** [review]
This looks good, thanks 👍

**Pull request merged**
