### PR TITLE
fix: Remove scripts from log payload 

### PR DESCRIPTION
**Pull request by OlaoluwaM**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Added check for `script` property in payload and returned placeholder if it existed. Checks were the same as those for the file property on the `results` object. Resolves issue #6714

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — COMMENTED** [review]
Thanks for the contribution!

How about we define the replacement (similar to `SCREENSHOT_REPLACEMENT`) as const and use a similar format, e.g. `<Script>`.

Also a unit test would be nice for this.

**Comment by OlaoluwaM** [comment]
Ok, no problem. For the unit test I assume it should either be the same as `results.file` or should at least extend that specific unit test right?

**Comment by christian-bromann** [comment]
I recommend to just extend [this unit test](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/tests/utils.test.ts#L41-L45).

**Comment by christian-bromann** [comment]
@OlaoluwaM let me know if I can assist in any way. Feel free to book a slot as part of our [open office hours](https://webdriver.io/community/openofficehours) if you want to pair on this.

**Comment by OlaoluwaM** [comment]
Done! Let me know what you think

**Comment by OlaoluwaM** [comment]
image

**Comment by christian-bromann** [comment]
@OlaoluwaM it didn't seem you pushed any tests to your branch.

**Comment by OlaoluwaM** [comment]
I dont really understand what you mean, could you explain?

**Comment by christian-bromann** [comment]
@OlaoluwaM sorry for not being clear enough. Your code change comes with no tests. It would be great if we could extend [this test](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/tests/utils.test.ts#L41-L45) to ensure there will be no regression in the future.

**Comment by OlaoluwaM** [comment]
Oh, but I did. Maybe I am missing something

**Comment by OlaoluwaM** [comment]
image

**Comment by christian-bromann** [comment]
Maybe you have a different PR somewhere else but if I go to https://github.com/webdriverio/webdriverio/pull/6921/files I only see changes in one file.

**Comment by OlaoluwaM** [comment]
Yeah I see the problem

**Comment by OlaoluwaM** [comment]
The main branch of my fork, which does not include the tests, was what I used to open this PR

**Comment by OlaoluwaM** [comment]
I will open another PR with the branch containing the changes. Will be alright?

**Comment by christian-bromann** [comment]
> Will that be alright?

Sounds good to me!

**Pull request closed without merging**
