### PR TITLE
[v7] Console logs and cucumber hooks support

### PR DESCRIPTION
**Pull request by sriteja777**
## Proposed changes
1. Add console logs support for observability
2. Add cucumber hooks support for observability

Related v8 PR: https://github.com/webdriverio/webdriverio/pull/11098

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by sauravdas1997 — APPROVED** [review]

**Comment by christian-bromann** [comment]
@sriteja777 let me know when this PR is ready for review.

**Comment by sriteja777** [comment]
@christian-bromann The PR is ready for review. Please review in your free time

**Comment by sourav-kundu** [comment]
@christian-bromann These changes are the same as [v8 changes](https://github.com/webdriverio/webdriverio/pull/11098).
Could you please review and release v7 as well?

**Review by christian-bromann — APPROVED** [review]
👍 LGTM

The build is currently broken for the `v7` branch, to fix it we need to downgrade the `saucelabs` package the way we have it in the `main` branch. If you can make this PR for the `v7` branch I am happy to release v7 today.

**Comment by sriteja777** [comment]
Thanks @christian-bromann, will make the changes. Can you please point to where exactly we need to downgrade the `saucelabs` package, and it would be helpful if there is any corresponding PR to main that I can refer?

**Comment by christian-bromann** [comment]
@sriteja777 please see https://github.com/webdriverio/webdriverio/commit/0a84c5eeb7d927bb54390b94de90705fc8d21c95

**Comment by sriteja777** [comment]
@christian-bromann Have made the PR. Can you please check once?

**Comment by sourav-kundu** [comment]
@christian-bromann Can we release a v7 version?

**Pull request merged**
