### PR TITLE
Fix work in Opera

### PR DESCRIPTION
**Pull request by DudaGod**
## Proposed changes

Few days ago I was faced with the problem that I can't run my test in opera 12.16 using webdriverio. I have a minimal case to reproduce the problem:
```js
const webdriverio = require('webdriverio');

var browser = webdriverio.remote({
    host: 'my-host.com',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        browserName: 'opera',
        version: '12.16',
    }
});

return browser
    .init()
    .url('http://webdriver.io')
    .saveScreenshot('wdio.png')
    .catch((e) => console.log(e))
    .end();
```
I caught the error `Couldn't connect to selenium server`.

Then I've tried check the same test in the [wd](https://github.com/admc/wd). And it works without any problem:
```js
const gridUrl = 'http://my-host.com:4444/wd/hub';

const wd = require('wd');
const path = require('path');

const browser = wd.promiseChainRemote(gridUrl);

browser
    .init({
        browserName: 'opera',
        version: '12.16'
    })
    .get('https://github.com')
    .then(() => browser.saveScreenshot(path.resolve('wd.png')))
    .then(() => browser.quit())
    .catch(console.log)
    .done();
```

It was pretty strange and I started digging deeper and I found a line in commit where it was broken - https://github.com/webdriverio/webdriverio/commit/7921d3f86c7c9388ff17a6b6fa6ad3ba41bd6a4c#diff-acb49f79a9c7899043b34bf7de5b5d17R169

Here we can see that new condition is not the same that it was:
BEFORE:
```js
if (err || (body && body.status !== 0)) {
    reject()
} else {
    resolve()
}
```
AFTER:
```js
if (!err && body && body.status === 0) {
    resolve()
} else {
    reject()
}
```

So before refactoring the http call that returns empty body will be successfully resolved. But after refactoring it will be rejected.
I don't know why but operadriver ~~returns body only on init request and for all subsequent requests the body is empty.~~ doesn't return body on `browser.url` request.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by DudaGod** [comment]
тесты не проходят, что-то с sauselabs

**Comment by eGavr** [comment]
@DudaGod 

Na eglish language, pozaluista.

**Comment by christian-bromann** [comment]
@DudaGod don't worry about the tests

**Comment by DudaGod** [comment]
@christian-bromann ping. What you think about this PR?

**Comment by christian-bromann** [comment]
@DudaGod I will take a look once I have a free minute. Can you please sign the CLA? This is new as we joined the JSF yesterday

**Comment by DudaGod** [comment]
@christian-bromann no problem, I've just signed it

**Comment by DudaGod** [comment]
@christian-bromann sorry for disturb you, but I really need this fix.

**Comment by DudaGod** [comment]
@christian-bromann ping

**Comment by christian-bromann** [comment]
I hear you, will have to check this fix and release it. I am currently super busy but will try to get this out asap.

**Comment by DudaGod** [comment]
@christian-bromann hello, do not forget about this PR please. I still need these changes.

**Comment by DudaGod** [comment]
@christian-bromann ping

**Comment by christian-bromann** [comment]
@DudaGod thanks for the PR, I fixed the issue with a bit different approach on testing.

**Pull request closed without merging**
