### PR TITLE
docs: AI copilot implementation

### PR DESCRIPTION
**Pull request by nickscamara**
## Proposed changes

Hey team,

I've been thoroughly enjoying WebdriverIO.

Recently, when trying to implement in our Node.js environment I stumbled into some questions. So, I ended up ingesting the webdriver documentation into Mendable.ai (my project) and started using to answer some of the questions that I had about product. 

I thought it did a great job answering most of them, so I figured to offer as a feature for your docs. I implemented a small button on the screen's bottom right which unveils an AI-powered chat interface when clicked. There, users can ask questions about WebdriverIO's documentation and even debug code. The bot will learn with the documentation daily so it will be always updated with recent doc changes. (100% free btw)

I would love to hear your feedback! Super excited for what yall are building and hopefully this can help a tiny bit :)

A bit of background: I am one of the co-founders Mendable.ai. We are supporters of open-source projects and we'd love to offer Mendable for free, with the goal of helping yall out teach developers about your product and answer users queries. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc

### CODE REVIEW

**Comment by christian-bromann** [comment]
@nickscamara thanks for raising the PR, I will take a look at Mendable.ai and will see if it is suited to be integrated into our docs. In the meantime, mind signing the CLA?

**Comment by nickscamara** [comment]
Hi @christian-bromann! Awesome, thank you! Let me know if you have any questions. I have signed the CLA, although doesn't seem like it has updated.

**Review by christian-bromann — APPROVED** [review]
This is pretty awesome 🤩 I will merge and see what the community things about it.

Is there a way to find out what people have asked? I think there is a clever process here where we can focus our docs efforts based on questions asked by the community. What do you think?

**Comment by jan-molak** [comment]
@christian-bromann - I like it, the "verified sources" option is great too. It even knows about Serenity/JS 😎

**Comment by nickscamara** [comment]
yey! Glad yall liked it. @christian-bromann I will email you an invite to the account I used to set it up. There you are able to see all the questions asked by the community and more! :)

**Pull request merged**
