### PR TITLE
fix(junit-reporter): strip ansi escape codes from error stack

### PR DESCRIPTION
**Pull request by alk-sdavid**
## Proposed changes

Backporting fix from main branch to v7 branch: https://github.com/webdriverio/webdriverio/pull/9091

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

None

### CODE REVIEW

**Review by erwinheitzman — APPROVED** [review]
LGTM

**Comment by erwinheitzman** [comment]
@alk-sdavid are you sure you created this branch from v7 and not from v8? The jobs are currently failing

**Comment by alk-sdavid** [comment]
@erwinheitzman I think I cherry-picked the commit... but I don't remember exaclty 😅 I'll do it again

**Comment by alk-sdavid** [comment]
I think I messed up while resolving snapshots conflicts of my cherry-pick, I hope it's better now 🤞

**Comment by alk-sdavid** [comment]
on the other hand I don't see how the current workflow errors are related to my changes 🤔

**Comment by erwinheitzman** [comment]
Yeah me brighter, I have asked if anyone knows what might be causing this

**Comment by christian-bromann** [comment]
Working on unblocking this.

**Comment by christian-bromann** [comment]
@alk-sdavid mind updating your branch?

**Comment by alk-sdavid** [comment]
@christian-bromann Done: I rebased and now the tests passed except the windows one which timeouts:

```
[Chrome Headless 106.0.5249.119 win32 #0-1] Running: Chrome Headless (v106.0.5249.119) on win32
[Chrome Headless 106.0.5249.119 win32 #0-1] Session ID: d9e1591f-77bd-4004-a977-d36032f22d86
[Chrome Headless 106.0.5249.119 win32 #0-1]
[Chrome Headless 106.0.5249.119 win32 #0-1] » \e2e\wdio\headless\test.e2e.js
[Chrome Headless 106.0.5249.119 win32 #0-1] main suite 1
[Chrome Headless 106.0.5249.119 win32 #0-1]    ✓ foobar test
[Chrome Headless 106.0.5249.119 win32 #0-1]    ✓ should allow to check for PWA
[Chrome Headless 106.0.5249.119 win32 #0-1]    ✓ should also detect non PWAs
[Chrome Headless 106.0.5249.119 win32 #0-1]    ✖ should allow to do performance tests
[Chrome Headless 106.0.5249.119 win32 #0-1]
[Chrome Headless 106.0.5249.119 win32 #0-1] 3 passing (1m 4.8s)
[Chrome Headless 106.0.5249.119 win32 #0-1] 1 failing
[Chrome Headless 106.0.5249.119 win32 #0-1]
[Chrome Headless 106.0.5249.119 win32 #0-1] 1) main suite 1 should allow to do performance tests
[Chrome Headless 106.0.5249.119 win32 #0-1] Timeout of 60000ms exceeded. The execution in the test "main suite 1 should allow to do performance tests" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (D:\a\webdriverio\webdriverio\e2e\wdio\headless\test.e2e.js)
```

**Comment by christian-bromann** [comment]
Thanks, yeah our windows test are broken atm. Will go ahead and merge.

**Pull request merged**
