### PR TITLE
Fix for newWindow called twice opens only one window

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

Continuation of #7224

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by christian-bromann** [comment]
@praveendvd please review, thanks!

**Comment by praveendvd** [comment]
`Looks good to me , the failed test are same as we had for the other pull request```


   expect(received).toContain(expected) // indexOf

    Expected substring: "No window found"
    Received string:    "cov_u16zs3gt is not defined"

      54 |             await browser.switchWindow('foobar')
      55 |         } catch (e) {
    > 56 |             expect(e.message).toContain('No window found')
         |                               ^
      57 |         }
      58 |     })
      59 |

      at Object.<anonymous> (packages/webdriverio/tests/commands/browser/switchWindow.test.ts:56:31)
```

**Review by praveendvd — APPROVED** [review]
Looks good to me

**Comment by christian-bromann** [comment]
> cov_u16zs3gt is not defined

This means that Jest populated some instrumentation code into our script which will not work when run in a browser, usually we would put these scripts into the `scripts` folder where these are ignored already but such a simple script can be just be added inline with a `/* istanbul ignore next */`

**Comment by praveendvd** [comment]
> > cov_u16zs3gt is not defined
> 
> This means that Jest populated some instrumentation code into our script which will not work when run in a browser, usually we would put these scripts into the `scripts` folder where these are ignored already but such a simple script can be just be added inline with a `/* istanbul ignore next */`

Thank you for the explanation @christian-bromann

**Pull request merged**
