### PR TITLE
@wdio/mocha-framework - fix deprecation warning

### PR DESCRIPTION
**Pull request by unickq**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Fix for https://github.com/webdriverio/webdriverio/issues/7040

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### Reviewers: @webdriverio/project-committers
@christian-bromann

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍  thanks for the quick fix.

**Comment by christian-bromann** [comment]
@unickq I believe you need to also update `@types/mocha`.

**Comment by unickq** [comment]
Yep, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts is 8.2.2 based.

**Comment by christian-bromann** [comment]
But tests still fail due to:

```
Error: packages/wdio-mocha-framework/src/index.ts(89,70): error TS2345: Argument of type '{ delay: boolean; }' is not assignable to parameter of type 'boolean'.
```

**Comment by christian-bromann** [comment]
Seems that types are not correct: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts#L1403

**Comment by unickq** [comment]
Yes, it requires creating new RunnerOpts for https://github.com/mochajs/mocha/blob/master/lib/runner.js#L143
in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts

**Comment by unickq** [comment]
I'll reopen PR with a fix once types updates released or I do that by myself

**Comment by tehhowch** [comment]
Types are now published

**Comment by christian-bromann** [comment]
@tehhowch mind raising a PR?

**Comment by unickq** [comment]
https://github.com/webdriverio/webdriverio/pull/7171 @christian-bromann

**Pull request closed without merging**
