### PR TITLE
Log duration of hook execution

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

To get more visibility as to how long hooks have been running I added a log statement to capture this information.

see also discussion in #6191

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

**Comment by mgrybyk** [comment]
May you please share an example how it looks now?

**Comment by christian-bromann** [comment]
@mgrybyk here is a log file example:

```
2020-12-14T14:49:04.604Z INFO @wdio/local-runner: Run worker command: run
2020-12-14T14:49:04.608Z DEBUG @wdio/local-runner:utils: init remote session
2020-12-14T14:49:04.610Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
2020-12-14T14:49:04.829Z DEBUG @wdio/local-runner:utils: init remote session
2020-12-14T14:49:04.830Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-12-14T14:49:04.832Z INFO webdriver: [POST] http://localhost:4444/session
2020-12-14T14:49:04.832Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
2020-12-14T14:49:06.525Z INFO webdriver: COMMAND getTitle()
2020-12-14T14:49:06.525Z INFO webdriver: [GET] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a/title
2020-12-14T14:49:06.526Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 3ms
2020-12-14T14:49:06.527Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
2020-12-14T14:49:06.527Z INFO webdriver: COMMAND navigateTo("https://webdriver.io/")
2020-12-14T14:49:06.527Z INFO webdriver: [POST] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a/url
2020-12-14T14:49:06.527Z INFO webdriver: DATA { url: 'https://webdriver.io/' }
2020-12-14T14:49:06.531Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
2020-12-14T14:49:06.531Z INFO webdriver: COMMAND getLogTypes()
2020-12-14T14:49:06.532Z INFO webdriver: [GET] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a/se/log/types
2020-12-14T14:49:06.536Z INFO webdriver: RESULT 
2020-12-14T14:49:07.029Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
2020-12-14T14:49:07.029Z INFO webdriver: COMMAND getTitle()
2020-12-14T14:49:07.029Z INFO webdriver: [GET] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a/title
2020-12-14T14:49:08.286Z INFO webdriver: RESULT [ 'browser', 'driver' ]
2020-12-14T14:49:08.287Z DEBUG @wdio/runner: Fetching logs for browser, driver
2020-12-14T14:49:08.287Z INFO webdriver: COMMAND getLogs("driver")
2020-12-14T14:49:08.287Z INFO webdriver: [POST] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a/se/log
2020-12-14T14:49:08.287Z INFO webdriver: DATA { type: 'driver' }
2020-12-14T14:49:08.288Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 1ms
2020-12-14T14:49:08.289Z INFO webdriver: COMMAND getLogs("browser")
2020-12-14T14:49:08.289Z INFO webdriver: [POST] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a/se/log
2020-12-14T14:49:08.290Z INFO webdriver: DATA { type: 'browser' }
2020-12-14T14:49:08.294Z INFO webdriver: RESULT WebdriverIO · Next-gen browser and mobile automation test framework for Node.js
2020-12-14T14:49:08.301Z INFO webdriver: RESULT []
2020-12-14T14:49:08.302Z INFO webdriver: RESULT []
2020-12-14T14:49:08.302Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
2020-12-14T14:49:08.302Z INFO webdriver: COMMAND deleteSession()
2020-12-14T14:49:08.302Z INFO webdriver: [DELETE] http://localhost:4444/session/30835eec249a0ee154b897ce53d3d51a
```

Note that I only leveraged the `beforeCommand` hook (no services that would trigger other hooks) and therefor you only see logs for `beforeCommand`. These are also debug logs so can be disabled by setting `logLevel` to `info`.

**Comment by christian-bromann** [comment]
@mgrybyk is this good to go then?

**Comment by mgrybyk** [comment]
The tests are falling

**Comment by christian-bromann** [comment]
@mgrybyk updated, should be good to go now.

**Review by mgrybyk — APPROVED** [review]

**Pull request merged**
