### PR TITLE
webdriverio: update minimum required nodejs version

### PR DESCRIPTION
**Pull request by erwinheitzman**
## Proposed changes

Update the minimum required nodejs version for webdriverio.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Also I think we can set v6 (latest) as required version.

**Comment by abjerstedt** [comment]
@christian-bromann i don't think node 6 works at all for us.

**Comment by christian-bromann** [comment]
> i don't think node 6 works at all for us.

Why not? I don't see any problems running webdriverio with node v6

**Comment by abjerstedt** [comment]
@christian-bromann 
https://webdriver.io/docs/gettingstarted.html#run-your-test-file
> Make sure you have at least Node.js v8.11.2 or higher installed. 

The minimum supported version was 8 when i first started working on v5, and we agreed on 8.11.2 specifically :D back in like November.

**Comment by erwinheitzman** [comment]
Taken from the `Get started` guide.

Run your test file
Make sure you have at least Node.js v8.11.2 or higher installed. To update your current running Node.js version install nvm and follow their instructions. Once that is done run the test script by calling:

**Comment by erwinheitzman** [comment]
And yes I can update this for all the packages that we maintain ourselves.

**Comment by christian-bromann** [comment]
ok, I guess we can release it saying we dropped support for node < v8.11

**Comment by erwinheitzman** [comment]
I have updated all packages to reflect a minimum version of 8.11.0 (I can drop it to 8.9.0 since this was the lowest LTS version back then and we could work like that from now on perhaps. Take lowest LTS version and set that as the minimum requirement)

**Pull request merged**
