### PR TITLE
set agent.keepAlive based on Connection header

### PR DESCRIPTION
**Pull request by kellyselden**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

I attempted to turn off the default keep-alive behaviour like this:

```js
      browser = await remote({
        headers: {
          Connection: 'close',
        },
      });
```

but I was still seeing `Connection: 'keep-alive'` in the browser. I tracked down our handoff to the `request` package, and the custom header was correctly `Connection: 'close'`. Turns out, if you send both `Agent.keepAlive` and `Connection: 'close'` to `request`, it will overwrite any custom headers with what is in your agent config. This fixes our agent keep-alive assumption to match the Connection header.

Unfortunately, since we have to now mutate the agents, they can't be globally stored anymore.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
> but I was still seeing `Connection: 'keep-alive'` in the browser.

What do you mean by this? The headers options defines header properties between WebdriverIO and the browser driver.

**Comment by kellyselden** [comment]
Ah, you're right. This doesn't fix the issue.

**Comment by kellyselden** [comment]
Is there a way to get a `browser.url` call to not use `Connection: keep-alive`?

**Comment by christian-bromann** [comment]
> call to not use `Connection: keep-alive`?

It is how your user would request your page, why would you want to modify this?

**Comment by kellyselden** [comment]
My test server is closing via

```js
    await new Promise(resolve => {
      this.server.close(resolve);
    });
```

but it is taking 5 seconds to close because of the default https://nodejs.org/api/http.html#http_server_keepalivetimeout. If I set keepAliveTimeout to `1`, it works as expected, but I was looking for a better way to do this.

**Comment by kellyselden** [comment]
This sped up my tests a lot. I was just trying to come up with a better solution. https://github.com/CrowdStrike/faltest/pull/129

**Pull request closed without merging**
