### PR TITLE
Enforce file extensions in imports

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

Let's enforce this as we can't import directories anymore using ESM. This patch fixes all imports (mostly within tests).

<a href="https://gitpod.io/#https://github.com/webdriverio/webdriverio/pull/8597"></a>

### CODE REVIEW

**Comment by erwinheitzman** [comment]
Maybe a silly question but can't we now update to native import/export instead?

**Comment by christian-bromann** [comment]
> Maybe a silly question but can't we now update to native import/export instead?

Yes, since we moved to ESM. ESM imports require however a file extension everywhere which is why I added this eslint rule. For all vitest tests it appears that this wasn't needed, either because TypeScript or Vitest has some smart module resolution and understands to look into the right place.

**Comment by erwinheitzman** [comment]
If you can resolve the conflicts then I'll review again :)

**Comment by christian-bromann** [comment]
@erwinheitzman rebased. Not sure if this PR needs a big review, given it is basically just adding file extensions to the imports.

**Comment by christian-bromann** [comment]
merged into `main`

**Pull request closed without merging**
