### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by christian-bromann**

### CODE REVIEW

**Review by DevDengChao — CHANGES_REQUESTED** [review]
These documents are still in English.

**Comment by christian-bromann** [comment]
> These documents are still in English.

Yep, because they are all not translated yet. Would you be interested helping us with one language?

**Comment by DevDengChao** [comment]
I may create a PR for some documents later 🤣

**Comment by christian-bromann** [comment]
We will have to revisit the Crowdin integration once `v8` is released.

**Pull request closed without merging**
