### PR TITLE
[v7] @wdio/browserstack-service: Add session naming options

### PR DESCRIPTION
**Pull request by SCG82**
## Proposed changes

Additionally,  set session name before suite/test instead of after.

See #9107

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by ablok** [comment]
This would be very useful. I just don't get the current way of setting session names in Mocha with this plugin. It always changes it to the last executed test. And only the test name and 1 parent describe, regardless if that is the top describe or not. Or am I just using it wrong?

**Comment by SCG82** [comment]
> This would be very useful. I just don't get the current way of setting session names in Mocha with this plugin. It always changes it to the last executed test. And only the test name and 1 parent describe, regardless if that is the top describe or not. Or am I just using it wrong?

You're not using `@wdio/browserstack-service` incorrectly, that's the current behavior for Mocha: https://github.com/webdriverio/webdriverio/blob/v7/packages/wdio-browserstack-service/src/service.ts#L98

**Comment by christian-bromann** [comment]
@SCG82 before merging, are all changes from https://github.com/webdriverio/webdriverio/pull/9107 also applied here?

**Comment by SCG82** [comment]
> @SCG82 before merging, are all changes from #9107 also applied here?

yes

**Pull request merged**
