### PR TITLE
Fix for missing suite causing error in wdio-mocha-framework

### PR DESCRIPTION
**Pull request by Joosakur**
## Proposed changes

Adding a null-check to fix an earlier breaking change. Fixes https://github.com/webdriverio/webdriverio/issues/8973

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Nice simple fix! Mind raising the same PR for the `v7` branch so we can release it for the current `stable` version?

**Comment by christian-bromann** [comment]
Why did this PR get closed?

**Comment by Joosakur** [comment]
> Why did this PR get closed?

I closed it as I first understood that I should have made the PR against v7 instead 😅 but got you now. I'll leave this open and create another fresh PR against the v7 branch later 👍

**Review by christian-bromann — APPROVED** [review]
LGTM, thank you! 👍

**Pull request merged**
