### PR TITLE
fix(webdriverio): don't support deep piercing in iframes

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

It doesn't seem to be currently supported to locate nodes using Bidi primitives when in an iframe.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by danielhjacobs** [comment]
> It doesn't seem to be currently supported to locate nodes using Bidi primitives when in an iframe.

So how can we locate nodes within an iframe/frame with v9?

**Comment by christian-bromann** [comment]
> So how can we locate nodes within an iframe/frame with v9?

Theoretically yes, the problem is that while we can do look-ups in `iframe`s and we can switch frames before interacting with elements, we have the limitation that this would only work if you interact with a single element, e.g.:

```ts
// works
$('element-within-iframe').getText()
// fails
$$('element-within-iframe').map((el) => el.getText())
```

Hence we decided to not support this yet until we have a solution to this.

**Comment by danielhjacobs** [comment]
Isn't this a regression from v8: see https://github.com/webdriverio/webdriverio/issues/13384 ?

**Comment by danielhjacobs** [comment]
In other words, is there a way I can rewrite https://github.com/ruffle-rs/ruffle/blob/master/web/packages/selfhosted/test/polyfill/classic_frames_injected/test.ts and similar tests?

**Comment by danielhjacobs** [comment]
So for https://github.com/ruffle-rs/ruffle/blob/master/web/packages/selfhosted/test/polyfill/iframes_provided/test.ts, I had an idea to work around this and it seems close to working but I'm having trouble finishing supporting it. Do you know what I'm doing wrong?

```diff
-        await browser.$("ruffle-object").waitForExist();
+        await browser
+            .$(() =>
+                document
+                    .querySelector("#test-frame")
+                    .contentDocument.body.querySelector("ruffle-object"),
+            )
+            .waitForExist();
-        const actual = await browser
-            .$("#test-container")
+        const actual = await browser
+            .$(() =>
+                document
+                    .querySelector("#test-frame")
+                    .contentDocument.body.querySelector(
+                        "#test-container",
+                    ),
+            )
             .getHTML({ includeSelectorTag: false, pierceShadowRoot: false });

```I get an error `TypeError: $3 is not a function` from the `const actual = await browser` line. It's specifically related to the await. If I do the same line as `const promise = browser`, I don't get any error, but of course then `expect(promise).html.to.equal(expected);` says that the promise doesn't equal the string. It doesn't matter where I put the `await` or if I use `resolve`, no matter what I get the TypeError wherever I put the await or resolve.

**Comment by christian-bromann** [comment]
> Isn't this a regression from v8: see #13384 ?

I haven't looked into this bug but no, v8 didn't support iframe lookups, you have to switch into the frame first.

Chances are that there are some regression in regards to using a function as selector, I will have to look into that. Any contributions are appreciated.

**Comment by danielhjacobs** [comment]
I must have misunderstood. We weren't using a function as a selector before though. I switched to that because the CSS selector of ruffle-object within the iframe/frame wasn't working even after switching into the frame in v9, even though it worked in v8.

**Comment by danielhjacobs** [comment]
Maybe I misunderstand, but whether intentional or not, isn't this condition true when using a string CSS selector after switching into an iframe? 

`this.isBidi`: True if there is WebDriver Bidi support

`typeof selector === 'string'`: True for "ruffle-object" as the selector

`selector.startsWith(DEEP_SELECTOR)`: False because "ruffle-object" doesn't start with ">>>"

`shadowRootManager.isWithinFrame(`: True because we are inside a frame so the shadow root is too.

**Comment by christian-bromann** [comment]
Let's continue this conversation in #13384 or create a new issue if this is different.

**Pull request merged**
