### PR TITLE
6859 - Fixes the issue where wdio before/after Step gets wrapped around a Cucumber Before/After Step

### LINKED ISSUE #6859: Make Cucumber before/after step hooks trigger before/after wdio hooks
Please see #6838 

Currently if you have an `beforeStep` or `afterStep` hook defined in Cucumber it would trigger the `beforeStep`/`afterStep` WebdriverIO hooks where in reality it should trigger `beforeHook`/`afterHook`.

As this is a breaking change let's plan a fix for v8.

### PR DESCRIPTION
**Pull request by jonn-set**
## Proposed changes

[//]: # Fixes #6859 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # It removes parameter `context` returned to `beforeStep` & `afterStep` and instead returns `scenario` object and also returns a `boolean` for passed as 3rd parameter in `afterStep`

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
This makes totally sense, thanks so much! 👍

**Comment by jonn-set** [comment]
> This makes totally sense, thanks so much! 👍

@christian-bromann can you help me with the test failures please. I am unable to run the command `npm run setup-full` on `main` branch. I am getting this error.
image

Only line the file, `shared-store-service.d.ts` has is 
```
../../shared-store-service.d.ts
```
And there's no such file in that location

**Comment by christian-bromann** [comment]
> @christian-bromann can you help me with the test failures please.

It seems that your pipeline is failing because of the smoke tests not because of a compile error. Seems that your dev environment is not clean. Maybe try to set up a fresh installalation?

**Comment by jonn-set** [comment]
> > @christian-bromann can you help me with the test failures please.
> 
> It seems that your pipeline is failing because of the smoke tests not because of a compile error. Seems that your dev environment is not clean. Maybe try to set up a fresh installalation?

@christian-bromann, can you approve please? My earlier changes had taken `beforeHook`/`afterHook` out, I have reinstated it now and this is how it runs now:
image

As you might notice, it only runs `beforeHook`/`afterHook` around Cukes Hooks and not WDIO hooks. Hope this is the expected behaviour.

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
This started to appear on `main` as well, I can fix it and give you an update so you can update your branch.

**Comment by jonn-set** [comment]
> This started to appear on `main` as well, I can fix it and give you an update so you can update your branch.
Thanks 👍

**Comment by christian-bromann** [comment]
I updated the `main` branch, please update yours to fix the pipeline.

**Comment by christian-bromann** [comment]
> [@jonn-set](/jonn-set) [jonn-set](/jonn-set) requested a review from [christian-bromann](/christian-bromann) [1 hour ago](#event-4778031100)

It seems the pipeline is still broken, please update your branch.

**Comment by christian-bromann** [comment]
It seems that there are still one snapshot failing.

**Comment by jonn-set** [comment]
> It seems that there are still one snapshot failing.

Unit test cases are missing /broken and snapshot missing, I will fix in a bit and push.

Cheers

**Comment by jonn-set** [comment]
> It seems that there are still one snapshot failing.

Pushed, please approve

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
