### PR TITLE
Enable support for both --inspect and --debug

### PR DESCRIPTION
**Pull request by codiophile**
## Proposed changes

As promised in #2350 here's the pull request for enabling debugging for newer versions of node.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

I didn't have the chance to fully test this yet and I didn't update the documentation. The logic is put directly in `startInstance`, but could be broken out into its own function, which would make it unit testable. #2350 was done in a similar fashion, so I'm not sure unit tests are considered important for this functionality.

### CODE REVIEW

**Comment by christian-bromann** [comment]
How is this different from #2350?

**Comment by codiophile** [comment]
> How is this different from #2350?

It addresses all the concerns I had with #2350 as per my [comment](https://github.com/webdriverio/webdriverio/pull/2350#issuecomment-341683970) and adds a few additional improvements. Here's the list:

1. The children inherit the debug flag from its parent, rather than adding it if `debug` is set in the configuration.

2.  The children will use `--inspect` in case the parent is using `--inspect` and `--debug` if the parent is using `--debug`. This means that we do not have to worry about the node version, since the user will start the parent with the appropriate flag for the version of node he or she is using.

3. It passes on the host from the parent to the children. I'm not sure how used this feature is, but it was simple enough to add it.

4. Under no circumstances will it run the children with both `--debug` and `--inspect`, which is something #2350 would do.

**Comment by codiophile** [comment]
@christian-bromann I've been using this quite successfully for a while now. I would appreciate feedback on what's missing to get this merged. I can see that the tests are failing, but I don't really see why `sauce-connect-launcher` would be affected by this change. Maybe you could help me figure out if it is a side effect of this change?

In addition to this change, the `debug` option in the config should be properly deprecated. Alternatively we could keep it and hide this functionality behind that option, but I'm not sure why we would want that. I haven't done that yet, because I'd like to know if this will get merged before investing more time in it.

**Comment by christian-bromann** [comment]
> what's missing to get this merged

My lack of time 😉 

> I can see that the tests are failing

Because travis is not setup properly to run tests on SauceLabs when you propose PRs. I haven't got around to fix this.

> In addition to this change, the debug option in the config should be properly deprecated.

Once we stop supporting node v5 and lower we can remove it completely.

**Comment by mltsy** [comment]
Yay! :confetti_ball: Thanks for fixing this :+1:

**Comment by mltsy** [comment]
It might be a good time to switch these sections around to make Node 6+ the main documented strategy, and link to a special section for "Node versions < 6.3": http://webdriver.io/guide/testrunner/debugging.html#Node-Inspector

**Pull request merged**
