### PR TITLE
fix methods for the multiremote

### PR DESCRIPTION
**Pull request by elaichenkov**
## Proposed changes

bugfix: #6760 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks for raising the PR 👏 

I suggest to add a smoke test to https://github.com/webdriverio/webdriverio/blob/main/tests/multiremote/test.js where a command is called via `browser.<browserName>.<command>()` so we can ensure it works properly. You can read more about our smoke tests in the [contribution guidelines](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#run-e2e-experience-with-smoke-tests). Let me know if you have any questions.

**Comment by elaichenkov** [comment]
I've just pushed one test, but again I'm not sure that's what we actually need for that case :(
So, feel free to modify it :)

**Comment by christian-bromann** [comment]
@elaichenkov the smoke test the way you put it makes sense. However when I reviewed the change as a whole it turns out that it already got fixed by this patch: #6759. Can you double check? In this case I would suggest to not merge given that adding `writeable` is not really necessary.

**Comment by elaichenkov** [comment]
I've just tested it with the patch you've mentioned, but unfortunately, the problem still exists with the same message: we cannot assign it to read-only property. After adding the `writable` property the issue seems to be disappeared.

**Comment by christian-bromann** [comment]
@elaichenkov you are right, the only problem is that the smoke test also passes without the change. So running the example using the example wdio script fails but running the multiremote smoke test passes just fine.

**Comment by christian-bromann** [comment]
A bit of investigation showed that `_NOT_FIBER` is where the error is thrown in the passing case `undefined` and in the failing case a `[Function: wrapCommandFn]`

**Comment by elaichenkov** [comment]
> @elaichenkov you are right, the only problem is that the smoke test also passes without the change. So running the example using the example wdio script fails but running the multiremote smoke test passes just fine.

Totally agree with you.


> A bit of investigation showed that `_NOT_FIBER` is where the error is thrown in the passing case `undefined` and in the failing case a `[Function: wrapCommandFn]`

Well, sorry for the silly question but what does it mean for us?

**Comment by christian-bromann** [comment]
> Well, sorry for the silly question but what does it mean for us?

Sorry for not being clear, I did a `console.log(this._NOT_FIBER)` right before the error is thrown and when running with the example files (where it fails) I get `[Function: wrapCommandFn]` and when running using the smoke tests (and where it passes) I get `undefined`. This confuses me because both things run with the same setup (wdio testrunner + `@wdio/sync`). While I am not too much concerned about this it would be great if the multiremote test could help us validate this fix.

**Comment by elaichenkov** [comment]
Oh, I see. 
Thank you for explaining. 
I'll try to explore it and conduct a root cause.

**Comment by konstantin-gorbachev-Simpligov** [comment]
New updates. Also when I try use `await browser.url("/")` in async mode. Have the error: **Cannot assign to read only property '_NOT_FIBER' of object '#<MultiRemoteDriver>'**

**Comment by christian-bromann** [comment]
What is the status of this? Anything I can do to help move this forward?

**Comment by elaichenkov** [comment]
Sorry, I haven't gotten a chance to take a look at this yet.

**Comment by christian-bromann** [comment]
Closing due to inactivity. I believe this is fixed now.

**Pull request closed without merging**
