### PR TITLE
Add missing start <a> element.

### PR DESCRIPTION
**Pull request by graingert**
doc fix

### CODE REVIEW

**Comment by christian-bromann** [comment]
This actually is not a fix. The example should demonstrate how to fetch an element by any text not just by link text

**Comment by graingert** [comment]
@christian-bromann that is what the example shows.

**Comment by christian-bromann** [comment]
The example above shows for tag name + text, the modified example should show with classname or id + text

**Comment by graingert** [comment]
@christian-bromann it still shows classname or id + text

**Comment by christian-bromann** [comment]
Yes so I don't understand why we need an extra link around it?

**Comment by christian-bromann** [comment]
we can replace the div with h1 tho

**Comment by christian-bromann** [comment]
@graingert ahh no I get it. Fixed the issue.

**Pull request closed without merging**
