### PR TITLE
Use expectAsync for jasmine tests

### LINKED ISSUE #6839: Async (TS) samples are not working with Jasmine and Expect
**Describe the bug**
When using the default examples from WDIO in combination with Jasmine the following code fails

`await expect(SecurePage.flashAlert).toHaveTextContaining('You logged into a secure area!');`

Because the promise is not resolved before executing the assertion

**To Reproduce**
Set up a new project by following the instructions from https://webdriver.io/docs/gettingstarted and choose the following options:

```log
=========================
WDIO Configuration Helper
=========================

? Where is your automation backend located? On my local machine
? Which framework do you want to use? jasmine
? Do you want to use a compiler? TypeScript (https://www.typescriptlang.org/)
? Where are your test specs located? ./test/specs/**/*.ts
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? ./test/pageobjects/**/*.ts
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? chromedriver
? What is the base url? http://localhost

```

It then mentions `npx wdio run wdio.conf.js`, which needs to be `npx wdio run wdio.conf.ts`

**Expected behavior**
The promises for `expect-webdriverio` are resolved before using the matchers

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**
```log
npx wdio run wdio.conf.ts

Execution of 1 spec files started at 2021-05-10T10:18:14.174Z

2021-05-10T10:18:14.230Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2021-05-10T10:18:14.351Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-05-10T10:18:14.351Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.ts
[0-0] 2021-05-10T10:18:14.774Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /test/specs/example.e2e.ts
[0-0] 2021-05-10T10:18:15.163Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-05-10T10:18:15.163Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2021-05-10T10:18:15.163Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2021-05-10T10:18:17.281Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2021-05-10T10:18:17.282Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/url
[0-0] 2021-05-10T10:18:17.282Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2021-05-10T10:18:20.043Z INFO webdriver: COMMAND findElement("css selector", "#username")
[0-0] 2021-05-10T10:18:20.043Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element
[0-0] 2021-05-10T10:18:20.043Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2021-05-10T10:18:20.056Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '98425206-3be5-46f7-a7b1-0de781666e0f'
[0-0] }
[0-0] 2021-05-10T10:18:20.061Z INFO webdriver: COMMAND elementClear("98425206-3be5-46f7-a7b1-0de781666e0f")
[0-0] 2021-05-10T10:18:20.061Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element/98425206-3be5-46f7-a7b1-0de781666e0f/clear
[0-0] 2021-05-10T10:18:20.086Z INFO webdriver: COMMAND elementSendKeys("98425206-3be5-46f7-a7b1-0de781666e0f", "<Screenshot[base64]>")
[0-0] 2021-05-10T10:18:20.086Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element/98425206-3be5-46f7-a7b1-0de781666e0f/value
[0-0] 2021-05-10T10:18:20.086Z INFO webdriver: DATA { text: 'tomsmith' }
[0-0] 2021-05-10T10:18:20.224Z INFO webdriver: COMMAND findElement("css selector", "#password")
[0-0] 2021-05-10T10:18:20.224Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element
[0-0] 2021-05-10T10:18:20.224Z INFO webdriver: DATA { using: 'css selector', value: '#password' }
[0-0] 2021-05-10T10:18:20.232Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '01be7ef9-4272-428e-a269-72bd516feb01'
[0-0] }
[0-0] 2021-05-10T10:18:20.234Z INFO webdriver: COMMAND elementClear("01be7ef9-4272-428e-a269-72bd516feb01")
[0-0] 2021-05-10T10:18:20.234Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element/01be7ef9-4272-428e-a269-72bd516feb01/clear
[0-0] 2021-05-10T10:18:20.257Z INFO webdriver: COMMAND elementSendKeys("01be7ef9-4272-428e-a269-72bd516feb01", "SuperSecretPassword!")
[0-0] 2021-05-10T10:18:20.257Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element/01be7ef9-4272-428e-a269-72bd516feb01/value
[0-0] 2021-05-10T10:18:20.257Z INFO webdriver: DATA { text: 'SuperSecretPassword!' }
[0-0] 2021-05-10T10:18:20.308Z INFO webdriver: COMMAND findElement("css selector", "button[type="submit"]")
[0-0] 2021-05-10T10:18:20.308Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element
[0-0] 2021-05-10T10:18:20.308Z INFO webdriver: DATA { using: 'css selector', value: 'button[type="submit"]' }
[0-0] 2021-05-10T10:18:20.316Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '627ab543-42a4-493d-86f1-406db2db7c77'
[0-0] }
[0-0] 2021-05-10T10:18:20.317Z INFO webdriver: COMMAND elementClick("627ab543-42a4-493d-86f1-406db2db7c77")
[0-0] 2021-05-10T10:18:20.317Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element/627ab543-42a4-493d-86f1-406db2db7c77/click
[0-0] 2021-05-10T10:18:20.694Z INFO webdriver: COMMAND findElement("css selector", "#flash")
[0-0] 2021-05-10T10:18:20.695Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element
[0-0] 2021-05-10T10:18:20.695Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2021-05-10T10:18:20.696Z INFO webdriver: COMMAND findElement("css selector", "#flash")
[0-0] 2021-05-10T10:18:20.696Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/element
[0-0] 2021-05-10T10:18:20.696Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] Error in "My Login application should login with valid credentials"
Error: Expected [object Promise] to be existing.
    at <Jasmine>
    at <Jasmine>
    at /Users/wimselles/Sauce/Git/appium-boilerplate/.tmp/test/specs/example.e2e.ts:9:45
    at Generator.next (<anonymous>)
[0-0] 2021-05-10T10:18:20.700Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-05-10T10:18:20.700Z INFO webdriver: [DELETE] http://localhost:9515/session/6b117cd714324517f85788847f258356
[0-0] 2021-05-10T10:18:20.707Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '6639df39-ad33-4fa3-93d2-c943a5900ed1'
[0-0] }
[0-0] 2021-05-10T10:18:20.709Z INFO webdriver: COMMAND getElementText("6639df39-ad33-4fa3-93d2-c943a5900ed1")
[0-0] 2021-05-10T10:18:20.709Z INFO webdriver: [GET] http://localhost:9515/session/6b117cd714324517f85788847f258356/element/6639df39-ad33-4fa3-93d2-c943a5900ed1/text
[0-0] 2021-05-10T10:18:20.711Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '6639df39-ad33-4fa3-93d2-c943a5900ed1'
[0-0] }
[0-0] 2021-05-10T10:18:20.716Z INFO webdriver: COMMAND findElements("css selector", "#flash")
[0-0] 2021-05-10T10:18:20.716Z INFO webdriver: [POST] http://localhost:9515/session/6b117cd714324517f85788847f258356/elements
[0-0] 2021-05-10T10:18:20.716Z INFO webdriver: DATA { using: 'css selector', value: '#flash' }
[0-0] 2021-05-10T10:18:20.791Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
[0-0] 2021-05-10T10:18:20.793Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
[0-0] FAILED in chrome - /test/specs/example.e2e.ts
2021-05-10T10:18:20.886Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 90.0.4430.93 mac os x #0-0] Running: chrome (v90.0.4430.93) on mac os x
[chrome 90.0.4430.93 mac os x #0-0] Session ID: 6b117cd714324517f85788847f258356
[chrome 90.0.4430.93 mac os x #0-0]
[chrome 90.0.4430.93 mac os x #0-0] » /test/specs/example.e2e.ts
[chrome 90.0.4430.93 mac os x #0-0] My Login application
[chrome 90.0.4430.93 mac os x #0-0]    ✖ should login with valid credentials
[chrome 90.0.4430.93 mac os x #0-0]
[chrome 90.0.4430.93 mac os x #0-0] 1 failing (3.4s)
[chrome 90.0.4430.93 mac os x #0-0]
[chrome 90.0.4430.93 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 90.0.4430.93 mac os x #0-0] Expected [object Promise] to be existing.
[chrome 90.0.4430.93 mac os x #0-0] Error: Expected [object Promise] to be existing.
[chrome 90.0.4430.93 mac os x #0-0]     at <Jasmine>
[chrome 90.0.4430.93 mac os x #0-0]     at <Jasmine>
[chrome 90.0.4430.93 mac os x #0-0]     at /Users/wimselles/Sauce/Git/appium-boilerplate/.tmp/test/specs/example.e2e.ts:9:45
[chrome 90.0.4430.93 mac os x #0-0]     at Generator.next (<anonymous>)
[chrome 90.0.4430.93 mac os x #0-0] Expected [object Promise] to have text containing 'You logged into a secure area!'.
[chrome 90.0.4430.93 mac os x #0-0] Error: Expected [object Promise] to have text containing 'You logged into a secure area!'.
[chrome 90.0.4430.93 mac os x #0-0]     at <Jasmine>
[chrome 90.0.4430.93 mac os x #0-0]     at <Jasmine>
[chrome 90.0.4430.93 mac os x #0-0]     at /Users/wimselles/Sauce/Git/appium-boilerplate/.tmp/test/specs/example.e2e.ts:10:45
[chrome 90.0.4430.93 mac os x #0-0]     at Generator.next (<anonymous>)
[chrome 90.0.4430.93 mac os x #0-0] Expected [object Promise] to be existing.
[chrome 90.0.4430.93 mac os x #0-0] error properties: Object({ matcherName: 'toBeExisting', passed: undefined, expected: [  ], actual: [object Promise] })
[chrome 90.0.4430.93 mac os x #0-0] Error: Expected [object Promise] to be existing.
[chrome 90.0.4430.93 mac os x #0-0]     at <Jasmine>
[chrome 90.0.4430.93 mac os x #0-0]     at <Jasmine>
[chrome 90.0.4430.93 mac os x #0-0]     at /Users/wimselles/Sauce/Git/appium-boilerplate/.tmp/test/specs/example.e2e.ts:9:45
[chrome 90.0.4430.93 mac os x #0-0]     at Generator.next (<anonymous>)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:06 

2021-05-10T10:18:20.887Z INFO @wdio/local-runner: Shutting down spawned worker
2021-05-10T10:18:21.140Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-05-10T10:18:21.140Z INFO @wdio/local-runner: shutting down
```

> Please use the correct markdown

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

Jasmine uses async matchers called `expectAsync`. We should use them when folks generate a project from the CLI wizard.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

fixes #6839

### CODE REVIEW

**Review by wswebcreation — CHANGES_REQUESTED** [review]
Looks good to me, but can we or update the docs that people need to use the `expectAsync` with Jasmine, or use a global function that will translate the `expect` into `expectAsync` so it will be generic for all frameworks?

**Comment by christian-bromann** [comment]
mhm .. there are multiple options here:

- rename global variable `expectAsync` to `expect` which would resolve the issue but would not allow anymore to do things like:
    ```js
    const title = await browser.getTitle()
    expect(title).toBe('foobar')
    ```
    this would fail with: `expect(...).toBe is not a function`
- just replace the Jasmine `expect` global with the `expect-webdriverio` one, but than we would not have the following matchers anymore: `toBeNegativeInfinity`, `toBePositiveInfinity`, `toHaveBeenCalledBefore`, `toThrowMatching`, `withContext`, `toHaveSize`, `toHaveClass`
- document that for jasmine , folks have to use `expectAsync` and hopefully get sync working eventually

What would you suggest?

**Comment by wswebcreation** [comment]
Good catch @christian-bromann 

I don't know how much work it is, but what if the matcher `toBeNegativeInfinity, toBePositiveInfinity, toHaveBeenCalledBefore, toThrowMatching, withContext, toHaveSize, toHaveClass` are added and the Jasmine expect is completely replaced by the one from `expect-webdriverio`

Or just accept that these matchers will be overwritten and mention that in the docs of `expect-webdriverio`

**Comment by christian-bromann** [comment]
Closing in favor of webdriverio/expect-webdriverio#545

**Pull request closed without merging**
