### PR TITLE
Added documentation for services

### PR DESCRIPTION
**Pull request by mhemesath**
## Proposed changes

Added documentation to create custom services.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mhemesath** [comment]
That makes sense but I was following the pattern of reports. The [Custom reporter documentation](http://webdriver.io/guide/reporters/customreporter.html) currently exists alongside the reporters. Would you like me to also move that under testrunner for consistency?

**Comment by christian-bromann** [comment]
> Would you like me to also move that under testrunner for consistency?

Yes, that would be great

**Comment by christian-bromann** [comment]
@mhemesath would you mind to sign the cla? Didn't see that you didn't do it yet!

**Comment by mhemesath** [comment]
I believe I signed it already. When I visit the [CLA](https://cla.js.foundation/webdriverio/webdriverio) it says its signed. Let me know if there is something else I need to do. Thanks!

**Pull request merged**
