### PR TITLE
Updated wdio.conf.ejs

### PR DESCRIPTION
**Pull request by nyarasha**
Updated spelling and grammar of wdio.conf.ejs so comments are more readable.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@nyarasha thanks so much! Could you also apply these changes to `/examples/wdio.conf.js`?

**Comment by nyarasha** [comment]
@christian-bromann Sure! I'll take a look right now and update the request.

**Comment by nyarasha** [comment]
@christian-bromann Ok, updated both files and they should be in sync.

**Comment by christian-bromann** [comment]
Awesome! Thanks!

**Pull request merged**
