### PR TITLE
Fix typo in call.ts

### PR DESCRIPTION
**Pull request by zeljkofilipin**
Change `depcrecating` to `deprecating`.

## Proposed changes

The commit only fixes a typo I've noticed.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@zeljkofilipin thanks for the change, mind signing the CLA?

**Comment by zeljkofilipin** [comment]
@christian-bromann sure, I'm waiting for reply from my company on what type of CLA to sign (individual or corporate).

**Comment by christian-bromann** [comment]
@zeljkofilipin any updates?

**Comment by zeljkofilipin** [comment]
@christian-bromann Sorry, I was busy with other things. Also, this seems to be more complicated that I thought. 😅 I'm working on it.

**Comment by christian-bromann** [comment]
Fixed by https://github.com/webdriverio/webdriverio/commit/109b70358747d72c178149d0b0fc1eebee82b08d

**Pull request closed without merging**
