### PR TITLE
Fix missing mocha test hooks in a junit report

### PR DESCRIPTION
**Pull request by vgrigoruk**
## Proposed changes

After upgrading to wdio 6 (and mocha 8), we have noticed that junit report doesn't contain failed mocha hooks anymore.

It looks like mocha test hook titles are changed in mocha 8. Previously, it is used to be `"before all" hook"`, `"after all" hook`, etc, but now it is `"before all" hook for "test name"`.
This PR fixes the condition used to add `failed` hooks to a generated junit report. It also adds `beforeEach/afterEach` hooks to the junit report.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
Can you please add a test for that?

**Review by emilyrohrbough — APPROVED** [review]

**Comment by christian-bromann** [comment]
@vgrigoruk please let us know if we can help you with the unit tests 😉

**Comment by vgrigoruk** [comment]
We already have a test for`before all` and `after all` hooks (however, the fixture data have titles in a pre-mocha-8 format and that's why it didn't fail previously). I've kept this test as is to prove the change is backward-compatible.
I've also added tests for failed `before each` and `after each` hooks, which test against mocha 8 format of hook `title` field.

**Review by christian-bromann — APPROVED** [review]
👍 thank you!

**Pull request merged**
