### PR TITLE
Update the types for suites to fix the compile error

### PR DESCRIPTION
**Pull request by iamatharva**
## Proposed changes

The proposed changes aim to fix a type definition issue in the suites configuration in the webdriverIO codebase. Currently, the type definition does not accurately represent the allowed data structure, leading to compilation errors in VS Code. This PR adjusts the type definition to support a mixture of single strings and string arrays in the suites configuration, resolving the compilation error.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [x] Back-ported PR at `#XXXXX`

## Further comments

I've thoroughly tested these changes locally to ensure they resolve the compilation error in VS Code. If you have any questions or need further clarification on any aspect of this PR, please let me know.

### CODE REVIEW

**Comment by iamatharva** [comment]
It will resolve the following bug https://github.com/webdriverio/webdriverio/issues/12849

**Comment by iamatharva** [comment]
@christian-bromann Initially EsayCLA check was failing for me and after figuring out how to fix that,
 I fixed it and modified the commit history to keep it clean.
Hopefully, my first open-source contribution to the world and to the WDIO will be accepted.

**Comment by christian-bromann** [comment]
> * This change is solely for `v9` and doesn't need to be back-ported

Are you sure you don't like to backport this for v8?

**Comment by iamatharva** [comment]
The option was a bit confusing for me as a first-time contributor as it ask to point to pr XXXXX.
Now deselected the previous option and selected the backpot option.

**Comment by christian-bromann** [comment]
@iamatharva mind raising the same PR to the `v8` branch then?

**Comment by christian-bromann** [comment]
Nevermind, let me cherry-pick this.

**Review by christian-bromann — APPROVED** [review]
👍

**Pull request merged**
