### PR TITLE
Migration to Docusaurus v2

### LINKED ISSUE #5522: Move docs to Docosaurus v2
The tool for generating the docs (Docosaurus) has publish a [v2](https://v2.docusaurus.io/) of their framework. We should transition over to use the new version.

### PR DESCRIPTION
**Pull request by JapneetSingh5**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Migrating site to Docusaurus v2
Resolves #5522 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@JapneetSingh5 what is the status of this? Based on the current changes it doesn't look like this is for review yet.

**Comment by JapneetSingh5** [comment]
I can't move forward without all the Markdown files being converted to MDX.

**Comment by christian-bromann** [comment]
> without all the Markdown files being converted to MDX.

Can't this be part of this PR? What is blocking your from converting them?

**Comment by JapneetSingh5** [comment]
I am not able to fix the lint errors, somehow new ones keep cropping up. Is there an automated tool that you recommend which can work well here? Manually going through all the files will be a very lengthy task.

**Comment by christian-bromann** [comment]
> Is there an automated tool that you recommend which can work well here?

I am not aware of such a tool. Can you describe what kind of lint errors crop up? I wasn't aware that *.mdx is that much different from standard markdown files.

> Manually going through all the files will be a very lengthy task.

Maybe creating separate, well described issues of what needs to be done helps others to participate in this effort.

**Comment by christian-bromann** [comment]
@JapneetSingh5 any updates?

**Comment by JapneetSingh5** [comment]
My college started a couple of weeks ago and its exam time right now. Extremely hard to work on OS projects these days. Really sorry for this.

**Comment by JapneetSingh5** [comment]
However, Docusaurus has now released the migration cli. It supports a --mdx flag which automatically converts md into mdx. Should work out pretty well, just haven't got time to try it out yet.

**Comment by christian-bromann** [comment]
Gotcha, no pressure, just wanted to check in.

**Comment by christian-bromann** [comment]
@JapneetSingh5 I am inclined to close this given we haven't seen any progress on this effort. What do you think?

**Comment by christian-bromann** [comment]
Closing.

**Pull request closed without merging**
