### PR TITLE
Fixes type generation for URL variables

### PR DESCRIPTION
**Pull request by ablok**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

This PR fixes the webdriver type generation. When there were more URL variables than `sessionId` or `elementId` they would not end up in the typings as input parameters.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)
Since the variables are in the url, they are always of type `string` and can not be optional.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@StephenABoyd do you mind taking a look?

**Comment by ablok** [comment]
Actually, just thought of something. Would variables come before parameters in the input parameters? Or the other way around? Or does one exclude the other?

**Comment by christian-bromann** [comment]
> Would variables come before parameters in the input parameters?

Yes, here is an example:

```json
  "/session/:sessionId/element/:elementId/element": {
    "POST": {
      "command": "findElementFromElement",
      "description": "The Find Element From Element command is used to find an element from a web element in the current browsing context that can be used for future commands.",
      "ref": "https://w3c.github.io/webdriver/#dfn-find-element-from-element",
      "variables": [{
        "name": "elementId",
        "description": "the id of an element returned in a previous call to Find Element(s)"
      }],
      "parameters": [{
        "name": "using",
        "type": "string",
        "description": "a valid element location strategy",
        "required": true
      }, {
        "name": "value",
        "type": "string",
        "description": "the actual selector that will be used to find an element",
        "required": true
      }],
      "returns": {
        "type": "String",
        "name": "element",
        "description": "A JSON representation of an element object."
      }
    }
  },
```
If you want to call this command you would need to do this:
```js
// packages⁩/⁨webdriverio⁩/src/commands/element⁩/selectByAttribute.js
const normalized = `[normalize-space(@${attribute.trim()}) = "${value.trim()}"]`
    const optionElement = await this.findElementFromElement(this.elementId, 'xpath', `./option${normalized}|./optgroup/option${normalized}`)
```

**Comment by ablok** [comment]
Switched the order so that variables will be the first input parameters.

**Pull request merged**
