### PR TITLE
Update services.json

### PR DESCRIPTION
**Pull request by tzurp**
## Proposed changes

[//]: # Adding the performance service docs to the official webdriver.io page.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Very interesting service you build there 👍  Do you have a link to where the source code is hosted?

**Comment by tzurp** [comment]
Hi Christian,

Thanks!
The source code is currently in a private repository at GitHub. Is there a requirement to expose it?

Regards,

Tzur


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by christian-bromann** [comment]
> The source code is currently in a private repository at GitHub. Is there a requirement to expose it?

No, but I would recommend to do that so WebdriverIO user can propose changes and help maintaining the service. It is also more trustworthy if the service code is open sourced.

**Comment by tzurp** [comment]
Hi Christian,
I guess I’ll follow your recommendation and make it public soon.

Thanks,

Tzur

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tzurp** [comment]
The public repository is here: [https://github.com/tzurp/performance-total](https://github.com/tzurp/performance-total)
Should I raise another PR with this link?

**Pull request merged**
