### PR TITLE
(scripts): migrate AWS SDK for JavaScript v2 APIs to v3

### PR DESCRIPTION
**Pull request by trivikr**
## Proposed changes

This PR migrates AWS SDK for JavaScript v2 APIs to v3 in scripts

From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.

## Types of changes

Updating scripts

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Awesome to see the SDK supporting promises 🙌 

LGTM 👍

**Comment by christian-bromann** [comment]
@trivikr thanks for raising the PR and helping to transition to the new major version. Really appreciate it!

**Comment by christian-bromann** [comment]
I am seeing some issues deploying the docs:

```
Uploading /home/runner/work/webdriverio/webdriverio/website/build to S3 bucket webdriver.io
Invalidate objects from distribution ***
/home/runner/work/webdriverio/webdriverio/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10
        throw new Error("Region is missing");
              ^

Error: Region is missing
    at default (/home/runner/work/webdriverio/webdriverio/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /home/runner/work/webdriverio/webdriverio/node_modules/@smithy/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /home/runner/work/webdriverio/webdriverio/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at async coalesceProvider (/home/runner/work/webdriverio/webdriverio/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async /home/runner/work/webdriverio/webdriverio/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28
    at async useFipsEndpoint (/home/runner/work/webdriverio/webdriverio/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
    at async resolveParams (/home/runner/work/webdriverio/webdriverio/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:37:40)
    at async getEndpointFromInstructions (/home/runner/work/webdriverio/webdriverio/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:15:28)
    at async /home/runner/work/webdriverio/webdriverio/node_modules/@smithy/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
    at async /home/runner/work/webdriverio/webdriverio/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

Any idea what that could be?

**Comment by trivikr** [comment]
```console
        throw new Error("Region is missing");
              ^
```

How was region set earlier in JS SDK v2?

The S3 client is created without any configuration in source code https://github.com/webdriverio/webdriverio/blob/81496a30b1c50e7d4129be6997f1a557f9659224/scripts/updateDocs.js#L27

The infrastructure might be setting region somewhere else, like in `AWS_REGION` environment variable, or `region` in shared ini.

**Comment by christian-bromann** [comment]
Good question, it seems like it wasn't set before at all.

**Comment by christian-bromann** [comment]
Found another issue 😉  https://github.com/webdriverio/webdriverio/commit/a64ed8652726905f535377e7830196586dcd9533#diff-b5dd452c7b25cc1278ad2baf3ac8c31e2348b59ebba6eab66655722917a98c47R38

**Pull request merged**
