### PR TITLE
Upgrade lighthouse dependencies and fix performance tests

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

supersedes #6961

This patch bumps Lighthouse and Puppeteer versions and makes sure performance tests work again.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

Thanks @esaari for your help on this!

### CODE REVIEW

**Comment by christian-bromann** [comment]
This is blocked on a weird behavior in Chrome where it doesn't install a web manifest if the devtools app is not being opened. This requires some additional investigation.

**Comment by esaari** [comment]
Will address https://github.com/webdriverio/webdriverio/issues/6932 and https://github.com/webdriverio/webdriverio/issues/6604 once complete.

**Comment by christian-bromann** [comment]
We should also add `firstInputDelay` metric.

**Comment by christian-bromann** [comment]
> We should also add `firstInputDelay` metric.

Already added via `maxPotentialFID`

**Comment by christian-bromann** [comment]
The problem with moving this forward is that there is a weird behavior with Chrome DevTools. Given you have the following test script:

```js
describe('webdriver.io page', () => {
    it('should have the right title', () => {
        browser.url('https://webdriver.io')
        const result = browser.checkPWA()
        console.log(result)
    })
})
```
Lighthouse would detect the ServiceWorker to be registered and starting:

```
[0-0] RECEIVED {
[0-0]   versions: [
[0-0]     {
[0-0]       versionId: '0',
[0-0]       registrationId: '0',
[0-0]       scriptURL: 'https://webdriver.io/sw.js?params=%7B%22offlineMode%22%3Afalse%2C%22debug%22%3Afalse%7D',
[0-0]       runningStatus: 'starting',
[0-0]       status: 'new',
[0-0]       scriptLastModified: 0,
[0-0]       scriptResponseTime: 0,
[0-0]       controlledClients: [],
[0-0]       targetId: '95432B44D4DB8620E7B9509D94E698E7'
[0-0]     }
[0-0]   ]
[0-0] }
```
But then no other events happen until you open the DevTools app. I wonder which CDP commands trigger the commands to come in. This needs some further investigation.

**Comment by esaari** [comment]
A couple thoughts - 
1. I had not noticed that Lighthouse 8.0 will be shipping with Chrome version 93: https://github.com/GoogleChrome/lighthouse/blob/v8.1.0/changelog.md#800-2021-06-02
The latest stable version is still 92.x.  It may be worth trying this on a dev build of Chrome 93 or waiting until it hits the stable channel to see if the changes now spin up the worker. 
2. Lighthouse is now bumped to 8.1: https://github.com/GoogleChrome/lighthouse/blob/v8.1.0/changelog.md#800-2021-06-02  I am unsure how to bump that here without opening a superseding PR.

**Comment by tobeliketree** [comment]
I am also curious of an update on this.   I believe the bug I reported is also related to this. https://github.com/webdriverio/webdriverio/issues/7233. 

It's rendered dev-tools completely inoperable  for us and we use dev tools in a number of ways from throttle to performance testing.  When this issue shows and it's all the time now pages just don't render and ever test fails.

**Comment by esaari** [comment]
I'm having trouble getting a solid reproduction of the issue. If anybody would like to assist, a good first step would be to file a bug report within the Lighthouse package: https://github.com/GoogleChrome/lighthouse/issues and see what they say, and possibly cross-reference this issue. @tobeliketree perhaps you could help us with this?

**Comment by christian-bromann** [comment]
Raised an issue in the Lighthouse project: https://github.com/GoogleChrome/lighthouse/issues/13127

**Comment by christian-bromann** [comment]
@esaari mind resigning the CLA (we got a new one that is very similar to the old CLA from the JS Foundation).

**Comment by christian-bromann** [comment]
@esaari good news, I was able to fix the problem. Only need to adjust unit tests and clean up some things.

**Comment by christian-bromann** [comment]
🎉

**Pull request merged**
