### PR TITLE
V9 Remove JSONWireProtocol

### LINKED ISSUE #11859: [💡 Feature]: Remove all JSONWireProtocol artifacts
### Is your feature request related to a problem?

Years ago all automation would happen through the JSONWireProtocol which was the predecessor of WebDriver. Today all browser and vendors support WebDriver and there is no reason to keep supporting JSONWireProtocol.

### Describe the solution you'd like.

Remove all artifacts related to the JSONWireProtocol. Note that Appium still uses some JSONWP commands, e.g. `isElementDisplayed` so we should move them to the Appium protocol [dcoument](https://github.com/webdriverio/webdriverio/blob/5a628cb7239f85d2499ce8246f1b999bf55d6734/packages/wdio-protocols/src/protocols/appium.ts).

### Describe alternatives you've considered.

We could keep it but I haven't seen anyone still using it.

### Additional context

This is a v9 task and pull requests should be raised against the [`v9`](https://github.com/webdriverio/webdriverio/tree/v9) branch. Join the `🙏-contribute` channel on [Discord](https://discord.webdriver.io) if you are interested to join us in this effort.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tamil777selvan**
## Proposed changes

Fixes #11859

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
Thanks for the contribution @tamil777selvan , I think we should calling "code-freeze" on the main branch, create a `v8` branch, and continue v9 development on `main`. With those big changes it will be hard, if not impossible to maintain 2 development branches.

Could you do me a favor and join us on Discord? I would love to invite you to the collaborator channel so we can better coordinate the development.

**Comment by christian-bromann** [comment]
@tamil777selvan can you please rebase the PR so we can merge it? I'ld suggest to push your branches directly to this repository so e.g. I could resolve them myself.

**Comment by tamil777selvan** [comment]
> @tamil777selvan can you please rebase the PR so we can merge it? I'ld suggest to push your branches directly to this repository so e.g. I could resolve them myself.

sure @christian-bromann let me do a rebase now.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍  thanks for keeping the JSONWP commands around still used by Appium.

**Comment by allmoatasem** [comment]
@christian-bromann is JSONWP still around in v9.1.0? Our team is running wdio test on android and iOS and `driver.setGeoLocation` isn't recognised anymore. Tests are failing with error `TypeError: driver.setGeoLocation is not a function`.

**Comment by allmoatasem** [comment]
Got to work by installing the standalone https://github.com/webdriverio-community/wdio-jsonwp-service. Thanks still!

**Pull request merged**
