### PR TITLE
Fixed missing github icon on the Team page

### PR DESCRIPTION
**Pull request by arsen1c**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
image

### Fixed the missing github icon on the Team page of the Documentation.
The `GithubLink` component was lacking a github icon SVG, so I added the github svg in `GithubLink` comopnent. That fixed the missing icon issue, but raised another whitespace issue on the webpage that's because the `GithubLink` component had a `className` attribute set to "githubProfile" but there were no actual class with that name defined  in the `custom.css` file. So, I went ahead and made "githubProfile" class same as "twitterProfile" class and that fixed that white space issue.
## Types of changes
[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Awesome! 👍 

Would you mind to sign the CLA?

**Comment by arsen1c** [comment]
> Awesome! 
> 
> Would you mind to sign the CLA?

Done, sir!

**Comment by christian-bromann** [comment]
Thank you!

**Comment by christian-bromann** [comment]
@arsen1c I deployed the website, something I've discovered is that in dark mode the icons are black rather than white:

Screenshot 2021-04-01 at 12 26 05

We have the white version of the logo in the header:
Screenshot 2021-04-01 at 12 26 28

Do you think we can switch the logo when user toggle into dark mode?

**Comment by arsen1c** [comment]
Hey, @christian-bromann I noticed that too and have started working on it already :)  Also, thanks for potinting that header logo, I used the same technique as the header logo does and the issue is now seems to be fixed

**Comment by arsen1c** [comment]
image

**Comment by arsen1c** [comment]
Also, I removed the svg i added previously in the `GithubLink` component and implemented the github logo just like the github logo in the header with minor chanes in the dimensions.

**Pull request merged**
