### PR TITLE
wdio-junit-reporter: Fix nested and multiple describes

### PR DESCRIPTION
**Pull request by naddison**
## Proposed changes

I reverted my previous changes which caused this issue and added a unit test to capture the case of having multiple describe blocks (including nested). I also added documentation describing the output from the reporter.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by naddison** [comment]
This fixes https://github.com/webdriverio/webdriverio/issues/3855

**Comment by WillBrock** [comment]
Thanks! Can you rebase your branch?

**Comment by oxsav** [comment]
This pull request broke the functionality of junit reporter.
You are relying on the test-suites to increment the index and shouldn't be that way. You must look to `runner.specs`. 

With this version i got:
```
2019-04-19T10:03:57.902Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'replace' of undefined
    at JunitReporter.prepareXml (/Users/user/Documents/personal/test-functional/node_modules/@wdio/junit-reporter/build/index.js:50:259)
    at JunitReporter.onRunnerEnd (/Users/user/Documents/personal/test-functional/node_modules/@wdio/junit-reporter/build/index.js:23:22)
    at JunitReporter.WDIOReporter.on.runner (/Users/user/Documents/personal/test-functional/node_modules/@wdio/reporter/build/index.js:181:12)
    at emitOne (events.js:116:13)
    at JunitReporter.emit (events.js:211:7)
    at reporters.forEach.reporter (/Users/user/Documents/personal/test-functional/node_modules/@wdio/runner/build/reporter.js:53:49)
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/Users/user/Documents/personal/test-functional/node_modules/@wdio/runner/build/reporter.js:53:20)
    at Runner.run (/Users/user/Documents/personal/test-functional/node_modules/@wdio/runner/build/index.js:187:19)
    at <anonymous>
```

Here is a solution that worked for  me:
https://github.com/oxsav/webdriverio/blob/master/packages/wdio-junit-reporter/src/index.js#L25

**Comment by naddison** [comment]
> This pull request broke the functionality of junit reporter.
> You are relying on the test-suites to increment the index and shouldn't be that way. You must look to `runner.specs`.
> 
> With this version i got:
> 
> ```
> 2019-04-19T10:03:57.902Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'replace' of undefined
>     at JunitReporter.prepareXml (/Users/user/Documents/personal/test-functional/node_modules/@wdio/junit-reporter/build/index.js:50:259)
>     at JunitReporter.onRunnerEnd (/Users/user/Documents/personal/test-functional/node_modules/@wdio/junit-reporter/build/index.js:23:22)
>     at JunitReporter.WDIOReporter.on.runner (/Users/user/Documents/personal/test-functional/node_modules/@wdio/reporter/build/index.js:181:12)
>     at emitOne (events.js:116:13)
>     at JunitReporter.emit (events.js:211:7)
>     at reporters.forEach.reporter (/Users/user/Documents/personal/test-functional/node_modules/@wdio/runner/build/reporter.js:53:49)
>     at Array.forEach (<anonymous>)
>     at BaseReporter.emit (/Users/user/Documents/personal/test-functional/node_modules/@wdio/runner/build/reporter.js:53:20)
>     at Runner.run (/Users/user/Documents/personal/test-functional/node_modules/@wdio/runner/build/index.js:187:19)
>     at <anonymous>
> ```
> Here is a solution that worked for me:
> https://github.com/oxsav/webdriverio/blob/master/packages/wdio-junit-reporter/src/index.js#L25

This PR doesn't include the index anymore. This PR is a fix for that.

**Pull request merged**
