### PR TITLE
overwrite capabilities in config parser

### PR DESCRIPTION
**Pull request by baruchvlz**
## Proposed changes
#4894 

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by baruchvlz** [comment]
By default the config parser will merge the capabilities, I added the optional flag as a way to avoid breaking any projects who use this as the expected behaviour of the launcher. I agree that it can be confusing to the user since this is only for the config parser. Maybe we could add a third parameter to the launcher's constructor:

```js
new WDIOLauncher(wdioC0onfigPath, wdioConfigOpts, flags)
```

We could also always override the capabilities if any are passed via the launcher's config options and introduce this as a possible breaking change in v6? Let me know what you think.

**Comment by christian-bromann** [comment]
> We could also always override the capabilities if any are passed via the launcher's config options and introduce this as a possible breaking change in v6?

@baruchvlz Let's overwrite them completely then and make it a v6 patch.

**Comment by baruchvlz** [comment]
@christian-bromann Sounds good to me. I'll update the PR.

**Comment by baruchvlz** [comment]
@christian-bromann Should we also overwrite the capabilities in the [addConfigFile](https://github.com/webdriverio/webdriverio/blob/fdbec7b9ddbe6f8f1153f7dad5de2b654e52221e/packages/wdio-config/src/lib/ConfigParser.js#L43) method?

**Comment by christian-bromann** [comment]
> Should we also overwrite the capabilities in the [addConfigFile](https://github.com/webdriverio/webdriverio/blob/fdbec7b9ddbe6f8f1153f7dad5de2b654e52221e/packages/wdio-config/src/lib/ConfigParser.js#L43) method?

@baruchvlz I think this is not necessary. I made a small tweak to the docs change (since we didn't end up adding the `overwriteCapabilities` option).

**Pull request merged**
