### PR TITLE
@wdio/types: node16 module resolution compatibility

### PR DESCRIPTION
**Pull request by SCG82**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

`Node16` module resolution requires file extensions for all imports (including type only imports).

- Webdriver.Capabilities/DesiredCapabilities: change `type` to `interface` to avoid errors when two (or more) @wdio/types are present in a project, and to allow extending.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
> `Node16` module resolution requires file extensions for all imports (including type only imports).

I don't think for type imports this is needed. Do you have an example where this would fail. Also why only there and not in all other places in the code base?

**Comment by SCG82** [comment]
> > `Node16` module resolution requires file extensions for all imports (including type only imports).
> 
> I don't think for type imports this is needed. Do you have an example where this would fail. Also why only there and not in all other places in the code base?

All packages in the code base will need to have extensions added to support consumers using Node16 module resolution... just picking low hanging fruit.

**Comment by christian-bromann** [comment]
@SCG82 do you have an example project or can describe how I can reproduce this?

**Comment by SCG82** [comment]
> @SCG82 do you have an example project or can describe how I can reproduce this?

https://github.com/SCG82/cucumber-boilerplate/tree/node16

There will be no type information from `@wdio/types` in `config/mac-chrome-bs.conf.ts`. Changing `skipLibCheck` to `false` and opening up `@wdio/types` will show the error

```
Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'.
```

**Comment by christian-bromann** [comment]
Screenshot 2022-12-24 at 11 34 37

I don't get any errors, is there something I am missing?

**Comment by SCG82** [comment]
> I don't get any errors, is there something I am missing?

Just to make sure it isn't my setup I opened that branch in Codespaces:

Screen Shot 2022-12-24 at 2 50 30 AM

**Comment by christian-bromann** [comment]
Still no success reproducing the issue after opening a codespace on named branch:

Screenshot 2022-12-24 at 12 40 13

**Comment by christian-bromann** [comment]
I was able to reproduce now, let's enforce it for all type imports via EsLint.

**Review by christian-bromann — APPROVED** [review]
I couldn't find an Eslint rule for this so I will go ahead and merge.

Thanks 👍

**Comment by kyryloonufriiev** [comment]
@christian-bromann Hi 👋 . I see you did merge this PR. I want to let you know that the same very problem exists in the `wdio` packages as well. Would you like me to create a separate PR to do the same very thing as we have in this PR but for other packages?

**Comment by christian-bromann** [comment]
@kyryloonufriiev yes, that would be awesome!

**Pull request merged**
