### PR TITLE
Update repl.md

### PR DESCRIPTION
**Pull request by kxc-waddlaw**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@kxc-waddlaw thanks for raising the PR. The changes you suggest make sense however they current documentation is technically not wrong either. Can you explain what confused you here and what was the incentive to change it into what you propose?

**Comment by kxc-waddlaw** [comment]
@christian-bromann Thanks for the reply.
I don't know much about `wdio`, so I consulted some documentation and used the following setup page to get the test runner running for local mobile testing.

- https://webdriver.io/docs/typescript/

I created three files `wdio.conf.ts`, `wdio.local.ios.conf.ts` and `wdio.local.android.conf.ts` and configured each of them. It worked well up to this point, so next I decided to try running `wdio repl` by diverting the configuration files I created above, using the following page as a reference.

- https://webdriver.io/docs/repl/

There, it says `wdio.conf.ts example` but when I run it I get `". /path/to/wdio.config.js"`, which I thought might be wrong, so I created a PR.

However, after doing some research earlier, I now think that `.ts` will not work unless it is `.js` because `.ts` gives the following error when parsing the `ts-node` configuration file.

```
Error: Could not parse wdio.config.ts, failed with error : Unknown file extension ".ts"
```

----

I've been reading the relevant code and one thing is bothering me, so can I check it here?

The following code, it seems that the configuration file is not loaded when the naming convention is `wdio.android.config.ts` because `android` and `ios` are not an exact match.

https://github.com/webdriverio/webdriverio/blob/v8.39.0/packages/wdio-cli/src/utils.ts#L309-L312

Is this the intended behaviour?

**Comment by christian-bromann** [comment]
> Is this the intended behaviour?

No, I think we should raise an issue: "Support `.ts` files in REPL" and update the doc example to show both versions. WDYT?

**Comment by kxc-waddlaw** [comment]
I agree with you!

**Comment by christian-bromann** [comment]
Closing this PR in favor of #13109. Any contributions to support this use case are much appreciated!

**Pull request closed without merging**
