### PR TITLE
webdriver: fix #3252

### LINKED ISSUE #3252: WebDriver crashing when using Appium node with grid
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.2.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** N/A
 - **Platform name and version:** Mac
 - **Additional wdio packages used (if applicable):** 
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.12.18",
    "@types/webdriverio": "^4.13.1",
    "@wdio/cli": "^5.2.2",
    "@wdio/dot-reporter": "^5.2.2",
    "@wdio/local-runner": "^5.2.2",
    "@wdio/mocha-framework": "^5.2.2",
    "@wdio/sync": "^5.2.2",
    "ts-node": "^7.0.1",
    "tsconfig-paths": "^3.7.0",
    "typescript": "^3.2.2"

**Config of WebdriverIO**
```exports.config = {
  hostname: '127.0.0.1',
  port: 4441,
  maxInstances: 1,
  capabilities: [{
    maxInstances: 1,
    platformName: 'Android',
    platformVersion: '9.0.0',
    deviceName: 'Pixel 2',
    udid: 'FA8131A03509',
    chromeDriverPort: 8723,
    systemPort: 27723,
    browserName: 'chrome',
    chromeOptions: {
      args: ['--no-first-run'],
    },
    newCommandTimeout: 240,
  }],
  specs: [
    './test/specs/**/*.ts'
  ],
  framework: 'mocha',
  reporters: ['dot'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
    compilers: [
      'ts-node/register',
      'tsconfig-paths/register'
    ]
  },
  before: function (capabilities, specs) {
    require('ts-node/register');
  }
}
```

**Describe the bug**
Webdriver crashes when trying to make connection to grid server with 500 error.

**To Reproduce**
1. start selenium-server-standalone in grid mode
2. connect appium node to grid
3. run any test

**Expected behavior**
Appium started browser/app on mobile device;

instead of 500 error it should be 200 with body like
```
   body:
   { value:
      { capabilities: [Object],
        sessionId: '1ee14a7d-ead5-41f1-baa4-f137b1561195' } } }
```

**Log**
https://gist.github.com/xlenz/2f24464e629761742d5ce218f05a48d0

added console.logs to `node_modules/webdriver/build/request.js:113:21` to get full request options 
https://gist.github.com/xlenz/cca35e874e2843aa351867657c00da1b

Also, added full request options from webdriver 4 to make a proper comparison
https://gist.github.com/xlenz/46d4677bfdbf67bc757f5388988560a6

**Additional context**
I've tried following cases:
webdriver 4.14.1
- appium standalone  - works
- appium over grid - works 

webdriver 5.2.2
- appium standalone - works
- appium over grids - doesn't work (current issue)

haven't tried other 5.x.x versions.

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Fix #3252 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

According to https://www.w3.org/TR/webdriver/#processing-capabilities 
If alwaysMatch is undefined set value to empty JSON Object.

### CODE REVIEW

**Comment by christian-bromann** [comment]
This is not a fix for the issue. We need to send capabilities this way because it is how it has to be sent according to the WebDriver protocol.

**Comment by xlenz** [comment]
@christian-bromann agree. However there should be a mechanism to use wdio 4.x mechanism that was working properly with selenium grid in case we sending capabilities like deviceName or similar.

**Comment by christian-bromann** [comment]
@xlenz this is a different problem .. The selenium grid should support non w3c capabilities when used with appium.

**Comment by abjerstedt** [comment]
@xlenz You'll probably need to submit a pr/issue to the webdriver spec or selenium-standalone-server.

**Comment by christian-bromann** [comment]
> to the webdriver spec or selenium-standalone-server.

to the Selenium project

**Comment by xlenz** [comment]
@abjerstedt  @christian-bromann it supports non w3c capabilities perfectly well by passing them as desiredCapabilities instead of capabilities

**Comment by xlenz** [comment]
and it looks for me like this:
grid works fine with
- selenium standalone
- appium
- webdriver 4

but doesn't work with webdriver 5 because there is no way for user to set capabilities/desiredCapabilities manually

**Comment by christian-bromann** [comment]
> there is no way for user to set capabilities/desiredCapabilities manually

What do you mean by that?

**Comment by xlenz** [comment]
wdio config file:
```
capabilities: [{
    platformName: 'Android',
    platformVersion: '9.0.0',
    deviceName: 'Pixel 2',
    browserName: 'chrome'
  }]
```
Which is converted by webdriverio 5.x.x to
```
capabilities = {
    alwaysMatch: {
        platformName: 'Android',
        platformVersion: '9.0.0',
        deviceName: 'Pixel 2',
        browserName: 'chrome'
    },
    firstMatch: [ {} ]
  }
```
and 
```
desiredCapabilities = {
    platformName: 'Android',
    platformVersion: '9.0.0',
    deviceName: 'Pixel 2',
    browserName: 'chrome'
  }
```

If I could manually specify what should go to capabilities and what should go to desiredCapabilities it would be really nice and I can have fully working grid with appium nodes.

**Comment by christian-bromann** [comment]
> Which is converted by webdriverio 5.x.x to

Yes because we don't know if the user is running a w3c compatible driver or not

> If I could manually specify what should go to capabilities and what should go to desiredCapabilities it would be really nice and I can have fully working grid with appium nodes.

There is no reason to send different capabilities. The problem is that the selenium grid detects that it is a w3c capability so it reads it and detects that it contains appium capabilities which are not valid. This is a bug that needs to be reported in the Selenium project. At some point it will not accept `desiredCapabilities` anymore and then you will face the same issue.

**Comment by xlenz** [comment]
@christian-bromann after changing logic in selenium grid so that it won't crash due to Appium specific properties Appium node still won't start due to invalid logic here:

```
    const [w3cCaps, jsonwpCaps] = params.capabilities && params.capabilities.alwaysMatch
    /**
     * in case W3C compliant capabilities are provided
     */
    ? [params.capabilities, params.capabilities.alwaysMatch]
    /**
     * otherwise assume they passed in jsonwp-style caps (flat object)
     */
    : [{
      alwaysMatch: params.capabilities,
      firstMatch: [{}]
    }, params.capabilities];
    const sessionRequest = new _request.default('POST', '/session', {
      capabilities: w3cCaps,
      // W3C compliant
      desiredCapabilities: jsonwpCaps // JSONWP compliant

    });
```

So, my wdio config is like 
```
  capabilities: [{
    alwaysMatch: {
      deviceName: 'Pixel 2',
      platformName: 'Android',
    },
    maxInstances: 1,
    browserName: 'chrome'
  }]
```

I'm getting error from Appium:
`the desired capabilities must include either an app, appPackage or browserName`

this is because of 
`    ? [params.capabilities, params.capabilities.alwaysMatch]`

we are sending only params.capabilities.alwaysMatch as desiredCapabilities while Appium expect everything to be desired capabilities.
It can be fixed with passing all capabilities as desired capabilities
`    ? [params.capabilities, { ...params.capabilities, ...params.capabilities.alwaysMatch }]`

and it is absolutely correct because I want to have one node where I can run both browser and app, so that only deviceName and platformName are required (alwaysMatch) while browserName / app are not always required and should NOT be in alwaysMatch block, otherwise I have to hardcode my app name / browser in node config which is not valid scenario.

**Comment by christian-bromann** [comment]
you caps are wrong .. currently WebdriverIO doesn't allow you to set alwaysMatch and firstMatch, just do
```js
  capabilities: [{
    deviceName: 'Pixel 2',
    platformName: 'Android',
    maxInstances: 1,
    browserName: 'chrome'
  }]
```

**Comment by xlenz** [comment]
@christian-bromann sorry to say it won't work because in this case I have to hardcode browserName in appium node configuration.
Having such configuration won't allow me to run my app on this node

**Comment by xlenz** [comment]
btw,
tests are passing having merged object of capabilities and alwaysMatch as desiredCapabilities without alwaysMatch and firstMatch properties:
`    ? [params.capabilities, { ...params.capabilities, ...params.capabilities.alwaysMatch, alwaysMatch: undefined, firstMatch: undefined }]`

**Pull request closed without merging**
