### PR TITLE
Remove authuser=1 from url

### PR DESCRIPTION
**Pull request by fpereira1**
## Proposed changes

Fixes a link to the recorder chrome extension

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
@fpereira1 mind signing the CLA?

**Comment by fpereira1** [comment]
@christian-bromann there are a few more of those links that can be fixed. Shall I go ahead and fix them here on this PR?

**Review by christian-bromann — APPROVED** [review]
Thanks a lot 👍

**Pull request merged**
