### PR TITLE
Add resignApp capability type

### PR DESCRIPTION
**Pull request by dprevost-LMI**
## Proposed changes
Add [resignApp capability](https://www.browserstack.com/docs/app-automate/appium/advanced-features/disable-resigning-of-apps) type

We need to use this capability, but we stumble into typing issues.

## Types of changes

- [x] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- I have added tests that prove my fix is effective or that my feature works (N/A)

## Backport Request

- [x] Back-ported PR : https://github.com/webdriverio/webdriverio/pull/12851#issue-2288639253

### CODE REVIEW

**Comment by christian-bromann** [comment]
@dprevost-LMI thanks for the contribution, mind signing the CLA?

**Comment by dprevost-LMI** [comment]
> @dprevost-LMI thanks for the contribution, mind signing the CLA?

Done! That was a learning path...

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
> * Back-ported PR at `#XXXXX` (in progress)

The `main` branch is currently for v9 development if you are interested having this backported to v8, mind raising the same pr for the `v8` branch?

**Comment by dprevost-LMI** [comment]
> > * Back-ported PR at `#XXXXX` (in progress)
> 
> The `main` branch is currently for v9 development if you are interested having this backported to v8, mind raising the same pr for the `v8` branch?

Will do, I was waiting for the merge to cherry pick the main commit but I can also open a PR with the same commit

**Comment by dprevost-LMI** [comment]
See https://github.com/webdriverio/webdriverio/pull/12851#issue-2288639253 for the v8 PR

**Pull request merged**
