### PR TITLE
fix(webdriverio): switchWindow supports exact window handle match

### PR DESCRIPTION
**Pull request by jan-molak**
This change enables `browser.switchWindow(matcher)` to accept an exact window handle and switch to it directly without cycling through all the open tabs.

Enables serenity-js/serenity-js#2572

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

Serenity/JS offers a [sophisticated API](https://serenity-js.org/api/web/class/Page/) to allow developers to switch the active browser window to a desired one. 

```ts
await actor.attemptsTo(
  Switch.to(Page.whichUrl(startsWith('https://github.com')))
)
```

Under the hood, Serenity/JS relies on the following WebdriverIO APIs:
- `browser.getWindowHandle`
- `browser.getWindowHandles`
- `browser.switchToWindow` (deprecated)

However, `switchToWindow(handle)` is now deprecated, and the `switchWindow(matcher)` that replaces it does not currently support switching to the exact window handle Serenity/JS has found.

This change extends and improves the performance of `browser.switchWindow(matcher)` by making it exit early and avoid looping over the open window handles if:
- the `matcher` is the current window handle
- the `matcher` is one of the already open window handles

If there's no exact window handle match, the `switchWindow` function continues as before.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @webdriverio/project-committers

Discussed with @christian-bromann

### CODE REVIEW

**Comment by jan-molak** [comment]
Looks like we have a couple of tests in the pipeline failing due to timeout issues that don't seem to be related to the proposed change.

**Review by christian-bromann — COMMENTED** [review]
Thanks @jan-molak for the contribution!

Mind adding to the example a version where we switch to a window with a given handle?

**Comment by jan-molak** [comment]
Sure thing; please hold off with merging for a moment, I just noticed something I'd like to fix.

**Comment by jan-molak** [comment]
@christian-bromann - should be good to go I think

**Pull request merged**
