### PR TITLE
Make custom$ return Element object when an element is not found

### PR DESCRIPTION
**Pull request by nextlevelbeard**
## Proposed changes

Make custom$ return Element object when an element is not found

Prevents uncatchable errors such as 

```
Error: Your locator strategy script must return an element
    at Browser.custom$ (file:///Users/user/repos/repo/node_modules/webdriverio/build/commands/browser/custom$.js:44:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Browser.wrapCommandFn (file:///Users/user/repos/repo/node_modules/@wdio/utils/build/shim.js:81:29)
    at async Element.wrapCommandFn (file:///Users/user/repos/repo/node_modules/@wdio/utils/build/shim.js:81:29)
    at async Element.wrapCommandFn (file:///Users/user/repos/repo/node_modules/@wdio/utils/build/shim.js:81:29)
    at async Element.elementErrorHandlerCallbackFn (file:///Users/user/repos/repo/node_modules/webdriverio/build/middlewares.js:18:32)
    at async Element.wrapCommandFn (file:///Users/user/repos/repo/node_modules/@wdio/utils/build/shim.js:81:29)
    at async Element.wrapCommandFn (file:///Users/user/repos/repo/node_modules/@wdio/utils/build/shim.js:81:29)
    at async Scenario.<anonymous> (file:///Users/user/repos/repo/e2e/steps/dashboard.steps.ts:63:5)
```
This change triggers proper error handling:

```
Error: waitUntil condition failed with the following reason: Can't call <command> on element with selector "[example="foo"]" because element wasn't found

```

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@nextlevelbeard thanks for the contribution.

Can you share a code snippet where this behavior can be reproduced?

**Comment by christian-bromann** [comment]
ping @nextlevelbeard , any comment?

**Comment by nextlevelbeard** [comment]
> ping @nextlevelbeard , any comment?

Sorry for the delay, example reproduction:

```ts
browser.addLocatorStrategy('myCustomStrategy', (selector, root) => {
    const scope = root ? root : document
    return scope.querySelectorAll(selector)
})

// Try to find an element and have it not exist in the DOM
// This throws error and crashes test: Your locator strategy script must return an element
// Should be handled gracefully by WDIO
const elem = await browser.custom$('myCustomStrategy', '.thisClassDoesNotExist')
```

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

I will add tests and fix the lint bug after merging.

**Comment by christian-bromann** [comment]
In case you are interested: https://github.com/webdriverio/webdriverio/commit/67d5df94dcee0118fcb3d28257318bb0b317d829

**Pull request merged**
